openmicroscopy/openmicroscopy

components/tools/OmeroPy/test/integration/test_search.py
See: gh-3160
--rebased-from #3160
=> Try search repeatedly until success (rebase)

components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/util/player/MoviePlayer.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/util/player/MoviePlayerControl.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/util/player/MoviePlayerUI.java
This is the same as gh-2908 but rebased onto dev_5_0.
----
Fix few bugs related to movie player cf. https://trello.com/c/zmxUtwWp/63-movie-player-issues
To Test:
* Select an image with one z, Make sure the Error no longer occurs
* Select an image with several z and t
* Modify the value in the text field. No longer required to press Enter
* When moving to another field. Check that the value of the previous field is modified only if the value is not in the correct range.
=> Play movie (rebased onto dev_5_0)

components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/MeasurementViewerModel.java, components/insight/SRC/org/openmicroscopy/shoola/util/roi/model/ROIShape.java
This is the same as gh-3301 but rebased onto dev_5_0.
----
This PR allows to analyse the shape not linked to any plane. The plane currently displayed is in that case selected
To test
* Login as user-4/Test Group
* Open the OME-TIFF with ROIs/mouseWithROI.ome.tif
* Open the measurement, Do not save the ROI.
* Select one the shape
* Go to the Graph, Intensity View, Intensity Result View. Check that the shape is analysed.
=> Analyze shape (rebased onto dev_5_0)

etc/logback.xml
Makes it easier to edit, whenever I want to turn on graphs debugging. Doesn't change current log level.
--no-rebase
=> add useful log config line to change for graphs debugging

components/tools/OmeroWeb/omeroweb/webclient/controller/container.py, components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/ome.make_movie.js, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/scripts/base_custom_dialog.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/scripts/make_movie.html, components/tools/OmeroWeb/omeroweb/webclient/urls.py, components/tools/OmeroWeb/omeroweb/webclient/views.py, components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/ome.colorbtn.js, components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/ome.gs_utils.js, components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/ome.popup.js, components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/ome.viewport.js, components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/omero_image.js
This adds "Make Movie" functionality to the web client.
It should replicate the Insight functionality.
Test on images with sizeT > 1 or sizeZ > 1 or both.
- Test that Make Movie option is enabled ONLY when a single image with sizeT > 1 or sizeZ > 1 is selected.
- Check that the Make Movie dialog corresponds to Insight's when the same image is selected.
- Check that edits to parameters in the UI have the expected effect in the exported movie (check it's the same as Insight).
=> Make movie web

components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/util/model/FigureTableModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/ObjectInspector.java, components/insight/SRC/org/openmicroscopy/shoola/util/roi/figures/MeasureEllipseFigure.java, components/insight/SRC/org/openmicroscopy/shoola/util/roi/figures/MeasureLineFigure.java, components/insight/SRC/org/openmicroscopy/shoola/util/roi/figures/MeasurePointFigure.java, components/insight/SRC/org/openmicroscopy/shoola/util/roi/figures/MeasureRectangleFigure.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/drawingtools/figures/EllipseTextFigure.java
This is the same as gh-3186 but rebased onto dev_5_0.
----
This PR fixes 2 more issues with measurement tool
To test
* Open the measurement tool
* Draw an ellipse. 
* Go to the inspector tab. Check the scale proportionally is a checkbox and not N/A
* Edit the width and height of the ellipse in the inspector tab.
* Check that the shape of the ellipse is modified.
=> Roi inspector (rebased onto dev_5_0)

components/blitz/src/ome/services/blitz/repo/PublicRepositoryI.java, components/server/src/ome/security/SecuritySystem.java, components/server/src/ome/security/SecuritySystemHolder.java, components/server/src/ome/security/sharing/SharingSecuritySystem.java
File deletion should still work. Make sure the code changes look sensible and that the integration tests still pass.
--no-rebase as Delete2 is not available in 5.0
=> reimplement PublicRepositoryI.deletePaths using Delete2

components/blitz/resources/omero/Constants.ice, components/blitz/src/pojos/MapAnnotationData.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/util/ModelMapper.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/util/PojoMapper.java, components/tools/OmeroJava/test/integration/AbstractServerTest.java, components/tools/OmeroJava/test/integration/DeleteServiceTest.java, components/tools/OmeroJava/test/integration/MetadataServiceTest.java
Adds the Pojo for MapAnnotations and the integration tests.
Test: Check that the (annotation related) integration tests pass
(This PR also adds a namespace constant for client created MapAnnotations to Constants.ice /cc @will-moore  )
--no-rebase
--depends-on #3334
=> MapAnnotation Pojo and Tests 

components/tools/OmeroWeb/omeroweb/webgateway/__init__.py, components/tools/OmeroWeb/omeroweb/webgateway/admin.py, components/tools/OmeroWeb/omeroweb/webgateway/marshal.py, components/tools/OmeroWeb/omeroweb/webgateway/middleware.py, components/tools/OmeroWeb/omeroweb/webgateway/models.py, components/tools/OmeroWeb/omeroweb/webgateway/templatetags/common_filters.py, components/tools/OmeroWeb/omeroweb/webgateway/templatetags/common_tags.py, components/tools/OmeroWeb/omeroweb/webgateway/templatetags/defaulttags.py, components/tools/OmeroWeb/omeroweb/webgateway/templatetags/wikitags.py, components/tools/OmeroWeb/omeroweb/webgateway/tests/conftest.py, components/tools/OmeroWeb/omeroweb/webgateway/tests/seleniumbase.py, components/tools/OmeroWeb/omeroweb/webgateway/tests/test_webgateway.py, components/tools/OmeroWeb/omeroweb/webgateway/urls.py, components/tools/OmeroWeb/omeroweb/webgateway/util.py, components/tools/OmeroWeb/omeroweb/webgateway/views.py, components/tools/OmeroWeb/omeroweb/webgateway/webgateway_cache.py, setup.cfg
This PR flake8 the entire webgateway
--no-rebase
Tip: use https://github.com/openmicroscopy/openmicroscopy/pull/3347/files?diff=unified&w=1
=> Flake8 webgateway

components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/ImageLoader.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/Renderer.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/RendererComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/RendererModel.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/OmeroImageService.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/OmeroImageServiceImpl.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/ImageDataView.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/ImageDataViewImpl.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/ImageRenderer.java, components/insight/SRC/org/openmicroscopy/shoola/env/rnd/PixelsServicesFactory.java, components/insight/TEST/org/openmicroscopy/shoola/env/data/NullRenderingService.java
Make sure the correct compression level is used when opening the viewer
To test the PR
* Open an image. Modify the compression level e.g. set it to high
* Close the viewer
* Open another image, Modify the compression level e.g. to none. Check that the image is updated.
Problem noticed while working on https://github.com/openmicroscopy/openmicroscopy/pull/3368
=> Compression

components/blitz/src/omero/grid/InteractiveProcessorI.java
Intended for tracking down the problem on gretzky.
May not need to be merged.
cc @manics
=> Add debugging of NPE in InteractiveProcessorI

components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/jquery.editinplace.js
See: https://trac.openmicroscopy.org.uk/ome/ticket/12666
To test:
- Edit P/D/I name & description in web.
- Check that jsTree updates appropriately
- Check that name & description fields update correctly and don't get over-ridden by each other etc.
=> Fix edit name & description and jsTree update

components/blitz/src/omero/grid/InteractiveProcessorI.java
This is the same as gh-2309 but rebased onto develop.
----
Intended for tracking down the problem on gretzky.
May not need to be merged.
cc @manics
=> Add debugging of NPE in InteractiveProcessorI (rebased onto develop)

components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/ImageLoader.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/Renderer.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/RendererComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/RendererModel.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/OmeroImageService.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/OmeroImageServiceImpl.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/ImageDataView.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/ImageDataViewImpl.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/ImageRenderer.java, components/insight/SRC/org/openmicroscopy/shoola/env/rnd/PixelsServicesFactory.java, components/insight/TEST/org/openmicroscopy/shoola/env/data/NullRenderingService.java
Make sure the correct compression level is used when opening the viewer
To test the PR
* Open an image. Modify the compression level e.g. set it to high
* Close the viewer
* Open another image, Modify the compression level e.g. to none. Check that the image is updated.
PR opened following discussion on https://github.com/openmicroscopy/openmicroscopy/pull/3366
Likely to conflict with https://github.com/openmicroscopy/openmicroscopy/pull/3378
cc @pwalczysko
=> Viewer compression dev 5 0

components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/AdminCreator.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/AdminServiceImpl.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/Connector.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/OMEROGateway.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/AdminLoader.java
To test:
* Log as an admin
* Go to the admin tab
* Select a user and change password. 
* No error message should be displayed.
=> Reset password

history.txt
=> 5-0-7 version history

components/blitz/src/ome/formats/OMEROMetadataStoreClient.java
See https://trello.com/c/iNieNBuZ/77-remove-deprecated-methods.
--depends-on openmicroscopy/bioformats#1562
=> Remove deprecated setRoot(Object)

history.txt
This is the same as gh-3421 but rebased onto develop.
----
Based on release announcement
=> 5-0-7 version history (rebased onto develop)

history.txt
Adding 5.0.8 version history for OMERO.
=> 5-0-8 history

components/blitz/resources/omero/cmd/Graphs.ice, components/blitz/src/omero/cmd/graphs/Chgrp2I.java, components/blitz/src/omero/cmd/graphs/Chown2I.java, components/blitz/src/omero/cmd/graphs/Delete2I.java, components/tools/OmeroPy/src/omero/cli.py, components/tools/OmeroPy/src/omero/plugins/chgrp.py, components/tools/OmeroPy/src/omero/plugins/delete.py, components/tools/OmeroPy/test/integration/clitest/test_chgrp.py
`bin/omero chgrp` should now work fine for MIFs.
See http://trac.openmicroscopy.org/ome/ticket/10969 and http://trac.openmicroscopy.org/ome/ticket/11966.
--no-rebase
=> fix #10969: rearrange DoAll's in cli.py

components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterControl.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/FileUploader.java, components/insight/SRC/org/openmicroscopy/shoola/env/init/AgentsInit.java, components/insight/SRC/org/openmicroscopy/shoola/env/ui/UserNotifierManager.java, components/insight/SRC/org/openmicroscopy/shoola/util/file/ImportErrorObject.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/FileTable.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/FileTableNode.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/MessengerDialog.java
To test 
* Select a faulty plate
* Click Submit
* A dialog will pop up asking if you wish to submit the error.
* Click no. The process should stop
* Click Submit
* A dialog will pop up asking if you wish to submit the error.
* Click yes, The exception and log should be sent.
To test, use a plate under ```squig/team/jburel/broken plates from Petr```
=> Plate to QA

components/insight/SRC/org/openmicroscopy/shoola/env/data/OmeroImageServiceImpl.java
Fix problems when tagging ome-tiff at import see https://trac.openmicroscopy.org.uk/ome/ticket/12164
Images were not tagged
To test:
* Select an ome-tiff
* Select or create a new tag.
* Import the image.
* Check that the image is tagged.
=> Tagging ome tiff

components/insight/SRC/org/openmicroscopy/shoola/util/ui/drawingtools/figures/EllipseTextFigure.java
* Open an image with several z and/or several t
* Open the measurement tool
* Draw an ellipse
* Propagate the ellipse across z or t
* Select a newly created shape. (e.g. on z+1)
* Make sure that the ellipse does not jump to the top left-corner
see http://trac.openmicroscopy.org.uk/ome/ticket/12726
=> propagate ellipse

components/insight/SRC/org/openmicroscopy/shoola/MainIJPlugin.java, components/insight/SRC/org/openmicroscopy/shoola/agents/events/treeviewer/SaveResultsEvent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/ImporterAgent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/chooser/ImportDialog.java, components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/chooser/LocationDialog.java, components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/view/Importer.java, components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/TreeViewerAgent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/actions/SaveResultsAction.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/util/SaveResultsDialog.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/ToolBar.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewerControl.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/model/FileObject.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/model/ResultsObject.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/ImageDataView.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/ImageDataViewImpl.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/ResultsSaver.java, components/insight/SRC/org/openmicroscopy/shoola/env/event/SaveEvent.java, components/insight/SRC/org/openmicroscopy/shoola/env/ui/SaveResultsActivity.java, components/insight/SRC/org/openmicroscopy/shoola/env/ui/SaveResultsLoader.java, components/insight/SRC/org/openmicroscopy/shoola/env/ui/TaskBarManager.java, components/insight/SRC/org/openmicroscopy/shoola/env/ui/UserNotifierImpl.java, components/insight/SRC/org/openmicroscopy/shoola/plugins.config
* Update the omero-imagej plugin
* Open an image in imageJ
* Draw few ROIs and add them either as overlays or to the ROIManager
* Click on the Save ImageJ results button (in DataManager toolbar)
* Check that The rois are saved and linked to the image.
Test 2
* Open an image in ImageJ (not already imported)
* Click on the Save ImageJ results button.
* A dialog should pop up asking the user wants to import the image first. 
cc @bramalingam @pwalczysko
=> Omero to imagej

history.txt
Will no doubt need further work - I picked a bunch of stuff from the PR list not necessarily the most relevant point.
cc/ @joshmoore @jburel @sbesson
=> Initial m4 history

components/tools/OmeroWeb/omeroweb/webclient/controller/search.py
this should resolve deprecation warning. To test just see if searching works
=> fixing deprecated warning, ticket #12472

components/insight/SRC/org/openmicroscopy/shoola/env/LookupNames.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/DataServicesFactory.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/OMEROGateway.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/login/LoginServiceImpl.java, components/insight/SRC/org/openmicroscopy/shoola/env/ui/SplashScreenManager.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/login/ScreenLogin.java, components/insight/TEST/org/openmicroscopy/shoola/examples/data/Gateway.java
Allow to connect using session id.
A way to test the PR
* Run code in eclipse for example and print out the session ID
* launch the application
* Copy and paste this id in user field, password can be anything but not empty
* Click connect.
Note: I might go for empty password @gusferguson what do you think?
=> Connect with session ID

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/Editor.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorControl.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/PublishingDialog.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/view/MetadataViewerComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/util/ui/MovieExportDialog.java, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/scripts/make_movie.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/scripts/split_view_figure.html, components/tools/OmeroWeb/omeroweb/webgateway/templates/webgateway/viewport/omero_image.html, examples/Web/embed_viewer.html
Unify UI for make movie following intro of widget in web https://github.com/openmicroscopy/openmicroscopy/pull/3282
To test:
* Check that both dialogs (insight, web) have similar display and options.
* Check in web text for "Scale bar" (instead of scalebar) and "Color" instead of "Colour"
cc @gusferguson
=> Make movie

components/blitz/resources/omero/Repositories.ice
fixes http://trac.openmicroscopy.org/ome/ticket/12742
--no-rebase
=> correct omero::grid::Repository documentation for root()

components/blitz/src/ome/services/blitz/impl/RawFileStoreI.java
Prompted by https://trello.com/c/sWlIbIsi/426-setfileid-exception.
--no-rebase
=> catch SecurityViolation from setFileId

docs/install/VM/omerovm.sh
Increase bootup time, switch to Ubuntu_64. Note this image contains PostgreSQL 9.3 and Ice 3.5.
=> Use Ubuntu 14.04 for the VBox image

components/tools/OmeroWeb/omeroweb/webclient/controller/__init__.py, components/tools/OmeroWeb/omeroweb/webclient/controller/basket.py, components/tools/OmeroWeb/omeroweb/webclient/controller/container.py, components/tools/OmeroWeb/omeroweb/webclient/controller/help.py, components/tools/OmeroWeb/omeroweb/webclient/controller/history.py, components/tools/OmeroWeb/omeroweb/webclient/controller/impexp.py, components/tools/OmeroWeb/omeroweb/webclient/controller/index.py, components/tools/OmeroWeb/omeroweb/webclient/controller/search.py, components/tools/OmeroWeb/omeroweb/webclient/controller/share.py, components/tools/OmeroWeb/omeroweb/webclient/custom_forms.py, components/tools/OmeroWeb/omeroweb/webclient/decorators.py, components/tools/OmeroWeb/omeroweb/webclient/show.py, components/tools/OmeroWeb/omeroweb/webclient/templatetags/webclient_tags.py, components/tools/OmeroWeb/omeroweb/webclient/tests/__init__.py, components/tools/OmeroWeb/omeroweb/webclient/tests/test_webclient.py, components/tools/OmeroWeb/omeroweb/webclient/tree.py, components/tools/OmeroWeb/omeroweb/webclient/webclient_gateway.py, components/tools/OmeroWeb/omeroweb/webclient/webclient_utils.py, setup.cfg
This PR fixes many files under `omeroweb/webclient` to be flake8 compliant. Two files `urls.py` and `forms.py` are excluded from this first run and will be the object of a separate PR.
As always, append `&w=1` to the diff URL on GitHub might be handy to review this PR.
--no-rebase
=> Webclient flake8 1

docs/install/VM/omerovm.sh
This is the same as gh-3546 but rebased onto dev_5_0.
----
Increase bootup time, switch to Ubuntu_64. Note this image contains PostgreSQL 9.3 and Ice 3.5.
=> Use Ubuntu 14.04 for the VBox image (rebased onto dev_5_0)

components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/chooser/ImportDialog.java, components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/util/SaveResultsDialog.java
To test
* Open a mif in imageJ
* draw a roi on one image. Save as overlay
* Click on the plugins>OMERO>Save to OMERO (not Upload and Save)
* Check that the image are imported and the rois saved on the correct ones.
=> Save imagej

components/model/src/ome/util/PixelData.java
Use FormatTools to set interval.
To test:
make sure you can see the images correctly
--depends-on https://github.com/openmicroscopy/bioformats/pull/1634
--no-rebase
Samples images:
* ubm (32bit)
* varian-mri (float)
* dv (unint16)
* avi (unint8)
* gatan-dm2 (int16)
=> RE clean-up

examples/Training/matlab/DeleteData.m, examples/Training/matlab/ROIs.m
Expand Matlab examples by setFillColor, setStokeColor and setTextValue.
=> Matlab add colours to rois examples

components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/actions/BrowseContainerAction.java
Do not browse project with empty datasets.
see https://trac.openmicroscopy.org/ome/ticket/11952
To test
* Select a project containing empty datasets.
* Make sure the browse action is not enabled.
=> Browse project

components/tests/ui/resources/robot.template, components/tests/ui/testcases/web/webadmin_create_group_and_user.txt
To Test:
```
./build.py -f components/tests/ui/build.xml web-chrome -DTEST=webadmin_create_group_and_user.txt
```
And check if all tests pass. 
Note: Please follow set-up instructions given in "openmicroscopy/components/tests/ui/README.md", before running the test. Please install google chrome as well.
=> robotframework : Test default (edit) behaviour of Administrator's groups list

examples/Training/python/Create_Image.py, examples/Training/python/Read_Data.py
Updated a couple of Python code examples for how to work with units, getting and setting pixel sizes.
To test, read examples, then run (edit image Ids and login credentials as needed)
```
$ cd examples/Training/python
$ python Read_Data.py
$ python Create_Image.py
```
=> Examples units

components/tools/OmeroPy/src/omero/gateway/__init__.py, components/tools/OmeroWeb/omeroweb/webclient/controller/search.py, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/search/search_details.html
As in Insight, searching for Plate "Runs" should work the same as for Plates.
To test:
- Tag a plate 'Run'
- Search for the Tag - Run should be in results
- Click it to display in right panel
- Click "Browse" to browse to the run.
=> Search plate acquisition

examples/Training/python/Connect_To_OMERO.py, examples/Training/python/Render_Images.py, examples/Training/python/Write_Data.py
Following #3606, added a few more examples using new features of the Blitz Gateway.
To test, read examples, then run (edit image Ids and login credentials as needed)
```
$ cd examples/Training/python
$ python Connect_To_OMERO.py
$ python Render_Images.py
$ python Write_Data.py
```
=> Examples mapannotation etc

components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/DataLoader.java, components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/chooser/LocationDialog.java, components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/util/FileImportComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/view/ImportLocationDetails.java, components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterModel.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/OMEROGateway.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/OmeroImageServiceImpl.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/model/ImportableObject.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/util/SecurityContext.java
Allow group owner to import data for another member of the group.
Test:
* Log in as group owner and import data for another. e.g. user-1 and user-3.
* Check that you can still import as an admin.
=> Import as owner

components/blitz/resources/omero/api/IAdmin.ice
see http://downloads.openmicroscopy.org/omero/5.1.0-m4/api/slice2html/omero/cmd.html
--no-rebase
=> adjust deprecation comments to refer to new requests

components/server/src/ome/security/policy/BinaryAccessPolicy.java
populate_roi.py was also triggering a LazyInitializationException,
so the Hibernate initialization (which throws an AssertionFailure)
has been refactored out into the method `has()`.
cc: @sbesson
=> BinaryAccessPolicy: expand AssertionFailure check

components/tools/OmeroWeb/omeroweb/feedback/urls.py, components/tools/OmeroWeb/omeroweb/feedback/views.py
This PR just clean up the code.
To test send comment from web and check if you see *thank you* page once is done.
--no-rebase
=> code improvement

components/tools/OmeroPy/src/omero/plugins/admin.py
The help message should've been updated as part of https://github.com/openmicroscopy/openmicroscopy/pull/3331
=> Include webserver in `admin ports --help` example

components/tools/OmeroJava/test/integration/ExporterTest.java
=> Tests integration

components/insight/build/dist.xml, components/insight/ivy.xml, components/model/src/ome/util/SqlAction.java, components/server/src/ome/services/mail/FailedLoginMailSender.java, etc/blitz/mail-senders.example, etc/logback.xml
* https://github.com/joshmoore/openmicroscopy/commit/a3ab0123d710da44d228f7039339e669963a6f53 - remove newGroupMailSender [trac-7745](https://trac.openmicroscopy.org.uk/ome/ticket/7745)
* https://github.com/joshmoore/openmicroscopy/commit/bed8874a05e6a2ad475e88c4765cbf99e75dd2cf - reduce logging of `AssertionFailure` in Blitz-0.log
* https://github.com/joshmoore/openmicroscopy/commit/3551b8e5b2cfbac02bfb5e8ec83a93012f7c4232 - to fix the exception seen by @manics in https://github.com/openmicroscopy/ome-documentation/pull/1139#discussion_r26649273
* https://github.com/joshmoore/openmicroscopy/commit/1e352ba9430a4eebedd64ed9a589513bfeadc8f1 - push another jar (`omero.insight.jar`) to artifactory on release.
=> 5.1.0: minor bug fixes

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorControl.java, components/insight/SRC/org/openmicroscopy/shoola/agents/util/ui/DowngradeChooser.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/OmeroImageServiceImpl.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/util/Resolver.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/util/Target.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/util/TransformsParser.java, components/insight/SRC/org/openmicroscopy/shoola/util/file/IOUtil.java
In this PR, review the way we read entries from the catalog
To test:
* Select an image. 
* Select to export it as ome-tiff
* Check that the menu with older versions is displayed
* Select an older version and click export.
* Re-import the generated ome-tiff
This should now work on mac windows and linux
Check if the option is also available when using webstart
=> Downgrade insight

components/tools/OmeroPy/test/integration/clitest/test_import.py
This PR adds tests for unknown targets and adds Screens to wrong group targets, see gh-3658  The Python integration tests should pass.  /cc @sbesson 
--no-rebase
=> Add further import target tests

history.txt
Tries to combine various lists of new features etc - focusing on user facing things and pointing developers to read the milestone release details.
Won't be built on staging until the autogen job runs.
=> 5.1.0 version history

components/tests/ui/testcases/web/webadmin_create_group_and_user.txt
Check if the Integration tests pass.
=> RobotFramework (Bug fix): Create Group And User.Check Admin Edit Self

components/tools/OmeroM/src/createObjectDictionary.m, components/tools/OmeroM/src/delete/deleteObjects.m
To Test,
Download the omeroMatlab toolbox,
Follow the delete work flow as follows,
%Params
hostname= 'localhost';  %Host address
username = 'root';  %Username for Insight
imageId= 1;
password = 'ome'; %Password for Insight
%--------------------------------------------------------------------------
%load client 
client = loadOmero(hostname);
session = client.createSession(username, password);
%delete Image
deleteImages(session, imageId);
%Similarly try:
Projects,Datasets,PlateAcquisitions,Plates and Screens
=> Matlab : Update deleteObjects

components/tools/OmeroWeb/omeroweb/webclient/forms.py
Ticket: https://trac.openmicroscopy.org.uk/ome/ticket/10577
updating format date in help text
to test it:
- open create share form and check if date format is YYYY-MM-YY
- open create discussion form and check if date format is YYYY-MM-YY
cc: @gusferguson
=> updating date format

components/tools/OmeroJava/test/integration/AdminServiceTest.java
Cleanup
Make sure that the 40 tests still run.
i.e. Make sure https://ci.openmicroscopy.org/job/OMERO-5.1-merge-integration-java/ is green
=> Change permissions

components/tools/OmeroWeb/omeroweb/webclient/views.py, setup.cfg
Fixes `webclient.views` to be `flake8` compliant. Due to the large set of changes and the GitHub limits, this PR is split into small commits for reviewing ease.
--no-rebase
=> Webclient flake8 views

examples/Training/java/config/training.config, examples/Training/java/src/training/ConfigurationInfo.java, examples/Training/java/src/training/Connector.java, examples/Training/java/src/training/CreateImage.java, examples/Training/java/src/training/DeleteData.java, examples/Training/java/src/training/ROIs.java, examples/Training/java/src/training/ReadData.java, examples/Training/java/src/training/ReadDataAdvanced.java, examples/Training/java/src/training/Setup.java, examples/Training/java/src/training/WriteData.java, examples/Training/java/src/training/util/BytesConverter.java, examples/Training/java/src/training/util/DataSink.java, examples/Training/java/src/training/util/DoubleConverter.java, examples/Training/java/src/training/util/FloatConverter.java, examples/Training/java/src/training/util/IntConverter.java, examples/Training/java/src/training/util/Plane2D.java, examples/Training/java/src/training/util/ReadOnlyByteArray.java, examples/Training/java/src/training/util/UintConverter.java
Review the examples under training, modify reading of initial parameter so it can be part of CI job.
Marking on hold for now.
=> Example java

components/tests/python/library/__init__.py, components/tools/OmeroPy/test/integration/test_chgrp.py
This PR follows from a comment at https://github.com/openmicroscopy/openmicroscopy/pull/3696#issuecomment-90985790
The only tests affected are the ones modified in this PR, they should pass.
/cc @sbesson 
--no-rebase
=> Factor out doAllSubmit from test library.

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/DocComponent.java
In #3604 the view menu entry was removed, because in the scope of the OMERO.Editor removal it lost it's functionality. This PR brings the menu entry (and it's functionality) back.
Test:
Attach a file to an image; use "View" to open the file with your desktop's default application for this file type.
/cc @pwalczysko
=> FileAnnotation View button

components/tools/OmeroPy/test/integration/test_isession.py
See the linked tickets for details. With this,
there should be a few more green tests.
Tickets:
* https://trac.openmicroscopy.org.uk/ome/ticket/11542
* https://trac.openmicroscopy.org.uk/ome/ticket/2662
=> test_isession.py: remove a few broken markers

components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/ome.chgrp.js, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/chgrp_target_tree.html
Fixes https://trac.openmicroscopy.org.uk/ome/ticket/12798
Now the chgrp dialog asks you to choose a group and gives you a better warning if you hit 'OK' without choosing a group.
=> chgrp dialog clearer

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/metadata_preview.html
Fixes https://trac.openmicroscopy.org.uk/ome/ticket/12799
To test, browse SPW to open Preview panel for image in well.
- Edit rendering settings
- Click "Save To All"
- Should see settings applied to plate and thumbnails should update.
=> Save All for Plates

components/blitz/src/loci/ome/io/OmeroReader.java, components/insight/SRC/org/openmicroscopy/shoola/util/roi/io/ROIReader.java
Testing instructions:
1) Download and add the OMERO-IJ plugin to the Plugins folder of ImageJ.
2) Open an OMERO image on ImageJ using the Omero-IJ plugin.
3) Add ROIs to image (using the ROIManager/overlays). 
4) Now : Plugins --> OMERO --> Save ROIs to OMERO.
5) This should save all the ROI's to the OMERO image.
To Check:
1) Open the image on insight, using the view option within the plugin.
2) Check if the newly created ROI's have the correct Z and T information associated with them.
=> Omero-IJ Plugin : Roi reader update Z T

components/tools/OmeroWeb/omeroweb/webgateway/templates/webgateway/viewport/omero_image.html
This updates the help message available from the (?) button in the viewer 'Edit Channels' dialog to reflect changes in updating the settings (don't need to click "Apply").
=> Viewer "Changing display settings" text

history.txt
Based on draft text from https://trello.com/c/oac6QylW/318-5-1-1-omero-history-txt
=> Adding version 5.1.1 version history

history.txt
Update to history as discussed on #3758 cc @joshmoore
=> Remove GraphModify2 from history

components/tools/OmeroJava/test/integration/ModelMockFactory.java, components/tools/OmeroJava/test/integration/UpdateServiceTest.java
Add tests to annotate roi and shape
Also add missing tests to annotate plate acquisition
To test:
* Make sure https://ci.openmicroscopy.org/view/5.1/job/OMERO-5.1-merge-integration-java/ is green
=> Roi annotation

components/insight/SRC/org/openmicroscopy/shoola/env/ui/ActivityComponent.java, components/insight/SRC/org/openmicroscopy/shoola/env/ui/DownloadsDialog.java, components/insight/SRC/org/openmicroscopy/shoola/env/ui/FileLoadingComponent.java
Replace "delete" icon (red cross) by "Remove" text in activity dialog
To test;
* Delete an image for example
* When the action is completed. Check that  a "remove" is displayed on the row instead of the red cross icon
cc @gusferguson @kennethgillen
=> Activity icon

components/server/src/ome/logic/LdapImpl.java
Previously, non-ldap groups were stripped from a user if
sync_on_login was set to true since the newly added `ldap`
flagged was not being checked. By only listing LDAP groups
for potential removal, manually-added, non-LDAP groups can
be maintained.
* Connect your server to a test LDAP instance.
* Login as a known user and check that they are present in the expected LDAP groups.
* Create a local, non-LDAP group via `bin/omero group add`
* Add the user via `bin/omero group adduser --name X --user-name Y`
* Check in `bin/omero user list` that the user is now in one extra group
* **Remove the user from one of the expected LDAP groups in the LDAP DB** (tricky)
* Create a new session as the user `bin/omero login -C Y@localhost`
* List the groups that the user is a member of `bin/omero user …
=> Fix sync_on_login

components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/StatusBar.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/border/ImageBorder.java
Trivial fix to Insight code, should be no change in behavior.
--no-rebase
=> correct "right" typo

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/mapannotations.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/includes/center_plugin.thumbs.js.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/plate.html, components/tools/OmeroWeb/omeroweb/webclient/views.py
Fixes https://trac.openmicroscopy.org.uk/ome/ticket/12857
To test:
- Add map annotation to well (saves to Image in well)
- Reload well to check it has been saved
- Try choosing different Field index to check annotation is added to correct index.
=> Map annotation of Wells

components/tools/OmeroJava/test/integration/delete/HierarchyDeleteTest.java
Review the code to check that the scenario that the test recreates corresponds with the bug described in http://trac.openmicroscopy.org/ome/ticket/12856. Try running it to see that it fails on the line you would expect.
Cc: @will-moore 
--no-rebase
=> assist #12856: add deletion integration test for projections

components/insight/SRC/org/openmicroscopy/shoola/env/data/model/FileObject.java
Handle file opened from URL. see https://trac.openmicroscopy.org.uk/ome/ticket/12849
* Open an image in ImageJ using File> Open Samples.
* Import the image to OMERO using the OMERO.ij plugin
* The image should now import.
=> ImageJ import

components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/AcquisitionDataLoader.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewer.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerUI.java
Show magnification (if data is available) instead of percentage zoom level. This PR basically does the same as #2291 just for Insight;
Test: also see PR #2291 and compare Insight and Web.
Fixes ticket: https://trac.openmicroscopy.org/ome/ticket/12201
=> Show magnification

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/containers.html
Fixing https://trac.openmicroscopy.org.uk/ome/ticket/11563
To test:
- right click on Screen, Plate, Acquasition and see if Create New is active. Then create new object.
=> enabling right click create menu on S/P/W

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/view/MetadataViewerComponent.java
Fix possible NPE when updating a tag. reported via QA system
To test:
* Select a tag in the tree (left-hand panel)
* Update the tag (right-hand panel)
* Save
=> Tag update

components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/ImViewerAgent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/actions/ROIToolAction.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ToolBar.java
Turn off the measurement tool when insight is used as a plugin.
Having it on leads to issue when the plugin is used in Fiji
To test:
* add the insight-ij plugin to the plugin folder of imageJ and Fiji
* Check that you cannot access the measurement tool.
=> Imagej roi

components/tools/OmeroWeb/omeroweb/webclient/views.py
Fixes https://trac.openmicroscopy.org/ome/ticket/12870
To test:
- Select a Well and try Rating it.
- Reload the Well to test that rating has been applied.
- Try to rate wells at different field indices.
=> Rating of Wells

components/tools/OmeroWeb/omeroweb/settings.py, components/tools/OmeroWeb/omeroweb/webadmin/forms.py, components/tools/OmeroWeb/omeroweb/webclient/views.py
this allows disabling check_version
test locally
cc @will-moore
=> making check_version configurable

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/scripts/include_param.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/scripts/script_ui.html
This is #3881 Closed and re-opened here because of an accidental force push of a wrong branch.
----
Fixes https://trac.openmicroscopy.org/ome/ticket/12080
To test:
- Open a script from the scripts menu
- On opening, the "focus" should be on the first input.
- Tab key should move you through all the fields, going to "Run Script" *before* "Cancel".
=> Script ui tabbing 12080

components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterUIElement.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/DeleteBox.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/UIUtilities.java
In this wrap, we fix the text wrapping
see https://trac.openmicroscopy.org.uk/ome/ticket/12890
To test:
* log as a group owner e.g. user-1
* Select a project
* Click delete
* Check that the text in red is wrapped
=> Line break

components/server/src/ome/services/query/PojosGetImagesByOptionsQueryDefinition.java, components/server/src/ome/services/query/PojosGetImagesQueryDefinition.java, components/tools/OmeroJava/test/integration/ModelMockFactory.java, components/tools/OmeroJava/test/integration/PojosServiceTest.java
Load the format when loading the image
=> Load format

components/blitz/src/omero/gateway/Gateway.java, components/blitz/src/omero/gateway/facility/Facility.java
Bugfix for the user switching problem
=> Fixed user switching problem

components/blitz/src/omero/gateway/Gateway.java, components/blitz/src/omero/gateway/exception/DSOutOfServiceException.java, components/blitz/src/omero/gateway/facility/Facility.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/ExperimenterDataLoader.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/browser/BrowserComponent.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/ConnectionExceptionHandler.java
This fixes the outstanding reconnection issue, see [Trello Test Checklist](https://trello.com/c/2WY5iyS7/8-java-gateway)
=> Reconnection fix (decoupling)

components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/util/ui/KeyDescription.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/MeasurementResults.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/MeasurementTableModel.java, components/insight/SRC/org/openmicroscopy/shoola/util/file/ExcelWriter.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/UIUtilities.java
See https://trac.openmicroscopy.org/ome/ticket/12952
To test:
* Open an image e.g. dv and draw a roi. Select the shape
* Go to the Results tab
* Export the results to excel
* Check that the values are correctly displayed in the excel sheet.
cc @pwalczysko
=> Export to Excel

components/tools/OmeroPy/src/omero/plugins/export.py, components/tools/OmeroPy/test/integration/test_client_ctors.py
See gh-3997 for discussion. The integration tests should pass.
(Minor typo fixed by @mtbc included here so that it doesn't feel lonely in its own PR)
=> Add an additional Python client ctor test

components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/chooser/FileSelectionTable.java, components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/chooser/ImportDialog.java, components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/util/FileImportComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/util/SaveResultsDialog.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/model/FileObject.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/model/ImportableFile.java
see https://trello.com/c/shcz0N2C/22-imagej-omero-round-trip
test 1:
* Open a mif from local file system
* Do not select all series.
* Save the images to OMERO
* After saving, Draw a roi on the image
* Click Save ROIs.
* Check that no dialog indicating "Do you want to import images..." pops up
* Check that the rois are saved.
test 2:
* Repeat the same steps with a tiff file
test 3:
* repeat the same steps with a single file e.g. dv
-----
extra tests:
test 4:
* Open a mif from local file system
* Do not select all series e.g. 2 series
* Save the images to OMERO but this time Select "Images from all windows"
* Check that the image is only imported once.
test 5:
* Open a mif from local file system
* Do not select all series e.g. 2 series
* Draw some rois
* Select the "save …
=> ij-omero round trip

components/tests/ui/resources/web/tree.txt, components/tests/ui/testcases/web/delete_test.txt, components/tests/ui/testcases/web/forms_test.txt, components/tests/ui/testcases/web/rdef_test.txt
This is the same as gh-3994 but rebased onto dev_5_1.
----
Following robot framework test improvement story this PR remove sleep and improved some of the tests
=> Improving form tests (rebased onto dev_5_1)

components/tests/ui/resources/web/tree.txt, components/tests/ui/testcases/web/delete_test.txt, components/tests/ui/testcases/web/forms_test.txt, components/tests/ui/testcases/web/rdef_test.txt
Following robot framework test improvement story this PR remove sleep and improved some of the tests
=> Improving form tests

components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/chooser/FileSelectionTable.java, components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/chooser/ImportDialog.java, components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/util/FileImportComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/util/SaveResultsDialog.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/model/FileObject.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/model/ImportableFile.java
--rebased-from #4001
test 1:
* Open a mif from local file system
* Do not select all series.
* Save the images to OMERO
* After saving, Draw a roi on the image
* Click Save ROIs.
* Check that no dialog indicating "Do you want to import images..." pops up
* Check that the rois are saved.
test 2:
* Repeat the same steps with a tiff file
test 3:
* repeat the same steps with a single file e.g. dv
-----
extra tests:
test 4:
* Open a mif from local file system
* Do not select all series e.g. 2 series
* Save the images to OMERO but this time Select "Images from all windows"
* Check that the image is only imported once.
test 5:
* Open a mif from local file system
* Do not select all series e.g. 2 series
* Draw some rois
* Select the "save rois" options (not save images …
=> Mif ij dev 5 1

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/MapAnnotationsComponent.java
Add null check if no table found
Select an image w/o map annotations
and click on the green + button above table annotation
cc @imunro
=> Add null check if no table.

components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/omero_image.js
This should fix channel buttons issue reported in https://trac.openmicroscopy.org/ome/ticket/12981
Test both channel buttons in Preview, Main viewer and rendering popup box in Viewer
cc: @pwalczysko
=> fixing channel background-colour

components/tests/ui/resources/web/login.txt, components/tests/ui/testcases/web/rdef_test.txt, components/tests/ui/testcases/web/search.txt, components/tests/ui/testcases/web/view_image.txt
cleaning up search tests, removing duplicates
=> improving robot tests

components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/omero_image.js
This is minor fix following https://github.com/openmicroscopy/openmicroscopy/pull/4041.
Check if Web.Rdef Test https://ci.openmicroscopy.org/job/OMERO-5.1-merge-robotframework/
didn't fail on ``KEYWORD: Wait For Channel Color rgb(...)``
--no-rebase
as it was cherry-picked to https://github.com/openmicroscopy/openmicroscopy/pull/4048
=> minor syntax update

components/tests/ui/robot_setup.sh
=> adding timestamp to robot user name to decouple

components/tests/ui/robot_setup.sh
This is the same as gh-4072 but rebased onto dev_5_1.
----
Decoupling robot Job
=> adding timestamp to robot user name to decouple (rebased onto dev_5_1)

components/tests/ui/resources/web/login.txt, components/tests/ui/testcases/web/rdef_test.txt, components/tests/ui/testcases/web/search.txt, components/tests/ui/testcases/web/view_image.txt
This is the same as gh-4030 but rebased onto dev_5_1.
----
cleaning up search tests, removing duplicates
=> improving robot tests (rebased onto dev_5_1)

components/tests/ui/resources/web/login.txt
reverting speed param used by CHROME deleted accidentally in https://github.com/openmicroscopy/openmicroscopy/pull/4030
--no-rebase
=> reverting speed param

components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/omero_image.js
This is the same as gh-4041 but rebased onto develop.
----
This should fix channel buttons issue reported in https://trac.openmicroscopy.org/ome/ticket/12981
Test both channel buttons in Preview, Main viewer and rendering popup box in Viewer
cc: @pwalczysko
=> fixing channel background-colour (rebased onto develop)

components/tools/OmeroPy/src/omero/util/ROI_utils.py, components/tools/OmeroPy/test/unit/test_rois.py, components/tools/OmeroWeb/omeroweb/webgateway/views.py
There are (at least) 2 formats for storing Points in ROI Polygons. The webgateway only had one of them.
https://trello.com/c/hJLlf1Xr/47-error-on-preview-rois
Are there any other formats?
=> Handle new ROI Points string format

build.xml
This is the same as gh-4068 but rebased onto develop.
----
This is the same as gh-4058 but rebased onto dev_5_1.
----
Following migration of the Virtual Appliance scripts to a standalone repository, this commit cleans up the duplicate scripts under the main source code repository.
/cc @manics
=> Clean up VM installation folder (rebased onto dev_5_1) (rebased onto develop)

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/util/FilesetInfoDialog.java
See [Ticket 12905](https://trac.openmicroscopy.org/ome/ticket/12905)
Test: Check the File path info dialog shows the correct number of files (compare with OMERO.Web)
=> Fixed wrong file count

components/tools/OmeroPy/src/omero/cli.py
See gh-4088 for testing info.
--rebased-from #4088
=> Tidy up some CLI file errors (dev)

components/insight/SRC/org/openmicroscopy/shoola/env/data/Connector.java
Same as #4052 , rebased to dev_5_1
=> Set sudo sessions timeout (rebased to dev_5_1)

components/tests/ui/resources/robot.template, components/tests/ui/testcases/web/delete_test.txt
This fixes delete tests. It removes sleep and set timeout now to 60 sec.
=> Improving robot

examples/Training/matlab/ConnectToOMERO.m, examples/Training/matlab/ReadData.m, examples/Training/matlab/WriteData.m, examples/Training/matlab/parseOmeroProperties.m, examples/Training/training_setup.sh
This PR rebases the additional commits included in in https://github.com/openmicroscopy/openmicroscopy/pull/4111 to test the group support via the training examples.
To test this PR, check https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-merge-training/ is green
--rebased-from https://github.com/openmicroscopy/openmicroscopy/pull/4111
=> Matlab group support training

components/rendering/src/omeis/providers/re/quantum/Quantization_32_bit.java, components/rendering/src/omeis/providers/re/quantum/Quantization_float.java, components/rendering/src/omeis/providers/re/quantum/QuantumStrategy.java
Fix problem related to floating point rendering (and 32-bit)
See ticket https://trac.openmicroscopy.org/ome/ticket/12912
To test:
* import image from QA 11111 and check https://www.openmicroscopy.org/community/viewtopic.php?f=4&t=7825  for details of problem
* also image ​https://trout.openmicroscopy.org/merge/webclient/img_detail/24054/ under user-1 should be fixed.
cc @sbesson
=> Rendering issue dev_5_1

components/rendering/src/omeis/providers/re/quantum/Quantization_32_bit.java, components/rendering/src/omeis/providers/re/quantum/Quantization_float.java, components/rendering/src/omeis/providers/re/quantum/QuantumStrategy.java
This is the same as gh-4104 but rebased onto develop.
----
Fix problem related to floating point rendering (and 32-bit)
See ticket https://trac.openmicroscopy.org/ome/ticket/12912
To test:
* import image from QA 11111 and check https://www.openmicroscopy.org/community/viewtopic.php?f=4&t=7825  for details of problem
* also image ​https://trout.openmicroscopy.org/merge/webclient/img_detail/24054/ under user-1 should be fixed.
cc @sbesson
=> Rendering issue dev_5_1 (rebased onto develop)

components/tools/OmeroPy/src/omero/plugins/tag.py, components/tools/OmeroPy/test/integration/clitest/test_tag.py
See gh-4134 for testing instructions.
--rebased-from #4134
=> List empty tagsets when using omero tag list (rebased)

components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/browser/BrowserModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/util/ImagePaintingFactory.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerControl.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerFactory.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ToolBar.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/DomainPane.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/PreviewCanvas.java, components/insight/SRC/org/openmicroscopy/shoola/env/LookupNames.java
This is the same as gh-4087 but rebased onto dev_5_1.
----
Same as #4084 but for Insight. 
Test: Best to be tested in conjunction with #4084 .
=> Interpolate config option (rebased onto dev_5_1)

components/common/src/omeis/providers/re/RGBIntBuffer.java, components/tools/OmeroJava/test/integration/delete/AnnotationDeleteTest.java
Minor code tweaks. Ensure that they make sense and that CI is green. See https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-java/lastCompletedBuild/testngreports/integration.delete/AnnotationDeleteTest/.
=> fix AnnotationDeleteTest

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/ChannelAcquisitionComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/util/EditorUtil.java
This is the same as gh-4149 but rebased onto dev_5_1.
----
Same as #4131 just for Insight.
Test: See test instructions on the above mentioned PR, compare with OMERO.Web.
=> Display times in more readable way (rebased onto dev_5_1)

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/ChannelAcquisitionComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/util/EditorUtil.java
Same as #4131 just for Insight.
Test: See test instructions on the above mentioned PR, compare with OMERO.Web.
=> Display times in more readable way

components/insight/SRC/org/openmicroscopy/shoola/env/LookupNames.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/DataServicesFactory.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/OMEROGateway.java, components/insight/SRC/org/openmicroscopy/shoola/env/init/AgentsInit.java
This PR sets the correct agent when insight is run as an imageJ plugin.
cc @aleksandra-tarkowska
=> Register imageJ agent.

history.txt
Initial stab at picking out relevant content. Will add blog post link for webstart once I get that sorted, hopefully later today.
=> 5.1.4 version history

history.txt
This is the same as gh-4198 but rebased onto develop.
----
Initial stab at picking out relevant content. Will add blog post link for webstart once I get that sorted, hopefully later today.
=> 5.1.4 version history (rebased onto develop)

components/insight/SRC/org/openmicroscopy/shoola/env/LookupNames.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/DataServicesFactory.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/OMEROGateway.java, components/insight/SRC/org/openmicroscopy/shoola/env/init/AgentsInit.java
same as gh-4190
Register the imagej plugin and importer agent correctly
* Check that the agent is correctly set in session table
* Check that we have one hit in the record
cc @dominikl @aleksandra-tarkowska 
--rebased-from #4190
=> Imagej agent develop

components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/browser/BrowserModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/util/ImagePaintingFactory.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerControl.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerFactory.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ToolBar.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/DomainPane.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/PreviewCanvas.java, components/insight/SRC/org/openmicroscopy/shoola/env/LookupNames.java
Same as #4084 but for Insight. 
Test: Best to be tested in conjunction with #4084 .
=> Interpolate config option

components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/chooser/ImportDialog.java, components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/util/SaveResultsDialog.java, components/insight/SRC/org/openmicroscopy/shoola/util/roi/io/ROIReader.java
This is the same as gh-4170 but rebased onto develop.
----
This PR combines commits from gh-4046 and gh-4045
Improve support of rois from ImageJ
Matches changes made in https://github.com/openmicroscopy/bioformats/pull/1974
To test:
* Follow scenarios described in https://github.com/openmicroscopy/bioformats/pull/1974
Cc @pwalczysko @stelfrich
=> Roi position (rebased onto develop)

components/insight/SRC/org/openmicroscopy/shoola/env/Container.java, components/insight/SRC/org/openmicroscopy/shoola/util/file/IOUtil.java
Remove ref to webstart in insight code.
=> Webstart insight

components/antlib/resources/global.xml, components/insight/build/build.xml, components/tools/bump_bf_version.py, etc/build.properties, etc/ivysettings.xml
See https://trello.com/c/EnGt2XDX/73-rename-local-properties-example
=> Rename local.properties.example as build.properties

components/insight/SRC/org/openmicroscopy/shoola/env/data/model/FileObject.java
Fix issue https://github.com/openmicroscopy/openmicroscopy/issues/4033
To Test:
* Open any image an save it to TIFF. 
* Open the newly created TIff image
* Save that image to OMERO (Plugins > OMERO > Save Image(s) to OMERO).
cc  @bramalingam 
Also test the parsing of the string with @bramalingam macro
--rebased-from #4034
=> new image(Develop)

components/insight/SRC/org/openmicroscopy/shoola/agents/util/EditorUtil.java
Remove the check if the image has a companion file
to test;
* Import an image
* Tag the image.
* Check that the "yellow" flag is displayed in the tree.
=> Annotation flag

components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/actions/SaveAction.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/browser/BrowserBICanvas.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/browser/BrowserModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/util/saver/ImgSaver.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewer.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/ToolBar.java, components/insight/SRC/org/openmicroscopy/shoola/env/LookupNames.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/model/SaveAsParam.java
Corresponding Insight PR to  #4262
Limits the export as jpg/png/tif function to a certain maximum image size.
Test: See instruction on above mentioned PR
=> Limit max export size

components/tools/OmeroPy/src/omero/plugins/web.py
This should fix https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-merge-deploy-win2012/13/console
cc: @sbesson
=> adding missing argument

components/tools/OmeroPy/src/omero_web_iis.py
updating wsgi handler as stated in https://docs.djangoproject.com/en/1.8/releases/1.7/#wsgi-scripts
=> updating wsgi app handler

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/GeneralPaneUI.java
Hide name, owner and id labels on multiselection.
=> Don't show name,owner,id on multiselection

components/tests/python/library/__init__.py, components/tools/OmeroWeb/omeroweb/webgateway/views.py, components/tools/OmeroWeb/test/integration/test_metadata.py
See https://trello.com/c/S302zihJ/52-web-crashes-if-plate-nsbulkannotations-isn-t-a-fileannotation
This follows on from https://github.com/openmicroscopy/openmicroscopy/pull/3875/files#diff-fc3a666f42c5099bec2593d6f4b4cf2dR2312
=> Check for FileAnnotations when looking for bulk-annotations

history.txt
Last minute updates to the `history.txt` file. The release announcement draft will need to be kept up-to-date.
cc: @hflynn
=> Minor history changes

components/tools/OmeroWeb/requirements-py26-iis.txt
For discussion with https://github.com/openmicroscopy/ome-documentation/pull/1322
=> Add requirements-py26-iis.txt

components/blitz/src/omero/gateway/Gateway.java, components/blitz/src/omero/gateway/LoginCredentials.java, components/tools/OmeroJava/test/integration/gateway/GatewayUsageTest.java
Add option to login by passing arguments
This should be tested using the minimal-omero-client
=> Gateway login

components/tools/OmeroPy/src/omero/plugins/admin.py
As reported in http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-November/005719.html, the rewrite subcommand could use a more descriptive help.
=> Expand admin rewrite help

components/blitz/src/omero/cmd/graphs/DuplicateI.java
This gets some small server code/doc adjustments into 5.2.1. They're from branches of larger work that will go into later versions, but we may as well avoid making releases without these small improvements in. Everything should remain green.
--no-rebase
=> small adjustments to server code/doc

components/tools/OmeroJava/test/integration/DuplicationTest.java
Adds a test that involves images sharing annotations. See https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-java/lastCompletedBuild/testngreports/integration/DuplicationTest/.
--no-rebase
=> add further integration test for Duplicate

components/tools/OmeroWeb/omeroweb/feedback/sendfeedback.py
This PR upgrades url library to send feedback
To test:
- open private/incognito window to avoid web browser cache.
- go to https://eel.openmicroscopy.org/merge/weberror/error_500/ | https://cowfish.openmicroscopy.org/merge/weberror/error_500/
- send feedback
- check new feedback in https://qa.staging.openmicroscopy.org/
cc @sbesson @pwalczysko
=> Feedback upgrade

components/tools/OmeroPy/src/omero_web_iis.py
This is follow up PR #4290, which that should allow deploy with Django 1.8 https://trello.com/c/d7pYClU9/64-windows-py2-7-django-1-8-iis
=> Call setup

components/tools/OmeroWeb/requirements-py26-apache.txt, components/tools/OmeroWeb/requirements-py26-nginx.txt, components/tools/OmeroWeb/requirements-py27-apache.txt, components/tools/OmeroWeb/requirements-py27-nginx.txt, components/tools/OmeroWeb/requirements-py27-win.txt
this PR removes comments only, as requested in https://github.com/openmicroscopy/openmicroscopy/pull/4319
nothing to test :)
=> removing temporary comment from requirements

components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/actions/UploadScriptAction.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewer.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewerComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/util/ui/ScriptUploaderDialog.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/OMEROGateway.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/OmeroImageService.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/OmeroImageServiceImpl.java, components/insight/SRC/org/openmicroscopy/shoola/env/ui/ScriptUploader.java
Implements [Ticket 13111](https://trac.openmicroscopy.org/ome/ticket/13111)
Test: Try to upload a faulty script. You should get an error dialog providing some information what's wrong with the script.
=> Pass on ValidationException info to user

history.txt
Autogen build needs to run before this will be displayed in staging docs but the formatting should be fine.
=> 5.2.1 version history

components/tools/OmeroWeb/omeroweb/webclient/controller/container.py, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/mapannotation.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/metadata_general.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/search/search.html, components/tools/OmeroWeb/omeroweb/webclient/views.py, components/tools/OmeroWeb/omeroweb/webgateway/templates/webgateway/viewport/omero_image.html
These are quick fixes that can be done more nicely further down the line.
+ Disable Show Rois (hard-coded)
+ Default to “All users” for search (hard-coded)
+ Map annotation above Table of annotations
=> IDR web tweaks

components/tools/OmeroPy/src/omero/plugins/metadata.py, components/tools/OmeroPy/src/omero/util/metadata_utils.py, components/tools/OmeroPy/src/omero/util/populate_metadata.py, components/tools/OmeroPy/test/unit/test_metadata_utils.py
=> Cli metadata more

.travis.yml, components/tools/travis-build
The original PR was closed.  This is the travis-specific part of the PR, so it will build with Ice 3.5 from downloads.openmicroscopy.org.
--------
Testing: check travis is green.
=> travis: Build with Ice from downloads.openmicroscopy.org

.travis.yml
This will send notifications to the #travis room.
=> Add slack notification to .travis.yml

components/blitz/src/omero/gateway/facility/BrowseFacility.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ControlPane.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/util/TreeCellRenderer.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/model/ProjectionParam.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/PopupHint.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/slider/TwoKnobsSlider.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/slider/TwoKnobsSliderModel.java, components/tools/OmeroJava/test/integration/gateway/BrowseFacilityTest.java
Fixed bugs and how to test them:
- [Ticket 13137](http://trac.openmicroscopy.org/ome/ticket/13137) : Hardly reproducible, maybe code review of 32b359f is sufficient.
- [Ticket 13141](http://trac.openmicroscopy.org/ome/ticket/13141) : Repeat the workflow which triggered the bug, see first comment on the ticket.
- [QA 16976](https://www.openmicroscopy.org/qa2/qa/feedback/16976/) : Move the separator which separates the left hand side tree panel (while showing the project/datasets tree) and the center panel as far too the left as possible.
- [Ticket 13069](http://trac.openmicroscopy.org/ome/ticket/13069) : Also hardly reproducible, code review only, see c28c76f
=> Various bugfixes

components/tools/OmeroWeb/omeroweb/webclient/controller/search.py, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/search/search.html, components/tools/OmeroWeb/omeroweb/webclient/webclient_utils.py, components/tools/OmeroWeb/test/unit/test_util.py
This silently ignores any invalid date formats in the search form. See https://trello.com/c/ai1te7XA/40-search-date-formatting
- To test, go to search page and click on Start Date input.
- The date-picker will popup but it is still possible to type numbers into the input.
- Type in an invalid date (random numbers) and perform search.
- Invalid date should be ignored (not throw exception).
=> Search date format

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/search/search.html, components/tools/OmeroWeb/omeroweb/webclient/views.py
Disable id helper in search and allow search in all groups by default, as tweaked in #4246
=> Search temp fix

components/blitz/src/omero/gateway/facility/BrowseFacility.java, components/blitz/src/omero/gateway/facility/ROIFacility.java, components/blitz/src/omero/gateway/model/FolderData.java, components/blitz/src/omero/gateway/util/PojoMapper.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/util/roitable/ROINode.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/util/roitable/ROITableCellRenderer.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/ROITable.java, components/tools/OmeroJava/test/integration/RoiServiceTest.java, components/tools/OmeroJava/test/integration/gateway/BrowseFacilityTest.java, components/tools/OmeroJava/test/integration/gateway/GatewayTest.java, components/tools/OmeroJava/test/integration/gateway/ROIFacilityTest.java
Step 2 of the Insight integration of ROI folders:
- Fixed minor outstanding issues of #4450 (FolderData null checks and ROIService integration test)
- Fixed ROI propagation for ROIs in multiple folders /cc @pwalczysko 
- Take folder visibility into account to determine visibility of ROIs /cc @pwalczysko 
- Display multi-level hierarchy of ROI folders
=> Insight folders step2

components/blitz/resources/omero/cmd/FS.ice, components/blitz/src/omero/cmd/graphs/DiskUsageI.java, components/tools/OmeroJava/test/integration/DiskUsageTest.java, components/tools/OmeroPy/src/omero/plugins/fs.py
Tested by http://regions-ci.docker.openmicroscopy.org:8080/job/OMERO-start/lastCompletedBuild/testReport/integration/DiskUsageTest/.
=> Have DiskUsage request include contents of Folders

components/server/src/ome/security/auth/PersonContextMapper.java, etc/omero.properties
Being "blessed" with a middle name myself, this is somewhat important to me. This was tested on the active directory installation here. 
I'm unsure about the changes I made to getControls(). I wasn't sure how they are being used, or how to test them.
=> Also allow mapping of middleName via omero.ldap.user_mapping

etc/omero.properties
This should be in preparation of OMERO 5.3.0-m1
=> Set Bio-Formats version to 5.2.0-m1 for upcoming OMERO milestone

components/blitz/src/omero/gateway/facility/ROIFacility.java
This PR fixes https://github.com/openmicroscopy/openmicroscopy/pull/4471#issuecomment-188358315 
Note: The workflow for triggering the bug is slightly different:
- Import an image which also contains folders and ROIs, e. g. a Folder A contains ROI R1
- Draw an ROI R2, but don't save it
- Add R2 to Folder A (without the PR this triggers an OptimisticLockException on R1)
=> Insight folders Step 3.0 - Bugfixes 

etc/omero.properties
This should allow Bio-Formats/OMERO coupled PRs to be reopened against this line. /cc @mtbc
=> Bump Bio-Formats to 5.2.0-SNAPSHOT for the next development cycle

history.txt
Missing from history.
The change matches the release announcement https://www.openmicroscopy.org/community/viewtopic.php?f=11&t=8008&p=16801#p16801
=> Bump bio-formats version history

components/blitz/src/omero/cmd/graphs/Chgrp2I.java, components/blitz/src/omero/cmd/graphs/Chmod2I.java, components/blitz/src/omero/cmd/graphs/Chown2I.java, components/blitz/src/omero/cmd/graphs/Delete2I.java, components/blitz/src/omero/cmd/graphs/DuplicateI.java, components/blitz/src/omero/cmd/graphs/GraphHelper.java, components/blitz/src/omero/cmd/graphs/GraphUtil.java, components/tools/OmeroJava/test/integration/chgrp/AnnotationMoveTest.java
Refactors common code out of the new graph request implementations. Should reduce total code lines while not changing behavior. CI should be green.
--no-rebase
=> refactor graph requests' common code

components/tools/OmeroPy/src/omero/plugins/obj.py
This PR tries to fix a problem seen by @aleksandra-tarkowska relating to gh-4508  This needs to be tested using Ola's workflow for deploying a server.
=> Fix import in obj plugin

components/insight/SRC/org/openmicroscopy/shoola/env/data/OMEROGateway.java
Tiny PR for fixing [Ticket 13187](https://trac.openmicroscopy.org/ome/ticket/13187)
**Test**: Download an archived image file.
=> Prevent NPE, download archived files

components/blitz/src/omero/gateway/facility/BrowseFacility.java, components/blitz/src/omero/gateway/facility/ROIFacility.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/util/roimenu/ROIPopupMenu.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/MeasurementViewerModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/ObjectManager.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/ROITable.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/ROIFolderSaver.java, components/tools/OmeroJava/test/integration/gateway/DataManagerFacilityTest.java, components/tools/OmeroJava/test/integration/gateway/ROIFacilityTest.java
Improves the performance for various ROI/Folder actions.
See [Trello - ROI Folder performance testing](https://trello.com/c/40dqTDE8/59-roi-folder-performance-testing)
**Test** Check performance with an image with 1000+ ROIs and within a group which additionally has thousands of unrelated ROIs. Check integration tests (http://regions-ci.docker.openmicroscopy.org:8080/job/OMERO-start/lastCompletedBuild/testReport/)
=> Improve roi/folder action performance

components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/ExperimenterImageLoader.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/browser/BrowserUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/util/DataMenuItem.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/util/GroupItem.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/ToolBar.java, components/insight/SRC/org/openmicroscopy/shoola/agents/util/browser/TreeFileSet.java, components/insight/SRC/org/openmicroscopy/shoola/env/LookupNames.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/SelectableMenuItem.java
corresponding PR of #4474 for insight
Add support for new properties.
Testing: 
* Follow test used for #4474
cc @pwalczysko @aleksandra-tarkowska
=> Client properties

components/blitz/src/omero/gateway/facility/BrowseFacility.java, components/blitz/src/omero/gateway/facility/ROIFacility.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/util/model/AnnotationDescription.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/util/model/FigureTableModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/util/roimenu/ROIPopupMenu.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/MeasurementResults.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/MeasurementViewerComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/MeasurementViewerControl.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/ObjectInspector.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/ROITable.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/ROIFolderSaver.java, components/insight/SRC/org/openmicroscopy/shoola/util/roi/model/annotation/AnnotationKeys.java, components/tools/OmeroJava/test/integration/gateway/DataManagerFacilityTest.java
Implementation of https://github.com/openmicroscopy/design/issues/30
**Test**
- Make sure integration tests still pass
- Delete a folder which contains ROIs and sub folders: Make sure ROIs are orphaned and sub folders become top level folders
- Select a couple of ROIs, create a new folder via context menu: Make sure the selected ROIs are added to the newly created folder. Note: The newly created folder will be a top level folder.
- Select a ROI which is part of a Folder. Check Inspector table; the folder(s) should be mentioned there.
- Switch to Results table. Add "Folders"  to the display (via Result Wizard). Check that the folder(s) the ROIs are part of are displayed.
=> Folders step 4

components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/css/ome.header.css
Fixes https://trac.openmicroscopy.org/ome/ticket/13210
To test:
- Need to find a server with a lot of scripts (see screenshot on ticket above)
- Long list should be handled with a scrollbar automatically being added to the menu.
=> Scripts menu scrollbar

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/LightSourceComponent.java
Same as #4568 rebased to develop.
=> Fix potential class cast/NPE for unknown metadata key

components/insight/SRC/org/openmicroscopy/shoola/agents/util/browser/TreeViewerTranslator.java
see https://trac.openmicroscopy.org/ome/ticket/13040
To test:
* create via cli cyclic tag sets
* Open insight and go the tag tab
cc @mtbc
=> cyclic tag sets

components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/chooser/FileSelectionTable.java
See https://trac.openmicroscopy.org/ome/ticket/12949
To test:
* Open the importer
* Select a plate
* Click the screens tab
* Create a new screen
* Add plate to the queue
* Check that the plate is imported in the screen
=> Plate into screen

examples/RegionsOfInterest/Main.java, examples/Training/java/src/training/ROIs.java
Remove transform from example
Code review
tested by training job
=> Transform examples

history.txt
Will be staged at https://www.openmicroscopy.org/site/support/omero5.2-staging/users/history.html once the autogen branch has been built.
=> 5.2.3 version history

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditableTextComponent.java
Tiny bugfix tackling [Ticket 13201](https://trac.openmicroscopy.org/ome/ticket/13201).
**Test** workflow mentioned in ticket.
=> Bugfix: Editing tool name overwrite

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/AttachmentsTaskPaneUI.java
See [Ticket 13223](https://trac.openmicroscopy.org/ome/ticket/13223), respectively point on Trello check list [Trac Tickets to consider](https://trello.com/c/ChsrJ25E/81-trac-tickets-to-consider).
**Test** workflow mentioned in ticket.
=> Don't overwrite files with same names

components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/browser/BrowserComponent.java
Tiny bugfix for [Ticket 13229](https://trac.openmicroscopy.org/ome/ticket/13229); **Test** workflow see ticket.
=> Bugfix: Don't clear tree selection when well is selected

history.txt
Will need the autogen docs running before it can be staged at https://www.openmicroscopy.org/site/support/omero5.2-staging/users/history.html
=> Add 5.2.4 history

components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/GraphPane.java
Just added a `null` check, fix for [QA17213](https://www.openmicroscopy.org/qa2/qa/feedback/17213/).
Test: Just code review should be sufficient (couldn't replicate QA issue).
=> Fixed potential NPE

.github/Pull_Request_Template.md
See https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/ -- perhaps this is a useful start for people to help them remember what to include in their pull request descriptions.
=> add a description template for pull requests

components/tools/OmeroPy/src/omero/cli.py
This PR allows the use of elided ID sequences in the arguments to CLI graph commands. As this can be dangerous the default action for such usage is a dry-run which needs to be overridden with a `--force` flag.
As this needs access to the CLI a local server build is useful. It's also useful to be able to create objects with sequential IDs so a local running server makes that more manageable.
Create some objects and then try using various graph commands. E.g.
```
$ bin/omero obj new Dataset name=1
Dataset:251
$ bin/omero obj new Dataset name=2
Dataset:252
$ bin/omero obj new Dataset name=3
Dataset:253
$ bin/omero delete Dataset:251-253
$ bin/omero obj get Dataset:251 name # check one of those hasn't been deleted
1
$ bin/omero delete Dataset:251-253 --force
omero.cmd.Delete2 Dataset:251 ok
$ …
```
=> Use hyphens in id lists

components/tests/ui/testcases/web/webadmin_create_group_and_user.txt
Fix for long-failing robot test:
https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-robotframework/328/robot/Web%20&%20Web/Web_1/Webadmin%20Create%20Group%20And%20User/Create%20Edit%20Group/
Check if test above is still failing
=> robot test fixes create user

components/blitz/resources/omero/api/IConfig.ice, components/blitz/src/ome/formats/OMEROMetadataStoreClient.java, components/blitz/src/ome/services/blitz/repo/ManagedImportProcessI.java, components/blitz/src/ome/services/blitz/repo/ManagedImportRequestI.java, components/blitz/src/ome/services/blitz/repo/ProcessContainer.java, components/blitz/src/ome/services/blitz/repo/RawAccessRequestI.java, components/blitz/src/ome/services/blitz/repo/RepositoryDaoImpl.java, components/common/src/ome/api/IConfig.java, components/common/src/omeis/providers/re/data/PlaneDef.java, components/server/src/ome/services/query/HierarchyNavigator.java, components/tools/OmeroJava/test/integration/ImportLibraryTest.java, components/tools/OmeroJava/test/integration/chmod/PermissionsTest.java
This PR just tidies comments and whitespace. (Inspired by @jburel's cleanup PRs, I may as well join the effort.)
CI should pass. The diff should look reassuringly trivial.
=> minor cleanup

.travis.yml, components/blitz/src/ome/formats/importer/cli/CommandLineImporter.java, components/tools/OmeroPy/src/omero/plugins/import.py
Backport fixes from https://github.com/openmicroscopy/openmicroscopy/pull/4731 to metadata52.
=> Screen import fixes

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/search/search.html
This PR extends https://github.com/openmicroscopy/openmicroscopy/pull/4436 by setting the default to 'All Members' on each group.
=> Change selected to All Users/Memebers

components/blitz/src/omero/gateway/Gateway.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/DataServicesFactory.java
Bugfix for [Ticket 13267](https://trac.openmicroscopy.org/ome/ticket/13267)
Connect to a server, click on "switch user", but don't log in again, instead click on "Quit". Insight should exit (before it didn't)
=> Switch user quit

.travis.yml
Attempt to fix travis build
https://travis-ci.org/openmicroscopy/openmicroscopy/builds/151222496
=> build BF manually to fix travis test

examples/Delete/FileAnnotationDelete.java, examples/OmeroClients/constants.java, examples/OmeroClients/primitives.java, examples/OmeroClients/queries.java, examples/OmeroClients/rcollection.java, examples/OmeroClients/updates.java, examples/RegionsOfInterest/Main.java, examples/ScriptingService/Notifications.java, examples/Training/java/src/training/ReadDataAdvanced.java
Remove ``import static rtypes``
This PR unifies all the examples.
Check that example job is green
See https://trello.com/c/9nZfJ6Pi/132-import-static-cleanup
and https://github.com/openmicroscopy/openmicroscopy/pull/4758
=> Remove static import

components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/IntensityResultsView.java
Insight's "intensity results view" table is essentially unsorted. This PR sorts it sensibly regardless of the order in which ROI results were added to the table.
(Excel export is unaffected: one may easily sort in Excel however one wishes.)
Ensure that the intensity results view table continues to work properly and always maintains a sensible row sort order.
http://trac.openmicroscopy.org/ome/ticket/9992
=> in Insight keep the Intensity Results View table sorted

components/insight/SRC/org/openmicroscopy/shoola/env/data/OmeroMetadataServiceImpl.java
This PR adjusts how Insight often submits delete requests, collating deletes for many objects into a single request.
Tag a couple of hundred images and in Insight multiselect them and click in the right pane to remove tags from all the images. With this PR the unlinking should occur quite quickly. (Unlinking is deletion of a link.)
This PR's changes are more far-reaching: they affect Insight's deletion more widely. Try other bulk deletes, especially if possible mixing objects that can be deleted with ones that can't (e.g., include in multiselect some else's images or tags) to ensure there are no regressions.
http://trac.openmicroscopy.org/ome/ticket/13139
=> have metadata service collate delete requests into one

components/blitz/src/omero/gateway/LoginCredentials.java, components/blitz/src/omero/gateway/UserCredentials.java
Just a tiny javadoc PR, to add information about how to connect to OMERO via Session ID to the relevant classes.
See @mtbc 's [Ticket 13248](http://trac.openmicroscopy.org/ome/ticket/13248) , respectively the related docs PR: https://github.com/openmicroscopy/ome-documentation/pull/1535
**Nothing to test**
=> LoginCredentials javadoc

components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/util/FileImportComponent.java
Fixes some rare, randomly occurring `ConcurrentModificationException`s in the Importer component.
Make sure the Importer component still works. I couldn't find a way to trigger the initial bug, it's a random timing issue, so there's not really a specific test to perform to make sure the bug is fixed.
https://trac.openmicroscopy.org/ome/ticket/13266
=> Importer ConcurrentModificationExceptions

components/tools/OmeroM/src/annotations/getOriginalFileContent.m
This is the same as gh-4831 but rebased onto dev_5_2.
What this PR does
ref:
https://www.openmicroscopy.org/community/viewtopic.php?f=6&t=8117
Testing this PR
Test the Matlab toolbox with the code snippet given in the forum post.
Check if the test-code runs without any errors.
=> Fix the casting from *uint8 to int8

components/tools/OmeroWeb/omeroweb/urls.py
This is the same as https://github.com/openmicroscopy/openmicroscopy/pull/4843 but with the support for older version of Django
**Note: `AppConfig` is only available for Django 1.7+ although this PR contains a patch to work with 1.6.x. This is not included in develop https://github.com/openmicroscopy/openmicroscopy/pull/4843!**
-------
allows to customize app urls regardless of original web app name is and allow loading apps that has no urls.py
if the app urls need to be different then package name, custom app would have to provide `label` value using AppConfig, see https://github.com/openmicroscopy/weberror/pull/9 as an example
```
from django.apps import AppConfig
class MyWebAppConfig(AppConfig):
name = "module_name"
label = "custom_label"  # this is used by urls
```
**testing matrix: …
=> allow customizing Django apps using AppConfig (rebased onto dev_5_2)

history.txt
Adds the version history for 5.2.6
Replaced gh-4851
=> 5 2 6 history

components/romio/src/ome/io/nio/AbstractFileSystemService.java
Close formatter to avoid leak
Notice the issue when investigating the thumbnail problem reported on https://github.com/openmicroscopy/openmicroscopy/pull/4823
Code review should be enough
=> leak FileSystem Service

components/tests/python/library/__init__.py, components/tools/OmeroPy/test/integration/clitest/test_render.py
See https://github.com/jburel/openmicroscopy/pull/11
This should fix the currently failing metadata52 tests.
=> Fix render py

components/tools/OmeroWeb/omeroweb/settings.py, components/tools/OmeroWeb/omeroweb/webclient/decorators.py, components/tools/OmeroWeb/omeroweb/webclient/forms.py, components/tools/OmeroWeb/omeroweb/webclient/static/webclient/css/layout.css, components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/ome.right_panel_mapanns_pane.js, components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/ome.tagging_form.js, components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/ome.tree.js, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/includes/metadata_general_comment.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/includes/metadata_general_file.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/includes/metadata_general_map.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/includes/metadata_general_other.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/includes/metadata_general_rating.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/includes/metadata_general_table.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/includes/metadata_general_tag.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/mapanns_underscore.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/metadata_general.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/base/base_container.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/includes/center_plugin.thumbs.js.html, components/tools/OmeroWeb/omeroweb/webclient/tree.py, components/tools/OmeroWeb/omeroweb/webclient/views.py, components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/css/ome.body.css, components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/ome.csrf.js, components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/omero_image.js, components/tools/OmeroWeb/omeroweb/webgateway/views.py
This PR:
- remove ajax cache to allow caching all urls, especially API
- allow manage and reorder of metadata pane accordion. Any suggestions about var naming, dict
=> more customizations for demo 3
