components/tests/ui/resources/web/tree.txt
components/tests/ui/testcases/web/forms_test.txt
components/tests/ui/testcases/web/post_test.txt
components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/ome.viewport.js
components/tools/OmeroWeb/omeroweb/webgateway/templates/webgateway/viewport/omero_image.html

Brought a few robot fixes from develop back into dev_5_0 and also found and fixed a couple of minor bugs in the dev_5_0 image viewer.
To test image viewer fixes:
- Open image viewer. Click "color" checkbox. It should toggle greyscale (previously was broken on the first click).
- Open the 'Edit' popup. Click on the same 'color' checkbox in the main window again. Check that the 'Render as color' checkbox in the Edit panel is kept in sync (and "Save" saves the current settings).

Robot fixes backported

---

components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/util/model/FigureTableModel.java
components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/util/ui/FigureTable.java
components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/util/ui/KeyDescription.java
components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/util/ui/ResultsCellRenderer.java
components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/MeasurementResults.java
components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/MeasurementTableModel.java
components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/MeasurementViewerComponent.java
components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/MeasurementViewerModel.java
components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/MeasurementViewerUI.java
components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/ObjectInspector.java
components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/ToolBar.java
components/insight/SRC/org/openmicroscopy/shoola/util/roi/figures/MeasureBezierFigure.java
components/insight/SRC/org/openmicroscopy/shoola/util/roi/figures/MeasureEllipseFigure.java
components/insight/SRC/org/openmicroscopy/shoola/util/roi/figures/MeasureLineConnectionFigure.java
components/insight/SRC/org/openmicroscopy/shoola/util/roi/figures/MeasureLineFigure.java
components/insight/SRC/org/openmicroscopy/shoola/util/roi/figures/MeasurePointFigure.java
components/insight/SRC/org/openmicroscopy/shoola/util/roi/figures/MeasureRectangleFigure.java
components/insight/SRC/org/openmicroscopy/shoola/util/ui/UIUtilities.java
components/insight/SRC/org/openmicroscopy/shoola/util/ui/drawingtools/creationtools/BezierTool.java
components/insight/SRC/org/openmicroscopy/shoola/util/ui/drawingtools/creationtools/DrawingBezierTool.java
components/insight/SRC/org/openmicroscopy/shoola/util/ui/drawingtools/creationtools/DrawingObjectCreationTool.java

This is the same as gh-3134 but rebased onto dev_5_0.
----
Fix some issues with ROI and big images
To test:
* Import a big image (>4kx4k plane) and some non big images.
* Open the measurement tool "results" tab is displayed
* Draw a rectangle (or any other shape)
* Check that the "results" tab is displayed and columns populated. (big images)
* Check that the formatting of the results tab. (cc @dominikl)
* Check that the area is now displayed when drawing a rectangle for example
* for big images, check that the font size changes according to the resolution level. (default was always 12)

Mt big images (rebased onto dev_5_0)

---

components/insight/SRC/org/openmicroscopy/shoola/util/ui/drawingtools/figures/EllipseTextFigure.java
components/insight/SRC/org/openmicroscopy/shoola/util/ui/drawingtools/figures/RotateEllipseFigure.java

This is the same as gh-3300 but rebased onto dev_5_0.
----
Fix display of ROI
To test:
* Open the Measurement tool
* Draw an ellipse
* Click Save. 
* Check that the ellipse does not "jump" to the top-left corner.

Roi ellipse (rebased onto dev_5_0)

---

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/ChannelAcquisitionComponent.java
components/insight/SRC/org/openmicroscopy/shoola/agents/util/EditorUtil.java

Fixes the Insight issues mentioned on trello board [Units Client Follow-up](https://trello.com/c/PiLauXgp/47-units-client-follow-up). Also fixes ticket [12620](http://trac.openmicroscopy.org.uk/ome/ticket/12620) 
Test: 
1) Use file with non-default units: [alternate.ome](https://github.com/qidane/bioformats/blob/some-units-samples/components/specification/samples/develop/6x4y1z1t1c8b-swatch-instrument-units-alternate.ome);  check that the units and values are displayed correctly. 
2) Import a file with deltaT but not exposure time data (e. g. the file from [QA 10330](https://www.openmicroscopy.org/qa2/qa/feedback/10330/)), make sure deltaT values are displayed.

Insight units followup

---

components/tools/OmeroWeb/omeroweb/webclient/forms.py
components/tools/OmeroWeb/omeroweb/webclient/views.py

Follow up for metadata panel display, see: https://trello.com/c/PiLauXgp/47-units-client-follow-up
To test (using units.ome.tif to test mostly):
- Web should now do the same as Insight and show Light Source attenuation of 0.8 as "Attenuation (%): 80".
- LightSource type should be displayed for Arc and Filament objects.
- ND filter (%) should also be converted from fraction to percent, and rounded to 2 significant figures. Used a different DV file to test this.

LightSource Attenuation as percent

---

components/insight/SRC/org/openmicroscopy/shoola/agents/dataBrowser/actions/ManageRndSettingsAction.java
components/insight/SRC/org/openmicroscopy/shoola/agents/dataBrowser/view/DataBrowserComponent.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/view/MetadataViewerFactory.java
components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewerControl.java

See Ticket: [12441](http://trac.openmicroscopy.org.uk/ome/ticket/12441)
To test, check the following rendering settings workflow with Plate/Wells (expected to work like Dataset/Images) 
- Modify the rendering settings of a particular well (of a plate you are not the owner of, important for the last check)
- Copy the rendering settings
- Select a subset of other wells and paste the rendering settings
- Reset some of the wells by "Set Original and Save"
- Reset some of the wells by "Set Owner's and Save"
--no-rebase

Paste rendering settings on selected wells

---

components/blitz/resources/ome/services/blitz-graph-rules.xml

With this fix, it is no longer possible to remove one's annotations from others' data by moving one's own annotated data. Furthermore, if others annotate our data and we move it, their comments should move too (unless also attached to something not moving!) but never their own tags.
cc: @pwalczysko
--no-rebase

keep our annotations on others' data

---

components/tests/ui/testcases/web/webadmin_create_group_and_user.txt

This is the same as gh-3279 but rebased onto dev_5_0.
----
This aims to fix occasional robot failures such as:
```
06:14:06 Create Edit Group :: Tests group creation                             | FAIL |
06:14:06 Page should have contained element 'xpath=//input[@id='id_name'][@value='test_group_1418364571']' but did not
``` 
E.g. https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-robotframework/104/console
Latest group / user is selected from the table by name (instead of sorting by ID and selecting first) which should be a bit more robust.
To test, check latest
https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-robotframework/lastCompletedBuild/console

robot edit new group / user by name, instead of sort by id (rebased onto dev_5_0)

---

components/insight/SRC/org/openmicroscopy/shoola/agents/dataBrowser/browser/BrowserModel.java
components/insight/SRC/org/openmicroscopy/shoola/agents/dataBrowser/browser/ImageFinder.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorUI.java

Enables shift+click range selection for wells and disables acquisition and preview tab if multiple images/wells are selected. (Follow-up to PR #3311)

Shift click range selection for wells

---

components/tools/OmeroJava/test/integration/DiskUsageTest.java
components/tools/OmeroJava/test/integration/UpdateServiceTest.java

#2919, #3110 and #3271 were merged without any direct integration tests. Look for passes at https://ci.openmicroscopy.org/job/OMERO-5.1-merge-integration-java/lastCompletedBuild/testngreports/integration/integration.DiskUsageTest/.
--no-rebase

add integration tests for disk usage request

---

docs/hudson/OMERO-homebrew-install.sh

This is the same as gh-3185 but rebased onto develop.
----
This commit patches OMERO-homebrew-install.sh to retrieve the CSRF token and
then pass it to the POST data in a second call testing the login.
To test this PR, check the http://ci.openmicroscopy.org/job/OME-5.0-merge-homebrew/ passes while testing the development Web server.
/cc @aleksandra-tarkowska

Update the OMERO install script to test Web login with CSRF (rebased onto develop)

---

components/blitz/src/omero/cmd/graphs/GraphUtil.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/OMEROGateway.java

A weakness in the graphs reimplementation's API compatibility layer prevented Insight users from being able to move sets of images between groups where that set included both a MIF and an image script-generated from the MIF. For testing, projecting from `Beta Catenin.lif`, then moving the lot after selecting the individual images, should now work in both Insight and web, and other moves and deletes should continue to work.
Fixes http://trac.openmicroscopy.org/ome/ticket/12701.
--no-rebase

fix #12701: combine facade requests even for different target types

---

components/insight/SRC/org/openmicroscopy/shoola/agents/dataBrowser/browser/BrowserModel.java
components/insight/SRC/org/openmicroscopy/shoola/agents/dataBrowser/browser/ImageFinder.java

Fixes a bug introduced with PR #3320 , see also [Ticket 12699](http://trac.openmicroscopy.org.uk/ome/ticket/12699)
Test: Open a Dataset with several Images (or a Plate with several Wells), check that the progress bar (status bar in central panel) progresses up to 100% and then disappears again. (Before: Progressbar stopped at 50%).

Insight progress bar fix

---

components/blitz/resources/ome/services/blitz-graph-rules.xml
components/tools/OmeroJava/test/integration/chgrp/AnnotationMoveTest.java
components/tools/OmeroJava/test/integration/chgrp/HierarchyMoveAndPermissionsTest.java

Marks three integration tests as no longer broken. Integration tests should still pass. Could look for regressions regarding moving images that have owner's and others' comments and tags between groups.

assist #9610: adjust rules for moving link children

---

components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/util/saver/ImgSaver.java
components/insight/SRC/org/openmicroscopy/shoola/util/image/io/WriterImage.java

Show a sensible error message if one exports an image from the full image viewer to a file one cannot write to. (See [Trac 12627](http://trac.openmicroscopy.org.uk/ome/ticket/12627)); before: the usual crash dialog showing the stack trace popped up, followed by the incorrect message that the image was successfully exported.
Test: Open an image in full viewer, export to a read-only location (or try to overwrite a read-only file)

Show sensible error message if image export fails

---

components/tools/OmeroWeb/omeroweb/settings.py

This updates the file used to autogenerate the configuration glossary to use the new djangodoc ext links. Note, the documentation submodule will need updating before this is merged. Also updates older links to django 1.6.

djangodoc links in autogen docs for web config

---

components/dsl/resources/ome/dsl/object.vm
components/tools/OmeroPy/test/integration/test_model51.py

Since the MapField properties are of little use
if the map itself has not been loaded, they are
now actively loaded. Queries need not include a
"left outer join fetch" clause.
Testing:
* integration tests should be green.
* some of @dominikl's work should pass **without** gh-3325

Enable eager fetching of maps

---

components/tools/OmeroPy/src/omero/gateway/__init__.py
components/tools/OmeroWeb/omeroweb/webclient/views.py
components/tools/OmeroWeb/omeroweb/webgateway/urls.py
components/tools/OmeroWeb/omeroweb/webgateway/util.py
components/tools/OmeroWeb/omeroweb/webgateway/views.py

This adds support for Z & T to the webgateway/render_thumbnail url, as an alternative to #3278.
E.g. webgateway/render_thumbnail/3455/?z=10
To test, try various z/t combinations.
Also test that you can set the default Z/T by POSTing like:
```
$.ajax({type:"POST", url: "http://localhost:4080/webgateway/saveImgRDef/3455/?z=22"})
```
Refreshing the thumbnail (without specifying z or t) should update to the default z or t set by this POST.
--no-rebase

Thumbnail by section

---

components/tests/python/library/__init__.py
components/tools/OmeroPy/test/integration/clitest/cli.py
components/tools/OmeroPy/test/integration/clitest/test_obj.py
components/tools/OmeroPy/test/integration/clitest/test_tag.py
components/tools/OmeroPy/test/integration/clitest/test_user.py
components/tools/OmeroPy/test/integration/fstest/test_rename.py
components/tools/OmeroPy/test/integration/scriptstest/test_coverage.py
components/tools/OmeroPy/test/integration/scriptstest/test_make_movie.py
components/tools/OmeroPy/test/integration/test_annotationPermissions.py
components/tools/OmeroPy/test/integration/test_client_ctors.py
components/tools/OmeroPy/test/integration/test_imetadata.py
components/tools/OmeroPy/test/integration/test_ishare.py
components/tools/OmeroPy/test/integration/test_permissions.py
components/tools/OmeroPy/test/integration/test_pixelsService.py
components/tools/OmeroPy/test/integration/test_reimport.py
components/tools/OmeroPy/test/integration/test_repository.py
components/tools/OmeroPy/test/integration/test_scripts.py
components/tools/OmeroPy/test/integration/test_tickets3000.py
components/tools/OmeroPy/test/integration/test_tickets4000.py
components/tools/OmeroWeb/test/integration/test_csrf.py
components/tools/OmeroWeb/test/integration/test_rendering.py
components/tools/OmeroWeb/test/integration/test_show.py
components/tools/OmeroWeb/test/integration/test_tree.py

This PR refactors the `ITest` class in the Python library to perform the setup at the class level instead of the method level. This should not affect the validity of the tests but mostly result in a performance improvements while running the integration tests due to the reduction of the setup overhead.
Specific test cases which were relying on the previous per-method setup should be corrected e.g. by using `self.new_clients()`.
To test this PR, check the Python/Web integration  tests are green and that the full time required to complete the Python integration tests is significantly reduced.
/cc @ximenesuk

Itest improvements

---

docs/hudson/OMERO-homebrew-install.sh

See also https://github.com/sbesson/openmicroscopy/commit/4321538e4f0abb0db6ca26c54a3ca9911afac526. This PR modifies the `OMERO-homebrew-install.sh` installation script under `dev_5_0` to use the new formulas introduced by https://github.com/ome/homebrew-alt/pull/70.
--no-rebase

Use 5.0 versions of OMERO and Homebrew formulas

---

components/tools/OmeroCpp/cmake/FindIce.cmake

- Work with cmake 3.1 (the cmake developers changed the variable quoting rules); fix pulled from cmake.git
- Work with Ice 3.6 (3.6b and 3.6.0 final)
--------
Testing: should be handled by the CI builds.

cmake: Fixes for cmake 3.1 and Ice 3.6

---

components/tools/OmeroWeb/omeroweb/webclient/forms.py
components/tools/OmeroWeb/omeroweb/webclient/webclient_utils.py
components/tools/OmeroWeb/test/unit/test_util.py

This removes the use of Decimal for formatting of percent fraction values (from #3309) for ND filter and attenuation.
Formatting should be as follows:
```
100 -> "100"
80.5 -> "81"
20 -> "20"
1.0 -> "1"
0.5 -> "0.5"
0.25 -> "0.3"
0 -> "0.0"
```

Don't use Decimal for percent_fraction formatting

---

components/tools/OmeroPy/src/omero/plugins/admin.py
components/tools/OmeroPy/src/omero/plugins/prefs.py
components/tools/OmeroPy/test/unit/clitest/test_admin.py

https://trello.com/c/ROD6R0L7/180-omero-web-custom-prefix
`omero admin ports --prefix N` now prefixes `omero.web.application_server.port` (`N4080`) in addition to the standard server ports by modifying `config.xml`. It also sets the port in `omero.web.server_list`.
Note: Updated with unit tests from @sbesson 
--no-rebase

Prefix application_server.port when calling `omero admin ports`

---

components/tools/OmeroPy/src/omero/tables.py
components/tools/OmeroPy/test/integration/tablestest/test_backwards_compatibility.py
components/tools/OmeroPy/test/integration/tablestest/test_service.py
components/tools/OmeroPy/test/unit/tablestest/test_hdfstorage.py

Fixes setAllMetadata, the last bit of https://trac.openmicroscopy.org.uk/ome/ticket/12606
Also add a workaround for numpy vs Python native types being stored in the table metadata (though I guess this means there is a danger that tables produced by different servers could use different types for the same thing).
--no-rebase

Tables set all metadata 12606

---

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorModel.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/model/DownloadActivityParam.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/model/SaveAsParam.java
components/insight/SRC/org/openmicroscopy/shoola/env/ui/ActivityComponent.java
components/insight/SRC/org/openmicroscopy/shoola/env/ui/DataObjectRemover.java
components/insight/SRC/org/openmicroscopy/shoola/env/ui/DownloadActivity.java
components/insight/SRC/org/openmicroscopy/shoola/env/ui/SaveAsActivity.java

If an image is exported as JPEG, PNG or TIFF the images are zipped into a Batch_Image_Export.zip file (attached to the image), which is then downloaded. Previously this file was kept and stayed attached to the image. Now it is removed after the download has finished.
Test: Make sure the export as JPEG/PNG/TIFF functionality still works and that the FileAnnotation with the zip file is deleted after it was downloaded.
--no-rebase

Delete FileAnnotation after image export

---

components/server/src/ome/security/basic/OmeroInterceptor.java
components/tools/OmeroPy/test/integration/test_model51.py

Previously, modifications to the CollectionOfElements
containing NamedValue instances were not being detected.
Anyone was allowed to modify the lists. To workaround
HHH-4897, we artificially bump the version field of the
containing object (the "owner") which triggers the regular
security process.
see:
* https://hibernate.atlassian.net/browse/HHH-4897
* https://forum.hibernate.org/viewtopic.php?f=1&t=1002411
* https://issues.openmrs.org/browse/SYNC-306
/cc @will-moore @mtbc

Add security fix for NamedValue lists (HHH-4897)

---

components/tools/OmeroPy/src/omero/util/upgrade_check.py

@rleigh-dundee asked to provide more information about OS in UpgradeCheck. This is because original implementation uses only ```platform.version()```. This change should give more details to registry.
Mac OS X:
```
>>> "%s-%s" % (platform.platform(),platform.mac_ver()[0])
'Darwin-12.5.0-x86_64-i386-64bit-10.8.5'
```
Linux:
```
>>> platform.platform()
'Linux-2.6.32-431.29.2.el6.x86_64-x86_64-with-centos-6.5-Final'
```
Windows:
```
>>> platform.platform()
'Windows-2008Server-6.0.6002-SP2'
```
Test library locally logging to web calling python directly:
```
from omero.util.upgrade_check import UpgradeCheck
check = UpgradeCheck("OMERO.test")
check.run()
```
```
2015-01-14 16:26:10,994 DEBUG [                 omero.util.UpgradeCheck] (proc.31949) run:136 Attempting to connect to …
```

os version in upgrade check

---

docs/QUICKSTART.bat
docs/hudson/OMERO-homebrew-install.sh
docs/hudson/OMERO-start.sh
docs/install/VM/setup_postgres.sh

https://trello.com/c/Fv1HZVfs/779-virt-microscope-pg-9-for-testing reveals the need for a UTF8-encoded database for OMERO since 5.1 patch 12.
PostgreSQL 8.4 references can be updated once version prerequisites suggested via http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-January/004982.html are approved, so for now they are left alone.
See https://github.com/openmicroscopy/ome-documentation/pull/1070#discussion_r22995970
--no-rebase

adjust createdb commands to specify Unicode databases

---

components/tests/python/library/__init__.py
components/tools/OmeroPy/src/omero/cli.py
components/tools/OmeroPy/src/omero/plugins/group.py
components/tools/OmeroPy/src/omero/plugins/user.py
components/tools/OmeroPy/test/integration/clitest/cli.py
components/tools/OmeroPy/test/integration/clitest/test_group.py
components/tools/OmeroPy/test/integration/clitest/test_user.py
components/tools/OmeroPy/test/unit/clitest/test_group.py
components/tools/OmeroPy/test/unit/clitest/test_user.py

Fixes https://trac.openmicroscopy.org/ome/ticket/12589
This PR adds 
- a `info` subcommand to both `UserControl` and `GroupControl` plugins. These commands have the same behavior as the `list` subcommand for a subset of users/groups. The following commands should now be accepted
```
bin/omero user info   # Give info about the context user
bin/omero user info user-1
bin/omero user info user-1 --user-id 3 --user-name user-4
bin/omero group info   # Give info about the context user
bin/omero group info read-write1
bin/omero group info read-write1 --group-id 3 --group-name read-annotate-1
```
- a `bin/omero group listusers` and a `bin/omero user listgroups` subcommands. Both subcommands either take no argument (using the context) or a single argument. The following calls should work:
``` …
```

Add CLI info, listusers and listgroups subcommands

---

components/common/resources/ome/config.xml
components/tools/OmeroPy/src/omero/gateway/utils.py
components/tools/OmeroPy/test/unit/gatewaytest/test_utils.py
components/tools/OmeroWeb/omeroweb/settings.py
components/tools/OmeroWeb/omeroweb/webadmin/views.py
components/tools/OmeroWeb/omeroweb/webadmin/webadmin_utils.py
components/tools/OmeroWeb/omeroweb/webclient/controller/container.py
components/tools/OmeroWeb/omeroweb/webclient/decorators.py
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/base/includes/group_user_content.html
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/container_tags_tree.html
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/containers_tree.html
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/includes/right_plugin.general.js.html
components/tools/OmeroWeb/omeroweb/webclient/views.py
components/tools/OmeroWeb/omeroweb/webclient/webclient_gateway.py
etc/omero.properties

This PR centralize common client properties.
- ```omero.web.scripts_to_ignore``` list of scripts shouldn't be displayed in the client. It became:
- omero.client.scripts_to_ignore
- ```omero.web.ui.tree.orphaned``` allows to customize name and description of the Orphaned Images container. It became:
- omero.client.ui.tree.orphans.name
- omero.client.ui.tree.orphans.description
- ```omero.web.ui.menu.dropdown``` allows to control which part of the User/Group menu should be displayed. It became:
- omero.client.ui.menu.dropdown.leaders
- omero.client.ui.menu.dropdown.leaders.enabled
- omero.client.ui.menu.dropdown.colleagues
- omero.client.ui.menu.dropdown.colleagues.enabled
- omero.client.ui.menu.dropdown.everyone
- omero.client.ui.menu.dropdown.everyone.enabled
To test use ```bin/omero …
```

Properties cleanup

---

components/tools/OmeroFS/fsUtil.py

This PR allows an untested version of Windows to be used for a DropBox server. If the environment variable `OMERO_PLATFORM_CHECK` is set to `false` then on a Windows system the check for the specific platform will be bypassed. This allows an as yet untested version of Windows to be tried at the user's own risk. There is no guarantee DropBox will start up if the version of Windows being used does not support file notifications in the same way as the tested versions.
The easiest way to test this PR would be to edit the list at https://github.com/ximenesuk/openmicroscopy/blob/fce53dfc0982d6089ca152f0751cd6e29db72b49/components/tools/OmeroFS/fsUtil.py#L42 to remove the entry corresponding to the Windows testing platform. By default DropBox should then fail to started. Setting the environment …

Dropbox platform check for Windows (dev_5_0)

---

components/tools/OmeroPy/src/omero/util/upgrade_check.py

This is the same as gh-3343 but rebased onto dev_5_0.
----
@rleigh-dundee asked to provide more information about OS in UpgradeCheck. This is because original implementation uses only ```platform.version()```. This change should give more details to registry.
Mac OS X:
```
>>> "%s-%s" % (platform.platform(),platform.mac_ver()[0])
'Darwin-12.5.0-x86_64-i386-64bit-10.8.5'
```
Linux:
```
>>> platform.platform()
'Linux-2.6.32-431.29.2.el6.x86_64-x86_64-with-centos-6.5-Final'
```
Windows:
```
>>> platform.platform()
'Windows-2008Server-6.0.6002-SP2'
```
Test library locally logging to web calling python directly:
```
from omero.util.upgrade_check import UpgradeCheck
check = UpgradeCheck("OMERO.test")
check.run()
```
```
2015-01-14 16:26:10,994 DEBUG [                 omero.util.UpgradeCheck] …
```

os version in upgrade check (rebased onto dev_5_0)

---

components/tools/OmeroPy/test/integration/test_model51.py
components/tools/OmeroPy/test/unit/test_jvmcfg.py
components/tools/OmeroPy/test/unit/test_model.py
components/tools/travis-build

As reported by @mtbc, the unit tests for the JVM configuration can vary depending on the level where they run, i.e. the following commands report different results
```
$ ./build.py -f components/tools/OmeroPy/build.xml test -DTEST=test/unit/test_jvmcfg.py
$ cd components/tools/OmeroPy && ./setup.py test -t test/unit/test_jvmcfg.py -v
```
This is due to one of the tests using the `server.jar` to calculate the system memory and not the other (because of a path issue). In all cases, some of the tests in the `testjvmcfg.json` have assumptions on the memory configuration of the system. This PR is monkeypatching `Strategy._system_memory_mb_java()` to return the default value. In a more advanced version of this PR, these settings could be made variable and also stored in the JSON.
Additionally, …

Fix jvmcfg unittests

---

components/insight/TEST/org/openmicroscopy/shoola/env/data/LuceneQueryBuilderTest.java

Trivial fix to remove an emory import that wasn't used anyway.

remove unused and wrong import

---

components/insight/TEST/org/openmicroscopy/shoola/env/data/LuceneQueryBuilderTest.java

Trivial fix to remove an emory import that wasn't used anyway.
--rebased-from #3389

remove unused and wrong import (rebased from dev_5_0)

---

components/tests/ui/testcases/web/webadmin_create_group_and_user.txt

Attempt to fix occasional failures like this in Firefox:
```
08:10:07 ------------------------------------------------------------------------------
08:11:18 Create Edit Group :: Tests group creation                             | FAIL |
08:11:18 Page should have contained element 'xpath=//input[@id='id_name'][@value='test_group_1421395699']' but did not
08:11:18 ------------------------------------------------------------------------------
```
To test, check status of https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-robotframework/

Robot framework check for new user_name or group_name

---

components/tools/OmeroPy/src/omero/plugins/sessions.py
components/tools/OmeroPy/src/omero/util/sessions.py
components/tools/OmeroPy/test/unit/clitest/test_sess.py

Fixes https://trac.openmicroscopy.org.uk/ome/ticket/12609
This PR mostly adds a session file storing the last port used while connecting with the CLI (without modifying the file storage logic). The `SessionStore.set_current()/SessionStore.get_current()` logic is modified to store/return this value and the corresponding unit tests are modified to document these new inputs.
To test this PR, try to connect to the same server on different ports, e.g.
```
$ bin/omero login user@localhost:14064
$ bin/omero logout
$ bin/omero login
```
The last call should output `Previously logged in to localhost:14064 as user-1` before prompting the user for connection information.

Store last CLI session port

---

components/tools/OmeroPy/src/omero/plugins/prefs.py
components/tools/OmeroPy/test/unit/clitest/test_prefs.py

With this PR, the following command
```
$ bin/omero config get --hide-password
```
should return the server configuration and hide the values of all keys ending with `.pass` or `.password` (replacing them with '*'). Also check the unit tests are passing.

Add option to hide passwords in bin/omero config get

---

components/tools/OmeroPy/src/omero/install/change_ports.py
components/tools/OmeroPy/test/unit/clitest/test_admin.py

Without this PR, calling `admin ports` appends `omero.port=PORT` to the `ice.config`. This results in the following calls:
```
bin/omero admin ports --prefix=1
bin/omero admin ports --prefix=1 --revert
```
will append the following tow lines
```
omero.port=14064
omero.port=4064
```
This PR fixes the `ice.config` modification logic in `bin/omero admin ports` by:
1- looking for an `omero.port=xxx` line in ICE_CONFIG and replacing it using the new port (as for the other configuration files)
2- if not present, looking for the `## omero.port=xxx` line which ships with the default `ice.config` and uncommenting it
3- if 2 is not applicable, appending `omero.port=xxx` as done previously
--no-rebase

Fix ice.config modification when using bin/omero admin ports --prefix

---

components/tools/OmeroWeb/omeroweb/webadmin/templates/webadmin/includes/drivespaceStats.html

In OMERO.webadmin the drive space statistics table can either be by group or by user. This PR includes a very simple visual change to the column header from `User` to `Group/User`. As the content is loaded by AJAX, changing the header itself based on the type of data being displayed is much more involved.
To test, open up OMERO.webadmin and examine the drive space statistics page (`.../webadmin/stats/`). The header for the leftmost column should be `Group/User`:

Column can be a group or user

---

components/rendering/src/omeis/providers/re/metadata/StatsFactory.java

This is the same as gh-2954 but rebased onto dev_5_0.
----
Always set the windows start-end to global min/max.
This should speed up the generation of rendering settings
* Import few images
* Check that for each channel the start-end is set to the min/max
* Select images imported previously (not the newly imported on)
* Click "reset defaults"
* Check that for each channel start-end=min, max

min-max set (rebased onto dev_5_0)

---

components/insight/SRC/org/openmicroscopy/shoola/util/ui/login/ScreenLogin.java
components/insight/SRC/org/openmicroscopy/shoola/util/ui/login/ServerDialog.java
components/insight/SRC/org/openmicroscopy/shoola/util/ui/login/ServerEditor.java

This is the same as gh-2906 but rebased onto dev_5_0.
----
Review the layout of the server dialog.
Problem noticed while running the client from the command line
To test:
* Start insight using the version matching your OS. e.g. mac
* Click on the wrench to display the server dialog. Check that the display is correct.
* Download the Linux client package and use the scripts from the command line to start insight
* Click on the wrench to display the server dialog. Check that the display is correct.

Server dialog (rebased onto dev_5_0)

---

components/tools/OmeroPy/src/omero/gateway/__init__.py
components/tools/OmeroWeb/omeroweb/webgateway/marshal.py
components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/ome.rangewidget.js
components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/ome.viewport.js
components/tools/OmeroWeb/omeroweb/webgateway/templates/webgateway/viewport/omero_image.html

This is PR #3039 rebased onto dev_5_0.
Some small changes to support floating point data ranges in the channel sliders in Preview tab and main image viewer.
To test:
- Open a float pixel-type image in Preview panel. Test various images with very small and large dynamic ranges.
- Start positions of slider handles are Integers (see above) but sliding handles should give a reasonable number of floating point increments (100 currently for full range of slider).
- Save will save floating point start/end to DB (although this can't be verified because of bug above).
- Launch Image Viewer from preview panel should apply the current floating point slider values to the image viewer.
--rebased-from #3039

Float rendering web dev 5 0

---

components/tests/python/library/__init__.py
components/tools/OmeroPy/src/omero/plugins/tag.py
components/tools/OmeroPy/test/integration/clitest/test_tag.py
components/tools/OmeroPy/test/integration/test_permissions.py

Fixes https://trac.openmicroscopy.org.uk/ome/ticket/11628
This PR;
- moves the permissions fixtures to the common library and adds a `get_name()` method to return a short name used in fixtures (instead of `fixturexxx`)
- modifies the CLI tag creation commands to return the created object under the form `TagAnnotation:xxx` in the standard output
- adds try/except statement in the CLI `tag link` subcommand to handle permission exceptions
- adds permissions test for the `tag link` subcommand using the PermissionsFixture

Add permissions tests for CLI tag plugin

---

components/tools/OmeroPy/src/omero/plugins/admin.py

This PR adds the JVM settigns to the output of `bin/omero admin diagnostics`. Additionally the SSL/TCP port  of the deployed applications are now moved next to the OMERO configuration properties.
To test this PR, check the output of `bin/omero admin diagnostics` for both running and non-running servers.

Add JVM settings to the diagnostics output

---

components/server/src/ome/formats/OMEROMetadataStore.java
components/server/test/ome/formats/utests/DetectorSettingsDetectorTest.java
components/server/test/ome/formats/utests/GenericReferenceTest.java
components/server/test/ome/formats/utests/MultiplePlateTest.java
components/server/test/unit.testng.xml

Logic and unit test cases for collapsing unique light paths. Test cases were also expanded to cover all other existing collapse logic. Some existing, but old and non-functional, test cases have been ported to TestNG and the entire suite of `ome.formats.*` unit tests added to the server unit test suite.
Due to the amount of white space changes that were required, adding `?w=1` to the end of the GitHub "Files Changed" page may be beneficial during review.
Manual testing has been performed:
* Imported one or more Plates with `LightPath` metadata populated (Flex in particular is useful here)
* Confirmed that `LogicalChannel` and `LightPath` reduction has taken place
* Confirmed that the Plates can be deleted
* Confirmed that the Plates can be be moved between groups
* Testing also took place …

Support for collapsing unique light paths

---

components/insight/build/dist.xml
lib/composite.py

Follow up of https://github.com/openmicroscopy/openmicroscopy/pull/3337, this PR splits the zip bundles for the insight/importer/editor clients and the clients bundles for Mac OS X into two: Java 6 and Java 7+. This should result in twice more OSX client artifacts but reduce the size of these artifacts by a factor of 2.
The zip bundles are now suffixed by `_Java6` or `_Java7+`. So do the applications stored in them. Alternatively we could only suffix the zip bundles and preserve `OMERO.insight`, `OMERO.importer`, `OMERO.editor` as the app name since we do not bundle different Java versions together.

Split OS X packaging into 2 sets

---

components/tools/OmeroWeb/omeroweb/webgateway/views.py

See: https://trac.openmicroscopy.org/ome/ticket/12697
Fixes the "Save to all" button in web preview panel.
To test:
- Choose an image with other similar ones in the same Dataset
- Edit rendering settings in Preview Panel and click "Save to all".
- Other compatible images in the Dataset should be updated (thumbnails) and
the rdef thumbnail in the Preview panel should also update.

Fix 'Save to All' in web preview panel

---

components/tests/ui/testcases/web/webadmin_create_group_and_user.txt

This is the same as gh-3355 but rebased onto dev_5_0.
----
Attempt to fix occasional failures like this in Firefox:
```
08:10:07 ------------------------------------------------------------------------------
08:11:18 Create Edit Group :: Tests group creation                             | FAIL |
08:11:18 Page should have contained element 'xpath=//input[@id='id_name'][@value='test_group_1421395699']' but did not
08:11:18 ------------------------------------------------------------------------------
```
To test, check status of https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-robotframework/

Robot framework check for new user_name or group_name (rebased onto dev_5_0)

---

components/rendering/src/omeis/providers/re/metadata/StatsFactory.java
components/rendering/src/omeis/providers/re/quantum/Quantization_32_bit.java
components/rendering/src/omeis/providers/re/quantum/Quantization_8_16_bit.java
components/rendering/src/omeis/providers/re/quantum/Quantization_float.java
components/rendering/src/omeis/providers/re/quantum/QuantumFactory.java
components/rendering/src/omeis/providers/re/quantum/QuantumStrategy.java
components/rendering/src/omeis/providers/re/quantum/Range.java
components/server/src/ome/services/RenderingBean.java
components/server/test/omeis/providers/re/utests/TestOnTheFly16BitRenderer.java
components/server/test/omeis/providers/re/utests/TestQuantumFactory.java
components/server/test/omeis/providers/re/utests/TestStandard16BitRendererLUTSizes.java
components/server/test/omeis/providers/re/utests/TestStandard32BitRendererLUTSizesShouldFail.java
components/server/test/omeis/providers/re/utests/TestStandardDoubleRenderer.java
components/server/test/omeis/providers/re/utests/TestStandardFloatRenderer.java
components/server/test/omeis/providers/re/utests/TestStandardSigned16BitRenderer.java
components/server/test/omeis/providers/re/utests/TestStandardSigned32BitRenderer.java
components/tools/OmeroJava/test/integration/RenderingEngineTest.java

This is the same as gh-2955 but rebased onto dev_5_0.
----
Add support for  32-bits images (pixels type)
* Import the following images. 
* test_image_good/ubm
* from skyking/gatan/chip/
* from skyking/gatan/qa-7642
* Check that you can view the images.
* Open the images in ImageJ or Fiji using BioFormats to validate.
Images imported w/o this PR can be found under 
trout/ port 14064 (latest), user-1 private-1 Project imported 18-08-14 to test 32 bit
Add support for floating point image
make sure that the unit tests under server/test/omeis.providers.re.utests are green
Import floating point images. a selection can be found under squig/team/will/float0-data.zip
View the image in OMERO, modify some values e.g. pixels window.
View the same image in ImageJ.
Note that the pyramid …

32 bit and float (rebased onto dev_5_0)

---

components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/util/player/MoviePlayerControl.java
components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ControlPane.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/actions/ManageRndSettingsAction.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/ChannelSlider.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/GraphicsPane.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/GraphicsPaneUI.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/Renderer.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/RendererComponent.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/RendererModel.java
components/insight/SRC/org/openmicroscopy/shoola/agents/util/flim/FLIMResultsDialog.java
components/insight/SRC/org/openmicroscopy/shoola/util/ui/NumericalTextField.java
components/insight/SRC/org/openmicroscopy/shoola/util/ui/PopupHint.java
components/insight/SRC/org/openmicroscopy/shoola/util/ui/slider/TextualTwoKnobsSlider.java
components/insight/SRC/org/openmicroscopy/shoola/util/ui/slider/TwoKnobsSlider.java
components/insight/SRC/org/openmicroscopy/shoola/util/ui/slider/TwoKnobsSliderModel.java
components/insight/SRC/org/openmicroscopy/shoola/util/ui/slider/TwoKnobsSliderUI.java

Gathered all UI changes for float images from develop branch together and rebased them to dev_5_0; this mainly affects the TwoKnobSlider.
Review: Check that the channel sliders work with int and float images. But also check other places where the TwoKnobSlider is used, e. g. the movie dialog.
To be able test this PR, #3366 should be included in the build.
/cc @jburel

Backported UI support for float images

---

components/romio/src/ome/io/nio/PixelsService.java
components/romio/test/ome/io/nio/utests/BfPixelBufferUnitTest.java
components/romio/test/ome/io/nio/utests/HugePixelBufferUnitTest.java
components/romio/test/ome/io/nio/utests/LargePixelBufferUnitTest.java
components/romio/test/ome/io/nio/utests/NormalPixelBufferUnitTest.java
components/romio/test/ome/io/nio/utests/PixelDataBitTest.java
components/romio/test/ome/io/nio/utests/PlanarDataTest.java
components/romio/test/ome/io/nio/utests/PyramidPixelBufferUnitTest.java
components/romio/test/ome/io/nio/utests/PyramidWriteLockUnitTest.java

This is the same as gh-3368 but rebased onto dev_5_0.
----
Turn off pyramid generation for float/double images
* Import an image stored on squig under team/jburel/ForMelissa/floatForPyramid or squig/team/will/float0-data.zip
* Make sure that no pyramid is created. Either check under /OMERO or open the viewer that the image is not a tiled image.

Pyramid (rebased onto dev_5_0)

---

components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/util/FileImportComponent.java
components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterUIElement.java

Fix ticket https://trac.openmicroscopy.org.uk/ome/ticket/12165
To test: 
test 1
* Select a folder to import
* When scanning is done, cancel elements. Make sure the "Cancel All" button is enabled until there are still some import to cancel.
test 2
* Select few files to import
* When scanning is done, cancel elements. Make sure the "Cancel All" button is enabled until there are still some import to cancel.

Cancel all

---

components/server/src/ome/services/graphs/GraphPathBean.java
components/server/src/ome/services/graphs/GraphPathReport.java

Introduces a standalone component of OMERO.server that generates the model object reference as at https://www.openmicroscopy.org/site/support/omero5.1-staging/developers/Model/EveryObject.html. This is an initial pull request to get the code into the repository. In the longer term it will probably have to be modified to ease the job of bringing this functionality into an automatic documentation update job. It can be run by configuring the server with `bin/omero config set`, and its database, appropriately such that it can start but, instead of starting it, do something like,
```
java -cp lib/server/\* `bin/omero config get | awk '{print"-D"$1}'` ome.services.graphs.GraphPathReport EveryObject.txt
```
and the `EveryObject.txt` Sphinx document will be generated, without an introductory …

OMERO model object reference generator

---

components/blitz/src/pojos/PixelsData.java

This is the same as gh-3387 but rebased onto dev_5_0.
----
Fixes ticket [Trac 12711](https://trac.openmicroscopy.org.uk/ome/ticket/12711)
To Test:
Open/Import floating point image; open ROI tool, draw/select ROI, make sure Graph, Intensity and Result tabs are working (without PR just a warning dialog popped up, saying there was an error performing the analysis)

Fixed ROI issue with floating point images (rebased onto dev_5_0)

---

components/tools/OmeroWeb/omeroweb/settings.py
components/tools/OmeroWeb/omeroweb/webclient/controller/container.py
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/includes/toolbar.html
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/metadata_general.html
components/tools/OmeroWeb/omeroweb/webclient/views.py
components/tools/OmeroWeb/omeroweb/webgateway/views.py
components/tools/OmeroWeb/setup.py
components/tools/OmeroWeb/test/integration/test_download.py

This is https://github.com/openmicroscopy/openmicroscopy/pull/2953 rebased back to dev_5_0 (discussed last Tuesday meeting).
This adds the "Download" menu (and fileset paths) to SPW images when wells are selected.
To test:
Import a Plate.
Also create a plate from a Dataset with Dataset_To_Plate.py script (simpler if images are not MIFs).
Select ONE well from each plate:
Test the "Show paths" button
Download the Original files for the well. This will be a single image for the created plate and the whole plate for the imported plate.
Export as png/jpeg/tiff. Check that you get the correct image for the current Plate 'index'.
Select MULTIPLE wells from each plate:
Test paths, download original and export png/jpeg/tiff as described above.

Download spw original files dev50

---

components/blitz/resources/omero/FS.ice
components/tools/OmeroFS/src/fsDropBox.py
components/tools/OmeroFS/src/fsMonitor.py
components/tools/OmeroFS/src/fsMonitorServer.py
components/tools/OmeroFS/src/fsUtil.py
etc/grid/templates.xml

This PR allows an untested version of Windows to be used for a DropBox server.  If `omero.fs.platformCheck` is set to `False` then on a Windows system the check for the specific platform will be bypassed. This allows an as yet untested version of Windows to be tried at the user's own risk. There is no guarantee DropBox will start up if the version of Windows being used does not support file notifications in the same way as the tested versions.
The easiest way to test this PR would be to edit the list at https://github.com/ximenesuk/openmicroscopy/blob/45e049f093462218625a4129806d8703e4e8ce61/components/tools/OmeroFS/src/fsUtil.py#L43 to remove the entry corresponding to the Windows testing platform. By default DropBox should then fail to started. Setting the config …

Dropbox platform check for Windows

---

components/tools/OmeroPy/src/omero/gateway/__init__.py

The Users/Groups dropdown in the webclient is not sorted on anything at the moment. This will sort the list on last name.
I'm not sure this is the preferable way to fix this, or whether you would like this configurable. 
How to test: check whether the dropdown is sorted on last name.

Sort users on last name in the webclient group dropdown

---

components/tools/OmeroWeb/omeroweb/webadmin/templates/webadmin/includes/drivespaceStats.html

This is the same as gh-3398 but rebased onto develop.
----
In OMERO.webadmin the drive space statistics table can either be by group or by user. This PR includes a very simple visual change to the column header from `User` to `Group/User`. As the content is loaded by AJAX, changing the header itself based on the type of data being displayed is much more involved.
To test, open up OMERO.webadmin and examine the drive space statistics page (`.../webadmin/stats/`). The header for the leftmost column should be `Group/User`:

Column can be a group or user (rebased onto develop)

---

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/batch_annotate.html
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/metadata_general.html

This PR attempts to make alert messages more explicit in case of failed file annotations upload in OMERO.web.
Testing requires nginx with a config such that:
* either no `client_max_body_size` is configured, hence using the default 1MB value
* or explicitly set to `client_max_body_size 1M;`
Test cases:
* Standard file annotation:
* create a dataset and attach a file larger than 1MB via the webclient from the local filesystem
* the browser's alert popup should display "Upload failed [413 Request body too large]" instead of "undefined"
* Batch file annotation:
* create two datasets, select both in the left panel and repeat the file upload >1M
* an alert popup should be displayed with a message as above instead of the error being silently ignored
Note: 
the issue is reproducible on `5.0.6` …

Fix web attachment error msg develop

---

components/blitz/src/loci/ome/io/OmeroReader.java

To Test:
1) Open Insight : Add roi's to an existing OMERO image and save (All kinds of ROI's).
2) Now close Insight, and download/setup the Insight-IJ plugin, open the same OMERO image on ImageJ using this plugin.
3) Please check the "Display ROIs","Display OME-XML metadata" and "Display Metadata" checkbox's in the Bio-Formats Import options and press OK.
4) This should now open the IMAGE from OMERO in ImageJ. And the ROI's should be loaded onto the ImageJ ROI Manager.
NOTE: The label text ROI's will be displayed in the metadata, but the support for displaying the same in the ImageJ ROIManager will be done via a separate PR.

Omero reader update : Open OMERO ROIs in ImageJ

---

components/tools/OmeroWeb/omeroweb/settings.py

See https://trello.com/c/C5yQwFGk/374-omero-web-use-omero-web-prefix-in-place-of-omero-web-force-script-name
At the moment both `omero.web.force_script_name` and `omero.web.prefix` have the same effect for backwards compatibility.

Add omero.web.prefix as an alias for FORCE_SCRIPT_NAME

---

components/blitz/src/pojos/PixelsData.java

Fixes ticket [Trac 12711](https://trac.openmicroscopy.org.uk/ome/ticket/12711)
To Test:
Open/Import floating point image; open ROI tool, draw/select ROI, make sure Graph, Intensity and Result tabs are working (without PR just a warning dialog popped up, saying there was an error performing the analysis)

Fixed ROI issue with floating point images

---

components/tools/OmeroPy/src/omero/plugins/web.py

See https://trello.com/c/VXklk1so/405-omero-web-refactor-configuration-logic
- set up a server with a deprecated Web configuration e.g. `bin/omero config set omero.web.force_script_name /prefix`
- check `bin/omero web -h` gives the help without warning about the configuration
- check `bin/omero web help` works, throws a warning about the deprecated configuration and output a fully populated configuration table
- check `bin/omero web config {nginx, nginx-development, apache, apache-fcgi}` work and throws a warning about the deprecated configuration
- check the other commands, `bin/omero web start/stop...` are unaffected by the lazy loading
--no-rebase

Fix config table and do lazy loading in CLI web plugin

---

components/tests/ui/resources/web/tree.txt
components/tests/ui/testcases/web/post_test.txt
components/tools/OmeroWeb/omeroweb/webclient/controller/container.py
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/containers.html

See: https://trac.openmicroscopy.org.uk/ome/ticket/12719
This fixes deletion of child objects when the parents are deleted in the jsTree.
Also includes a new Robot framework test that tests deletion of Project and Dataset (which fails without the first commit).
To test:
- Delete a Project containing a Dataset. Check the Dataset and Images are deleted too (not orphaned).
- Delete a Screen/Plate and check that the images are deleted (not found as orphans).

Delete - KEEP children

---

components/tools/OmeroPy/src/omero_ext/killableprocess.py

Copied from https://github.com/mozilla/addon-sdk/pull/1379
Fixes https://trac.openmicroscopy.org.uk/ome/ticket/12320
Testing: Scripts should now work on Windows with Python 2.7 (previously they only worked on 2.6). CI server is still being setup so you'll have to test on a local VM (or wait...).

Fix _execute_child on Windows Python 2.7+

---

components/insight/SRC/org/openmicroscopy/shoola/util/ui/slider/TwoKnobsSliderUI.java

Same as b8319c9fdb ; Fixes the ClassCastException in Projection view, [Ticket 12724](https://trac.openmicroscopy.org.uk/ome/ticket/12724)

Fixed a ClassCastException

---

.travis.yml

A new release of PEP8 (1.6.0) is out which invalids our Python code base. This commit should ensure Travis does not fail systematically

Impose pep8 1.5.7 for Travis validation

---

.travis.yml

This is the same as gh-3462 but rebased onto dev_5_0.
----
A new release of PEP8 (1.6.0) is out which invalids our Python code base. This commit should ensure Travis does not fail systematically

Impose pep8 1.5.7 for Travis validation (rebased onto dev_5_0)

---

components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/util/FileImportComponent.java

Fix https://trac.openmicroscopy.org.uk/ome/ticket/12162
To test 
* Select few DV, make sure you select a DV and its log file. (see screenshot)
* Click on "Cancel All", AFTER  log file has been checked (see screenshot)
* When completed make sure the spinner in Data manager toolbar is not active.

Cancel all DV

---

components/blitz/src/ome/services/blitz/repo/ManagedImportRequestI.java

Do some imports, look in the server's managed repository, and check that the import log file sizes on disk match those for the import logs in the database. Fixes http://trac.openmicroscopy.org.uk/ome/ticket/12513.
```
bin/omero hql "SELECT path||name, size FROM OriginalFile WHERE mimetype = 'application/omero-log-file'"
```
We do thus close the import log very slightly earlier, but it is still after the interesting stuff has all happened, and after one has destroyed the session it is rather harder to update the database.
--no-rebase

fix #12513: close import log earlier to set its size correctly

---

components/tools/OmeroM/src/io/getDatasets.m
components/tools/OmeroM/src/io/getProjects.m
examples/Training/matlab/ReadData.m

This PR should modify the default behavior of `getProjects()` and `getDatasets` to return unloaded graphs by default.
--no-rebase

Do not load graphs by default in getProjects/getDatasets

---

components/server/src/ome/services/graphs/GraphTraversal.java

https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-integration-python/344/testReport/test.integration.test_delete/TestDelete/test3639/ showed a very odd failure that must be very intermittent. It could be that an object disappeared underneath the feet of the traversal at just the wrong moment. This PR attempts to make the code more robust against that circumstance.
--no-rebase

make graph traversal more robust to poor transaction isolation

---

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/Editor.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorComponent.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorControl.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorModel.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/OMEROGateway.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/model/DownloadActivityParam.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/model/SaveAsParam.java
components/insight/SRC/org/openmicroscopy/shoola/env/ui/ActivityComponent.java
components/insight/SRC/org/openmicroscopy/shoola/env/ui/DownloadActivity.java
components/insight/SRC/org/openmicroscopy/shoola/env/ui/SaveAsActivity.java
components/insight/SRC/org/openmicroscopy/shoola/util/filter/file/ZipFilter.java
components/insight/SRC/org/openmicroscopy/shoola/util/ui/UIUtilities.java

See [Ticket 11895](https://trac.openmicroscopy.org/ome/ticket/11895)
Test: Select some images and export them as JPG, PNG or TIFF. You can now choose a name for the generated batch export zip file. Default name is "Batch_Image_Export.zip". Make sure that if a file with that name already exists, the default name will be incremented to "Batch_Image_Export(1).zip" and so on. Also check if the file gets overwritten if you select a file which already exists (and that you have to confirm this).

Customizable batch image export filename

---

components/insight/SRC/org/openmicroscopy/shoola/env/data/login/UserCredentials.java

See [Ticket 12547](https://trac.openmicroscopy.org.uk/ome/ticket/12547)
I don't know how to test this; but a code review should be sufficient (it's just an additional check for `null`, and `password` is the only Object which could trigger a `NullPointerException` in this `toString()` method)

Fixed potential NPE

---

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/GroupEditor.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/UserProfile.java

Fixes [Ticket 12378](http://trac.openmicroscopy.org.uk/ome/ticket/12378)
Also fixed: Save button did not become enabled if just the default group was changed.
Test: As an admin user try to change the default group of another user to a group the admin user is not a member of. This previously triggered the `DSOutOfServiceException: Can't modify the current group.` exception.

Bugfixes: Change user's default group

---

components/blitz/src/ome/formats/importer/ImportEvent.java
components/blitz/src/ome/formats/importer/ImportLibrary.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/util/StatusLabel.java

This is a PR for @jburel's evaluation. An extra `POST_UPLOAD` event, `IMPORT_STARTED` has been added and propagated to give the logfile ID to the client as early as possible. Previously the ID was sent after the metadata import step. For direct testing the cli importer should show something like the following on the console:
```
...
2015-01-23 09:15:05,016 11413      [      main] INFO   ormats.importer.cli.LoggingImportMonitor - FILESET_UPLOAD_END
2015-01-23 09:15:05,614 12011      [      main] INFO   ormats.importer.cli.LoggingImportMonitor - IMPORT_STARTED Import started. Logfile: 152
2015-01-23 09:15:07,561 13958      [l.Client-0] INFO   ormats.importer.cli.LoggingImportMonitor - METADATA_IMPORTED Step: 1 of 5  Logfile: 152
...
```
For testing within Insight an image file that fails …

Add extra event to return logfile id early.

---

etc/omero.properties

Regularly, the long_running Python tests cause my JVM to
segfault locally when out of memory conditions occur.
Setting dispose to true prevents this from happening.
This proposes setting `true` as the default. If issues
arise, sysadmins can manually set it back to false.
See:
* http://trac.openmicroscopy.org.uk/ome/ticket/11675
* https://github.com/openmicroscopy/openmicroscopy/pull/1865
* https://github.com/openmicroscopy/openmicroscopy/pull/1884
Testing:
* Tests especially the long_running ones should continue to pass and possibly speed up.
cc: @mtbc @ximenesuk @sbesson

Set omero.pixeldata.dispose=true by default (See #11675)

---

components/insight/SRC/org/openmicroscopy/shoola/env/data/Connector.java

Fixes [Ticket 12397](http://trac.openmicroscopy.org.uk/ome/ticket/12397)
Test: Open multiple images in fullviewer; don't close the image viewer windows (thus multiple rendering services are left open) and directly close Insight. This previously triggered the ConcurrentModificationException.

Fixed ConcurrentModificationException

---

components/tools/OmeroPy/src/omero/plugins/web.py
components/tools/OmeroPy/test/unit/clitest/test_web.py
etc/templates/nginx-development.conf.template
etc/templates/nginx.conf.template

See https://trello.com/c/llYcBf5H/408-omero-web-nginx-client-max-body-size and https://trello.com/c/lm5ZOYF0/412-omero-web-nginx-default-port-change-to-80-instead-of-8080.
The CLI web plugin and nginx templates has been modified to:
- reduce the complexity of the `config()` method
- group all nginx arguments into an argument group
- use `8080` as the default for the development nginx and `80` as the default for the system nginx
- set `max_client_body_size` and allow it to be control via CLI (defaulting to 0, i.e. no size check)
Unit tests have been updated to reflect these changes, test all combinations but also test the backwards compatible `bin/omero web config nginx --system`.
The improvements in this PR can be manually checked by running the following commands.
```
bin/omero web …
```

CLI nginx template improvements

---

history.txt

This is the same as gh-3457 but rebased onto develop.
----
Adding 5.0.8 version history for OMERO.

5-0-8 history (rebased onto develop)

---

components/blitz/src/pojos/AnnotationData.java
components/blitz/src/pojos/DataObject.java
components/insight/SRC/org/openmicroscopy/shoola/agents/dataBrowser/view/SearchResultTable.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/DocComponent.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/FilterGroupComponent.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/PropertiesUI.java
components/insight/SRC/org/openmicroscopy/shoola/agents/util/EditorUtil.java
components/insight/SRC/org/openmicroscopy/shoola/agents/util/ViewedByItem.java
components/insight/SRC/org/openmicroscopy/shoola/env/ui/ActivityComponent.java
components/insight/SRC/org/openmicroscopy/shoola/util/ui/UIUtilities.java
components/server/src/ome/services/query/PojosLoadHierarchyQueryDefinition.java
components/tools/OmeroJava/test/integration/PojosServiceTest.java

Follow-up PR to the General Pane alignment, see [Trello](https://trello.com/c/OBUND1Za/82-general-pane-client-alignment)
- Show creation date for Datasets, Projects, etc.
- Show Annotation tooltips like Web does (display namespace, description, etc.)
- Filters aren't wrapped into 'Light Path' titled border anymore
Also implements [Trac 12681](https://trac.openmicroscopy.org.uk/ome/ticket/12681) : The image ID can be selected and copied with CTRL+C

General pane followup

---

components/insight/SRC/org/openmicroscopy/shoola/agents/util/ui/ScriptComponent.java
components/insight/SRC/org/openmicroscopy/shoola/agents/util/ui/ScriptingDialog.java

Fix https://trac.openmicroscopy.org.uk/ome/ticket/12263
Do not run script
To test
* log as adm-user-6
* Click on the available scripts.
* Select Documents> ThumbnailFigure2.py (modified script for testing UI.)
* Make sure that all the fields are listed
```
scripts.String(
"Data_Type", optional=False, grouping="1",
description="The data you want to work with.",
values=dataTypes, default="Dataset"),
scripts.List(
"IDs", optional=False, grouping="2",
description="List of Dataset IDs or Image"
" IDs").ofType(rlong(0)),
scripts.List(
"Tag_IDs", grouping="3",
description="Group thumbnails by these tags."),
scripts.Bool(
"Show_Untagged_Images", grouping="3.1", default=False,
description="If true (and you're sorting by tagIds) also"
" show images without the specified tags"),
scripts.Long( …
```

Scripts grouping

---

components/tools/OmeroPy/src/omero/tables.py
components/tools/OmeroPy/src/omero_ext/portalocker.py
components/tools/OmeroPy/test/unit/tablestest/test_hdfstorage.py

Attempt to fix https://trac.openmicroscopy.org.uk/ome/ticket/12321
(i.e. Tables should now work on Windows).
Note this requires modifications to `omero_ext/portalocker.py`... what's the best way of doing this?
Requires manual testing (no Windows integration tests at the moment.... hopefully soon)
Definitely needs someone to carefully go over the change in locking (/cc @joshmoore)
--no-rebase

Fix windows tables

---

components/tools/OmeroWeb/omeroweb/webstart/templates/webstart/insight.xml

Fixes http://trac.openmicroscopy.org.uk/ome/ticket/12179.
* Bumps Java requirement up to 1.6.
* Removes preference for creating a desktop icon.
--no-rebase

fix #12179: adjust Insight JNLP specification for webstart

---

components/insight/SRC/org/openmicroscopy/shoola/util/ui/graphutils/HistogramPlot.java

While investigating [Ticket 12657](https://trac.openmicroscopy.org.uk/ome/ticket/12657) I noticed an if statement, which doesn't make sense, maybe a typo. I think the purpose of the statement is, to make sure that all three lists are not null and have the same size, therefore the 'and' should be an 'or'.
Test: Just review the changed if statement; apart from that, make sure the histogram plot (ROI/Measurement tool) still works.
Note: This isn't a fix for the ticket, but I'll close the ticket, because I can't reproduce it.
--no-rebase

Fixed typo(?) in HistogramPlot

---

components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerComponent.java
components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerUI.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/DomainPane.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/RendererComponent.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/RendererModel.java

Update z when viewing lifetime images.
See https://trac.openmicroscopy.org.uk/ome/ticket/12445
To test
* Import the following image  ```skyking/li-flim/samples/sample-extended.fli```
* Open the preview. Move the z-slider, make sure the image is updated
* Open the image in the main viewer. Move the z-slider, make sure the image is updated
* Also check that in the status bar, after small t there is not in bracket (55null)

Update z for lifetime

---

components/tools/OmeroWeb/omeroweb/webclient/static/webclient/css/layout.css
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/mapannotations.html

Fix issues from https://trello.com/c/Fx74klF5/17-map-annotation-schema-db
Only 1 change: Deletion of a row should select the next row (or previous row if the bottom row is deleted).

Select next row after deleting map annotation rows

---

components/server/src/ome/logic/JavaImageScalingService.java

This should fix the error noticed by @sbesson :
```
*: trout-merge master-err:
Exception in thread "Thread-2809" java.lang.ArrayIndexOutOfBoundsException: 2
at com.mortennobel.imagescaling.ResampleOp.verticalFromWorkToDst(ResampleOp.java:334)
at com.mortennobel.imagescaling.ResampleOp.access$200(ResampleOp.java:31)
at com.mortennobel.imagescaling.ResampleOp$2.run(ResampleOp.java:164)
at java.lang.Thread.run(Thread.java:744)
```
Unfortunately I don't know how to test this. One somehow has to request a thumbnail with a height/width less than 3 pixels. Is this done by some integration tests? If so, just check the trout-merge log again for above mentioned error.

Bugfix: JavaImageScalingService, images < 3px

---

components/validator/WebApp/validator/templates/master.kid

For completeness sake - removing the last FAQ link from the OMERO code (see https://trello.com/c/3uqvWhlq/240-faq-issues-needing-moved-to-docs-plone)
This file doesn't seem to exist on develop so
--no-rebase

Removing FAQ link for XML validator

---

components/tools/OmeroPy/src/omero/install/jvmcfg.py
components/tools/OmeroPy/src/omero/plugins/admin.py
components/tools/OmeroPy/test/unit/clitest/test_admin.py
components/tools/OmeroPy/test/unit/old_templates.xml
components/tools/OmeroPy/test/unit/test_jvmcfg.py

Fixes https://trac.openmicroscopy.org.uk/ome/ticket/12527
This PR should be tested via 2 scenarios:
1. from a merge server, download the `templates.xml` from a 5.0.2 or earlier server and put it under `etc/grid`, then either start the server or run `bin/omero admin jvmcfg`. 
2. set an improper strategy, e.g. `bin/omero config set omero.jvmcfg.strategy invalid_strategy` and run the same command as above (`bin/omero admin jvmcfg`). 
In both cases the CLI command should fail with an informative error message
Also check the new unit tests are green.
--no-rebase

Memory settings error handling

---

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/DocComponent.java

Tiny PR which fixes [Ticket 12734](http://trac.openmicroscopy.org.uk/ome/ticket/12734)
Problem: Despite being modal, it could sometimes loose focus, move into the background and block the whole UI. I think there's no need for the info popup to be modal. Now it's just closed if it looses focus.
Best being tested by @gusferguson , because the bug seems to need quite a specific environment to appear.
--no-rebase

Don't set info popup modal

---

components/insight/SRC/org/openmicroscopy/shoola/agents/dataBrowser/view/WellsModel.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/view/MetadataViewerModel.java

Fixes [Ticket 12729](https://trac.openmicroscopy.org.uk/ome/ticket/12729)
Test:
Select a plate; use a plate which contains a fair amount of images (e. g. a 96 well plate) and takes a few seconds to load (the error didn't occur with small plates). Choose a well and modify the rendering settings in the right hand side preview panel. Don't save the settings for the single well, but immediately apply the settings to all wells ("Save to All"). The settings should be saved and the thumbnails start to reload; watch the progressbar on the bottom of the central panel, it should run continuously to 100% and then disappear (before: it often got stuck at some random value). The error appeared rather randomly, so better test a couple of times.
--no-rebase

Bugfix: Progressbar stuck when plate thumbnails reloaded 

---

components/blitz/resources/omero/Repositories.ice

A trivial typo fix in our public docs.
--no-rebase

fix typo in repository API docs

---

components/insight/SRC/org/openmicroscopy/shoola/env/data/ProcessReport.java
components/insight/SRC/org/openmicroscopy/shoola/env/ui/ActivityComponent.java
components/insight/SRC/org/openmicroscopy/shoola/env/ui/DataTransferActivity.java
components/insight/SRC/org/openmicroscopy/shoola/env/ui/DeleteActivity.java

Show the GraphException message, if a move or delete action in fails (see [Ticket 12722](https://trac.openmicroscopy.org/ome/ticket/12722) ).
Test: Provoke a failed move and/or delete action; check that the GraphException message providing more details about the cause is shown in the activity status.
/cc @mtbc 
--no-rebase

Show GraphException message

---

components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/ome.roidisplay.js
components/tools/OmeroWeb/omeroweb/webgateway/templates/webgateway/viewport/omero_image.html
examples/Web/embed_rois_selection.html

OMERO's web viewer now integrates methods to selectively hide\show ROIs for an image.
This features can be used to display only a subset of the ROIs defined on an image or to enable controls to activate or deactivate ROIs at runtime.
The embed_rois_selection.html can be used as example to show how to add three checkboxes to an embedded viewer to switch ON\OFF ROIs.

Enable selective ROIs visualization on web viewer

---

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/MapAnnotationsComponent.java

Fixes [Ticket 12736](http://trac.openmicroscopy.org.uk/ome/ticket/12736)
If text was entered/modified within a MapAnnotation and the save button was hit, the latest changes weren't saved, unless the enter/tab button was pressed before to "confirm" the changes.
Test: Modify some keys/values of a MapAnnotation, don't hit enter/tab after the last change,but directly press save button (or switch do another DataObject in the browser - should automatically save the changes). Make sure also the last modification has been saved.
Note: The save button still doesn't become enabled on typing only; but as changes are saved automatically, I think we should remove the save button anyway in another PR (also to make it conform to Web).
--no-rebase

Save "pending" MapAnnotations changes

---

components/insight/SRC/org/openmicroscopy/shoola/env/data/OmeroMetadataServiceImpl.java

Fix for [Ticket 12738](http://trac.openmicroscopy.org.uk/ome/ticket/12738)
Testing: Log in as an user in the private group on trout and create a MapAnnotation on a dataset (or project, image, whatever). Change to an admin user. Try to edit the MapAnnotation you just created for the other user. Make sure no exception is thrown and the data has been saved.
--no-rebase

Bugfix: Admin editing other user's Annotation

---

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/containers.html
components/tools/OmeroWeb/omeroweb/webclient/views.py

Fixes a couple of bugs that were found today in latest.
To test:
- Run the Thumbnail_Figure script. Check that when the script completes, the Activities panel displays the result without error. Fixes this error:
```
File "/opt/hudson/workspace/OMERO-5.1-merge-deploy/src/dist/lib/python/omeroweb/webclient/views.py", line 2628, in activities
obj_data['name'] = v.name.val
```
- Double-click an Image in the tree to open an Image Viewer (viewer was previously not opening).
--no-rebase

New bug fixes feb2015

---

components/tools/OmeroPy/src/omero/fs/__init__.py
components/tools/OmeroPy/src/omero/gateway/__init__.py
components/tools/OmeroPy/src/omero/plugins/fs.py
components/tools/OmeroWeb/omeroweb/webclient/static/webclient/css/layout.css
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/includes/name.html
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/metadata_general.html
components/tools/OmeroWeb/omeroweb/webclient/webclient_gateway.py
components/tools/OmeroWeb/omeroweb/webgateway/urls.py
components/tools/OmeroWeb/omeroweb/webgateway/views.py

This replicates Insight's indication of images that are imported with "in place" import.
To test:
- import an image with transfer, E.g: ``` $ bin/omero import -- --transfer=ln_s my_file.dv ```
- Check that this image shows the link icon to the right of Image ID in right panel, with tooltip.
- Check other images or P/D etc don't show this.
--no-rebase

Show in place imported images

---

components/tests/ui/plugins/robot.py
components/tests/ui/resources/robot.template

For servers where HTTP is redirected to HTTPS, the OMERO.web robot framework tests will systematically fail. This commit allows to configure the transfer protocol when generating the configuration file, defaulting to HTTP.

Add --protocol option to configure Web protocol in Robot config file

---

components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/ome.webclient.actions.js
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/mapannotation.html
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/mapannotations.html

Filter map annotations by 'me' or 'others'.
To test:
- check that map annotations are now filtered correctly when "me" or "others" are chosen in the filter.
--no-rebase

Filter map annotations by 'me' or 'others'

---

components/common/test/ome/util/search/LuceneQueryBuilderTest.java
components/server/src/ome/services/fulltext/FullTextBridge.java
components/tools/OmeroPy/test/integration/test_search.py

In order for the name-value pairs attach to objects
to be searchable by Lucene, a handler for the map
annotations needed to be added.
To discuss/do:
To test:
* Add a map annotation to an object and search for either the key or the value.
* Additionally, searching for "key:value" should also return the object.

Index map annotations (Fix #12318)

---

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/MapAnnotationsComponent.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/OmeroMetadataServiceImpl.java
components/insight/SRC/org/openmicroscopy/shoola/util/ui/table/TableRowTransferHandler.java

Fixes several issues discovered during m4 testing:
- [Ticket 12747](https://trac.openmicroscopy.org.uk/ome/ticket/12747)
- [Ticket 12748](https://trac.openmicroscopy.org.uk/ome/ticket/12748)
- NPE when you tried to paste Key/Values when no MapAnnotation was selected and no own user table exists (e.g. admin annotating other user's DataObject in private group)
- Fixed bug which removed the text caret from cells (which had the effect, that you only could overwrite the cells content).

MapAnnotation bugfixes

---

components/blitz/src/ome/services/blitz/repo/CheckedPath.java
components/blitz/src/ome/services/blitz/repo/RepositoryDaoImpl.java

The underlying logic in `RepositoryDaoImpl` is expecting checked path equivalence checks to succeed either via `equals()` or `hashCode()`. This PR ensures that will be the case resulting in single level saves in `RepositoryDaoImpl._internalRegister()` which was the original intention of parts of gh-3399.  Performance and resource utilisation are dramatically increased where the file count is high (>1000) or
especially high (>10000).
Without these changes, `CheckedPath` is never equivalent as far as the `ListMultimap` in `_internalRegister()` is concerned. This results in a __single__ `createOriginalFile()` operation for every original file that needs to be registered. Where the file count is especially high (>10000) this can mean registration times in the __hours__ and very high resource …

Fix checked path equivalence checks

---

components/tools/OmeroWeb/omeroweb/webclient/views.py

Fixes script menu display on Windows. See https://trello.com/c/PVZVUd6g/316-display-of-scripts-list-in-omero-web-on-windows-server-is-messed-up
NB: not tested on a Windows server locally.

Fix parsing of script path on Windows

---

components/tools/OmeroWeb/omeroweb/settings.py

Automatically append / to omero.web.static_url if necessary instead of failing with a warning that a trailing slash is required. Note this also removes the unused `omeroweb.settings.remove_slash` method.
Testing: Test `omero.static.url` with/without a trailing /, and unset.
--no-rebase

Automatically append / to omero.web.static_url

---

components/tests/ui/testcases/web/view_image.txt

New Robot test to test the opening of an image viewer with a double-click on tree or thumbnail, or click of "Image Viewer" button (recent bug fixed in https://github.com/openmicroscopy/openmicroscopy/pull/3492).
To test, check status of https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-robotframework/

Robot view image

---

components/tests/ui/testcases/web/forms_test.txt

Attempt to fix failures in "Test Channel Rename" at https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-robotframework/154/console
However, tests passed locally both before and after these tweaks, so not sure if this will make a difference.

Tweaks to robot channel_rename test

---

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/mapannotations.html

Fix for https://trac.openmicroscopy.org/ome/ticket/12754
There is no nice way to catch the click on the Tree and save any current Map Annotation edits before clearing the right panel.
An alternative solution is to simply automatically save a second after the last edit.
We already save the whole Map Annotation to the server whenever you leave a Key/Value input field and the 1 second delay should limit the number of calls to reduce synchronous updates.
To test: 
- simply try a number of rapid edits, moving between key/value fields, with short delays etc
- try editing a field, then navigating away in the Tree while still editing the field. Change should still be saved (unless you are very quick)!
--no-rebase

Auto save 1 second after Map Annotation Edit

---

components/blitz/src/pojos/ImageData.java
components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/chooser/ImportDialog.java
components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterComponent.java
components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterModel.java
components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/util/SaveResultsDialog.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/model/FileObject.java

Add support for overlay and MIF
To test
* open  a mif in imageJ using B-F importer e.g. ```test_images_good/leica-lif/Beta Catenin.lif```
* Make sure you select all series. 5 windows should opened
* Draw a roi on an image e.g. series004, add it as an overlay
* Draw a roi on an another image e.g. image001, add it as an overlay
* Import the image to OMERO
* Check the rois are on the correct images.

Imagej mif

---

components/tools/OmeroPy/src/omero/plugins/admin.py
components/tools/OmeroPy/src/omero/util/cleanse.py

After an image is deleted, its files are deleted from the managed repository but its empty directories are not deleted. Try importing some images, especially plates with subdirectory structure, in the client delete a subset of those images, then see if running cleanse as admin now deletes the corresponding empty directories.
--no-rebase

have cleanse plugin delete empty directories from the managed repos

---

components/blitz/resources/omero/cmd/FS.ice
components/blitz/src/omero/cmd/IRequest.java
components/blitz/src/omero/cmd/graphs/DiskUsageI.java
components/tools/OmeroJava/test/integration/DiskUsageTest.java

* adds `classes` member to indicate "all instances of given classes"
* adjusts `objects` member so that in Java the IDs come as a list, not an array (should be unchanged for Python)
--no-rebase

adjust disk usage request API

---

components/tests/ui/testcases/web/tagging_test.txt
components/tools/OmeroWeb/omeroweb/webclient/controller/container.py
components/tools/OmeroWeb/omeroweb/webclient/views.py

Fixes https://trac.openmicroscopy.org/ome/ticket/12665
To test:
- Select 2 or more objects and add Tags dialog.
- Any tags that are on all selected objects should be shown in right 'selected' column.
- E.g. try adding a tag to all selected objects. When the dialog is opened again this Tag should be in the right column.
- Removing a Tag from the right column should remove it from all selected objects.
Permissions test (fails in Insight: https://trello.com/c/43AhivR0/325-insight-tag-dialog-for-admins)
- In the case where an Admin is removing tags using the Tag dialog, he/she should not be able to remove Tags that another user has added.
- Tags should only show up in the right column if Admin themselves has added that Tag to all selected objects.
- If Admin has added Tag to all selected …

Batch remove tags

---

components/blitz/resources/omero/cmd/Graphs.ice
components/blitz/src/ome/services/blitz/repo/PublicRepositoryI.java
components/blitz/src/omero/cmd/graphs/Chgrp2I.java
components/blitz/src/omero/cmd/graphs/ChgrpFacadeI.java
components/blitz/src/omero/cmd/graphs/ChildOptionI.java
components/blitz/src/omero/cmd/graphs/ChildOptionsPolicy.java
components/blitz/src/omero/cmd/graphs/Chown2I.java
components/blitz/src/omero/cmd/graphs/ChownFacadeI.java
components/blitz/src/omero/cmd/graphs/Delete2I.java
components/blitz/src/omero/cmd/graphs/DeleteFacadeI.java
components/blitz/src/omero/cmd/graphs/GraphUtil.java
components/blitz/src/omero/cmd/graphs/SkipHeadI.java
components/blitz/src/omero/cmd/graphs/WrappableRequest.java
components/blitz/test/omero/cmd/graphs/GraphUtilTest.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/Requests.java
components/tools/OmeroJava/test/integration/DiskUsageTest.java

OMERO should still work, including moves and deletes, and tests should still pass: there should be no change in behavior.
*Update:* Now provides Insight with a utility class for constructing graphs requests.
--no-rebase

adjust graphs API to provide Collections-based Java interface

---

components/blitz/src/ome/formats/importer/ImportEvent.java
components/blitz/src/ome/formats/importer/ImportLibrary.java
components/blitz/src/ome/formats/importer/cli/CommandLineImporter.java
components/blitz/src/ome/formats/importer/exclusions/AbstractFileExclusion.java
components/blitz/src/ome/formats/importer/exclusions/FileExclusion.java
components/blitz/src/ome/formats/importer/exclusions/FilenameExclusion.java
components/blitz/src/ome/formats/importer/exclusions/package-info.java

Similar to the FileTransfer interface, well-known or third
party FileExclusion instances can be passed to the ImportLibrary
in order to influence the import process. Each exclusion is
given the chance to veto the import of a given ImportContainer
which has been chosen, e.g., by ImportCandidates. For example,
passing `--exclude=filename` searches for a file with the same
name on the server and then subsequently checks that the hash
matches. If it goes, the call to `importImage` exits early with
the log statement:
```
INFO   ....exclusions.FilenameExclusion - Checksum match for filename:
```
Testing:
* `bin/omero import $SOMEFILE`
* `bin/omero import $SOMEFILE # This should produce a duplicate`
* `bin/omero import -- --exclude=filename $SOMEFILE # This should import nothing.`
* `bin/omero …

FileExclusion: new extension for the ImportLibrary

---

components/tools/OmeroPy/test/unit/clitest/reference_templates/apache-fcgi-withoptions.conf
components/tools/OmeroPy/test/unit/clitest/reference_templates/apache-fcgi.conf
components/tools/OmeroPy/test/unit/clitest/reference_templates/apache-withoptions.conf
components/tools/OmeroPy/test/unit/clitest/reference_templates/apache.conf
components/tools/OmeroPy/test/unit/clitest/reference_templates/nginx-development-withoptions.conf
components/tools/OmeroPy/test/unit/clitest/reference_templates/nginx-development.conf
components/tools/OmeroPy/test/unit/clitest/reference_templates/nginx-withoptions.conf
components/tools/OmeroPy/test/unit/clitest/reference_templates/nginx.conf
components/tools/OmeroPy/test/unit/clitest/test_web.py

This should make it easier to review the effects of any future config changes.
Reference configs exist for each web-server with defaults, and each web-server with all options together. Combinations of options continue to be tested by the existing tests.

Compare full generated web configs

---

components/tests/ui/plugins/robot.py
components/tests/ui/resources/robot.template

This is the same as gh-3491 but rebased onto dev_5_0.
----
For servers where HTTP is redirected to HTTPS, the OMERO.web robot framework tests will systematically fail. This commit allows to configure the transfer protocol when generating the configuration file, defaulting to HTTP.

Add --protocol option to configure Web protocol in Robot config file (rebased onto dev_5_0)

---

components/tools/OmeroPy/src/omero/gateway/scripts/dbhelpers.py
components/tools/OmeroPy/src/omero/gateway/scripts/testdb_create.py

This PR removes the need for a personal URL as the necessary files are made public.
To test it, check the gateway tests still pass.

Fix gateway test helpers to point at downloads.openmicroscopy.org

---

components/tools/OmeroWeb/omeroweb/webclient/urls.py

This should resolve HTTP 404 when coping and pasting rendering onto image in share.
To test:
- choose user who has 2 images with the same number of channels (to make sure will be able to copy and past rendering settings) in private group.
- share them with another user2 who normally cannot access these images.
- login as user2 and try to copy and past rendering settings from one image to another in image viewer (not Preview tab)
Check Firebag console if there are no HTTP 404 responses
--no-rebase

fixing copy/past rendering settings in share

---

components/tools/OmeroPy/src/omero/plugins/basics.py
components/tools/OmeroPy/test/unit/clitest/test_basics.py
components/tools/OmeroPy/test/unit/clitest/test_help.py

Following discussion https://github.com/openmicroscopy/openmicroscopy/pull/3507, this PR also aims to address https://trac.openmicroscopy.org/ome/ticket/10851.
Notable changes to the CLI `HelpControl` class are listed below:
- `--all/topic` are moved in a mutually exclusive group
- a `--recursive` argument is added to the parser allowing to display subcommands help
- a `--list` argument is added to the parser allowing to list all commands/subcommands
- the command title is formatted to distinguish commands and subcommands
- Sphinx compatible separators are used in case we want including this output of `bin/omero help --all --recursive` in the documentation
- unit tests are added and should be run by Travis
To test this PR, review the various versions of the command:
```
bin/omero help -h …
```

CLI: review help command and add recursive argument

---

components/tools/OmeroPy/test/integration/test_permissions.py

This is a trivial PR that shouldn't need review. Its aim is to tidy the results of https://ci.openmicroscopy.org/job/OMERO-5.1-merge-integration-broken/ where the number of fails (and passes) of should drop, fewer tests run. The number of tests run in https://ci.openmicroscopy.org/job/OMERO-5.1-merge-integration-python/ will increase but there should be no extra fails due to this PR.
--no-rebase

Mark broken tests as xfail until hibernate update.

---

components/tools/OmeroPy/src/omero/gateway/scripts/dbhelpers.py
components/tools/OmeroPy/src/omero/gateway/scripts/testdb_create.py

This is the same as gh-3533 but rebased onto dev_5_0.
----
This PR removes the need for a personal URL as the necessary files are made public.
To test it, check the gateway tests still pass.

Fix gateway test helpers to point at downloads.openmicroscopy.org (rebased onto dev_5_0)

---

components/insight/build/app.xml

This PR should stop builds failing due to running out of heap space. I'm not sure if there is a rigorous way to test this other than that a local default build should be successful. 
/cc @joshmoore in case he can suggest better testing.

Carry maxmem setting through to Insight app build file.

---

components/blitz/src/ome/formats/OMEXMLModelComparator.java
components/blitz/src/ome/formats/model/ReferenceProcessor.java

A LightSettings object can be attached to either a Channel (with 2
indexes) or a MicrobeamManipulation (with 3 indexes).  This removes the
hard-coded index counts and updates ReferenceProcessor to fill in the
index map appropriately for both cases.  This should prevent
OMEXMLModelComparator from incorrectly detecting the LSID equality when
there are many of both types of LightSettings linkages, which in turn ensures that each LightSettings' reference to a LightSource is properly resolved.
Fixes http://trac.openmicroscopy.org/ome/ticket/12603.
To test as in the ticket, run:
```mkfake test.fake -plates 4 -runs 4 -rows 4 -columns 4 -fields 4```
and then import ```test.fake```.  Without this PR, an exception should be thrown during metadata processing as in the ticket; with this PR, the …

Make LightSettings indexing work with Channel and MicrobeamManipulation

---

components/blitz/src/ome/services/blitz/repo/CheckedPath.java
components/blitz/src/omero/cmd/Helper.java
components/blitz/src/omero/cmd/RequestObjectFactoryRegistry.java
components/blitz/src/omero/cmd/graphs/Chgrp2I.java
components/blitz/src/omero/cmd/graphs/ChgrpFacadeI.java
components/blitz/src/omero/cmd/graphs/Chown2I.java
components/blitz/src/omero/cmd/graphs/ChownFacadeI.java
components/blitz/src/omero/cmd/graphs/Delete2I.java
components/blitz/src/omero/cmd/graphs/DeleteFacadeI.java
components/blitz/src/omero/cmd/graphs/DiskUsageI.java
components/blitz/src/omero/cmd/graphs/GraphRequestFactory.java
components/blitz/src/omero/cmd/graphs/SkipHeadI.java
components/server/src/ome/services/graphs/GraphPathBean.java
components/tools/OmeroJava/test/integration/DiskUsageTest.java

For instance, try `bin/omero fs usage Blah:1`; also check that https://ci.openmicroscopy.org/job/OMERO-5.1-merge-integration-java/lastCompletedBuild/testngreports/integration/DiskUsageTest/ passes.
--no-rebase

Have disk usage give an error message when a bad class name is given

---

components/tools/OmeroPy/src/omero/plugins/fs.py
components/tools/OmeroPy/src/omero/util/text.py

This PR is intended to improve the output options for the disk usage plug-in now that size and file counts are available at a per-user, per-group, per-component level. Firstly it allows totals to be summed by any of the three parts above:
```
--sum_by {user,group,component} [{user,group,component} ...]`
```
which will sum the totals by one, two or all three options. Summing by all three options is the same as not using this flag at all, ie the default. This only has an effect when the `--report`` option is used.
The second addition is:
```
--pretty
```
This pretty-prints the sizes by making the human-readable. This works for both the single value and for the table when `--report` is used. It is, however, overridden by any `--units` setting for the single value. The other minor point is …

Improvements to disk usage plugin

---

components/tools/OmeroPy/src/omero/gateway/utils.py
components/tools/OmeroPy/test/unit/gatewaytest/test_utils.py
components/tools/OmeroWeb/omeroweb/webadmin/forms.py
components/tools/OmeroWeb/omeroweb/webadmin/views.py
components/tools/OmeroWeb/omeroweb/webclient/forms.py
components/tools/OmeroWeb/omeroweb/webclient/views.py

As pointed in https://github.com/openmicroscopy/openmicroscopy/pull/3433#issuecomment-73008462 toBoolean should handle "on" as well
To be tested:
- **active** and **admin** checkbooks on experimenter form, test both creation and editing
- **ssl** on Login panel
- **enable** checkbox on share form, test both creation and editing
- **import/Acquisition** date select box in search
- checkbox on confirmation when deleting single and multiple objects
- check if you see all 3 categories in dropdown menu
- test locally. Disable ```omero.client.ui.menu.dropdown.colleagues.enabled``` and check if list of members disappeared.
cc: @chris-allan 
--no-rebase

adding "on" as a True value in toBoolean

---

components/tools/OmeroWeb/omeroweb/webgateway/marshal.py
components/tools/OmeroWeb/test/integration/test_marshal.py

This is a simple workaround that allows the webclient to open the MicroManager file that fails with re.getTileSize() in https://trac.openmicroscopy.org/ome/ticket/12750
We do not need to call re.getTileSize() if it's not a big image.
Insight may already be applying this logic (or catching the exception) since this image is viewable in Insight.

imageMarshal getTileSize if tiles

---

components/tools/OmeroWeb/omeroweb/webclient/views.py

From: https://trello.com/c/GkdpN8wD/311-rfe-change-default-group-to-active-group-in-uis
To test:
- Browse to different group data in web, then logout. See that when you log in again you back to your Default group and this isn't changed on logout.
- Can also confirm this by changing default group in user settings.

Don't change group on web logout

---

components/tests/ui/testcases/web/webadmin_create_group_and_user.txt
components/tools/OmeroWeb/omeroweb/webadmin/forms.py
components/tools/OmeroWeb/omeroweb/webadmin/static/webadmin/css/chosen.css
components/tools/OmeroWeb/omeroweb/webadmin/templates/webadmin/email.html
components/tools/OmeroWeb/omeroweb/webadmin/templates/webadmin/experimenter_form.html
components/tools/OmeroWeb/omeroweb/webadmin/templates/webadmin/group_form.html
components/tools/OmeroWeb/omeroweb/webadmin/templates/webadmin/group_form_owner.html
components/tools/OmeroWeb/omeroweb/webadmin/views.py

This PR reverts changes to webadmin experimenter forms to simply allow choosing default group and fix few bugs.
tests:
- check if robot tests passed
to test experimenter:
- Click **New user** and fill data:
- by adding user to a group it imminently should become default group, choosing more groups shouldn't update default group.
- Edit the user and see if all data are correct and default group is set.
- Make user an admin and check if system group is added to the list. Choose system group as default. Save
- Edit user again and uncheck admin, see if system group was removed and but default group remain selected -> message should appear: ```"Choose default group"``` Click save button and check if validation fail with message above default group saying ```"No default group selected"``` and …

Webadmin set default group

---

components/tools/OmeroPy/src/omero/util/sessions.py
components/tools/OmeroPy/test/unit/clitest/test_sess.py

Minor bug reported by @manics. Under certain conditions a local session file can be with no `omero.port=xxx` line while using the default port. When this session is re-attached via:
```
bin/omero session -s host -k key -p 4064
```
it results in a conflict between the old port (`None`) and the new port (`4064`). This PR adds a special case in `store.conflicts` to handle this particular case and implements the corresponding unit tests (which should pass).
--no-rebase

CLI key session

---

components/blitz/src/ome/formats/OMEROMetadataStoreClient.java
components/blitz/src/ome/services/blitz/repo/ManagedImportRequestI.java

Annotations with namespace NSCOMPANIONFILE are no
longer needed since all the files in a single fileset
are grouped in the database and are parseable via
Bio-Formats. Clients can continue looking for old
companion annotations but no assumption should be
made that all images will have them.

Disable companion attachments (Fix #12519)

---

components/tools/OmeroPy/src/omero/plugins/web.py
etc/templates/apache.conf.template
etc/templates/nginx-development.conf.template
etc/templates/nginx.conf.template

See https://trello.com/c/FHk2rdFe/433-remove-non-tcp-fastcgi-apache-config
We never use or test FastCGI with sockets so there should be no visible effect of this PR. Just check that the generated templates are unchanged.
Note: FastCGI sockets continue to be usable with OMERO.web, but you'll have to create the web-server configuration file yourself.

Remove fastcgi -socket from web template generation

---

components/tools/OmeroWeb/omeroweb/webclient/urls.py
setup.cfg

This PR fixes `urls.py` to be flake8 compliant. Note the same convention as in `settings.py` is adopted i.e. urls are either preserved as single lines when possible or split across multiple-lines for each attribute.
--no-rebase

Webclient: flake8 urls

---

components/tools/OmeroPy/src/omero/plugins/prefs.py
components/tools/OmeroPy/test/unit/clitest/test_prefs.py

See https://www.openmicroscopy.org/community/viewtopic.php?f=5&t=7752#p15430
This PR should prevent an operation like
```
bin/omero config set omero.property= value
```
Apart from checking the unit tests are green in Travis, testing this PR should include running this command and testing `config.xml` remains unmodified.
--no-rebase

Prevent property with trailing equal sign in config set

---

components/blitz/resources/omero/cmd/API.ice
components/blitz/src/omero/cmd/HandleI.java
components/blitz/src/omero/cmd/basic/DoAllI.java
components/blitz/src/omero/cmd/graphs/SkipHeadI.java
components/blitz/test/omero/cmd/admin/ResetPasswordRequestTest.java
components/blitz/test/omero/cmd/fs/OriginalMetadataRequestTest.java
components/blitz/test/omero/cmd/mail/SendEmailRequestTest.java
components/tools/OmeroPy/test/integration/test_delete.py

Addresses some of the discussion on https://trac.openmicroscopy.org/ome/ticket/10474. Ensure that https://ci.openmicroscopy.org/job/OMERO-5.1-merge-integration-python/lastCompletedBuild/testReport/test.integration.test_delete/TestDelete/ passes.
--no-rebase

add a "current step" to status of async server jobs

---

components/insight/SRC/org/openmicroscopy/shoola/agents/dataBrowser/view/AdvancedResultSearchModel.java
components/insight/SRC/org/openmicroscopy/shoola/agents/dataBrowser/view/SearchComponent.java
components/insight/SRC/org/openmicroscopy/shoola/agents/dataBrowser/view/SearchPanel.java
components/insight/SRC/org/openmicroscopy/shoola/agents/dataBrowser/view/SearchResultTableModel.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/GeneralPaneUI.java
components/insight/SRC/org/openmicroscopy/shoola/agents/util/finder/AdvancedFinder.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/OMEROGateway.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/OmeroDataServiceImpl.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/util/PojoMapper.java
components/server/src/ome/services/fulltext/FullTextBridge.java
etc/omero.properties

Fixes the blockers discovered in todays testing session, see [GDoc](https://docs.google.com/spreadsheets/d/1nPQbPov8dwIlHswGey0K779JirYsjdEg2CKK5khtI9w/edit#gid=1171413927)
Test:
- Search for a MapAnnotation key or value, when the checkbox "Annotation" is ticked (before: no results)
- Enter an invalid expression, e. g. a term with two colons asdf:123:asdf. You should see a message dialog, saying that the search expression is invalid (before: default crash/error dialog popped up)
- Enter something in the search field in the main toolbar, hit enter. The search panel on the left should open and show the same what you've entered in the main toolbar without a trailing space.
- Annotate a plate run and then search for it (before: plate runs were ignored)
- Check that the number of search …

Mapannotation search fixes

---

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/container_tags.html

Fixes http://trac.openmicroscopy.org/ome/ticket/12773
To test, simply browse the Tags tree in web, double-click on Image and see if Image Viewer opens.
--no-rebase

Tag tree double-click

---

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/base/base.html
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/history/history.html
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/search/search.html

This fixes the preview panel viewer on the basket page, as reported https://github.com/openmicroscopy/openmicroscopy/pull/3531
but the bug was actually the missing infieldlabel.js javascript library on the basket page.
Also found that this lib was duplicated for search and history pages, being also present in their parent template.
To test:
- Check that in-line labels work (the placeholder text is removed when you start to type) in right panel Comments field on basket page, search results page and history page.
- Check that in-line labels work for top search field on basket page.
- Check that image viewer works in Preview panel on basket page.

Basket preview viewer fix

---

components/tools/OmeroWeb/omeroweb/webclient/tree.py
components/tools/OmeroWeb/test/integration/test_tree.py

Fix for http://trac.openmicroscopy.org/ome/ticket/12771
When multiple Projects containing multiple Datasets are retrieved by projection in marshal_projects() they are initially P-D pairs,
```
p1 - d1
p1 - d2
p2 - d3
```
and are organised into hierarchies by sorting by Project name, then collapsing datasets if 2 adjacent Projects are the same. 
E.g.
```
p1 - d1
- d2
p2 - d3
```
However, if we have many Projects with the same name, then the same Project will not be sorted beside each other and not fully collapsed.
E.g. 
```
p1 - d1
p2 - d3
p1 - d2
```
Fix is to simply sort by ID after sorting by Project name.
To test, check that multiple same-named Projects with multiple Datasets only appear a single time in the tree. See ticket above for links to existing data in trout.
Also applied the …

Duplicate projects in tree

---

components/tools/OmeroWeb/omeroweb/webgateway/templates/webgateway/viewport/omero_image.html

A couple of minor fixes, including http://trac.openmicroscopy.org.uk/ome/ticket/12758
To test:
- Open the web image viewer. The "Normal" projection radio button should be checked.
- For single Z-plane images, the "Max Intensity" projection should be disabled (also check it's not disabled in Z-stack images).

Image viewer projection fixes

---

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/UserUI.java

No longer display user details in an expandable/collapsable component
To test:
* Select user in tree and check the right hand pane
see https://trac.openmicroscopy.org/ome/ticket/10472

user settings

---

components/tools/OmeroPy/test/unit/clitest/reference_templates/apache-fcgi-withoptions.conf
components/tools/OmeroPy/test/unit/clitest/reference_templates/apache-fcgi.conf
components/tools/OmeroPy/test/unit/clitest/reference_templates/apache-withoptions.conf
components/tools/OmeroPy/test/unit/clitest/reference_templates/apache.conf
components/tools/OmeroPy/test/unit/clitest/reference_templates/nginx-development-withoptions.conf
components/tools/OmeroPy/test/unit/clitest/reference_templates/nginx-development.conf
components/tools/OmeroPy/test/unit/clitest/reference_templates/nginx-withoptions.conf
components/tools/OmeroPy/test/unit/clitest/reference_templates/nginx.conf
components/tools/OmeroPy/test/unit/clitest/test_web.py
components/tools/OmeroWeb/omeroweb/settings.py

Change the OMERO.web fastcgi workers to listen on 127.0.0.1 by default instead of 0.0.0.0 (all interfaces including public ones).
https://trello.com/c/aRDoP7dC/355-omero-web-startup-review-default-ip
Testing: Regenerate nginx/apache-2.2/apache-2.4 web configs and check everything works.
Also check you can't connect to the app server (defaults to listening on port 4080) other than from localhost.
--norebase

OMERO.web default listen IP

---

components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/chooser/FileSelectionTable.java
components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/chooser/ImportDialog.java
components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/chooser/ImportLocationSettings.java
components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/chooser/LocationDialog.java
components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterComponent.java
components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterModel.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/model/FileObject.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/model/ImportableObject.java

In this PR
* Fix control when used in image mode. Check that you do not have in the main window 2 close/refresh buttons
* Pop up the location dialog when selecting Save results from plugins menu for images not already imported
* Fix the "new from folder" option when importing from imagej. Make sure it works for both insight client and insight as ij plugin
See https://trello.com/c/deNMiFvH/88-plugins-for-imagej-implementation
cc @pwalczysko @bramalingam

Import location ij

---

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/GeneralPaneUI.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/ToolBar.java
components/insight/SRC/org/openmicroscopy/shoola/agents/util/EditorUtil.java

This PR tackles a few problems with the metadata panel:
- Aligns the 'Located in' task pane like the other task panes (and not at the bottom) - *make sure the 'Located in' pane still works, does not stick on the bottom, and behaves like the other panes.*
- Brings back the download button in the toolbar, which I accidently removed in a previous PR - *check that the download button is there, and still works like expected*
- Rounds all values shown in Metadata panel to two decimal places (you can test the rounding for example with test_images_good/lei_martin_sp2; these images contain many metadata values with lots of decimal places) - *check that you don't see any metadata value with more than 2 decimal places*

Right panel adjustments

---

components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewerComponent.java

Allow to move dataset out of project via DnD.
see https://trac.openmicroscopy.org/ome/ticket/11083
To test:
* Select a dataset in a Project
* Move the dataset out of the project using DnD
* The action should be performed w/o dialog popping up

DnD move dataset

---

components/tools/OmeroWeb/omeroweb/webgateway/util.py

See http://trac.openmicroscopy.org/ome/ticket/12776
When downloading multiple files with duplicate names, use a simple index to name sub-directories.
To test:
- import the same image 3 times
- Select the 3 images -> Download
- Download the created zip and unzip.
- Files from one image should be in the root directory, with two other directories /1/ and /2/ containing the files for the other images.

Download dir names

---

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/AnnotationDataUI.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/DocComponent.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/MapAnnotationsComponent.java
components/insight/SRC/org/openmicroscopy/shoola/agents/util/EditorUtil.java
components/insight/SRC/org/openmicroscopy/shoola/agents/util/ToolTipGenerator.java

Modifies MapAnnotation panel so that it takes the 'show all', 'added by me' and 'added by others' filter into account. Also adds a tooltip to the MapAnnotation panel (Tooltip is active on the title border around the MapAnnotations panel, which means the user's own MapAnnotation doesn't have a tooltip).
Test: Check that the "Show all", "Show added by me" and "Show added by others" filter in the Annotations panel works for MapAnnotations like it does for all other kinds of annotations. Check that the tooltip is shown when you hover of the titled border of another user's MapAnnotation.
See [Ticket 12752](https://trac.openmicroscopy.org/ome/ticket/12752)

Filter MapAnnotations

---

components/tools/OmeroPy/src/omero/plugins/obj.py
components/tools/OmeroPy/test/integration/clitest/test_obj.py

Three new commands have been added to obj.py to enable the testing of https://github.com/openmicroscopy/openmicroscopy/pull/3593 :
* `bin/omero obj map-set CLASS:ID FIELD KEY VALUE`
* `bin/omero obj map-get CLASS:ID FIELD`
* `bin/omero obj null CLASS:ID FIELD`
Integration tests are in place, but minor local testing is welcome. Help is provided via `bin/omero obj -h`
cc: @ximenesuk @pwalczysko

obj.py commands: map-get, map-set, null

---

components/tools/OmeroPy/src/omero/gateway/__init__.py
components/tools/OmeroPy/test/integration/gatewaytest/test_image.py

In 5.1 the API for methods that return units is unchanged from 5.0. E.g.
```
pixels.getPhysicalSizeX().getValue()
```
However, in the Blitz Gateway this is now broken
```
pixels.getPhysicalSizeX().getValue()
AttributeError: 'UnitsLength' object has no attribute 'getValue'
```
We get this error in Make_Movie script (although this used to work until recently)?
This PR updates Blitz Gateway ``` __getattr__ ``` to handle units and includes a test:
```
$ cd OmeroPy
$ ./setup.py test -t test/integration/gatewaytest/test_image.py -k testUnitsGetValue
```
Check that tests are passing at https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-integration/ and Make_Movie script works.
--no-rebase

Blitz getattr with units

---

components/tools/OmeroPy/src/omero/config.py
components/tools/OmeroPy/test/unit/test_config.py

This was previously opened as #3579.
To test:
- BEFORE building with this PR, set top_links to have a single link, E.g.
```
$ bin/omero config set omero.web.ui.top_links '[["Test", "www.ome.org"]]'
```
- Webclient should only show a single 'Test' link in header.
- Now upgrade / build with this PR and start OMERO.
- Should see "Data", "History", "Help", "Test" links at top of webclient.
- restart the server again and check that more links are not added!
- Open dist/etc/grid/config.xml and check for 2 version blocks that state "5.1.0" (under 2 different ```<properties>``` blocks)
```
<property name="omero.config.version" value="5.1.0" />
```
Tests should also pass:
```
$ cd OmeroPy
$ ./setup.py test -t test/unit/test_config.py
```
--no-rebase

Upgrade settings toplinks

---

components/blitz/resources/omero/api/RenderingEngine.ice
components/blitz/src/ome/services/blitz/impl/RenderingEngineI.java
components/common/src/omeis/providers/re/RenderingEngine.java
components/server/src/ome/services/RenderingBean.java
components/tools/OmeroJava/test/integration/RenderingEngineTest.java

These methods will properly set the lookupTable
field on ChannelBinding. For the moment, that is
the extent of implementation for 5.1.0. A next
step will be to teach the RenderingEngine how to
make use of these properties.

RenderingEngine: lookupTable getters/setters

---

components/blitz/resources/omero/api/IUpdate.ice
components/insight/SRC/org/openmicroscopy/shoola/env/data/OMEROGateway.java

Deprecates `IUpdate.deleteObject` arising from discussion on https://trac.openmicroscopy.org/ome/ticket/2683. Definitely make sure that Insight object-delete options still work: this isn't the button for deleting images, datasets, etc., but instead subtler uses, like in cut/unlink or in changing / removing shapes in ROIs. In checking deletion, ensure that *only* the correct object(s) was deleted.
--no-rebase

RFC: Deprecate IUpdate.deleteObject API method

---

components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ControlPane.java

Use normal combobox.
see https://trac.openmicroscopy.org/ome/ticket/11742
To test:
* Select an image with several z
* Open the full viewer.
* Go to the projection tab.
* Check that the options are displayed in a general combobox.

projection combobox

---

components/blitz/resources/omero/cmd/FS.ice
components/blitz/src/omero/cmd/RequestObjectFactoryRegistry.java
components/blitz/src/omero/cmd/fs/UsedFilesRequestI.java

This new request is easily tested from a simple script. For instance, for `user-2` to check which files are associated with their image ID 143 on trout's merge server,
```python
from omero.gateway import BlitzGateway
from omero.cmd import UsedFilesRequest
from omero.callbacks import CmdCallbackI
conn = BlitzGateway('user-2', 'ome', host='trout.openmicroscopy.org', port=4064)
conn.connect()
prx = conn.c.sf.submit(UsedFilesRequest(imageId=143))
print CmdCallbackI(conn.c, prx).loop(500, 500)
conn._closeSession()
```
Then, the names of these files (e.g., with IDs 45, 47) can be checked with something like,
```
bin/omero hql "SELECT id, path||name FROM OriginalFile WHERE id IN (45,47)"
```
In testing, include both pre-FS and FS data, images both from and not from plates (oughtn't work at all …

add a new "used files" request to the server

---

components/tools/OmeroPy/test/integration/scriptstest/test_inputs.py
components/tools/OmeroPy/test/integration/scriptstest/test_rand.py

`test_inputs` uses a callback block time of 500ms while a similar test, `test_rand`, has 2000ms. Increasing the former to 2000 seems to make the test reproducibly pass locally. (Conversely, decreasing the latter to 500 causes that test to fail intermittently.)The only test here is whether this test passes in the CI builds.
—no-rebase
(though this could well be rebased if necessary)

Reduce likelihood of test_inputs failing intermittently 

---

components/blitz/resources/omero/Constants.ice
components/model/resources/mappings/acquisition.ome.xml
components/model/src/ome/model/internal/NamedValue.java
components/model/src/ome/model/internal/Permissions.java
components/server/resources/ome/services/hibernate.xml
components/server/resources/ome/services/sec-primitives.xml
components/server/src/ome/security/ACLEventListener.java
components/server/src/ome/security/ACLVoter.java
components/server/src/ome/security/CompositeACLVoter.java
components/server/src/ome/security/auth/SimpleRoleProvider.java
components/server/src/ome/security/basic/BasicACLVoter.java
components/server/src/ome/security/basic/OmeroInterceptor.java
components/server/src/ome/security/policy/BinaryAccessPolicy.java
components/server/src/ome/security/policy/DownloadPolicy.java
components/server/src/ome/security/sharing/SharingACLVoter.java
components/server/src/ome/services/RawFileBean.java
components/server/src/ome/tools/hibernate/ProxyCleanupFilter.java
components/tests/python/library/__init__.py
components/tools/OmeroPy/src/omero/plugins/download.py
components/tools/OmeroPy/test/integration/clitest/test_download.py
components/tools/OmeroPy/test/integration/test_permissions.py
components/tools/OmeroWeb/omeroweb/settings.py
etc/omero.properties

This PR aims to build on gh-3543 by:
cc: @pwalczysko @aleksandra-tarkowska 
* For plates, in the UIs the Download and Download Original Metadata menus are missing. If a group enables `+plate`, then the UI menus will come back.
* All the downloads of non-plate data should work as before.
* Like (A), but no override is possible for individual groups.
* As (B) above, but download will be restricted for members of the group who:
* are not the owners of an image (assuming a non-`rwrw--` group)
* are not owners of the group
* are not in the system group
* Downloads should be **enabled** for all objects.
* A single group can disable plate imports by setting `-plate`.
* Downloads should be **disabled** for all objects. (Just setting `-write` is sufficient for this setting, which is equivalent to …

Restrict download (Take 2)

---

components/tests/python/library/__init__.py
components/tools/OmeroPy/src/omero/gateway/__init__.py
components/tools/OmeroWeb/omeroweb/webclient/webclient_gateway.py
components/tools/OmeroWeb/omeroweb/webgateway/views.py
components/tools/OmeroWeb/test/integration/test_download.py

https://github.com/openmicroscopy/openmicroscopy/pull/3543 follow up.
As long as PR #3593 is in, this should validate default settings and enable download button for image and file annotations but not allow to download plate. For custom config this can be tested as stated in #3593
**To test** go to Read-Ann group, choose user, choose own image and download. Repeat the same test in read-only and private group, try also with big image. Then test plate. Arrow button was turned on but you should see only export as, no Download.
Check if test passed
https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-integration-web/lastCompletedBuild/testReport/test.integration.test_download/TestDownload/test_spw_download/
--no-rebase

Fixing Download button

---

components/insight/SRC/org/openmicroscopy/shoola/agents/dataBrowser/actions/DownloadAction.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorControl.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorModel.java
components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/actions/DownloadAction.java
components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewerComponent.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/model/DownloadArchivedActivityParam.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/views/MetadataHandlerView.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/views/MetadataHandlerViewImpl.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/ArchivedImageLoader.java
components/insight/SRC/org/openmicroscopy/shoola/env/ui/ArchivedLoader.java
components/insight/SRC/org/openmicroscopy/shoola/env/ui/DownloadArchivedActivity.java

There were several issues with the Download dialog, e. g. it claimed you could modify the name but didn't use the modified name ([Ticket 12784](https://trac.openmicroscopy.org.uk/ome/ticket/12784)), if multiple images were selected the first image was zipped but not the other ones, etc. With this PR the file(s) will always be zipped (name of zip file can be modified), and it also unifies the dialog when invoked from different places (Metadata panel, treeviewer, etc.). Also fixes an issue with download of file annotations from the tree viewer (previously it picked the destination folder name as file name).
Test:
- Check that download of original images (with single and multiple selection) works, initiated from all possible places (left hand side tree viewer, central data browser and right …

Download original files

---

components/blitz/src/ome/services/blitz/repo/ManagedImportRequestI.java

Do not set the min max values to full range for big images of type float or double
We do not generate pyramid for big images of that pixels type
to test the PR:
* Import ```team/will/float-data/mrc/AMI-public-data/GroEL/...ef.mrc``` team/will/float-data.zip
* Check that the min max does not correspond is resp. ```181.491``` and ```627.354``` (was ```-2147483648``` and ```2147483647```)
* Open the image in imageJ and check it matches the omero image.

Float big image

---

components/tools/OmeroPy/src/omero/plugins/db.py
components/tools/OmeroPy/test/unit/clitest/test_db.py

- `omero db script`: only prompts for the root password
- `omero db script --password ome`: Shouldn't prompt for anything
- `omero db script --version DBVERSION --patch DBPATCH`: Set db.version and db.patch for developers
- `omero db script DBVERSION DBPATCH`: Old deprecated behaviour (positional args)
- All other existing flags should continue to work
https://trello.com/c/8PPlaBmP/456-remove-compulsory-version-patch-args-from-db-script
--no-rebase

Remove version and patch prompts from `omero db script`

---

components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/ome.roidisplay.js

As a follow up https://github.com/openmicroscopy/openmicroscopy/pull/3587 web also removes yellow background behind the text.
To test:
- draw ROIs (rectangular and elipse) with text, add Text ROI. Save
- open the same image in web and check if text has no yellow background behind the text.
- test if selected objects are marked with blue line overlapping border of ROI 
test with big image and see if line remain minimum half of the ROI line
--no-rebase

ROI text background

---

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/actions/ManageRndSettingsAction.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/ChannelSlider.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/PreviewToolBar.java

Fix some UI issues when no stats info for the image
To test
* Import an image using the CLI see https://github.com/openmicroscopy/openmicroscopy/pull/3580
* Go to preview in insight:
*  check that channel slider is correctly displayed
* Check that the min/max is not enabled.
Note that Web still has the min/max enabled, if click on min/max, it defaults to Full range.
is it the behaviour we want? @gusferguson @will-moore @pwalczysko

No stats ui

---

components/tools/OmeroWeb/omeroweb/webclient/views.py

Test locally, log in to webclient and check the console
```
[16/Mar/2015 10:16:48] "POST /webclient/login/?url=%2Fwebclient%2F HTTP/1.1" 302 0
dist/lib/python/omero/gateway/__init__.py:2757: DeprecationWarning: Deprecated. Use ExperimenterGroupWrapper.groupSummary()
DeprecationWarning)
[16/Mar/2015 10:16:49] "GET /webclient/ HTTP/1.1" 200 115697
```
This should **disappear**
--no-rebase

fixing deprecated warning

---

.travis.yml
components/tests/python/library/__init__.py
components/tools/OmeroPy/test/integration/clitest/test_chgrp.py
components/tools/OmeroPy/test/integration/clitest/test_download.py
components/tools/OmeroPy/test/integration/clitest/test_group.py
components/tools/OmeroPy/test/integration/clitest/test_user.py
components/tools/OmeroPy/test/integration/cmdtest/test_chgrp.py
components/tools/OmeroPy/test/integration/scriptstest/test_repo.py
components/tools/OmeroPy/test/integration/test_admin.py
components/tools/OmeroPy/test/integration/test_counts.py
components/tools/OmeroPy/test/integration/test_delete.py
components/tools/OmeroPy/test/integration/test_itimeline.py
components/tools/OmeroPy/test/integration/test_mail.py
components/tools/OmeroPy/test/integration/test_permissions.py
components/tools/OmeroPy/test/integration/test_rawfilestore.py
components/tools/OmeroPy/test/integration/test_simple.py
components/tools/OmeroWeb/test/integration/test_chgrp.py
components/tools/OmeroWeb/test/integration/test_csrf.py
components/tools/OmeroWeb/test/integration/test_marshal.py
components/tools/OmeroWeb/test/integration/weblibrary.py

This PR provides various improvements for the Python/Web integration tests requested in https://trello.com/c/99yzWP3v
Major changes:
- `ITest` now defines a `DEFAULT_PERMS` which can be overriden by test classes requiring a different default permission for the group
- the user, group and context initially created by `ITest.setup_class()` are stored as attributes of the class
- a generic `ITest.skip_if(config, condition)` is introduced allowing to skip tests conditionally based on a server configuration
Most integration tests should be modified to make use of these features. Some unnecessary user/client creation are removed from tests. To review this PR, check all Python/Web integration tests are passing. A corresponding documentation PR will need to be opened to describe these additions …

Python tests library improvements

---

components/tools/OmeroWeb/omeroweb/webclient/static/webclient/css/layout.css

From https://trac.openmicroscopy.org/ome/ticket/12783
This fixes the layout of the map annotation table with long Key Value strings.
To test, enter long text strings into the Key and Value fields.
Text that is too big for the table will simply be hidden, and the Key / Value table cells will remain at 50% width of the table.
--no-rebase

Preserve map ann table layout with long strings

---

components/blitz/resources/omero/ROMIO.ice
components/blitz/resources/omero/api/RenderingEngine.ice
components/blitz/src/omero/util/IceMapper.java
components/common/src/omeis/providers/re/data/PlaneDef.java
components/server/src/ome/services/RenderingBean.java

This PR cleans up mask rendering by adding a new `PlaneDefWithMasks` subclass of `PlaneDef` and deprecating the unused, ugly and broken `setOverlays()` method on the rendering engine. This was discussed as the best way forward for the 5.1.0 milestone with @jburel and @joshmoore.
There should be no affect on the clients as none of them were using this logic. Intentions are to expand and make use of this API in 5.1.1 or later. Getting the API changes in for 5.1.0 was paramount. For the moment the old code stands as it is, parts of it are fixed by #3580, and some new example code has been added that works against Mask shapes matching the previous rendering criteria associated with the current image.
Review should be performed by @jburel and @joshmoore.
/cc @emilroz

Clean up mask rendering

---

components/tools/OmeroPy/src/omero/plugins/script.py
components/tools/OmeroPy/src/omero/plugins/sessions.py
components/tools/OmeroPy/test/integration/clitest/test_sessions.py

Reported by @manics. The addition of last port in https://github.com/openmicroscopy/openmicroscopy/pull/3370 broke `bin/omero sessions file`.
This PR should fix this bug and add an integration test to extend our coverage.
--no-rebase

Fix CLI sessions file

---

components/tools/OmeroWeb/omeroweb/settings.py

1. This should help with side effect reported in https://trello.com/c/aRDoP7dC/355-omero-web-startup-review-default-ip. To test:
- add
```
bin/omero config set omero.web.session_cookie_domain "localhost"
```
- open private windows in your webbrowser
- go to localhost:4080, and log in. All shoudl be as normal
- if you have another domain configured on you machine use it, otherwise go to 127.0.0.1:4080 and log in. you should be back to your login page without any error message. that means you cookie wasn't save.
if you remove ```omero.web.session_cookie_domain``` you should be able to log in from all possible domains assigned to the same machine
1.  This should also resolve issue reported in https://github.com/openmicroscopy/openmicroscopy/pull/3629#issuecomment-82874726. To test:
- remove …

session cookie domain

---

examples/Training/python/Connect_To_OMERO.py
examples/Training/python/Create_Image.py
examples/Training/python/Delete.py
examples/Training/python/Filesets.py
examples/Training/python/Groups_Permissions.py
examples/Training/python/Metadata.py
examples/Training/python/Parse_OMERO_Properties.py
examples/Training/python/ROIs.py
examples/Training/python/Raw_Data_Access.py
examples/Training/python/Read_Data.py
examples/Training/python/Render_Images.py
examples/Training/python/Tables.py
examples/Training/python/Write_Data.py
examples/Training/python/__main__.py

This commit implements the same logic as the one used for MATLAB training
examples to run the Python examples automatically via Continuous Integration.
The configuration properties are read from an ice.config files using
omero.client() but can be overridden by editing Parse_OMERO_Properties
manually.
To be tested by the http://ci.openmicroscopy.org/job/OMERO-5.1-merge-training/ job
--no-rebase

Move Python training examples configuration for CI testing

---

components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/MeasurementViewerUI.java

Workaround for [Ticket 12790](https://trac.openmicroscopy.org/ome/ticket/12790)
Problem: Graph and Intensity view pane should actually be disabled for big images, but float images aren't recognized as big images (PixelService.requiresPixelPyramid() always returns false for float images -> which on the client side means, it's not a big image). And with #3525 float big images don't have a statsinfo anymore, i. e. global min/max of channels can't be determined, which raised the exception in the ticket above, because this is needed for the graph and intensity view pane. This PR disables the graph and intensity view pane in these cases.
It's more a workaround, because the underlining cause (float images aren't recognized as 'big images') is not tackled here. 
@jburel Your thoughts, use this …

Disable graph and intensity pane for bigimages without stats

---

components/tools/OmeroWeb/omeroweb/webgateway/views.py

This fixes http://trac.openmicroscopy.org/ome/ticket/12794 which is due to a couple of bugs in webgateway/download_as for batch exporting images as PNG, JPG etc. See https://www.openmicroscopy.org/community/viewtopic.php?f=5&t=7766
We were using ``` @login_required(doConnectionCleanup=False) ``` incorrectly here, since we are not streaming data from OMERO directly (don't need to keep services open once the request returns and streaming starts). This meant that open Rendering Engines were not getting closed.
We were also failing to call image._re.close() for each image after rendering and saving into the zip folder. For each image, a new ProxyObjectWrapper for each rendering engine was getting created but the underlying rendering engines were not getting closed each time.
Both these issues …

Download_as closes RE

---

components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/chooser/ImportDialog.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/model/FileObject.java

Do not save the roi in the ome-tiff.
To test:
* Open a local image in ImageJ
* Crop the image
* Draw rois on the cropped image. Add them as overlays or add them to the roi manager
* Save the cropped image to omero
* The cropped image will be imported as ome-tiff
* Check that the ROIs are imported but they are not included into the ome-tiff
* To check that the rois are not included in the ome-tiff. Download the original file
* Open the ome-tiff and check the XML part of it does not content any roi.

Import ome tiff

---

history.txt

OMERO 5.1.0-m5 version history to be auto-generated in the docs
--no-rebase
cc @sbesson @jburel @joshmoore

Add m5 version history

---

components/tools/OmeroPy/src/omero/gateway/__init__.py

Since it's no longer an error to have no stats info (see https://github.com/openmicroscopy/openmicroscopy/pull/3580) we should log this merely at 'debug' level instead of 'error'.
To test:
- Import image with no stats
- Open in web - observe Web log for lack of errors.
--no-rebase.

Log null statsInfo at 'debug' instead of 'error'

---

components/blitz/resources/ome/services/blitz-graph-rules.xml
components/tools/OmeroJava/test/integration/delete/AdditionalDeleteTest.java

#3142 removed https://github.com/openmicroscopy/openmicroscopy/blob/352c6d1f7d23b163c8c2f4925de274beb61ef990/components/blitz/test/ome/services/blitz/test/DeleteITest.java. This code resurrects and somewhat fixes up many of those test methods in a new form: the class is now in `OmeroJava` extending `AbstractServerTest`, deleting using `Delete2`. Check that https://ci.openmicroscopy.org/job/OMERO-5.1-merge-integration-java/lastSuccessfulBuild/testngreports/integration.delete/AdditionalDeleteTest/ is passing.
In the longer term, QA permissions review will determine what tests should exist and clean up the coverage from the legacy tests that already exist. For the meantime, more tests are probably better than fewer.
--no-rebase

resurrect DeleteITest

---

examples/Delete/FileAnnotationDelete.java
examples/Delete/FileAnnotationDelete.py
examples/Training/java/src/training/DeleteData.java

Updates some examples to use `Delete2`, now that `Delete` is deprecated. Examples should still compile and run.
(I am happy to accept corresponding `examples/Training/matlab/DeleteData.m` fixes against this branch.)
--no-rebase

update some delete examples

---

components/insight/SRC/org/openmicroscopy/shoola/env/data/DataServicesFactory.java

This fixes a NPE which is thrown on startup of OMERO.Importer client
Test: Just start OMERO.Importer client

Fixed NPE in importer only startup

---

build.xml
components/antlib/resources/version.xml
components/antlib/scripts/source-archive.py
components/tools/OmeroCpp/cmake/Version.cmake

The git version used by various git commands in `components/antlib/resources/version.xml` was a short 6-digit form of the commit hash.  This is too short to use without risk of clashes.  This PR adds a long form of the hash and uses that instead; a short revision copy of the hash is retained for user display where needed.
I also noticed we weren't saving the UNIX release date for cmake, so that's also fixed here.
See also: https://github.com/openmicroscopy/bioformats/pull/1664/files
--no-rebase
/cc @sbesson 
--------
Testing:
Check the content of `components/antlib/resources/gitversion.xml` `components/tools/OmeroCpp/cmake/GitVersion.cmake`, `components/bioformats/ant/gitversion.xml` and `components/bioformats/cpp/cmake/GitVersion.cmake`; these should have short and long git versions. …

build: Use long and short git revisions

---

components/insight/SRC/org/openmicroscopy/shoola/plugins.config

Rename the menu item entry in the ```Plugins>OMERO``` menu
To test:
* Add the insight-ij plugins to the plugins folder of omero
* Check that the new entry is ```Save ROIs to OMERO```  see https://trello.com/c/fNLzoJ58/91-5-1-mx-follow-up

imagej plugins menu item

---

components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterComponent.java
components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterModel.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/OmeroImageServiceImpl.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/model/ImportableFile.java

Problem noticed when retesting ticket https://trac.openmicroscopy.org.uk/ome/ticket/12676
A black thumbnail could be displayed when importing for other
to test:
* log as admin or group owner
* Select a folder
* Import as a user from the group.
* Check that thumbnails are not black.

Import as thumbnail

---

components/blitz/src/ome/formats/OMEROMetadataStoreClient.java
components/tools/OmeroPy/test/integration/clitest/test_import.py

This PR mitigates the effect of bug described in https://trac.openmicroscopy.org.uk/ome/ticket/12781 It catches the error early and thus avoids the creation of a Fileset and the upload of files for what is a doomed import.
Test via a user who is a member of more than one group. From the CLI try importing into a Dataset in a group other than the one the user is logged in to. It should fail with a meaningful error message. Try a Dataset in the current group, that should work okay. Switching group using `omero sessions` should allow the failed import to succeed. Importing without a target Dataset should succeed. The same applies to Screens. Import via Insight is unaffected.
For example:
```
$ omero import -d 2 ~/Work/Images/dv/CFPNEAT01_R3D.dv
...
Created session …
```

Handle failure if target container is in different group.

---

components/tools/OmeroWeb/omeroweb/webstart/views.py

Minor fix adding build year to index template.
To test it go to:
- https://trout..../merge/index/
- https://trout.../merge/webstart/
check if 2007-2015 appears in a footer
--no-rebase

adding build year to index templates

---

components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/omero_image.js
components/tools/OmeroWeb/omeroweb/webgateway/views.py
components/tools/OmeroWeb/test/integration/test_csrf.py
components/tools/OmeroWeb/test/integration/weblibrary.py

Fix bug found today. To test:
- View another user's data in a group that is **NOT** your default group
- Using tree right-click menu, check that you can reset to "Imported" and "Owner's" settings on user's Dataset, Image, Plate & Run.

Reset defaults owners

---

components/tools/OmeroWeb/omeroweb/settings.py

https://github.com/aleksandra-tarkowska/openmicroscopy/commit/f01f975990d1ff214474cbebb2dbcfc830ab4e3b#commitcomment-9945312
This should pick up automatically email properties set for omero server
To test set:
- debug false
- ```bin/omero config set omero.mail.from "email@domain"```
- ```bin/omero config set omero.mail.host "localhost"```
- ```bin/omero config set omero.mail.port 25```
- ```bin/omero config set omero.mail.username```
- ```bin/omero config set omero.mail.password```
- ```bin/omero config set omero.web.admins '[["Full Name", "email@domain"]]'```
then go to https://trout/merge/tagsearch/. There is a broken link.
For 500 test locally
cc: @joshmoore @sbesson

renaming mail properties to match omero.mail.*

---

components/tools/OmeroJava/test/integration/ExporterTest.java

Add more tests for stylesheets not used in the catalog (3 stylesheets), Last round of tests to fully covered all stylesheets.
if you want to run the test locally, use
```
./build.py -f components/tools/OmeroJava/build.xml test -DTEST=integration/ExporterTest
```
Check that https://ci.openmicroscopy.org/view/5.1/job/OMERO-5.1-merge-integration-java/ is green

Stylesheets test

---

components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/util/SaveResultsDialog.java

Fix problem reported by @bramalingam  during week 4 testing see https://trello.com/c/4Dgz8Hs1/88-weekly-testing
To test:
* Open an image stored in OMERO in ImageJ using the imageJ plugin
* Draw a roi.
* Crop the image
* Select "Save ROIs to OMERO" item in "Plugins>OMERO"
* Check that the image is imported as ome-tiff

Modified image ImageJ

---

components/blitz/src/ome/services/blitz/impl/RawFileStoreI.java
components/blitz/src/ome/services/blitz/impl/ScriptI.java
components/blitz/src/ome/services/blitz/repo/PublicRepositoryI.java

Fix for [Ticket 12687](https://trac.openmicroscopy.org/ome/ticket/12687)
The session created for downloading an original file is correctly closed but the ServantHolder still holds a reference to it, this is why - I guess on some automatic cleanup task - several hours later the server again tries to close the session, which raises the error in the log file.
It's a bit tricky to test. Without the PR you see a pattern like this in the Blitz log.
After downloading an original file:
```
2014-10-28 11:50:40,344 INFO  [                      omero.cmd.SessionI] (erver-2898) Added servant to adapter: df58a5b5-368c-41d1-a8f3-fd810faf5871/c0bb169e-a772-41d8-bb68-f141d72afcc9omero.api.RawFileStore(omero.api._RawFileStoreTie@fabde1db)
...
2014-10-28 11:50:43,654 WARN  [ …
```

RawFileStore sessions

---

components/tools/OmeroCpp/CMakeLists.txt

Without conversions.h in lib/include/omero, compiling
a client is all but impossible.
cc: @rleigh-dundee @emilroz

C++: add conversions.h to CMakeLists.txt

---

.travis.yml

Enable the sudo: false setting in travis.yml
This activates the container build which has
some restrictions, but should increase total
performance.
Based on PyTables 427

Travis container build

---

.travis.yml

Reverts openmicroscopy/openmicroscopy#3647
The container-based travis builds are now failing due to a "137" exit code, similar to the "247" exit code issues that we had recently (https://github.com/travis-ci/travis-ci/issues/2507). Since this destability causes frequent rebuilds, the time won by quicker start-ups is more than lost. Reverting.
For an example, see https://travis-ci.org/openmicroscopy/openmicroscopy/jobs/57021300
```
...
icegen2:
[copy] Copying 162 files to /home/travis/build/openmicroscopy/openmicroscopy/components/blitz/generated
[copy] Copying 162 files to /home/travis/build/openmicroscopy/openmicroscopy/components/blitz/generated
Killed
The command "./components/tools/travis-build java-build" failed 3 times.
The command "if [[ $BUILD == 'build-java' ]]; then travis_retry …
```

Revert "Travis container build" due to "137" exit code.

---

examples/Training/matlab/DeleteData.m
examples/Training/matlab/ROIs.m

Review ROI examples for OMERO.matlab, in particular:
- extend coverage to test all shapes 
- move shape deletion to `DeleteData`
To test this PR, check the shapes created by `ROIs.m`. Shapes should not be deleted anymore and be viewable by any of the clients.

MATLAB: ROI examples

---

components/insight/SRC/org/openmicroscopy/shoola/env/data/OMEROGateway.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/OmeroDataServiceImpl.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/util/PojoMapper.java

Use the new graphs API in Insight, see #3515
Changed the OMEROGateway to use Chgrp2 instead of old Chgrp.
With respect to the other commands:
- Use of Delete2 was already added to OMEROGateway by @mtbc , right?
- Chown2: Couldn't find any reference to Chown in Insight. Is it actually used at all in Insight, @jburel ?
Test:
- Use the "Move to Group" function on different objects
- Try to delete various data types (Images, Project, Projects with Datasets, etc.)
--no-rebase

Adjust graphs API usage in Insight

---

examples/Training/java/src/training/ReadData.java
examples/Training/java/src/training/util/DoubleConverter.java
examples/Training/java/src/training/util/FloatConverter.java
examples/Training/java/src/training/util/IntConverter.java
examples/Training/java/src/training/util/Plane2D.java
examples/Training/java/src/training/util/ReadOnlyByteArray.java
examples/Training/java/src/training/util/UintConverter.java

* Handle NPE if fake image is used.
Check the output of https://ci.openmicroscopy.org/job/OMERO-5.1-merge-training and make sure that the following error is no longer displayed
```
image:4386 test.fake
5
10
3
512
512
java.lang.NullPointerException
at training.ReadData.loadImage(ReadData.java:220)
at training.ReadData.<init>(ReadData.java:342)
at training.Setup.<init>(Setup.java:132)
at training.Setup.main(Setup.java:145)
```

training java

---

components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/browser/BrowserComponent.java
components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/browser/BrowserUI.java

Fixes ticket: https://trac.openmicroscopy.org/ome/ticket/12795
Test:
Select a well and make sure the "Delete" action is disabled, in the context menu as well as in the "Screens" toolbar. Check that the action is enabled otherwise, e. g. if the Run or the Plate is selected.
--no-rebase

Disable delete action if a well field is selected

---

components/tools/OmeroPy/src/omero/plugins/sessions.py
components/tools/OmeroPy/src/omero/util/sessions.py
components/tools/OmeroPy/test/unit/clitest/test_sess.py

See http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-April/005225.html
This PR does not modify the existing behavior/limitations of the CLI sessions rejoining logic but extends the unit test coverage for session key-based connection in preparation of future improvements/bug fixes. 
Summary of main changes:
- unit tests are added to cover multiple scenarios of session re-attachments (with/without port/group properties). The stored/passed properties are stored as tuples of the test class for clarity.
- the error message in the case of conflicting properties is reviewed and promoted to `self.ctx.err()` level so that it appears more systematically for debugging purposes /cc @PaulVanSchayck
- check all the unit tests are passing
- try a conflicting property scenario …

CLI session unit tests

---

components/tools/OmeroPy/src/omero/gateway/__init__.py

Fixes exception when browsing share image preview panel for incomplete images, see: https://trac.openmicroscopy.org/ome/ticket/12805
To test:
- log in to trout as 'root' and browse to public shares.
- Browse share '1401', select image and open Preview panel.
- Image will be incomplete (viewer won't work) but you shouldn't see any exception/crash

share_preview_panel_12805

---

components/tools/OmeroPy/src/omero/plugins/web.py

Reported by @kennethgillen during a production server upgrade to 5.1.0. With https://github.com/openmicroscopy/openmicroscopy/pull/3415, the start of OMERO.web now automatically performs a cleanup of the expired Django sessions. This step can be time consuming especially if the number of stale sessions is large. Additionally, there is no logging information for system administrators which may be misinterpreted as the inability for OMERO.web to start.
This PR:
- adds some basic logging information for the sessions clean-up step. Because it is fully delegated to Django there does not seem to be an easy way to have either a time estimate or a progression status /cc @aleksandra-tarkowska ?
- adds an optional `--keep-sessions` flag to skip the expired sessions clean-up in `start`, `restart` …

Clearsessions message

---

components/tools/OmeroWeb/omeroweb/webclient/forms.py
setup.cfg

This is the last PR on the openmicroscopy side going through the Python code to meet the flake8 standard. All changes are made on a single file `formats.py` and are split by section for readability via the interface. As always with these PRs, most of the changes are mostly about formatting. The main logical change is introduced in 5a437c6 with the introduction of a helper method `save_metadata` for handling the javascript. This method is then systematically used in all the following commits.
/cc @will-moore 
--no-rebase

Webclient flake8 forms.py

---

components/tools/OmeroCpp/test/integration/chgrp.cpp
components/tools/OmeroCpp/test/integration/delete.cpp
components/tools/OmeroCpp/utils/chgrp.cpp

C++ tests run by CI should remain green.
*Update*: Also, now C++ standalone chgrp tool is updated. Just use plain typenames, no "/"-prefix.
--no-rebase

have C++ code use new graph requests

---

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/annotations_share.html
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/includes/toolbar.html
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/metadata_acquisition.html
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/metadata_general.html
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/metadata_preview.html
components/tools/OmeroWeb/omeroweb/webclient/urls.py
components/tools/OmeroWeb/omeroweb/webclient/views.py
components/tools/OmeroWeb/omeroweb/webclient/webclient_gateway.py

Ticket: https://trac.openmicroscopy.org/ome/ticket/12787
This should resolve issues related to all 3 general, acquisition and preview panels as well as viewer.
As share offers limited functionality that is most what we can offer in that specific context.
To test check if you are satisfying with:
- metadata in general pane + download as JPEG, PNG, TIFF
- metadata in acquisition pane.
- rendering in preview
- make sure save buttons never became active
- test with image that has multiple user settings, try too apply them (you won't be able to save)
- rendering in full viewer
cc: @pwalczysko

metadata panel and share

---

components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/browser/BirdEyeViewComponent.java
components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/browser/ImageCanvasListener.java

Fixes [Ticket 12829](http://trac.openmicroscopy.org.uk/ome/ticket/12829)
Test: Open an image (not a *big* image) with multiple Z frames. Make sure the mouse wheel scrolling through the Z frames works.

Mouse wheel Z-frame scrolling

---

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorModel.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/ImportType.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/PropertiesUI.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/TextualAnnotationComponent.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/ToolBar.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/util/FilesetInfoDialog.java
components/insight/SRC/org/openmicroscopy/shoola/agents/util/EditorUtil.java
components/insight/SRC/org/openmicroscopy/shoola/util/ui/omeeditpane/OMEWikiComponent.java

Fixes some issues with the metadata panel:
- Use same font style for "creation date" label as for "acquisition date", "creation date", etc. **Test: Check font style of the "creation date" label**
- Show "creation date" also for plate runs (PlateAcquisitions) **Test: Make sure "creation date" label is shown for plate runs**
- FilesetInfoDialog (accessed via the "../../" icon) now shows the real inplace import option used (ln or ln_s) **Test: Import an image with `--transfer=ln_s` and one with `transfer=ln` and check that these options are shown in the FilesetInfoDialog**
- Reduced the linebreak threshold for channel names; long channel names and/or images with many channels made the channel names label quite big, so you heavily had to use the horizontal scrollbar. **Test: Open an image …

Metadata panel followup

---

components/tools/OmeroWeb/omeroweb/webadmin/views.py

See: http://trac.openmicroscopy.org/ome/ticket/12821
When another admin is editing 'root' user, the "Active" checkbox is disabled (since you can't disabled 'root'). But in the form handling, the disabled checkbox is ignored, so this was trying to disable 'root' and gives a security violation.
Now we manually check if we're editing 'root' and don't try to disable if we are.
To test:
- Log in as an admin (not 'root') and make any change to root user and submit the form. Should see no exception. Check save has worked.

Edit root user

---

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/container_subtree.html
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/public/public.html

This fixes https://trac.openmicroscopy.org/ome/ticket/10578
To test, create a share:
- Browse the share as owner, double-click on image in tree. Should open image viewer *without* share permissions. E.g. url without share-id like  ``` .../webclient/img_detail/<imageId>/ ```
- Browse the share as share member, double-click on image in tree. Should open image viewer *with* share permissions. E.g. url without share-id like  ``` .../webclient/<shareId>/img_detail/<imageId>/ ```

Share tree open viewer 10578

---

components/server/src/ome/logic/JavaImageScalingService.java

Fixes (hopefully this time finally) the ArrayIndexOutOfBoundsExceptions in master.err noticed by @joshmoore . Ensures that thumbnails are at least 3x3 pixels and that ResampleOp is only used for images >=  3x3 pixels.
Test: I don't really know what triggered these errors (integration tests maybe?), must have to do with images < 3px in width or height. Probably just review code and watch out in master.err for these errors.
--no-rebase

Avoid ResampleOp ArrayIndexOutOfBoundsExceptions

---

components/tools/OmeroWeb/omeroweb/webgateway/templates/webgateway/viewport/omero_image.html

This fixes issue mentioned at https://github.com/openmicroscopy/openmicroscopy/commit/583a5facc3e2c2323369d41c468a6b6e3dee48b8#commitcomment-10645482
NB: you can see this bug on nightshade by trying the image viewer popup at http://www.lifesci.dundee.ac.uk/gre/staff/professor-jason-swedlow-frse
To test, you need to have a window open viewer at another site.
E.g. log in to nightshade, open an image viewer, copy the url and use it to create an html file like this (replace the url), save locally "test.html" then open test.html in a browser and click the link.
```
<html>
<a href="#" onClick="window.open('http://localhost:4080/webclient/img_detail/6702/'); return false;">Open Viewer</a>
</html>
```
Should see the image viewer working OK.

Use try/catch to test for access to window.opener

---

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/public/public.html

See https://trac.openmicroscopy.org/ome/ticket/12832
Disables script menu for share page. Although the image owner *may* be able to run scripts on their own images in share, the majority of times it will be users who only have access to the images via share permissions, so the script won't be able to access the images.
To test:
- Go to public share page.
- The script menu button should look disabled and clicking on it won't launch script menu. Tooltip will tell you it's disabled in shares.

Disable scripts menu in share page

---

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/DocComponent.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/util/FigureDialog.java
components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewerModel.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/model/appdata/LinuxApplicationDataExtractor.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/FilesLoader.java
components/insight/SRC/org/openmicroscopy/shoola/env/ui/OpenObjectLoader.java

Fixes [Ticket 12028](https://trac.openmicroscopy.org/ome/ticket/12028) and some other issues with "Open with" functionality
- Removes the "View" button (doesn't have a function anymore)
- Fixes a bug with respect to "Open with" file attachments
- Fixes the "View" issues in Import and Script dialog on Linux 
- End the "Open with" activity if an error occurs
- Fixes a problem with mimetype detection and mimetype-application association
Test (on multiple platforms if possible, but focus on Linux)
- Attach a File to an image (dataset, whatever). Select the image and make sure that there is no "View" button anymore in the attachment popup menu (right hand side metadata panel)
- Open the Attachments view in the left hand side panel. Select an attachment and open it with "Open with...". Check …

Bugfix open FileAnnotation

---

components/server/src/ome/security/sharing/SharingACLVoter.java
components/tools/OmeroPy/test/integration/test_ishare.py
components/tools/OmeroWeb/omeroweb/webclient/webclient_gateway.py
components/tools/OmeroWeb/test/integration/test_share.py

The no-op method in SharingACLVoter was incorrect in
that by not calling copyRestrictions, there were *no*
restrictions on the object as opposed to nothing being
allowed. Now, all should return False in the context
of a share.
Testing: This should keep the same behavior as gh-3688
but without @aleksandra-tarkowska's workaround.

Use allow=0 for share post-processing (Fix #12562)

---

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorComponent.java

Tiny fix for [Ticket 12679](http://trac.openmicroscopy.org.uk/ome/ticket/12679)
I couldn't reproduce the missing tag issue, but I fixed the problem, that the dialog showed all tags available. Now just the ones which are attached to the selected images are shown.
Test:
Select a few images with different tags attached to them. Open the ThumbnailFigure dialog and make sure only the tags which are attached to the selected images are shown.

Show tags of the selected objects only

---

components/tools/OmeroPy/src/omero/plugins/sessions.py
components/tools/OmeroPy/src/omero/util/sessions.py
components/tools/OmeroPy/test/unit/clitest/test_sess.py

Follow up of https://github.com/openmicroscopy/openmicroscopy/pull/3702 and http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-April/005245.html.
This PR fixes a first bug where rejoining a stored session file using the session key was restricted to using the same connection arguments (including the initial connection group). Main changes of this PR are:
- fixing the port assymmetry (i.e. session file stored with the default port or without any omero.port can be rejoined without passing the port/by passing `-p 4064`)
- remove the group check restriction when joining an existing session stored on disk using the session key
- unit tests are modified to cover these bug fixes
- the unit tests when reusing session (i.e. without key) are also extended to cover all the group/port …

CLI sessions: do not check group while rejoining session with key

---

components/blitz/src/ome/formats/importer/transfers/AbstractExecFileTransfer.java

In-place import already checks if the import-user has
permissions to write to the server before allowing an
in-place import to commence. But previously, no check
was being made if the server process could access the
files which were uploaded.
See testing instructions in http://trac.openmicroscopy.org.uk/ome/ticket/12755

Check for readability of in-place targets (Fix #12755)

---

components/blitz/src/ome/services/blitz/fire/SessionManagerI.java
components/blitz/src/ome/services/blitz/repo/ManagedImportProcessI.java
components/blitz/src/ome/services/blitz/repo/ProcessContainer.java
components/blitz/src/omero/cmd/HandleI.java
components/blitz/src/omero/util/ServantHolder.java
components/blitz/src/org/hibernate/stat/ConcurrentStatisticsImpl.java
components/common/src/ome/system/PreferenceContext.java
components/dsl/resources/ome/dsl/object.vm
components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/util/UnitBarSizeDialog.java
components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/IntensityView.java
components/insight/SRC/org/openmicroscopy/shoola/agents/util/EditorUtil.java
components/insight/SRC/org/openmicroscopy/shoola/env/config/RegistryImpl.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/Connector.java
components/server/src/ome/logic/RenderingSettingsImpl.java
components/server/src/ome/security/auth/LoginAttemptListener.java
components/server/src/ome/security/basic/BasicMethodSecurity.java
components/server/src/ome/services/RawPixelsBean.java
components/server/src/ome/services/sessions/SessionManagerImpl.java
components/server/src/ome/services/sessions/state/SessionCache.java

ConcurrentHashMap undergoes API changes among Java 6, 7, 8, so to keep code nicely portable it's generally easier to simply avoid using it given that we already have Guava available and that offers a suitable substitute.
Testing: No tests or builds should break, and the OMERO source should no longer contain direct usage of ConcurrentHashMap. (It has already been removed from Bio-Formats.) Import should still work, and management of Insight sessions / connectors should still be fine; @jburel may have specific testing ideas there. (I guess, try logging in and out and switching user and whatnot.)
To avoid regressions, the less-trivial code changes should be reviewed by eye.
--no-rebase

remove concurrent hashmap

---

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/util/FilesetInfoDialog.java
components/insight/SRC/org/openmicroscopy/shoola/util/ui/tdialog/TinyDialog.java

Tiny fix for [Ticket 12824](http://trac.openmicroscopy.org.uk/ome/ticket/12824)
Test: Make sure the Location dialog ("Show parent projects and datasets") behaves like the "Show file paths" dialog; both should be automatically closed if they loose the focus.

Filepath info and Location dialog

---

components/tests/python/library/__init__.py
components/tools/OmeroPy/test/integration/test_delete.py
components/tools/OmeroPy/test/integration/test_figureExportScripts.py
components/tools/OmeroPy/test/integration/test_icontainer.py
components/tools/OmeroPy/test/integration/test_itimeline.py
components/tools/OmeroPy/test/integration/test_permissions.py
components/tools/OmeroPy/test/integration/test_tickets2000.py

See https://trello.com/c/OTdzTuMZ
This PR is only modifying the Python test API and some of the integration tests. The first commit is split  library methods by functionality for better readability and expands/reviews the helper methods used for object creation and manipulation. The following set of commits is using these object helpers in a subset of test classes.
All tests should still be passing with this PR. Additionally, what should be assessed is whether this proposal improve the readability of individual tests while reducing the amount of logic for each test setup.
/cc @ximenesuk

Python test library object helpers

---

components/tests/ui/testcases/web/search.txt
components/tools/OmeroWeb/omeroweb/webclient/controller/search.py
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/search/search.html

Better handling of search errors, particularly those caused by parsing of invalid queries with a colon.
To test, try searching with valid and invalid key:value queries.
Invalid searches should give a useful error message.
Screenshots below are BEFORE and AFTER this change:

Only show useful search errors

---

components/tools/OmeroPy/src/omero/cli.py
components/tools/OmeroPy/src/omero/plugins/sessions.py
components/tools/OmeroPy/src/omero/util/temp_files.py
components/tools/OmeroPy/test/unit/clitest/test_sess.py

Fixes https://trac.openmicroscopy.org.uk/ome/ticket/12392 and https://trac.openmicroscopy.org.uk/ome/ticket/12834
To test this PR, check Travis is green and reproduce the scenarios described in both tickets.
For 12392, the main change is that inactive sessions purged by default by the `sessions list` subcommand are not listed anymore by the command output, i.e. the command lists all local non-expired sessions. To list all local sessions independently of their status, `bin/omero sessions list --no-purge` should be used. Listing differences between the output of two consecutive calls to `bin/omero sessions list` should be only caused by either newly created sessions or sessions which expired in-between the two calls.
/cc @kennethgillen @pwalczysko

CLI sessions list

---

components/tools/OmeroPy/src/omero/gateway/__init__.py
components/tools/OmeroPy/src/omero/tables.py
components/tools/OmeroPy/test/integration/tablestest/test_service.py

A few references were still left to the deprecated then removed IDelete service. Here we:
* fix reference to queueDelete in `tables.py`
* remove 'broken' marker from `test_services.py` cc: @ximenesuk 
* also remove `DeleteService` from `gateway/__init__.py` cc: @will-moore 
* comments out a failing [assert](https://github.com/openmicroscopy/openmicroscopy/pull/3729/files#diff-fa6bb86e1444246dbf41f9ac2fcd9e32R155) cc: @mtbc 
This primarily needs to keep tests green and have the API changes reviewed. [This test](https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-integration-broken/lastCompletedBuild/testReport/test.integration.tablestest.test_service/TestTables/testDelete/) should drop off the "broken radar" though.

Remove leftover IDelete uses (Py)

---

components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/browser/BrowserComponent.java

Tiny fix for [Ticket 12814](http://trac.openmicroscopy.org.uk/ome/ticket/12814)
Test: Log in as a user who has some images in 'Orphaned Images' (e. g. user-3), select an orphaned image -> you should see it's metadata in the right panel; click on an empty space in the central panel -> metadata panel should be empty; select the **same** image again -> you should again see the metadata of the image.

Bugfix: Orphaned images selection

---

components/tools/OmeroPy/src/omero/gateway/__init__.py
components/tools/OmeroPy/test/unit/test_gateway.py

Fix a typo bug found in `ImageWrapper.simpleMarshal()` during performance testing and improvement. Unit tests included.
/cc @jballanc

Fix image simple marshal

---

components/tools/OmeroPy/src/omero/cli.py

Fixes https://trac.openmicroscopy.org.uk/ome/ticket/1293
This PR reviews the help for the debug topic of the CLI, bringing it in line with the subcommands help. It also removes the reference to the deprecated `DEBUG` environment variable.
To test this PR, review the output of
```
bin/omero help debug
```

CLI: review debug help

---

components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/util/DataMenuItem.java
components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/util/GroupItem.java
components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/ToolBar.java
components/insight/SRC/org/openmicroscopy/shoola/util/ui/SelectableMenuItem.java

Fixes [Ticket 12042](https://trac.openmicroscopy.org/ome/ticket/12042)
In the user/group menu different items were used (JCheckBoxes, custom JCheckBox menu items, etc.); on OSX they appeared to look the same, but you could see the difference on Windows. With this PR only the customized JCheckBox style menu item will be used in the popup menu.
Test: Make sure that on all platforms, OSX, Windows and Linux, the user/group menu in the main toolbar has a uniform style.
--no-rebase

Uniform User/Group Menu

---

components/tests/python/library/__init__.py
components/tools/OmeroPy/test/integration/test_annotation.py
components/tools/OmeroPy/test/integration/test_annotationPermissions.py
components/tools/OmeroPy/test/integration/test_chgrp.py
components/tools/OmeroPy/test/integration/test_counts.py
components/tools/OmeroPy/test/integration/test_delete.py
components/tools/OmeroPy/test/integration/test_figureExportScripts.py
components/tools/OmeroPy/test/integration/test_icontainer.py
components/tools/OmeroPy/test/integration/test_ishare.py
components/tools/OmeroPy/test/integration/test_itimeline.py
components/tools/OmeroPy/test/integration/test_mail.py
components/tools/OmeroPy/test/integration/test_search.py
components/tools/OmeroPy/test/integration/test_tickets2000.py
components/tools/OmeroPy/test/integration/test_tickets3000.py
components/tools/OmeroWeb/test/integration/test_share.py

Follow up of https://github.com/openmicroscopy/openmicroscopy/pull/3728
- more fixes across top-level integration tests to use `self.new_xxx`/`self.make_xxx()`/`self.link()` methods
- exposition of acquisition date in image creation helper methods
- migration of the BlitzGateway share test to OmeroPy (see https://github.com/openmicroscopy/openmicroscopy/pull/3715#issuecomment-93940978)
- migration of `create_share` helper method to `ITest` /cc @aleksandra-tarkowska 
Apart from checking that integration tests remain green and that changes are sensible, `test_icontainer.testFindAndCountAnnotationsForSharedData` should be reviewed more closely. The logic of the test has been modified as it didn't seem to include the second created client anywhere previously.

Library object helpers (part 2)

---

components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewerComponent.java

While checking [Ticket 12171](https://trac.openmicroscopy.org.uk/ome/ticket/12171) I noticed that moving a single image which is part of a MIF via drag&drop into another group crashed Insight with an IllegalStateException being thrown. This PR fixes the issue.
**Test:** 
Select a subset of images of a MIF and move them via Drag&Drop into another group; expected: All images of the MIF should be moved (but you should get asked for confirmation beforehand).

Fixed DnD mif move

---

components/tools/OmeroPy/src/omero/gateway/__init__.py
components/tools/OmeroPy/test/integration/gatewaytest/test_missing_pyramid.py
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/includes/toolbar.html

Fixes https://trac.openmicroscopy.org.uk/ome/ticket/12835
The "Download" drop-down menu for an image no-longer calls getDefaultZ/T to generate download urls.
Urls are generated without Z/T, which will also result in the default Z and T indices being used anyway.
To test, try loading the right "General" panel after importing a Big 'png' or 'jpeg', during Pyramid Generation. Should see no exception (although Download > png/jpeg won't work).
Also test that the Download > PNG / JPEG / TIFF functionality is working for non-big images using normal permissions AND in a share (when you don't otherwise have permission to access the image).

Right panel MissingPyramidException

---

components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/browser/ImageCanvasListener.java

Follow-up PR to #3712 , respectively [Ticket 12837](https://trac.openmicroscopy.org.uk/ome/ticket/12837)
As @will-moore mentioned, mouse dragging should always drag the image (and not scroll through Z/T or zoom the image). Previously the behaviour of mouse dragging in Insight was different for 'small' and 'big' images. With this PR mouse dragging will always drag the image regardless of the image size.

Always drag image, never scroll through Z/T or zoom

---

components/blitz/src/omero/cmd/graphs/Chgrp2I.java
components/blitz/src/omero/cmd/graphs/Chown2I.java
components/blitz/src/omero/cmd/graphs/Delete2I.java
components/blitz/src/omero/cmd/graphs/GraphUtil.java
components/server/src/ome/services/graphs/GraphTraversal.java
components/server/src/ome/services/graphs/ModelObjectSequencer.java
components/tools/OmeroJava/test/integration/AbstractServerTest.java
components/tools/OmeroJava/test/integration/DeleteServiceFilesTest.java

As suggested by https://trello.com/c/gglTLzkS/480-have-delete2-order-file-deletions, improves the new graph requests such that original file deletions may be combined within the same request regardless of if they must be deleted in a certain order.
Integration tests ought still pass, including the new `DeleteServiceFilesTest.testRecursiveDelete` at https://ci.openmicroscopy.org/job/OMERO-5.1-merge-integration-java/lastCompletedBuild/testngreports/integration/DeleteServiceFilesTest/testRecursiveDelete/.
Manual testing may be most easily effected with the help of @ximenesuk's CLI PRs as you need a hierarchy of original files that are not linked to anything else, and there is the extra complication that regular users appear not to be able to delete directories. Still, to give it a try from a …

fix OriginalFile ordering for deletion

---

components/tools/OmeroPy/src/omero/gateway/__init__.py
components/tools/OmeroPy/test/integration/gatewaytest/test_fs.py
components/tools/OmeroWeb/omeroweb/webgateway/views.py

Replaces https://github.com/openmicroscopy/openmicroscopy/pull/3695
----
**Original PR from @chris-allan**:
This PR includes various performance improvements to the stack required to extract original file paths from the server via the `/webgateway/original_file_paths/...` OMERO.web JSON endpoint. Without these or similar changes there is the very real scenario where requesting the original file paths could **crash** your server due to the sheer amount and complexity of data being processed.
The "real world" example dataset which spurred the need for the improvements has 4608 Images (384 Wells, 12 Fields) and 4608 OriginalFiles (one per field) associated with the same Fileset. Half that number is needed to run a server out of memory with a 1GB heap. Call tree is as follows:
``` …
```

Optimize and fix original file paths

---

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/containers_icon.html

Fixes https://trac.openmicroscopy.org.uk/ome/ticket/12791
To test:
- browse to dataset
- show centre panel in table layout
- Try drag-selecting the table header. It shouldn't be selectable.
- Drag-selecting table rows and sorting should work as normal.

selection when list

---

components/tools/OmeroPy/src/omero/gateway/__init__.py
components/tools/OmeroPy/test/integration/gatewaytest/test_rdefs.py

Fixes https://trac.openmicroscopy.org.uk/ome/ticket/12796
Even if you can't annotate an image, you should be able to call resetDefaults() to get the "Imported" rendering settings.
To test:
- view an image that you can't annotate
- Try to reset to "Imported settings"
- Check you get the same as the owner of the image.
Also added a gateway test.

ResetDefaults cant annotate

---

components/server/src/ome/services/ThumbnailBean.java
components/tools/OmeroPy/test/integration/test_thumbs.py

Thumbnails that are generated while pyramids are being
created (i.e. the clock symbol) should have a version of
-1 so that clients know to refresh.
There is currently no case where `version == null` is
used or even possible.

Set pyramid thumb versions to -1 (Fix #12538)

---

components/blitz/src/omero/cmd/CmdCallbackI.java

Attempt to fix [Ticket 12120](https://trac.openmicroscopy.org.uk/ome/ticket/12120) by catching the exception as suggested by @joshmoore . See last commit. The previous commits are just some refactoring, so that I was able to log the exception.
**Test:** No idea; the exception is thrown rarely and randomly, couldn't find a way to deliberately trigger the problem. **Code review sufficient?**
/cc @jburel

Crash on ICE ObjectNotExistException

---

components/model/src/ome/util/SqlAction.java
components/server/src/ome/services/util/ServiceHandler.java
components/server/test/ome/server/utests/ServiceHandlerUnitTest.java

https://trac.openmicroscopy.org.uk/ome/ticket/12820 describes long figure json strings being printed in Blitz-0.log. This should limit those strings to a max. length of 1000 chars. cc @will-moore 
`findRepoFiles` previously passed all the files (`basenames`)
in an entire directory into one query. This leads to strange
errors with PostgreSQL of the form:
```
IOException: Tried to send an out-of-range integer as a 2-byte value: 52671
```
Now, the list of basenames are grouped into batches, filling
up a single `Map<String, Long>` which is returned to the caller.
To test, generate a large directory and attempt to import:
```
/tmp/dont-look-here$ cat make.sh
echo "test_Z<00000-60000>.fake" > fake.pattern
for x in $(seq 0 60000); do touch $(printf "test_Z%05d.fake\n" $x); done
```
If the …

5.1.1 misc size fixes

---

components/tools/OmeroWeb/omeroweb/webclient/webclient_gateway.py

See: https://trac.openmicroscopy.org.uk/ome/ticket/12842
Handle deleted images in shares.
To test:
- Put some images in a share
- Delete one of them
- Browse the share
- Share should load and display all other images OK
- Should see "Object deleted" in tree and placeholder thumbnail.

Handle deleted images in shares

---

components/tools/OmeroPy/src/omero/cli.py
components/tools/OmeroPy/src/omero/plugins/sessions.py
components/tools/OmeroPy/src/omero/util/sessions.py
components/tools/OmeroPy/test/unit/clitest/test_sess.py
components/tools/OmeroPy/test/unit/clitest/test_sessions.py

Initial implementation of OMERO_SESSION_DIR led to the creation of a omero/sessions subfolders. This behavior is counter-intuitive and does not match the CLI documentation. This commit fixes this behavior by deprecating `OMERO_SESSION_DIR` in favor of `OMERO_SESSIONDIR` which allows to set the equivalent of `$HOME/omero/sessions` by environment variable.
To test this PR, check the sessions storage mechanism under various environments:
```
bin/omero login -s localhost -u user -w pass -C
bin/omero sessions file
OMERO_SESSION_DIR=~/xxx bin/omero login -s localhost -u user -w pass -C
OMERO_SESSION_DIR=~/xxx bin/omero sessions file
OMERO_SESSIONDIR=~/xxx2 bin/omero login -s localhost -u user -w pass -C
OMERO_SESSIONDIR=~/xxx2 bin/omero sessions file
OMERO_SESSIONDIR=~/xxx2 …
```

Fix usage of OMERO_SESSION_DIR

---

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/basket/basket.html
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/basket/basketContent.html
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/containers_icon.html
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/history/history_details.html
components/tools/OmeroWeb/omeroweb/webgateway/templatetags/common_filters.py

This is part of #3713 after discussion with @joshmoore.
Now, if the thumbnail version is -1 (during Pyramid generation) then we use a random version number to prevent caching of the clock thumbnail in the browser.
Clock thumbnails will be retrieved each time a Dataset is refreshed until we get version 0.
To test, import a Big image (png/jpeg) load the Dataset then use only the tree toolbar refresh button to reload the dataset repeatedly during pyramid generation.
When pyramid generation finishes, the new thumbnail should be loaded.

Pyramid generation thumbnails

---

components/blitz/src/ome/formats/importer/transfers/AbstractExecFileTransfer.java
components/blitz/src/ome/formats/importer/transfers/TransferState.java

In-place import (e.g. `--transfer=ln`) was leading
to dangling file handles on the server since multiple
calls to `TransferState.getUploader` were being made
without the return values being properly closed. This
commit is slightly uglier than it should be in order
to not break the `FileTransfer` API. Later refactorings
should pass `TransferState` everywhere rather than the
`RawFileStorePrx`.
* Record the open file handles for your server: `lsof -p $(bin/omero admin ice server pid Blitz-0) > before.txt`
* Choose a dataset with a number of files (see make.sh below)
* Import with `--transfer=ln` or `--transfer=ln_s`
* Record the open file handles after the import: `lsof -p $(bin/omero admin ice server pid Blitz-0) > after.txt`
* Look at the `diff` of the two files. At most, only the single …

Fix in-place server-side file leak

---

components/blitz/resources/omero/Repositories.ice
components/blitz/src/ome/services/blitz/repo/PublicRepositoryI.java
components/blitz/src/omero/cmd/graphs/GraphUtil.java
components/server/src/ome/security/basic/BasicACLVoter.java
components/server/src/ome/services/graphs/GraphTraversal.java
components/tools/OmeroJava/test/integration/DeleteServiceFilesTest.java

Fixes https://trello.com/c/dWphbVIw/486-deletion-of-repository-hierarchies-by-normal-users and largely tested by integration tests. The keen may wish to:
1. reproduce @ximenesuk's problem in https://github.com/openmicroscopy/openmicroscopy/pull/3751#issuecomment-95619415 when he wasn't root
1. try out recursive delete with http://downloads.openmicroscopy.org/omero/5.1.1/api/slice2html/omero/grid/Repository.html#deletePaths.
--no-rebase

allow non-admin users to delete many related original files (and directories) in one request

---

components/tools/OmeroPy/src/omero/cli.py
components/tools/OmeroPy/src/omero/plugins/chgrp.py
components/tools/OmeroPy/src/omero/plugins/delete.py
components/tools/OmeroPy/src/omero/plugins/fs.py
components/tools/OmeroPy/src/omero/plugins/group.py
components/tools/OmeroPy/test/integration/clitest/test_chgrp.py
components/tools/OmeroPy/test/integration/clitest/test_delete.py
components/tools/OmeroPy/test/integration/test_chgrp.py

This PR refactors the CLI plugins `delete` and `chgrp` to use the new `Delete2` and `Chgrp2` requests respectively. In addition `fs rename` has been modified to use `Delete2`.
The `--edit` option has been removed as it was broken by the earlier changes
The `--opt` option have been removed and its usage replaced by two new options `--include` and `--exclude`. How the old option maps to the new ones is detailed in the testing section below.
A new option `--ordered` has been introduced to force the preservation of the order of the arguments.
Integration tests have been added but, as ever, more would be useful to test more complex functionality.
Testing
-------
Relevant cli unit and integration tests should pass.
A number of simple delete and chgrp should be checked, see `--help` for …

Refactor plugins using Delete2 & Chgrp2 requests

---

components/tools/OmeroFS/src/fsUtil.py

Can be tested using the server deployed by https://ci.openmicroscopy.org/job/OMERO-5.1-merge-deploy-win2012/
I've only looked at `2012-r2`, not `2012`.

Enable Dropbox on W2012-R2

---

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/includes/hotkeys.js

Fixes https://trac.openmicroscopy.org.uk/ome/ticket/12831 and http://trac.openmicroscopy.org.uk/ome/ticket/12840 (also see https://www.openmicroscopy.org/community/viewtopic.php?f=4&t=7785).
To test, use a keyboard with a "Delete" key:
- Check that Delete doesn't do anything to the tree main webclient page, shares or tags page.

Disable delete key in jsTree

---

components/tools/OmeroPy/test/unit/clitest/reference_templates/apache-fcgi-withoptions.conf
components/tools/OmeroPy/test/unit/clitest/reference_templates/apache-fcgi.conf
components/tools/OmeroPy/test/unit/clitest/reference_templates/apache-withoptions.conf
components/tools/OmeroPy/test/unit/clitest/reference_templates/apache.conf
components/tools/OmeroPy/test/unit/clitest/test_cli.py
components/tools/OmeroPy/test/unit/clitest/test_web.py
etc/templates/apache-fcgi.conf.template
etc/templates/apache.conf.template

See https://github.com/openmicroscopy/openmicroscopy/pull/3769#issuecomment-97706639
This PR users `/var/run/omero.fcgi` as the default filename for the `FastCGIExternalServer` directive in the Apache stanza. This change is expected to reduce the number of  `Permission Denied` issues encountered when upgrading a server and starting OMERO.web in production as highlighted byhttps://github.com/openmicroscopy/ome-documentation/pull/1203. Since `/var/run` exists on all UNIX-like platforms and should be readable/executable by the Apache agents, this filename was chosen as the lowest common denominator for all platforms. 
This PR should be tested both under Apache 2.2 and 2.4 by downloading the server, generating the Apache stanza via `bin/omero web config` and starting OMERO.server and …

Apache stanza fcgi

---

components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/css/ome.viewport.css
components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/ome.viewport.js
components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/ome.viewportImage.js
components/tools/OmeroWeb/omeroweb/webgateway/templates/webgateway/viewport/omero_image.html

Fixes http://trac.openmicroscopy.org/ome/ticket/12828 (see https://www.openmicroscopy.org/community/viewtopic.php?f=4&t=7786).
To test:
- Zoom in a lot in web image viewer
- Toggle the "Interpolate" checkbox (checked by default).
- When unchecked, image should appear pixelated.
- Compare with same image in Insight, to check this pixelation is valid.

Viewer Interpolate checkbox

---

components/blitz/resources/ome/services/blitz-graph-rules.xml
components/tools/OmeroJava/test/integration/DeleteServicePermissionsTest.java

Fixes http://trac.openmicroscopy.org/ome/ticket/2997 and adds tests to https://ci.openmicroscopy.org/job/OMERO-5.1-merge-integration-java/lastCompletedBuild/testngreports/integration/DeleteServicePermissionsTest/ to confirm fix.
Now, others' comments and ratings on an image are deleted when the image is deleted.
--no-rebase

fix #2997: delete non-sharable annotations with image

---

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/containers.html
components/tools/OmeroWeb/omeroweb/webclient/views.py

See http://trac.openmicroscopy.org.uk/ome/ticket/12860
This is a small fix to the delete dialog message, to use 'Plate Run' instead of 'Acquisition' and remove '-locked' from the message (if you were not the owner). Also fixes refresh of Plate during Run deletion:
To test:
- Login as Admin and try to delete data belonging to another user.
- Project etc should simply be "Project" in the delete confirm dialog (not 'Project-locked').
- Acquisition should be "Plate Run" (see first screenshot).
- On delete, centre panel should be cleared and nothing should be selected in tree (fixes bug shown in second screenshot).
Before this PR, centre panel reloaded Plate while Run was deleting.
NB: Empty plate is not well handled in Web:
And worse in Insight:

Delete Plate Run

---

components/tools/OmeroPy/src/omero/gateway/__init__.py
components/tools/OmeroPy/test/integration/gatewaytest/test_image_wrapper.py
components/tools/OmeroPy/test/integration/gatewaytest/test_plate_wrapper.py
components/tools/OmeroWeb/omeroweb/webgateway/plategrid.py
components/tools/OmeroWeb/omeroweb/webgateway/views.py
components/tools/OmeroWeb/test/integration/test_plate_grid.py
components/tools/OmeroWeb/test/integration/test_plategrid.py

This change improves the performance of the `plateGrid_json` method called when displaying a plate in three main ways:
* getting the grid size
* retrieving wells in the plate
* generating the metadata for the plate grid
Various tests have been added to cover the expected behaviour and were used throughout development to attempt to ensure that no API deviation has taken place.
Based on some rough benchmarks, these changes represent an order of magnitude improvement in the overall request time. Bringing the overall request time down below the high watermark of 1 second for all OMERO.web calls.
The dataset used is the same as that outlined in #3695/#3753: 4608 Images (384 Wells, 12 Fields).
Before:
time to set grid constraints: 0:00:01.567579
time to get well grid: 0:00:00.012914
time to get …

Optimize plate grid metadata

---

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/public/public.html

The icon for Remove Content in Public tab in Web (share) was the same as the Delete icon under Data tab. Now it uses *scissors* to make clear the Delete action from Share is not possible

updating icon

---

components/blitz/resources/ome/services/blitz-graph-rules.xml

Fixes error in workflow from http://trac.openmicroscopy.org/ome/ticket/12868. Now a group owner Alice may delete Bob's dataset that includes images that Bob tagged.

fix #12868: prevent error when deleting container with undeletable content

---

components/tests/ui/resources/web/tree.txt
components/tests/ui/robot_setup.sh
components/tests/ui/testcases/web/delete_test.txt
components/tests/ui/testcases/web/post_test.txt
components/tests/ui/testcases/web/rdef_test.txt
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/containers.html

Fixes https://trac.openmicroscopy.org.uk/ome/ticket/12866
To test:
- Delete an image in a Dataset
- Dataset should become selected but centre panel should NOT reload (thumbnail should simply disappear).
NB: this bug was a result of recent PR https://github.com/openmicroscopy/openmicroscopy/pull/3784
Also added Robot tests which includes changes to the setup script to import a number of images for deletion.

Delete refresh centre

---

components/tools/OmeroWeb/omeroweb/webclient/forms.py

From https://trello.com/c/ScEErwT9/222-5-1-2-follow-up
Web does same as Insight and displays "Model" then "Manufacturer" in that order for all acquisition metadata objects.
This fixes it in Dichroic, Microscope, Detector and LightSource.
To test:
- View metadata and check 1 or more of the above objects.
- May need to "Show Unset Fields"
- Should see Model, then Manufacturer (as in Insight)
Screenshot is 1h.oib.

Order: 'Model',  'Manufacturer'

---

components/tools/OmeroPy/src/omero/gateway/__init__.py
components/tools/OmeroPy/test/integration/gatewaytest/test_annotation.py
components/tools/OmeroPy/test/integration/gatewaytest/test_services.py
components/tools/OmeroPy/test/integration/gatewaytest/test_user.py
components/tools/OmeroPy/test/integration/gatewaytest/test_wrapper.py
components/tools/OmeroPy/test/unit/gatewaytest/test_argument_errors.py
components/tools/OmeroWeb/omeroweb/webclient/webclient_utils.py

This PR replaces deprecated delete and chgrp methods in the gateway and the gateway tests.
With the PR as it stands the tests pass. However, not all functionality may be fully tested and so this PR is probably best tested on a breaking build. In particular methods such as `deleteSettings` and calls to `deleteObjects` with extended graph specs that will exploit `SkipHead` need through checking.
The one method of concern is is `deleteObjectDirect`:
https://github.com/ximenesuk/openmicroscopy/blob/deprecated-gateway/components/tools/OmeroPy/src/omero/gateway/__init__.py#L3803
This is used extensively by the web but a couple of basic patterns, using `Delete2` commands or using `deleteObjects` did cause at least one test to fail. The tests now pass through re-ordering the deletes. It may be …

Replace deprecated Delete/Chgrp methods in gateway

---

components/tools/OmeroWeb/test/integration/test_plategrid.py

It is possible to get off-by-one errors due to updates happening on
second boundaries with multiple save actions.  This PR removes that
possibility by saving only once and only picking up the creation event
time after that singular save.
Reference test failure:
* https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-integration-web/326/testReport/test.integration.test_plategrid/TestPlateGrid/test_creation_date/
```
self = <test_plategrid.TestPlateGrid object at 0x615a750>
plate_wells_with_no_acq_date = {'creation_date': 1431059881L, 'plate': object #0 (::omero::model::Plate)
{
_id = object #1 (::omero::RLong)
{...   _val = 803ddbc5-7a55-4c54-aef4-3aaec0726596
}
_description = <nil>
}}
conn = <omero.gateway._BlitzGateway object at 0x615aad0>
def test_creation_date(self, …
```

Avoid update event race condition by saving only once

---

components/blitz/resources/ome/services/blitz-graph-rules.xml
components/blitz/resources/ome/services/blitz-servantDefinitions.xml
components/blitz/resources/omero/api/IAdmin.ice
components/blitz/resources/omero/cmd/Graphs.ice
components/blitz/src/omero/cmd/RequestObjectFactoryRegistry.java
components/blitz/src/omero/cmd/graphs/BaseGraphPolicyAdjuster.java
components/blitz/src/omero/cmd/graphs/BaseGraphTraversalProcessor.java
components/blitz/src/omero/cmd/graphs/Chgrp2I.java
components/blitz/src/omero/cmd/graphs/ChildOptionsPolicy.java
components/blitz/src/omero/cmd/graphs/Chmod2I.java
components/blitz/src/omero/cmd/graphs/ChmodFacadeI.java
components/blitz/src/omero/cmd/graphs/ChmodI.java
components/blitz/src/omero/cmd/graphs/Chown2I.java
components/blitz/src/omero/cmd/graphs/Delete2I.java
components/blitz/src/omero/cmd/graphs/GraphRequestFactory.java
components/blitz/src/omero/cmd/graphs/NullGraphTraversalProcessor.java
components/blitz/test/ome/services/blitz/test/ChmodITest.java
components/server/src/ome/services/graphs/GraphPolicy.java
components/server/src/ome/services/graphs/GraphPolicyRule.java
components/server/src/ome/services/graphs/GraphTraversal.java
components/tests/python/library/__init__.py
components/tools/OmeroJava/test/integration/AbstractServerTest.java
components/tools/OmeroJava/test/integration/AdminServiceTest.java
components/tools/OmeroJava/test/integration/chmod/PermissionsTest.java
components/tools/OmeroJava/test/integration/chown/PermissionsTest.java
components/tools/OmeroPy/test/integration/test_annotationPermissions.py
components/tools/OmeroWeb/omeroweb/webclient/webclient_gateway.py
etc/omero.properties

Uses of `Chmod` requests are now actioned by the `Chmod2` implementation. Chmod-related integration tests should pass. Also try changing group permissions from the client to make sure it works correctly. (The admin service's `changePermissions` still uses the old `Chmod` but the clients don't much use that.)
This PR *should* be suitable for 5.1 so that a 5.1.1 (or trout-latest) client can work with a 5.1.2 (or trout-merge) server and vice versa: no commits with this PR switch clients to use `Chmod2` directly.
--no-rebase

introduce Chmod2 request

---

components/tools/OmeroPy/src/omero/gateway/__init__.py

Fixes http://trac.openmicroscopy.org.uk/ome/ticket/12879
To test:
- A user needs to be owner of their Default group and a regular member of another group.
- Check that they are listed correctly under the Group / User menu as Owner and Member of the correct groups (not owner of both).

Group summery isLeader

---

components/tools/OmeroCpp/src/omero/callbacks.cpp
components/tools/OmeroCpp/src/omero/callbacks.h
components/tools/OmeroPy/src/omero/callbacks.py
components/tools/OmeroPy/src/omero/plugins/prefs.py
components/tools/OmeroPy/src/omero/util/__init__.py

Few minor fixes to the Python library (and C++ where necessary to keep symmetry):

Python lib fixes

---

components/dsl/resources/ome/dsl/psql-header.vm
components/model/resources/ome/util/actions/psql.properties
components/model/src/ome/util/SqlAction.java
components/server/resources/ome/services/startup.xml
components/server/src/ome/services/util/DBUnicodeUnitsCheck.java
sql/psql/OMERO5.1DEV__11/OMERO5.1DEV__10.sql
sql/psql/OMERO5.1DEV__13/OMERO5.1DEV__12.sql
sql/psql/OMERO5.1__1/OMERO5.0__0.sql
sql/psql/OMERO5.1__1/psql-header.sql

See https://trello.com/c/CVUflk8g/490-encoding-for-db-init-upgrade-script. Adds a startup check to the server to prevent the server being used if the wrong character encoding was used to set up its database. Also tweaks SQL scripts to ensure that those with Unicode symbol literals are read with the correct encoding.
--no-rebase
***
To test, start out with a local OMERO.server and SQL scripts that do not have this PR merged. Partway through testing you will switch to a local OMERO.server and SQL scripts that do have this PR merged.
1. Start out without this PR.
1. Use `export PGCLIENTENCODING=WIN1252` in your shell to mess up the reading of Unicode SQL scripts.
1. Empty your binary repository and use `bin/omero db script` and `psql` to create a 5.0 or 5.1 database. If you used a 5.0 …

check for Unicode units on startup

---

components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/ome.viewport.js
components/tools/OmeroWeb/omeroweb/webgateway/templates/webgateway/viewport/omero_image.html

This PR fixes issue reported by @emilroz regarding unnecessary parameters preventing caching. 
To test it:
- open regular image and zoom in to see just a part of an image. Move the viewer. Copy image link and past into the new window. View of the image should be preserved including zoom level and position
inspect image element and checking if src doesn't contain z,x,y
```
```
- open big image zoom in to 1:1. Move the viewer. Copy image link and past into the new window. View of the image should be preserved including zoom level and position
inspect image tile element and checking if src doesnt contain z,x,y
```
```
cc: @will-moore @emilroz

Improving links in viewer

---

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/download_placeholder.html
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/includes/toolbar.html
components/tools/OmeroWeb/omeroweb/webclient/views.py

This allows the downloading of individual files from a set of files selected for download.
To test:
- Select 1 or more images, check the tooltip on "Download..." menu item for number of files that will download.
- If more than 1, then clicking "Download" will open download placeholder dialog
- You will see the option to download all files as zip (same as before)
- Also should be a list of files, clicking on one will download it directly.
- If multiple filesets are selected, files will be grouped in filesets and fileset indicated
on hover (see screenshot).
- Clicking on Zip, should show a "creating zip" message and hide everything else.

Download single files

---

components/tools/OmeroPy/test/integration/test_delete.py
components/tools/OmeroWeb/omeroweb/webclient/controller/container.py
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/containers.html

This is a slight improvement to the way we handle Comment deletion.
When a Comment is removed from an object, we need to check whether it is linked to any other objects. If it isn't then we delete the Comment itself.
Previously, we simply looked up links to Projects, Datasets, Images etc in turn.
Now, we use a Delete2 with ```dryRun = True``` to see if the Comment delete would have deleted any links to P/D/I etc.
To test, select several objects, add a Comment.
Then remove the comment from each in turn, checking the DB to see that it is deleted only after being removed from last object.
Also added integration test for this behaviour.

Comment Delete2 dryRun

---

components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/ome.viewportImage.js

This extends the Interpolate / pixelate effect to the big image viewer which was missed in #3772.
To test, zoom in to max (400%) in the big image viewer, then toggle the ```Interpolate``` checkbox and see if the image becomes pixelated when Interpolate is off.
This is kinda subtle since the max zoom is only 400%.

Viewer interpolate for big images

---

components/tools/OmeroWeb/omeroweb/webclient/views.py

This fixes a bug in display of script UI, introduced by the flake8 of webclient views.py https://github.com/openmicroscopy/openmicroscopy/pull/3674
which causes Boolean parameters not to be recognised (no checkbox displayed):
To test, check script UI to see if there's checkboxes for Boolean (E.g. Channel offsets script).

script_ui isinstance

---

components/tools/OmeroPy/test/integration/gatewaytest/test_services.py
components/tools/OmeroPy/test/integration/gatewaytest/test_user.py
components/tools/OmeroPy/test/integration/gatewaytest/test_wrapper.py

The python gateway integration tests should effectively test the same situations and continue to pass.
--no-rebase

fix Python gateway tests to use Chmod2

---

components/tools/OmeroPy/src/omero/callbacks.py
components/tools/OmeroWeb/omeroweb/webclient/views.py

In 5.1.0 and before, the CmdCallbackI constructor
in Python (unlike Java and C++) was performing its
initial polling invocation in the calling thread.
Due to its statelessness, OMERO.web was making use
of this fact. Now by passing foreground_poll=True,
the previous, deprecated behavior can be revived.
More complicated behavior should be achieved by
subclassing CmdCallbackI and overriding initialPoll.

Revive foreground_poll logic for callbacks.py

---

components/tools/OmeroWeb/omeroweb/webclient/webclient_gateway.py

@mtbc said this was a good idea?
To test:
- Edit the permissions of a group as Admin.
- And as a group owner.
Check that groups are updated as expected.

Use chmod2 for group updatePermissions

---

components/tools/OmeroWeb/omeroweb/webgateway/views.py

Noticed a very minor issue with roi thumbnails when shapes don't have Z or T set.
To test:
- I don't think you need to find a shape that has Z/T unset, just check that the web image viewer ROI table displays ROI "preview" thumbs is still working OK.
- Tested locally that this does work when Z is None.

roi_thumb shapes with no Z/T

---

components/tests/python/library/__init__.py
components/tools/OmeroPy/src/omero/cli.py
components/tools/OmeroPy/src/omero/plugins/delete.py
components/tools/OmeroPy/test/integration/clitest/test_delete.py

This PR mirrors the default action in the other clients and does not delete linked annotations (File, Tag and Term) without confirmation.
```
omero delete Image:51
``` 
will delete the image but not its annotations. Whereas
```
omero delete Image:51 --include Annotation
``` 
will also delete the images annotations. Individual annotation types can be selected,
```
omero delete Image:51 --include FileAnnotation
``` 
will delete any linked FileAnnotation objects but not other types. Other annotations can be deleted in the same command,
```
omero delete Image:51 Annotation:101
``` 
will not delete linked annotations but it will delete the separate specified annotation. Individual linked annotations can be deleted by explicitly using their IDs,
```
omero delete Image:51 Annotation:51
```
will …

Exclude annotations in CLI delete

---

components/tests/ui/testcases/web/delete_test.txt

From comment at https://github.com/openmicroscopy/openmicroscopy/pull/3757#issuecomment-95871006
This robot test creates a share with an image, deletes the image and looks for the "Object Deleted" text on the same in in the Public tree.
To test:
- check https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-robotframework for failures of this test.

Robot test delete image in share

---

examples/Training/java/src/training/CreateImage.java

As pointed out by @ctrueden in http://lists.openmicroscopy.org.uk/pipermail/ome-devel/2015-May/003302.html, we do not have a clear example making use of `RawPixelsStore.setPlane()` in the case of multi-channel images.
This PR modifies the existing `CreateImage` training example to create a new image of the same dimensionality as the original one instead of a single channel image.
/cc @imunro @jburel

Modify CreateImage training example to create multi-channel image

---

build.xml
components/tools/OmeroPy/src/omero/plugins/admin.py

- https://trello.com/c/xDMnFnPd/498-fix-omero-web-var-permissions
- https://github.com/openmicroscopy/ome-documentation/pull/1210
Testing: server.zip should include a `var` directory. If it's deleted then when a new `var/` is created it should always have the default umask, it shouldn't matter whether you run `omero admin` or `omero web` first.

Use default perms when creating var/

---

components/blitz/resources/ome/services/blitz-servantDefinitions.xml
components/blitz/resources/omero/Collections.ice
components/blitz/resources/omero/cmd/Admin.ice
components/blitz/src/omero/cmd/IRequest.java
components/blitz/src/omero/cmd/RequestObjectFactoryRegistry.java
components/blitz/src/omero/cmd/admin/CurrentSessionsRequestI.java
components/blitz/src/omero/cmd/admin/UpdateSessionTimeoutRequestI.java
components/blitz/test/ome/services/blitz/test/AbstractGraphTest.java
components/server/src/ome/security/basic/BasicSecuritySystem.java
components/server/src/ome/services/sessions/SessionManager.java
components/server/src/ome/services/sessions/SessionManagerImpl.java
components/server/src/ome/services/sessions/state/SessionCache.java
components/server/test/ome/server/utests/sessions/SessMgrUnitTest.java
components/tools/OmeroPy/src/omero/gateway/__init__.py
components/tools/OmeroPy/src/omero/plugins/sessions.py
components/tools/OmeroPy/test/integration/clitest/test_sessions.py
components/tools/OmeroPy/test/integration/test_isession.py

In order to complete the CLI session workflow changes, a few API changes were needed.
* `omero.cmd.UpdateSessionTimeoutRequest` can now be used to modify the `timeToLive` and `timeToIdle` values. cc: @sbesson 
* `omero.cmd.CurrentSessionsRequest` can now be used to query the in-memory state of all sessions as opposed to the in-database state. Inactive sessions will be timed-out in the process of querying and will *not* be included in the list. cc: @kennethgillen 
Check the various CLI commands, their various arguments, and their associated help:
* `bin/omero sessions group`
* `bin/omero sessions timeout`
* `bin/omero sessions who`
Clients should take care when talking to pre-5.1.2 servers to handle the `null` return value from `session.submit`: …

5.1.2: session api additions

---

components/blitz/src/ome/formats/importer/ImportLibrary.java
components/tools/OmeroPy/src/omero/plugins/admin.py

Though not an entire `fs fsck` solution this at least
alerts users to the fact that a .lock file is present.
The result of these files *could* be that imports are
not possible.
See: https://trello.com/c/WiG4Kd78/510-fs-fsck
* Start your server and find the lock file, e.g. /OMERO/.omero/repository/a9aadade-139e-426c-9ff8-788b0ca90c23/.lock
* Stop the server
* The lock file should be gone. `touch` the lock file location.
* Run `bin/omero admin start` and check for the following warning:
```
$ dist/bin/omero admin start
WARNING: lock files in /OMERO
----------------------------------------
/OMERO/.omero/repository/a9aadade-139e-426c-9ff8-788b0ca90c23/.lock
----------------------------------------
You may want to stop all server processes and remove
these files manually. Lock files can remain …
```

Add a check for .lock files on startup

---

components/tools/OmeroPy/src/omero/cli.py

When a user is in a new writeable-group (a new
feature for 5.1.2) *AND* is trying to perform
an operation on an object they don't own, then
print a "WARNING" message before acting. With
the hope that users will first issue a --dry-run,
this will hopefully suffice to prevent false
deletions, etc. The only other option would be
to require confirmation, which would be quite a
new CLI introduction at this point.
Create an image as a user in a rwrw group and then try to delete (`--dry-run`) it as another user. A warning of the form: `WARNING: Image:51 belongs to user 2` should be printed. E.g.
```
612  dist/bin/omero login root@localhost
613  dist/bin/omero import /tmp/a.fake
614  dist/bin/omero group add rw --perms=rwrw--
615  dist/bin/omero user add writer Writer User rw
616  dist/bin/omero …
```

Add WARNING on group-write graph operation

---

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/containers.html
components/tools/OmeroWeb/omeroweb/webclient/tree.py
components/tools/OmeroWeb/omeroweb/webclient/webclient_gateway.py
components/tools/OmeroWeb/test/integration/test_tree.py

Equivalent to #3811 in Insight, we now show a warning if any of the objects selected for Delete are not owned by the user.
To test:
- Try to delete your own object and another user's object (in Read-Write group or as group owner).
- You should only see warning in Delete dialog if data doesn't belong to you.
NB: Noticed that the "-locked" flag is still shown to indicate non-ownership but this should be removed in 5.2.3 as discussed with @aleksandra-tarkowska since it is not longer needed and is buggy.

Delete not owned warning

---

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/view/MetadataViewerModel.java
components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewerComponent.java

Allow to annotate well sample in RW.
Fix the error occurring while annotating images of a plate.
See https://trac.openmicroscopy.org/ome/ticket/12862
To test:
* Log in as user-11
* Switch to read-write group. By default you are logged in read-annotate
* Browse a plate.
* Select a well sample. 
* Annotate in insight. Check that you can view data in web
* Annotate in web. Check that you can view data in insight

Annotate well samples

---

components/tools/OmeroPy/src/omero/plugins/delete.py

This PR alters the output of the `--report` option of the `omero delete` command in line with https://github.com/openmicroscopy/openmicroscopy/pull/3725#issuecomment-96042925
The deleted objects list should use comma-separated ID lists rather than one object per line as before. Deleted `ome.model.display.*` objects should be excluded from the output:
```
$ omero delete Image:101 --dry-run --report
omero.cmd.Delete2 Image 101... ok
Steps: 1
Elapsed time: 0.451 secs.
Flags: []
Deleted objects
ome.model.fs.FilesetEntry:101
ome.model.core.Image:101
ome.model.core.OriginalFile:156,155
ome.model.core.LogicalChannel:51
ome.model.core.Channel:51
ome.model.jobs.PixelDataJob:53
ome.model.jobs.IndexingJob:55
ome.model.fs.Fileset:51
ome.model.jobs.ThumbnailGenerationJob:54 …
```

Tweak the CLI delete report

---

components/tools/OmeroPy/src/omero/plugins/sessions.py
components/tools/OmeroPy/src/omero/util/sessions.py
components/tools/OmeroPy/test/integration/clitest/test_sessions.py

Following https://github.com/openmicroscopy/openmicroscopy/pull/3786, this PR:
- implements the logic for the `--timeout` argument using a new property `omero.timeout` to minimize the API modification under `omero.util.sessions`
- add an integration test covering this implementation
- sets the default timeout for `--sudo` sessions using the `omero.sessions.timeout` configuration value

CLI: implement timeout logic 

---

components/server/resources/ome/services/service-ome.api.ILdap.xml
components/server/src/ome/logic/LdapImpl.java
components/server/src/ome/security/auth/LdapConfig.java
components/server/src/ome/security/auth/NewUserGroupOwnerBean.java
components/server/src/ome/security/auth/QueryNewUserGroupBean.java
components/server/src/ome/security/auth/RoleProvider.java
components/server/src/ome/security/auth/SimpleRoleProvider.java
etc/omero.properties

A new property `new_user_group_owner` has been
added which is used by `NewUserGroupOwnerBean`
implementations to query for groups that some
user should be considered an owner of. If the
sync_on_login property is set and the user is
loses the *owner* attribute, then the flag in
OMERO will also be removed.
Currently, only supported for `:query:` based
groups.
This began largely as a test of https://github.com/joshmoore/apacheds-docker to set up general LDAP testing. Turns out adding support was easy enough in that context that I figured I'd open a PR.
* **0. Test that the LDAP connection works for you and get a feel for what data (users & groups) is present:**
```
$ ldapsearch -h $SERVER -p 10389 -x -D uid=admin,ou=system -W -b dc=example,dc=com
Enter LDAP Password:
```
To explain the …

LDAP-support for group-owners

---

build.py
components/antlib/resources/lifecycle.xml
components/tools/OmeroPy/src/omero/install/jvmcfg.py
components/tools/OmeroPy/test/unit/old_templates.xml
components/tools/OmeroPy/test/unit/test_jvmcfg.json
components/tools/OmeroPy/test/unit/test_jvmcfg.py
etc/omero.properties

Our use of MaxPermSize has led to a number of warnings
in Java8 about the removal of that option. To prevent
these warnings, this adds another flag to ignore unknown
flags....
We're looking to remove this everywhere:
```
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
```
* `./build.py` should no longer print it.
* It should no longer show up in `var/log/master.err`
At the same time, this should not break any Java version from 6-8, and the jvmcfg unit tests should remain green.

Add IgnoreUnrecognizedVMOptions flag

---

components/tests/ui/robot_setup.sh
components/tests/ui/testcases/web/rdef_test.txt
components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/ome.viewport.js
components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/omero_image.js
components/tools/OmeroWeb/omeroweb/webgateway/templates/webgateway/viewport/omero_image.html

This fixes http://trac.openmicroscopy.org.uk/ome/ticket/12709 in web.
To test:
- Open Preview panel
- Change Z or T index
- Save button should become enabled and saving should update Thumbnail etc.
- Test same behaviour in Image Viewer.
NB: we don't have a whole undo/redo queue for Z/T changes, so after Z/T change and "Save" is enabled, if you change rendering settings then click "Undo" the Save button will become disabled again.

Save enabled on z/t change

---

components/common/resources/ome/config.xml
components/tools/OmeroPy/src/omero/gateway/__init__.py
components/tools/OmeroWeb/omeroweb/webstart/templates/webstart/insight.xml
components/tools/OmeroWeb/omeroweb/webstart/views.py
etc/omero.properties

This PR should allow passing login parameters to auto login into Insight.
JNLP file now gets host port and session ID that is minimum to log in
```
<property name="jnlp.omero.host" value="trout...org"/>
<property name="jnlp.omero.port" value="4064"/>
<property name="jnlp.omero.sessionid" value="79e4596a-bb8c-470f-8e6a-47b91ed0c5ab"/>
<property name="jnlp.omero.web.host" value="http://omero.testdomain.com:4080/"/>
```
Note: Webstat page is also available when user is **not logged in**. In this case there will be default server host and port set and no sessionid provided. These parameters should be used as a helper to choose the right server from the list.
cc: @jburel @dominikl

adding login params for autologin

---

components/insight/SRC/org/openmicroscopy/shoola/env/Container.java
components/insight/SRC/org/openmicroscopy/shoola/env/init/SplashScreenInit.java
components/insight/SRC/org/openmicroscopy/shoola/env/ui/SplashScreenManager.java
components/insight/SRC/org/openmicroscopy/shoola/util/ui/login/ScreenLogin.java

Handle the parameters specified when using webstart
To test:
* Log using the web client
* Start insight from web
* After the standard steps, insight splashscreen should only show the progress bar displayed when initializing the internal services. No username/password field
* When completed, the application should automatically log in and the data manager should pop up.
cc @dominikl @aleksandra-tarkowska 
see gh-3810

Jnlp parameters

---

components/tools/OmeroWeb/omeroweb/webadmin/forms.py
components/tools/OmeroWeb/omeroweb/webadmin/templates/webadmin/group_form.html
components/tools/OmeroWeb/omeroweb/webadmin/templates/webadmin/group_form_owner.html
components/tools/OmeroWeb/omeroweb/webadmin/templates/webadmin/groups.html
components/tools/OmeroWeb/omeroweb/webadmin/views.py

This allows Admins to create 'Read-Write' groups in webadmin. See https://trac.openmicroscopy.org/ome/ticket/10751
To test:
- Log in as Admin, go to webadmin, create a Group...
- See that there is now a 4th "Read-Write" option for group perms.
- Create a group with these perms.
- Test new group behaves / appears as expected in web (or insight)
- Edit the new group (check that perms are "Read-Write" before editing)
- Edit permissions and check updated OK.

Webadmin 'Read-Write' perms

---

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/GroupProfile.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/UserProfile.java
components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/util/AdminDialog.java
components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/util/GroupPane.java
components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/DeleteBox.java
components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewerComponent.java
components/insight/SRC/org/openmicroscopy/shoola/agents/util/ui/PermissionsPane.java

Enables ReadWrite group permission in Insight, [Trello](https://trello.com/c/RpdAOmKp/50-permissions-system-problems-chown)
Test:
- Create a new group with ReadWrite permission and add two users to it, make one owner of the group.
- Log in as one of the users and import some images.
- Switch to the other user and delete an image of the previous user. Make sure the confirmation dialog states that you're going to delete another user's data.
- Log in as the group owner. Change permission level of the group. Make sure you cannot change the permission back to ReadWrite.
- Log in as admin. Change permission level back to ReadWrite

Read write

---

components/blitz/src/ome/formats/importer/ImportConfig.java

In case the SLF4J logging implementation in play is not logback classic,
let's be defensive before casting.

ImportConfig: be defensive when casting

---

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/download_placeholder.html
components/tools/OmeroWeb/omeroweb/webclient/urls.py
components/tools/OmeroWeb/omeroweb/webclient/views.py

Fixes the download vv viewing of files in browser.
To test:
- Run a script, E.g. split view figure and inspect the resulting image and stdout (i) from the Activities dialog. These should open in the browser instead of downloading.
- Check that downloading still works - Select image(s) with more than 1 original file > Download. In the downloader dialog, click on individual files to download. These should download directly.

Original file download

---

components/blitz/src/omero/model/ElectricPotentialI.java
components/blitz/src/omero/model/FrequencyI.java
components/blitz/src/omero/model/LengthI.java
components/blitz/src/omero/model/PowerI.java
components/blitz/src/omero/model/PressureI.java
components/blitz/src/omero/model/TemperatureI.java
components/blitz/src/omero/model/TimeI.java
components/blitz/src/omero/util/IceMapper.java
components/blitz/test/ome/formats/utests/UnitsTest.java
components/blitz/test/omero/util/test/TempFileManagerTest.java
components/model/src/ome/model/enums/UnitsElectricPotential.java
components/model/src/ome/model/enums/UnitsFrequency.java
components/model/src/ome/model/enums/UnitsLength.java
components/model/src/ome/model/enums/UnitsPower.java
components/model/src/ome/model/enums/UnitsPressure.java
components/model/src/ome/model/enums/UnitsTemperature.java
components/model/src/ome/model/enums/UnitsTime.java
components/model/src/ome/model/units/UnitEnum.java
components/tools/OmeroPy/test/integration/test_model51.py
components/tools/travis-build

`projection("select x.unit"...)`-style queries were failing in
IceMapper because no RType was defined to store the return value.
Rather than define multiple RTypes for each of the quantities and
their enums, the same strategy has been applied as for Permissions.
Returning a quantity object like omero.model.LengthI results in a
dictionary of values including the keys: value, unit, symbol, string.
Returning an enum produces the uppercase code enum value (as opposed
to the database/SI symbol).
In addition to the integration tests, `bin/omero hql` can be used to test the return values.
* `select planeInfo.exposureTime.value` will return just the value (**as previously**)
* `select cast(planeInfo.exposureTime.unit as text)` will return just the symbol, e.g. `s` (**as previously**)
* `select …

Handle projections of unit types

---

components/tools/OmeroPy/src/omero/gateway/__init__.py
components/tools/OmeroPy/test/integration/gatewaytest/test_image_wrapper.py
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/includes/core_metadata.html
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/metadata_general.html
components/tools/OmeroWeb/omeroweb/webclient/views.py

This is a fairly straight-forward change that should help improve the rendering
performance of the right-hand metadata panel for Images. Previously, in order
to get the list of Channel labels to display, the template would have to load
the image's pixels, the pixel's channels, and then each channel's logical
channel. With this change, the relevant labels are retrieved directly via HQL
query.
The following are times taken to render the complete template for the right-hand side panel. The first number in each set represents a plate with 3 wells, the last two a fully-populated plate.
* Before changes:
- 0:00:01.550193
- 0:00:02.114671
- 0:00:02.787666
* After switching to `getChannelLabels`:
- 0:00:00.118799
- 0:00:02.053346
- 0:00:02.155348
* `getChannelLabels` combined with …

Improve rendering of Image metadata details

---

components/tools/OmeroFS/src/fsPyinotifyMonitor.py

This PR attempts to fix the problem reported in https://www.openmicroscopy.org/community/viewtopic.php?f=4&t=7814
Creating a DropBox user directory with permissions that don't allow omero to read it should not cause DropBox to fail. Changing the permissions later should cause the directory to be watched. More specifically:
```
mkdir -m 300 /path/to/omero.data.dir/DropBox/username
```
should log an error in `MonitorServer.log` indicating that the directory isn't being watched. Then:
```
chmod 770 /path/to/omero.data.dir/DropBox/username
```
should log that the directory is now being watched.
--no-rebase

Dropbox permissions on Linux

---

components/tools/OmeroWeb/omeroweb/webclient/controller/container.py
components/tools/OmeroWeb/omeroweb/webclient/views.py
components/tools/OmeroWeb/omeroweb/webgateway/views.py

This handles unicode script param values when running scripts.
To test, need to check that all parameters passed to scripts can handle unicode strings and different scripts handle these values correctly.
E.g String parameters, Lists with unicode values and Maps with unicode values.
Set up:
- Rename a Dataset, Image and Channels with strings containing unicode characters. Also Tag the image with a unicode tag.
Scripts:
- Split view Figure, with unicode in channels and figure name.
- Thumbnail Figure, sorting by Tag with unicode.
- Combine Images, naming new channels (map) with unicode names.
Corresponding scripts PR: https://github.com/ome/scripts/issues/101 has unicode handling to Split_View_Figure and Thumbnail_Figure as well as other small fixes.

Unicode scripts 12571

---

history.txt

Adds history for 5.1.2. Will be staged at http://www.openmicroscopy.org/site/support/omero5.1-staging/users/history.html once autogen docs merge build is run.

5.1.2 history

---

components/tools/OmeroWeb/omeroweb/webadmin/templates/webadmin/group_form_owner.html

Group owner shouldn't be able to remove himself from the group he can manager users.
To test log in as group owner. Go to User Settings -> My Group and check if current user is highlited and there is no X allowing to delete from current group.

prevent group owner from self removal

---

components/tests/ui/testcases/web/delete_test.txt
components/tools/OmeroWeb/omeroweb/webadmin/templates/webadmin/group_form_owner.html
components/tools/OmeroWeb/omeroweb/webadmin/views.py

This fixes https://trac.openmicroscopy.org.uk/ome/ticket/12901 and also fixes failing Robot tests.
To test:
- Owner of a Read-Write group should be able to make changes to the group and the form should be submitted without errors.
- If owner is editing a Read-Write group, they should be able to click on other permission options, and will still be able to click on "Read-Write" again so as to make no permissions changes on Save.
- However, if they save with other permissions, they won't then be able to choose "Read-Write" permissions when they edit again.
- Check https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-robotframework/lastBuild/robot/ for failure in Test Delete Images in Share.

Group owner form read write

---

components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/ResultsSaver.java

Problem reported during the rc1 testing
To test:
* Open an image stored in OMERO in imageJ
* Draw rois. Do not open the results table in ImageJ
* Select "Plugins>OMERO>Save ROIs to OMERO"
* A Saving dialog will pop up. Keep the default option i.e. save rois and table
* Check that the rois are saved and no table are saved.
cc @pwalczysko @bramalingam

Roi table ij

---

components/tools/OmeroWeb/omeroweb/webclient/webclient_gateway.py

this extend waiting time to 60 sec as HTTP server response is set by default to 60 sec
replace https://github.com/openmicroscopy/openmicroscopy/pull/3852
See also:
* http://trac.openmicroscopy.org.uk/ome/ticket/12902#comment:2
* http://trac.openmicroscopy.org.uk/ome/ticket/12904#comment:1

Change perm locktimeout

---

components/blitz/src/omero/cmd/RequestObjectFactoryRegistry.java

Has the server use `ChmodI` instead of `Chmod2I` when given a `Chmod` request regardless of `omero.graphs.wrap`.

do not substitute Chmod requests with Chmod2

---

components/tools/OmeroPy/src/omero/cli.py
components/tools/OmeroPy/src/omero/plugins/chgrp.py
components/tools/OmeroPy/src/omero/plugins/delete.py

This PR modifies the `--report` option of `delete` to order object ids and compress to ranges when possible. The same option for `chgrp` is brought to the same level with some refactoring. As the report is now relatively concise the exclusion of some classes has been lifted - this also means that some reports will not be artificially empty. Finally, both usage docstrings have been updated with a few more examples.
Testing
-------
Try a variety of `delete` and `chgrp` commands with `--report` (and `--dry-run` to prevent and actual moves or deletes. The output should be something like this:
```
omero delete Image:52,51 --report --dry-run
...
omero.cmd.Delete2 Image 52,51... ok
Steps: 1
Elapsed time: 0.268 secs.
Flags: []
Deleted objects
Channel:51,52
Image:51,52
LogicalChannel:51,52 …
```

Modify delete and chgrp reporting

---

components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/chooser/LocationDialog.java
components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/TreeViewerAgent.java
components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/util/SaveResultsDialog.java

Fix problem reported while presenting to local users
Check the following:
* tick as default only the appropriate box in the Save ROIs... and Save Results... workflows (this means Save ROIs... would have the ROIs box ticked and Measurements unticked, and the Save Results... would have it the other way round
* reformulate the ```image from all image windows``` to ```images from all image windows```

Imagej fix

---

build.xml

The ome.model package was referenced from the top-level Javadocs page but not
included as a fileset. This should allow the ome.model classes to be picked up
and published with the rest of the API. /cc @mtbc

Include ome.model as part of the Javadocs

---

components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerComponent.java
components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerControl.java
components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerModel.java
components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/RendererModel.java

Enables the save button after Z or T has been changed. There are still some minor issues with the z/t sliders if both views (preview and full viewer) are open at the same time (z/t slider then shows the last selected z/t state, even if the z/t changes haven't been stored), not going to fix that in this PR.

Save z changes

---

components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/ome.postit.js

Fixes https://trac.openmicroscopy.org/ome/ticket/12894
To test, using **Chrome** browser, open an image that has a lot of ROIs (E.g. 30) in the web image viewer and "Show ROIs" so that the ROIs table is bigger than the 'postit' popup panel.
Use the mouse-wheel to scroll to the bottom of the table.
A scroll bar may or may not be shown initially but should appear while scrolling?

Postit panels scrolling

---

components/tools/travis-build

Lately Romio tests have been hanging frequently on Travis causing the build to fail.

Disable Romio tests in Travis build

---

components/tests/ui/testcases/web/forms_test.txt
components/tests/ui/testcases/web/tree_test.txt
components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/ome.webclient.actions.js
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/container_subtree.html
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/container_tags.html
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/container_tags_containers.html
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/container_tags_subtree.html
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/container_tags_tree.html
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/containers.html
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/containers_icon.html
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/containers_tree.html
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/includes/center_plugin.thumbs.js.html
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/includes/right_plugin.general.js.html
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/public/public.html
components/tools/OmeroWeb/omeroweb/webclient/tree.py
components/tools/OmeroWeb/test/integration/test_tree.py
components/tools/OmeroWeb/test/unit/test_tree.py

This PR clean up templates and removes ``-locked``. It also fixes issues in the tags tree (disables all actions as they are not supported).
*Note: there is ``jstree-locked `` in jstree lib that is unrelated.*
To test: I am not sure how to test is easily as this affects navigation in a tree in Explore, Tags and Public.
- Test Explore if you can navigate the tree and drag and drop entities.
- Test Tags tree if actions including drag and drop are disabled on each type fo entities. Make sure you test entire hierarchy TagSet/Tag and Tag only linked to Project/Dataset/Image/Screen/Plate...
- Test Public if drag and drop is disabled.
If there is any unexpected behavior please test first with latest to see if it was introduced here.
cc: @will-moore  @pwalczysko

Remove locked

---

components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/ome.webclient.actions.js
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/mapannotation.html

Fixes https://trac.openmicroscopy.org/ome/ticket/12774
Tooltip for map annotations is now displayed for the header.
Test that tooltip is displayed for map annotations, and still works for Tags & Files in right panel.

Map annotation tooltips

---

components/tests/ui/resources/web/tree.txt
components/tests/ui/robot_setup.sh
components/tests/ui/testcases/web/spw_test.txt
components/tools/OmeroPy/test/integration/tablestest/test_populate_metadata.py
components/tools/OmeroWeb/omeroweb/webclient/static/webclient/css/layout.css
components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/ome.webclient.actions.js
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/metadata_general.html
components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/omero_image.js
components/tools/OmeroWeb/omeroweb/webgateway/templates/webgateway/viewport/omero_image.html
components/tools/OmeroWeb/omeroweb/webgateway/views.py

This is the same as gh-3863 but rebased onto metadata.
----
See https://trello.com/c/MGeMSVXY/239-hdf-table-data-display-for-selected-wells-in-web
Load and display bulk annotations in metadata General tab.
Uses the same code as in the full image viewer.
Bulk annotations can be added as described: https://github.com/openmicroscopy/ome-internal/blob/master/testing_scenarios/BulkAnnotations.txt
NB: Bulk annotations are not filtered by owner as other annotations are. Is this needed?

bulk annotations right panel (rebased onto metadata)

---

components/blitz/resources/ome/services/graph-rules/blitz-chgrp-rules.xml

Fixes http://trac.openmicroscopy.org/ome/ticket/12932 by improving the error message to reference the culprit image and wellsample. This isn't for end users, but will be rather more helpful for developers. One of the workflows causing the error is http://trac.openmicroscopy.org/ome/ticket/12932#comment:4.

fix #12932: improve error message for moving plates of projections

---

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/ToolBar.java
components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewer.java
components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewerComponent.java
components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewerControl.java
components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewerWin.java
components/insight/SRC/org/openmicroscopy/shoola/agents/util/ui/ScriptingDialog.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/model/ScriptObject.java

In this PR, few problems when running script from the search view (see http://trac.openmicroscopy.org/ome/ticket/12934)
to test this PR:
Test 1:
* Log as user-2. Check that you are in private-1
* Go to the search tab
* Search for dv (few results are returned)
* Select one image result from read-only group.
* Click on the run script button in the toolbar. Select for example, channel offsets script
* Check that the id field is populated with the id of the selected image.
* Run the script.
* Check that the script returns without error
Test 2:
* Log as user-2. Check that you are in private-1
* Go to the search tab
* Search for dv (few results are returned)
* Select one image result. The group context does not matter
* Go to the right-hand pane and select one of the publishing script e.g. …

Script from search

---

components/insight/SRC/org/openmicroscopy/shoola/util/ui/slider/TwoKnobsSlider.java

see https://trac.openmicroscopy.org.uk/ome/ticket/11632
To test:
* Select an image
* Go to preview
* Move the right-hand knob of the channel slider
* Move it next to the left knob. Keep dragging.
* Check that the right knob does not move back to the right

Slider move

---

components/insight/SRC/org/openmicroscopy/shoola/agents/util/browser/TreeViewerTranslator.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/OmeroMetadataServiceImpl.java

- Enables Tagset selection on import stage, see [Ticket 12920](http://trac.openmicroscopy.org.uk/ome/ticket/12920); *Test: Create a Tagset, open the import dialog, and make sure you can see and select the tagset there.*
- Fixes a problem that tagged plates disappeared from the tree view after switching and returning to the Tag browser. *Test: Tag a plate; switch to the Tags browser; expand the tag the plate was tagged with and make sure the plate is displayed as a sub node of the tag node. Switch to another browser, Search, Screens, whatever. Return to the Tags browser and make sure it still looks like before (tag node expanded showing the plate).*
See [Trello - Tagging problems](https://trello.com/c/eo1Svfvp/30-tagging-problems)

Tagging fixes

---

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/PropertiesUI.java
components/insight/SRC/org/openmicroscopy/shoola/util/ui/omeeditpane/OMEEditPane.java
components/insight/SRC/org/openmicroscopy/shoola/util/ui/omeeditpane/OMEWikiComponent.java

Problem noticed while reviewing tickets
Updating the description did not enable the save button
To test:
* Select an object e.g. project
* Modify the description.
* Check that the save button is enabled.

Description edit

---

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/PublishingDialog.java

Enable roi split view figure for images with one channel. see https://trac.openmicroscopy.org.uk/ome/ticket/11164
To test:
* Select an image with one channel
* Draw a roi e.g. rectangle
* Go to the right-hand pane
* Click on the "publishing" button.Check that the "ROI split figure" is enabled.
* Run the script.

ROI split figure

---

components/blitz/src/pojos/PixelsData.java

If an image uses pixel as unit for the pixel size, Insight crashes because the transformation into microns is not possible. With this PR pixel sizes in pixel will be ignored and treated like no pixel size is provided.
`PixelsData.getPixelSizeX/Y/Z()' is the only place where I can think of this could be an issue.  Are there other places? @jburel
See [QA 11140](https://www.openmicroscopy.org/qa2/qa/feedback/11140)

PixelSize in px fix

---

components/insight/SRC/org/openmicroscopy/shoola/agents/dataBrowser/browser/BrowserControl.java

Fixes a potential NPE, see [QA 11139](https://www.openmicroscopy.org/qa2/qa/feedback/11139/)
I don't know how to trigger the bug, because navigation via arrow keys shouldn't be possible if nothing is selected in the central panel, so I think for testing it's sufficient to check if the arrow key navigation in central panel still works.

Fix for QA 11139

---

components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/util/FileImportComponent.java
components/insight/SRC/org/openmicroscopy/shoola/util/ui/UIUtilities.java

Add option to copy import error to the clip board. See https://trac.openmicroscopy.org.uk/ome/ticket/12889
To test:
* Import a bad image e.g. test_images_bad/mike.dv
* Click on the failed button
* Click on "Copy Exception to Clipboard"
* Then go an text editor for example. Click Cmd+v to paste the exception

Copy to clipboard

---

components/tools/OmeroWeb/omeroweb/webgateway/templates/webgateway/viewport/omero_image.html

I fixed a few bugs in OMERO.web related to ROIs management.
It was possible to click the "Show ROIs" button when ROIs were already on screen and this action restored all the ROIs, even the ones deactivated using the web UI filter.
Hiding ROIs with the "Hide "button or the "X" button on the table with ROIs details turned ROIs OFF but didn't reset ROIs table, so when hitting "Show ROIs" again all ROIs were displayed by the checkboxes of the deactivated ones will be shown as unchecked even if ROIs are visible on screen.
What I introduce with this PR is:
* the "Show ROIs" and "Hide" buttons will disable each other when used; if ROIs are on screen only the "Hide" button will listen to a click action and vice versa
* when showing ROIs with the "Show ROIs" button all the checkboxes of the ROIs …

Minor improvements in OMERO.web ROIs interface

---

build.xml

If the Bio-Formats submodule is not removed from the main repository, this
should prevent the build system from entering components/bioformats.
/cc @rleigh-dundee @joshmoore

Exclude Bio-Formats from Ivy buildlist targets

---

components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/ome.roidisplay.js

Fixes https://trac.openmicroscopy.org.uk/ome/ticket/12394
Previously, the whole shape (stroke and fill) were getting set opacity set according to the line "alpha" in Insight. Now, we set the opacity of the fill and stroke independently.
To test:
- In Insight, create a shape (E.g. rectangle) that has different opacity for fill and line.
- Check display in web to see that opacity is same for stroke and line.

Shape Alpha

---

components/blitz/resources/ome/services/graph-rules/blitz-chgrp-rules.xml
components/blitz/resources/ome/services/graph-rules/blitz-chown-rules.xml
components/blitz/resources/ome/services/graph-rules/blitz-delete-rules.xml
components/blitz/src/omero/cmd/graphs/BaseGraphPolicyAdjuster.java
components/blitz/src/omero/cmd/graphs/Chown2I.java
components/blitz/src/omero/cmd/graphs/SkipHeadPolicy.java
components/server/src/ome/services/graphs/GraphPolicy.java
components/server/src/ome/services/graphs/GraphPolicyRule.java
components/server/src/ome/services/graphs/GraphPolicyRulePredicate.java
components/server/src/ome/services/graphs/PermissionsPredicate.java
components/tools/OmeroJava/test/integration/chown/PermissionsTest.java

This PR rewrites how the `Chown2` requests work to make them easier to adjust in the future. It introduces and uses a pluggable matcher for objects among the graph policy rules and adds more integration testing.
Testing: #3879 will help, especially its `--report` option. This PR should not introduce any regressions but change-owner has been rather untested anyway, so at this stage I'll be happy enough if it doesn't have obvious misbehaviors! We can fix smaller RFEs in later PRs.

rewrite the policy rules for Chown2

---

components/tools/OmeroPy/src/omero/cli.py
components/tools/OmeroPy/src/omero/plugins/chown.py
components/tools/OmeroPy/test/integration/clitest/cli.py
components/tools/OmeroPy/test/integration/clitest/test_chgrp.py
components/tools/OmeroPy/test/integration/clitest/test_chown.py
components/tools/OmeroPy/test/integration/clitest/test_delete.py

Idly talking with @mtbc in Paris about Chown2 it was clear that a `chown` command would pretty much be a search and replace of the `chgrp` command. So here it is. This is mainly intended to facilitate testing of `Chown2` but is exposed in the CLI. As this is a copy of `chgrp` I may have left some of the old stuff behind, particularly in docstrings and comments.
There are some minimal integration tests: two users in the same group - transfer possible, two users in different groups - transfer not possible. There are no admin tests as yet - these need to be added. The argument parsing is not tested here as the same superclass as `chgrp` and `delete` is used and so that is tested sufficiently elsewhere.
To test try various `chown` operations between different users, different groups, etc. The …

Add chown command to CLI

---

components/tools/OmeroWeb/omeroweb/webclient/views.py

Fixes https://trello.com/c/JcQw9nOY/35-python-plate-acquisitions
It turns out that we were simply failing to pass the correct field index to the plate.html template.
To test, find a plate with multiple Acquisitions. For each, check that the right images are loaded into each field (compare with Insight).

plate run index bug

---

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/includes/core_metadata.html
components/tools/OmeroWeb/omeroweb/webclient/webclient_gateway.py
components/tools/OmeroWeb/test/integration/test_metadata.py
components/tools/OmeroWeb/test/integration/test_rendering.py

See https://www.openmicroscopy.org/qa2/qa/feedback/11146/
This fixes display of pixel sizes for images that have pixel size units that are incompatible with microns.
E.g. in the example above, exception is thrown trying to convert from PIXEL to MICROMETER.
To test, set pixel sizes to E.g. PIXEL (complete code sample below) and try viewing in web:
```
$ omero shell --login
In [1]: from omero.gateway import BlitzGateway
In [2]: conn = BlitzGateway(client_obj=client)
In [3]: i = conn.getObject("Image", 8551)
In [4]: from omero.model.enums import UnitsLength
In [5]: u = omero.model.LengthI(9.8, UnitsLength.PIXEL)
In [6]: p = i.getPrimaryPixels()._obj
In [7]: p.setPhysicalSizeX(u)
In [8]: p.setPhysicalSizeY(u)
In [9]: conn.getUpdateService().saveObject(p)
```

Pixels to microns

---

components/insight/SRC/org/openmicroscopy/shoola/env/init/ContainerConfigInit.java

ref : https://trac.openmicroscopy.org/ome/ticket/12925
Testing isntructions:
1) Add "OMEROIJ" plugin and bioformats_package.jar or loci-tools.jar to the plugins folder of imageJ.
2) open imageJ , "Plugins-->OMERO-->Connect to OMERO". This Should throw up the Insight login screen.
Now, rename the bioformats_package.jar (within the plugins folder) with something like,
bioformats_package-1.jar or biformats_package 1.jar or etc (concatenate any string to the name of the jar post bioformats_package or loci-tools with *.jar) and repeat the workflow specified above.
You should still get the Insight login screen.
Note : (when any string extension is added to bioformats_package or loci-tools) Without this PR the above workflow will throw a warning window  saying: can't find bioformats_package or …

OMEROIJ_Bioformats_dependency_check

---

etc/ivysettings.xml

Create a `spring-resolver` dedicated to resolving the spring artifacts. When
Spring is upgraded and the springsource repository is used, the `repo` resolver
can be dropped from the spring-resolver chain.
/cc @joshmoore

Separate Spring artifact resolution

---

components/blitz/resources/omero/api/IQuery.ice

IProjection is the only location which is currently
using the JSON-like serialization of Perms and Units.
It seems useful then to place the documentation for
these directly on the method.
See: https://trello.com/c/vdyTStEq/40-unit-documentation

Add doc block for IQuery.projection

---

components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerComponent.java

Tiny fix to prevent a potential NPE, see [Ticket 12816](https://trac.openmicroscopy.org/ome/ticket/12816)
Unfortunately I couldn't reproduce the NPE, so code review must be sufficient and maybe check if you can still load big images (which triggers the affected loadTiles()` method).

Fix for ticket 12816

---

components/tools/OmeroPy/src/omero/util/populate_metadata.py
components/tools/OmeroWeb/omeroweb/webclient/static/webclient/css/layout.css
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/metadata_general.html
components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/css/ome.viewport.css
components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/omero_image.js
components/tools/OmeroWeb/omeroweb/webgateway/views.py

This simply hides tabular data where there is no value to avoid showing empty column names in the right panel or the full viewer.
Before and after:

Hide empty column data

---

components/tools/OmeroPy/src/omero/util/populate_metadata.py

This backports a number of PRs from @glencoesoftware (78, 89, 95) which fix minor issues in the populate_metadata.py script. To do so, it was necessary to revert @ximenesuk's flake8 changes, since those three PRs were made against dev_5_0.
Primary changes include:
* Handle variable Image names.
* Allow resolving the bulk annotations at image level.
* Expand the robustness of populate metadata so that it is more inclined to complete successfully, warn more accurately and fail more gracefully when the source CSV is less than ideal. Also fixed issues with the loading of the metadata under cross-group conditions.

Populate metadata

---

components/tools/OmeroWeb/omeroweb/settings.py

This PR fixed ```SEND_BROKEN_LINK_EMAILS``` that was removed in Django 1.6 infavour of ```django.middleware.common.BrokenLinkEmailsMiddleware```.
To test it:
- set ```bin/omero config set omero.web.debug False```
- set mail config https://www.openmicroscopy.org/site/support/omero5.1/sysadmins/mail.html
- locally SMTP mock (you will not get real email):
- set ```bin/omero config set omero.mail.from "your@email``` and ```bin/omero config set omero.mail.host "localhost"```
- start SMTP mock ```sudo python -m smtpd -n -c DebuggingServer localhost:25```. *Email message will be shown as a plane text on your console.*
- set your email in ```bin/omero config set omero.web.admins '[["Username", "your@email"]]'```
- try to get HTTP500 and 404 (must come from broken link in template, do not access …

Fixing broken links email notification

---

components/blitz/resources/ome/services/graph-rules/blitz-chmod-rules.xml
components/blitz/src/omero/cmd/RequestObjectFactoryRegistry.java
components/blitz/src/omero/cmd/graphs/BaseGraphPolicyAdjuster.java
components/blitz/src/omero/cmd/graphs/Chgrp2I.java
components/blitz/src/omero/cmd/graphs/Chmod2I.java
components/blitz/src/omero/cmd/graphs/Chown2I.java
components/blitz/src/omero/cmd/graphs/Delete2I.java
components/server/src/ome/services/graphs/GraphTraversal.java
components/tools/OmeroJava/test/integration/AbstractServerTest.java
components/tools/OmeroJava/test/integration/ModelMockFactory.java
components/tools/OmeroJava/test/integration/chmod/PermissionsTest.java
components/tools/OmeroJava/test/integration/chown/PermissionsTest.java
components/tools/OmeroJava/test/integration/delete/HierarchyDeleteTest.java

This PR rewrites how the `Chmod2` requests work to make them easier to adjust in the future, and reintroduces default automatic substitution of legacy `Chmod`. Now in some cases it is possible to downgrade a group to private where previously it wasn't, but at the cost of those downgrades running slowly on large groups; for instance, see http://trac.openmicroscopy.org/ome/ticket/8566. Every other permissions change should remain fast.
This PR should not introduce any regressions. Integration tests should continue to pass.

rewrite the policy rules for Chmod2 and make it often fast

---

components/server/src/ome/security/basic/AllGroupsSecurityFilter.java
components/server/src/ome/security/basic/OneGroupSecurityFilter.java

This removes the static strings in `AllGroupsSecurityFilter` and
`OneGroupSecurityFilter` that define the filter condition and replaces
them with `static` methods of the same name. The only place this string
was being used in either class was in `getDefaultFilterCondition`, so
that reference has been changed to a call to the new method.

Move filter condition static string to function

---

components/tools/OmeroCpp/cmake/FindIce.cmake

We already had support for the beta release in place; this removes it, leaving support for the final release only.  It also adds support for finding the various programs provided with Ice in addition to the slice generators; we don't use these at present.
See also: https://github.com/Kitware/CMake/pull/161
--------
Testing: Builds should continue to be green.  We don't use 3.6 at present, so this won't have any functional effect until Ice 3.6.0 is installed and detected.  If you wish to verify the logic is working, you can install the ZeroC rc2 candidate, but since it's just removing the beta version from the list, this is obviously correct.  Tested by me on Windows with Visual Studio 2012 and 2013 x86 and x64 (the supported platforms for 3.6.0).

cmake: FindIce: Update for Ice 3.6.0 release

---

etc/ivysettings.xml
etc/local.properties.example

This PR proposes a strategy allowing merge OMERO builds to consume merge SNAPSHOTS of Bio-Formats preserving the current statu quo in terms of deployment/review workflow. Major changes are the following:
- a new OME resolver is defined specifically for artifacts associated with the `ome` group (Bio-Formats + appbundle). The only 2 places considered are the Maven cache and the OME artifactory
- a non-Maven OME artifactory repository is registered in `ivysettings.xml`
- the last commit shows how to consume a SNAPSHOT from a non Maven repository, by setting the bioformats.versions to `5.1.3-SNAPSHOT` and setting the `ome-resolver` to use the unstable repository directly (without caching the artifacts to Maven, i.e. use the local cache only)
To test this PR,
- run the build from 533b684 and …

 OME artifactory Ivy resolver

---

components/blitz/resources/omero/cmd/Graphs.ice
components/blitz/src/omero/cmd/graphs/Chown2I.java
components/tools/OmeroJava/test/integration/chmod/PermissionsTest.java
components/tools/OmeroJava/test/integration/chown/PermissionsTest.java
components/tools/OmeroJava/test/integration/delete/HierarchyDeleteTest.java

This PR expands `Chown2` such that it allows a non-admin to chown somebody else's data if they are an owner of the group in which the data is. Perhaps most easily tested from the CLI.
https://ci.openmicroscopy.org/job/OMERO-5.1-merge-integration-java/lastCompletedBuild/testngreports/integration.chown/ should continue to pass.

allow group owners to chown

---

components/antlib/resources/lifecycle.xml
components/tools/OmeroJava/test/integration/AbstractServerTest.java
etc/local.properties.example

This adds the ability to specify `omero.test.timeout` in
`local.properties`. This value will be used in `AbstractServerTest` for
the `scalingFactor` that is, in turn, used to determine the timeout for
`CallbackCmdI`-based tests.

Make test timeout configurable

---

components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/util/TreeCellRenderer.java
components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewerWin.java
components/insight/SRC/org/openmicroscopy/shoola/util/ui/JXTaskPaneContainerSingle.java
components/insight/SRC/org/openmicroscopy/shoola/util/ui/UIUtilities.java

Replaces the usage of TableLayout with GridBagLayout in the left hand side "browser container"; this should fix [11403](https://trac.openmicroscopy.org/ome/ticket/11403) and [12655](https://trac.openmicroscopy.org/ome/ticket/12655). 
Unfortunately the problems mentioned in the tickets are random and not reproducible, so for *testing this PR* make sure the left hand side panel in Insight still works as expected, i. e. switch between project, screen, administration, etc., change the size of the panel, make sure the scrollbar appears when there's not enough space, and so on.

Replaced TableLayout with GridBagLayout, JXTaskPaneContainer

---

.travis.yml
etc/ivysettings.xml

As part of https://github.com/openmicroscopy/openmicroscopy/pull/3931, the Ivy pattern for the local repository (under `lib/repository`) was erroneously modified, causing the Ivy resolution to unnecessarily interrogate the OME artifactory.
This PR also reverts to the container-based infrastructure in order to cache the Maven cache from build to build.

Revert to the *.ivy pattern for Ivy files in the local repository

---

components/blitz/build.xml
components/blitz/resources/beanRefContext.xml
components/blitz/resources/ome/services/blitz-repositories.xml
components/blitz/resources/ome/services/blitz-servantDefinitions.xml
components/blitz/resources/omero/Constants.ice
components/blitz/src/ome/services/blitz/fire/SessionManagerI.java
components/blitz/src/ome/services/blitz/impl/ScriptI.java
components/blitz/src/ome/services/blitz/impl/SharedResourcesI.java
components/blitz/src/ome/services/blitz/util/FindServiceFactoryMessage.java
components/blitz/src/ome/services/blitz/util/ParamsCache.java
components/blitz/src/omero/cmd/SessionI.java
components/blitz/src/omero/grid/InteractiveProcessorI.java
components/blitz/src/omero/grid/ParamsHelper.java
components/server/src/ome/services/scheduler/SchedulerFactoryBean.java
components/tools/OmeroPy/test/integration/test_scripts.py
etc/omero.properties

See: http://trac.openmicroscopy.org.uk/ome/ticket/10661#comment:7
An interesting recent bug lead to the review of the `JobParams` creation. The user-4 on merge/trout was receiving an exception when trying to run `Make_Movie.py` since the chosen color was not a member of a list of the form `["White", "Red", None, "Black", None, None, None]`. What seems to have happened is that some exception (`OutOfMemory`?) caused the params themselves to be corrupted. The reason that this was only happening for user-4 (and his/her group) was that `JobParams` were being created **per group**. This unnecessary overhead was a secondary bug.
Rather than trying to fix the 2 underlying bugs caused by caching params for each group (and trying to clean up old params, etc.), ticket 10661 suggested reloading all …

10661 dynamic params

---

build.xml

See https://github.com/openmicroscopy/openmicroscopy/pull/3871#issuecomment-118274227
This PR creates a new top-level folder share in the OMERO.server bundle which includes:
- the various licenses under lib/licenses
- the server/client dependencies generated by Ivy

Organize information under share/ folder of OMERO.server

---

components/tests/ui/resources/robot.template
components/tests/ui/resources/web/tree.txt
components/tests/ui/testcases/web/post_test.txt

As *Tree Test.Test Create Project Dataset*, *Post Test.Test Copy Paste Dataset* and *Post Test.Test Cut Paste Dataset* have been failing the most recently, this small improvement on waiting for reloading metadata panel should help.
In general is a bad idea to add sleep or delay in test. It should be determined by adding appropriate waiting time to **Wait Until...** keywords as a second argument.

Improving robot framework tests

---

components/tools/OmeroPy/src/omero/install/config_parser.py
etc/omero.properties

This PR follows up on https://github.com/openmicroscopy/openmicroscopy/pull/3825 which was adding DB properties parsing to the documentation page. Main changes are described as  follows:
- a new configuration section is introduced listing the `Database` server properties
- the `FS` section is renamed as `Binary repository` in the docs to unify with the existing semantics
- a new top-level `Core` section is created with hyperlinks to the fundamental server properties (any better name?)
- in terms of underlying logic, a `Header` object is added allowing to define for each configuration section a display name, a reference (to prevent breakage of `fs_configuration` refs) and a stub for a description (which could be displayed under the title).
To test this PR, check the output of the rST file …

Server configuration: autogenerated docs improvement

---

components/tools/OmeroJava/test/integration/AbstractServerTest.java

Prevent the WARN message when Java integration tests are run with `omero.test.timeout` taking its default value. In testing, check that setting or not setting `omero.test.timeout` still works as one would expect and still WARNs of silly values like `foo`.
cc: @jballanc

do not WARN when omero.test.timeout default is not overridden

---

components/tools/OmeroJava/test/integration.testng.xml

This reverts commit 3340ce1460bd73a0452f675c87f0a568818c9eee.
Now we consume merge Bio-Formats artifacts after merging the decoupling branch, we should be able to re-enable the OmeroJava exporter tests on the mainline. The execution of these tests depends on https://github.com/openmicroscopy/bioformats/pull/1866.
To review this PR, check https://ci.openmicroscopy.org/job/OMERO-5.1-merge-integration-java/ reincludes the `ExporterTest` and that these tests are passing.
Note: independently of the test results, this PR should not be merged until Bio-Formats 5.1.3 is released and `versions.bioformats` has been bumped to 5.1.3.

Revert "Temporary exclude ExporterTest from the integration suite"

---

components/blitz/src/pojos/ShapeSettingsData.java
components/insight/SRC/org/openmicroscopy/shoola/util/roi/io/InputServerStrategy.java

In this PR, fix the problem reported on forum see https://trac.openmicroscopy.org.uk/ome/ticket/12936
* log as user-3. 
* Go to ```Project-user-3/archivedv```
Test 1
* Open the first image (id 9461) in the full viewer
* Open the measurement tool
* Check that the stroke width is displayed correctly i.e. red and width of 15 and 10
Test 2
* Open the first image (id 9460) in the full viewer
* Open the measurement tool
* Check that no message pops up. Check that you can see the roi
Test 3
* Open the first image (id 9463) in the full viewer
* Open the measurement tool
* Check that no message pops up. Check that you can see the roi

Shape font

---

components/insight/SRC/org/openmicroscopy/shoola/env/data/model/FileObject.java

ref: https://www.openmicroscopy.org/community/viewtopic.php?f=4&t=7843
Testing Instructions:
1) Open OMERO Image (Multi-dimensional image) in ImageJ, and Click on Image-->Properties (in the ImageJ Menu).
2) Switch the Z and T values and click OK. This should switch the image properties in the ImageJ Image Window.
3) Plugins->OMERO->Save Image(s) to OMERO
This should save the modified image back to OMERO as an ome-tiff.
Without this PR, "add to queue"  in the import dialog will be active but not functional. (i.e you won't be allowed to add the modified image back to the import dialog).
For more details please read the thread (above).

OmeroIJ: Switch dimensions and save image

---

components/blitz/resources/ome/services/graph-rules/blitz-chgrp-rules.xml
components/blitz/resources/ome/services/graph-rules/blitz-chown-rules.xml
components/blitz/resources/omero/cmd/Graphs.ice
components/blitz/src/omero/cmd/graphs/Chown2I.java
components/tests/python/library/__init__.py
components/tools/OmeroJava/test/integration/chown/PermissionsTest.java
components/tools/OmeroPy/test/integration/clitest/test_chown.py

This PR prevents data owners from chown'ing, that being a safe initial position following discussion with @joshmoore and @will-moore. Integration testing should suffice but feel free to experiment manually via the CLI to confirm.

prevent data owners from chowning

---

components/server/src/ome/security/basic/EventListenersFactoryBean.java

The helper methods for `EventListenersFactoryBean` are called from
`protected` methods, but are themselves declared `private`. This limits
the ability of any subclass to override the `protected` methods in any
meaningful way. Changing the scope of these methods to `protected` will
fix this.

Change signature to `protected` for helper methods

---

components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/browser/Browser.java
components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/browser/BrowserUI.java
components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/util/TreeCellRenderer.java

Fixes a bug introduced by #3927 ; instead showing the nodes "Loading..." and "Empty" a node with the same name like the dataset was displayed.
Test: Expand a dataset in treeviewer, make sure it shows a childnode named "Loading..." while loading the dataset content. Expand an empty dataset, make sure it shows one childnode named "Empty"

Fixed 'Empty' and 'Loading...' nodes

---

components/tools/OmeroPy/src/omero/rtypes.py
components/tools/OmeroPy/test/unit/test_rtypes.py

Rather than have consumers start using the essentially
hidden and more lenient RStringI implementation, this
makes the `omero.rtypes.rstring` wrapper as lenient of
non-`str` types, including `unicode`.
See: https://trello.com/c/hjCA90az/18-rfe-rtype-methods-should-auto-convert
Testing:
* unit tests should suffice to show whether or no this will cause any problems since the method is now **more** lenient.
* However, discussion is needed on whether the change in behavior (i.e. no longer throwing a `ValueError` on non-`str` arguments) is acceptable for 5.1.x.
cc: @will-moore @sbesson @chris-allan @aleksandra-tarkowska @ximenesuk

Make rstring more tolerant of non-`str`

---

etc/grid/templates.xml

A recent change to Java dropped support for several
SSL ciphers which were being used by Glacier2. Attempts
to login from OMERO.java including the CLI importer and
insight failed with the exception:
```
2015-07-20 21:25:02,718 1196       [      main] ERROR  formats.importer.cli.CommandLineImporter - Error during import process.
Ice.SecurityException: javax.net.ssl.SSLHandshakeException: DHPublicKey does not comply to algorithm constraints
at IceInternal.ConnectRequestHandler.getConnection(ConnectRequestHandler.java:240) ~[ice.jar:na]
at IceInternal.ConnectRequestHandler.sendRequest(ConnectRequestHandler.java:138) ~[ice.jar:na]
at IceInternal.Outgoing.invoke(Outgoing.java:66) ~[ice.jar:na]
at Ice._ObjectDelM.ice_isA(_ObjectDelM.java:30) ~[ice.jar:na]
at …
```

Disable SSL ciphers unsupported by Java 8u51 et al.

---

components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/browser/BrowserComponent.java

Fixes the issue that an empty dataset/project (and orphaned images folder) continuously showed a child node named "Loading..." instead of "Empty" noticed by @mtbc  and @pwalczysko  (the problem arose as a combination of the decoupling PR with #3968 ).

Empty node fix

---

components/tools/OmeroWeb/omeroweb/webclient/tree.py

https://trello.com/c/lvyNfeoJ/42-run-ordering
To test, find a Plate with multiple acquisitions- these should be ordered by name instead of by ID.

Order PlateAcquisitions by name in web

---

components/tools/OmeroWeb/omeroweb/webadmin/forms.py

Load OMERO.web. The keyboard focus should default to the username field so instead of clicking on it first you should be able to enter your username straightaway, hit tab, enter your password, and hit enter to login.

Autofocus on web login username field

---

components/blitz/resources/ome/services/blitz-servantDefinitions.xml
components/blitz/resources/ome/services/graph-rules/blitz-chmod-rules.xml
components/blitz/src/omero/cmd/graphs/Chgrp2I.java
components/blitz/src/omero/cmd/graphs/Chmod2I.java
components/blitz/src/omero/cmd/graphs/Chown2I.java
components/blitz/src/omero/cmd/graphs/Delete2I.java
components/blitz/src/omero/cmd/graphs/GraphRequestFactory.java
components/server/src/ome/services/graphs/GroupPredicate.java
components/server/src/ome/services/graphs/PermissionsPredicate.java

Allow downgrade to private groups even when a root-owned script has been run by a user in the group. To test: import `test_images_good/bd-pathway/2009-05-01_000/` into a read-only group, then downgrade the group to private.

enable more downgrade to private groups

---

components/blitz/src/omero/client.java
components/tools/OmeroCpp/src/omero/client.cpp
components/tools/OmeroCpp/src/omero/client.h
components/tools/OmeroPy/src/omero/clients.py

The OMERO.client implementations: omero/client.java,
omero/clients.py, and omero/client.{h,cpp} were all
setting a number of Ice properties regardless of what
the client had passed in. This seems overly draconian.
The primary reason for allowing it, however, is that
if there are issues with upstream libraries like Java
or OpenSSL, it may be necessary to work around issues
as seen in:
http://blog.openmicroscopy.org/tech-issues/2015/07/21/java-issue/
cc: @manics @ximenesuk -- closing gh-3970 / gh-3971 for the moment.

Make all Ice properties configurable

---

components/blitz/src/omero/cmd/graphs/SkipHeadI.java
components/tools/OmeroJava/test/integration/delete/MultiImageFilesetDeleteTest.java

Fixes that `SkipHead` requests would hang for clients if an invalid class name was given. Noticed by @ximenesuk in trying something like `bin/omero delete Image/RenderingDefs:1234` (it's actually "RenderingDef" singular). The error isn't yet pretty, but at least it's now promptly delivered.
This PR also reworks and extends integration tests: https://ci.openmicroscopy.org/job/OMERO-5.1-merge-integration-java/lastCompletedBuild/testngreports/integration.delete/MultiImageFilesetDeleteTest/ should still pass.

fix SkipHead hang

---

components/blitz/resources/ome/services/graph-rules/blitz-chown-rules.xml
components/tools/OmeroJava/test/integration/chown/PermissionsTest.java

Arises from experimentation by @ximenesuk and discussion with @pwalczysko. If chowning an image, in read-annotate and read-write groups the annotations and ROIs should not be chowned. Integration tests should continue to pass.

do not chown images' annotations and ROIs in read-annotate groups

---

build.xml
components/antlib/resources/global.xml
components/blitz/build.xml
components/common/build.xml
components/dsl/build.xml
components/insight/build.xml
components/model/build.xml
components/rendering/build.xml
components/romio/build.xml
components/server/build.xml
components/tests/build.xml
components/tests/ui/build.xml
components/tests/ui/library/java/build.xml
components/tools/OmeroCpp/build.xml
components/tools/OmeroFS/build.xml
components/tools/OmeroJava/build.xml
components/tools/OmeroM/build.xml
components/tools/OmeroPy/build.xml
components/tools/OmeroWeb/build.xml
components/tools/build.xml

Without gitversion.xml imported, any component-level
build like ant -f components/tools/OmeroJava/build.xml
will fail with a version of UNKNOWN. Top-level builds
do not show this behavior since gitversion.xml is imported.
Testing:
* download the appropriate src build (openmicroscopy*.zip)
* run `./build.py build-dev`
* run `./build.py -f components/tools/OmeroJava/build.xml -Dtestng.useDefaultListeners=true -Dtestreports.dir=target/reports/unit test`

Add gitversion.xml to all build.xml import blocks

---

components/tests/ui/build.xml
components/tests/ui/resources/robot.template
components/tests/ui/resources/web/tree.txt
components/tests/ui/testcases/web/delete_test.txt
components/tests/ui/testcases/web/rdef_test.txt
components/tests/ui/testcases/web/view_image.txt
components/tests/ui/testcases/web/webadmin_create_group_and_user.txt
components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/metadata_preview.html
components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/ome.viewport.js
components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/omero_image.js
components/tools/OmeroWeb/omeroweb/webgateway/templates/webgateway/viewport/omero_image.html
components/tools/OmeroWeb/omeroweb/webgateway/templatetags/common_tags.py

Following #3942 this should improve tests that requires reloading preview panel. It was mandatory to introduce token to identify content (it shouldn't have any effect on application), clarify channell background-colour as FF convert hex  to rgb. Introducing delay for chrome resolved general  timing issues that affected http session.

Improving rendering and delete tests

---

components/tools/OmeroWeb/omeroweb/webadmin/views.py
components/tools/OmeroWeb/omeroweb/webclient/webclient_gateway.py

This handles CmdError when attempting to chmod the group permissions.
See https://trac.openmicroscopy.org/ome/ticket/12973
Can reproduce this by an Owner performing a projection (or Channel_Offsets) of another users' image in Read-Annotate group, then trying to change the group to Private.
Test that you see the error:
- When Admin changes group permissions
- When Group owner changes permissions

Handle cmd error on downgrade 12973

---

components/insight/SRC/org/openmicroscopy/shoola/agents/util/ui/PermissionsPane.java

Fixes https://trac.openmicroscopy.org/ome/ticket/12974 for Insight. Try downgrading a group to Private and see if the warning makes sense for what actually happens.

chmod to private now does unlinking, so warn accordingly

---

components/tools/OmeroWeb/omeroweb/webadmin/templates/webadmin/group_form.html
components/tools/OmeroWeb/omeroweb/webadmin/templates/webadmin/group_form_owner.html

This is the web equivalent of https://github.com/openmicroscopy/openmicroscopy/pull/3989/ in Insight.
To test, try downgrading a non-Private group to Private:
- As owner of the group
- As Admin.
Should see same error as Insight (screenshot below).

Downgrade to private warnings updated. See #12974

---

components/tools/OmeroPy/src/omero/plugins/chown.py
components/tools/OmeroPy/src/omero/plugins/group.py

This PR adds a couple of warnings and clarifications to CLI usage `chown` and `group perms`.
/cc @pwalczysko @mtbc @joshmoore

CLI usage warnings

---

components/tools/OmeroWeb/omeroweb/webgateway/webgateway_cache.py

Due to unknown circumstances in https://trac.openmicroscopy.org/ome/ticket/12969 this PR adds more logging details.
To test open image viewer, check if rendered image is visible and see if you get similar in logs
```
2015-07-16 13:47:02,367  INFO [             webgateway.webgateway_cache] (proc.14963) _imageKey:636 rv: img_1/0/2717/%s-c1-166.75:2129.6875-0000FF-2-237.65:2489.0625-00FF00-3-605.6:1851.2000000000003-FF0000-mc-q0.9-r-t <type 'unicode'>
2015-07-16 13:47:02,367  INFO [             webgateway.webgateway_cache] (proc.14963) _imageKey:637 z: 35 <type 'unicode'>
2015-07-16 13:47:02,367  INFO [             webgateway.webgateway_cache] (proc.14963) _imageKey:638 t: 0 <type 'unicode'>
```
First line should contain ``%s``
cc: @joshmoore @kennethgillen

updating string formatting

---

history.txt

Will be staged at https://www.openmicroscopy.org/site/support/omero5.1-staging/users/history.html tomorrow.
Final decisions still needed on whether to include ROI preview fixes, gateway...

Version history for 5.1.3

---

etc/omero.properties

When I removed this warning from the docs, I missed that it was in the config file still too.

Updating ldap warning in config

---

components/tools/OmeroPy/test/integration/test_client_ctors.py

This fixes a broken test by setting the port.

Quick fix to Python client ctor test

---

components/insight/SRC/org/openmicroscopy/shoola/env/data/model/FileObject.java

ref : https://trac.openmicroscopy.org/ome/ticket/12976
Testing Instructions:
1) User File--> Open to open an image(any supported format for ImageJ).
2) Plugins-->OMERO-->Save Images To OMERO
This should allow you to add the image to the import dialog, and the import should progress without any issues post that.
Without this PR: The image will not get added to the import dialog and consequently cannot be imported into OMERO from ImageJ.
Note: Please open the image with File-->Open, opening the image with Bio-Formats will not give you this bug, (even without this PR).

Bug fix:  ImageJ save Images to OMERO (Null pointer Exception isNewImage)

---

.gitmodules
build.xml
components/antlib/resources/global.xml
docs/sphinx-api/build.xml
docs/sphinx-api/conf.py
docs/sphinx-api/rules.xml
docs/sphinx-api/sphinx.xml

Following https://github.com/openmicroscopy/openmicroscopy/pull/3931, this PR decouples the OMERO Sphinx documentation from the OMERO source code. This should simplify development and remove unnecessary cyclic dependencies when entering the release process.
Main changes are described below:
- the `docs/sphinx` submodule is removed
- the `release-docs` target is modified to build the API documentation (Java, Python, slice2html) only
- the components from the Sphinx submodule required for building the Sphinx API documentation are copied over (may require some cleanup in a follow-up PR).
/cc @hflynn

Sphinx documentation decoupling

---

.gitmodules
build.xml
components/antlib/resources/global.xml
docs/sphinx-api/build.xml
docs/sphinx-api/conf.py
docs/sphinx-api/rules.xml
docs/sphinx-api/sphinx.xml

This is the same as gh-4006 but rebased onto dev_5_1.
----
Following https://github.com/openmicroscopy/openmicroscopy/pull/3931, this PR decouples the OMERO Sphinx documentation from the OMERO source code. This should simplify development and remove unnecessary cyclic dependencies when entering the release process.
Main changes are described below:
- the `docs/sphinx` submodule is removed
- the `release-docs` target is modified to build the API documentation (Java, Python, slice2html) only
- the components from the Sphinx submodule required for building the Sphinx API documentation are copied over (may require some cleanup in a follow-up PR).
/cc @hflynn

Sphinx documentation decoupling (rebased onto dev_5_1)

---

components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/util/SaveResultsDialog.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/model/ResultsObject.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/ResultsSaver.java

Allow the user to specify the name of the file
To Test:
* Open an image in imageJ. Image saved in OMERO
* draw a region. 
* Go to Analyze> Measure
test 1:
* Enter a name for the measurement e.g. test
* Check that the name is preserved and the saved file is test.csv
test 2:
* Enter a name for the measurement e.g. test.foo
* Check that the name is preserved, the extension is remove and the saved file is test.csv
test 3:
* Keep the field blank
* Check that the default name is set i.e. ImageJ-NameOfImage-Date.csv

Ij measurement

---

components/tools/OmeroWeb/omeroweb/webstart/templates/webstart/includes/webstart_insight_script.html

Regarding what @rleigh-dundee requested:
> If I enter the URL directly, chrome downloads it without prompting, but if I then click on the download link it fires up webstart.  Not sure why it doesn't do that automatically, but certainly exposing it would help rather than hinder the user even if it's not 100% automated.
test all web browsers if webstart starts up nicely

replacing javadeploy webstart button with direct link

---

components/tools/OmeroPy/src/omero/plugins/sessions.py
components/tools/OmeroPy/test/integration/clitest/test_sessions.py

See https://trello.com/c/dyRbaNiM/19-key-omero-sessions-key
Implement a simple RFE to return the current session key via the CLI. To test this PR:
- check the new integration test is green
- from the command line check the output of `bin/omero sessions key` is null if logged out and the current session key if logged in
- test a simple workflow reusing the session key:
```
bin/omero login USER@HOSTNAME
bin/omero -C -s HOSTNAME -k $(bin/omero sessions key) COMMAND
```

CLI: add sessions key

---

components/tools/OmeroWeb/omeroweb/webstart/templates/webstart/includes/webstart_insight_script.html

This is the same as gh-4002 but rebased onto dev_5_1.
----
Regarding what @rleigh-dundee requested:
> If I enter the URL directly, chrome downloads it without prompting, but if I then click on the download link it fires up webstart.  Not sure why it doesn't do that automatically, but certainly exposing it would help rather than hinder the user even if it's not 100% automated.
test all web browsers if webstart starts up nicely

replacing javadeploy webstart button with direct link (rebased onto dev_5_1)

---

components/tools/bump_bf_version.py

This script should simplify the bump of the Bio-Formats version number to either a release (x.y.z) or a snapshot (x.y.z-SNAPSHOT) version. Both the version number under `etc/omero.properties` and the resolver under `etc/local.properties.example` should be updated.
To test this PR, try:
- `python bump_bf_version.py x.y.z` (should set `version.bioformats=x.y.z` under `etc/omero.properties` and `ome-resolver` under `etc/local.properties.example`)
- `python bump_bf_version.py x.y.z-SNAPSHOT` (should set `version.bioformats=x.y.z-SNAPSHOT`  under `etc/omero.properties` and `ome-simple-artifactory` under `etc/local.properties.example`)
- `python bump_bf_version.py x.y` should fail with an informative message

Add simple utility script to bump Bio-Formats version

---

components/model/src/ome/model/units/GenericEnumType.java
components/model/src/ome/model/units/UNITS.java
components/server/src/ome/services/graphs/GraphPathReport.java

Generates https://github.com/openmicroscopy/ome-documentation/pull/1251 which is staged at http://www.openmicroscopy.org/site/support/omero5.2-staging/developers/Model/EveryObject.html. There should now be links from dimensioned quantities to reasonable units Javadoc.
Also shortens anchor names.
--rebased-to #4027

have model object glossary link unit properties to best Javadoc

---

components/model/src/ome/model/units/GenericEnumType.java
components/model/src/ome/model/units/UNITS.java
components/server/src/ome/services/graphs/GraphPathReport.java

Generates openmicroscopy/ome-documentation#1260 which is staged at http://www.openmicroscopy.org/site/support/omero5.1-staging/developers/Model/EveryObject.html. There should now be links from dimensioned quantities to reasonable units Javadoc.
Also shortens anchor names.
--rebased-from #4010

have model object glossary link unit properties to best Javadoc (rebased from develop)

---

build.xml
docs/hudson/OMERO.sh

Addresses @rleigh-dundee's comment https://github.com/openmicroscopy/openmicroscopy/pull/4006#issuecomment-127222532 and modifies the CI build command to use `build-dev`.
- check the https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-merge-build/ job is still green
- run `./build.py clean release-sphinx-api` and check the API doc is correctly generated.

Fix release-sphinx-api target

---

components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/util/SaveResultsDialog.java

Fix saving of rois when all windows option is selected. Problem reported by @bramalingam 
To test:
* Open a mif in imageJ using the B-F plugin
* Select some of the series.
* Save the images
* Draw roi on the image in imageJ. Add them as overlay
* Select the "Save the rois". Select the "all image windows" in the Saving dialog
* Check that no dialog pops up asking to import images not already imported.

mif all windows

---

components/blitz/src/ome/services/blitz/repo/ManagedRepositoryI.java
components/blitz/src/omero/cmd/graphs/GraphRequestFactory.java
components/server/src/ome/services/graphs/GraphPathBean.java
components/server/src/ome/services/graphs/GraphTraversal.java
etc/local.properties.example

Should be no change in behavior, largely tested by if the code compiles at all.
--no-rebase as Java 6 does not offer `ReflectiveOperationException`

use narrower reflective operation exception

---

components/blitz/resources/omero/cmd/Graphs.ice
components/blitz/src/omero/cmd/RequestObjectFactoryRegistry.java
components/blitz/src/omero/cmd/graphs/GraphRequestFactory.java
components/blitz/src/omero/cmd/graphs/LegalGraphTargetsI.java
components/tools/OmeroJava/test/integration/LegalGraphTargetsTest.java

Adds a new `LegalGraphsTarget` request that enables querying of which model object classes are legal targets for `Chgrp2`, `Chmod2`, `Chown2`, `Delete2`. Tested automatically by https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-java/lastCompletedBuild/testngreports/integration/LegalGraphTargetsTest/. Cc: @ximenesuk.
--no-rebase

Graph targets query

---

components/insight/SRC/org/openmicroscopy/shoola/env/data/OMEROGateway.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/Requests.java
components/tools/OmeroPy/src/omero/gateway/__init__.py
components/tools/OmeroPy/src/omero/plugins/group.py
components/tools/OmeroWeb/omeroweb/webclient/webclient_gateway.py

Integration tests should still pass. Change of group permissions should still work from all clients.
Also adds a host of Java convenience methods for constructing Chmod2 requests.
--no-rebase as the 5.1.0 server does not offer Chmod2

move more uses of legacy Chmod to new Chmod2

---

components/tools/OmeroPy/src/omero/plugins/sessions.py
components/tools/OmeroPy/test/integration/clitest/test_sessions.py

This is the same as gh-4005 but rebased onto develop.
----
See https://trello.com/c/dyRbaNiM/19-key-omero-sessions-key
Implement a simple RFE to return the current session key via the CLI. To test this PR:
- check the new integration test is green
- from the command line check the output of `bin/omero sessions key` is null if logged out and the current session key if logged in
- test a simple workflow reusing the session key:
```
bin/omero login USER@HOSTNAME
bin/omero -C -s HOSTNAME -k $(bin/omero sessions key) COMMAND
```

CLI: add sessions key (rebased onto develop)

---

components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterComponent.java
components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterModel.java
components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/util/SaveResultsDialog.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/model/ResultsObject.java
components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/ResultsSaver.java

This is the same as gh-4004 but rebased onto dev_5_1.
----
Allow the user to specify the name of the file
To Test:
* Open an image in imageJ. Image saved in OMERO
* draw a region. 
* Go to Analyze> Measure
test 1:
* Enter a name for the measurement e.g. test
* Check that the name is preserved and the saved file is test.csv
test 2:
* Enter a name for the measurement e.g. test.foo
* Check that the name is preserved, the extension is remove and the saved file is test.csv
test 3:
* Keep the field blank
* Check that the default name is set i.e. ImageJ-NameOfImage-Date.csv

Ij measurement (rebased onto dev_5_1)

---

components/tools/OmeroPy/test/integration/test_rawpixelsstore.py

With the Ice3.5 and Python 2.6 the following test fails (due to changes in Ice effectively), see:
https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-integration-python/50/testReport/OmeroPy.test.integration.test_rawpixelsstore/TestTiles/testTiles/
This PR skips that test unless Python is 2.7 or higher. This commit can be reverted once support of Python 2.6 is removed. The awkward mport is due to `flake8`.
The above test should be skipped on that ci node, it should pass locally with Python 2.7 and Ice 3.5.
--no-rebase

Skip testTiles if Python is not 2.7 or above

---

components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterComponent.java
components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterModel.java

The name was not taken into account for newly imported
images.
To test:
* open an image from local disk and go through the workflow (create ROI, save Analyse > Measure followed by Save Results to OMERO) 
* Enter a name of the results csv file.
* Check that the name is kept
see gh-4025
--no-rebase

measurement name

---

components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/GraphPane.java

This is the same as gh-4059 but rebased onto dev_5_1.
----
Tiny fix for Ticket [12994](http://trac.openmicroscopy.org/ome/ticket/12994).
- Draw a ROI
- Open Intensity view
- Deselect all channels and make sure an empty histogram plot is shown when no channel is selected (before: Insight crashed)

Draw empty histogram if there's no data (rebased onto dev_5_1)

---

components/blitz/src/omero/gateway/Connector.java

See Ticket [12972](http://trac.openmicroscopy.org/ome/ticket/12972)
Previously if a session for another user was created a zero timeout was set, with this PR now the same timeout as the existing session is used.
Test: Code review, check that the import as other user (will initiate a sudo session) still works.

sudo sessions timeout

---

components/insight/SRC/org/openmicroscopy/shoola/util/ui/JXTaskPaneContainerSingle.java

Fix for [Ticket 12997](https://trac.openmicroscopy.org/ome/ticket/12997)
The bug was introduced with #3927 , it allowed collapsing of all task panes, which then were re-layout in the center of the component. With this PR now, it should not be possible anymore to collapse all task panes (like it was before #3927 ).

Don't allow collapsing of all task panes

---

components/blitz/resources/omero/cmd/Graphs.ice
components/tools/OmeroPy/src/omero/cli.py
components/tools/OmeroPy/src/omero/plugins/group.py
components/tools/OmeroPy/src/omero/plugins/tag.py
components/tools/OmeroPy/test/integration/clitest/test_tag.py

This is a partial rebase of gh-4061 The one difference is that the `--list` option for `delete`m etc., is handled rather than suppressed.
--rebased-from #4061
Testing
-------
```
omero delete --help
```
should not show the --list-details options. However,
```
omero delete --list
omero delete --list-details
```
should both work and give a list of legal targets for this command (and `chgrp`).
The command
```
omero group perms
```
should give a helpful message when the user does not have permission to chnage the group permissions.
Three commits remove the prompt if no description is provided, this brings the CLI in line with other clients. To test:
```
omero tag create
omero tag createset
```
should both prompt for a name if not provided, via the --name option, but not a description if not …

A few minor CLI fixes (dev)

---

components/tools/OmeroPy/src/omero/cli.py
components/tools/OmeroPy/src/omero/plugins/group.py
components/tools/OmeroPy/src/omero/plugins/tag.py
components/tools/OmeroPy/test/integration/clitest/test_tag.py

This PR is a holder for a few minor CLI fixes.
Partially
--rebased-to #4076
The first is: prevent CLI chmod from timing out when downgrading to private. See https://trello.com/c/GZCqaV5D/35-chmod-on-cli-not-usable  This fix uses the same fix as in https://github.com/openmicroscopy/openmicroscopy/pull/3853 To test a group that has some complexity: users, data, etc. should be downgraded to private on the commandline:
```
omero group perms --id XX --perms "rw----"
```

A few minor CLI fixes
