openmicroscopy/openmicroscopy

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/util/FilesetInfoDialog.java
This is the same as gh-4070 but rebased onto dev_5_1.
----
See [Ticket 12905](https://trac.openmicroscopy.org/ome/ticket/12905)
Test: Check the File path info dialog shows the correct number of files (compare with OMERO.Web)
=> Fixed wrong file count (rebased onto dev_5_1)

components/insight/SRC/org/openmicroscopy/shoola/agents/util/SelectionWizardUI.java
Tiny fix for [Ticket 12300](https://trac.openmicroscopy.org/ome/ticket/12300) , has to be tested on Windows.
Try to add tags to an object, which opens the Tags dialog. The "Filter" text field should have the focus, and when start typing straight away the default text "Filter" should get removed (before: typing started after the text).
=> Make sure default "Filter" text is selected

components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/GraphPane.java
Tiny fix for Ticket [12994](http://trac.openmicroscopy.org/ome/ticket/12994).
- Draw a ROI
- Open Intensity view
- Deselect all channels and make sure an empty histogram plot is shown when no channel is selected (before: Insight crashed)
=> Draw empty histogram if there's no data

components/insight/SRC/org/openmicroscopy/shoola/util/ui/JXTaskPaneContainerSingle.java
This is the same as gh-4073 but rebased onto dev_5_1.
----
Fix for [Ticket 12997](https://trac.openmicroscopy.org/ome/ticket/12997)
The bug was introduced with #3927 , it allowed collapsing of all task panes, which then were re-layout in the center of the component. With this PR now, it should not be possible anymore to collapse all task panes (like it was before #3927 ).
=> Don't allow collapsing of all task panes (rebased onto dev_5_1)

components/tools/OmeroJava/test/integration/delete/AnnotationDeleteTest.java
http://trac.openmicroscopy.org/ome/ticket/12998 made me wonder if there is some problem with tag set deletion. Integration test coverage is poor so this PR adds a relevant test whose result one finds at https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-java/lastCompletedBuild/testngreports/integration.delete/AnnotationDeleteTest/.
--no-rebase
=> add integration test for tag set deletion

components/tools/OmeroWeb/omeroweb/webgateway/templates/webgateway/viewport/omero_image.html
See http://trac.openmicroscopy.org/ome/ticket/12983
This ensures that the "Show ROIs" button is not enabled until the image has loaded since it fails if used before then (noted on Big Images in particular).
To test:
- Open a Big Image with ROIs in the main image viewer.
- Note that the "Show ROIs" link doesn't become enabled until the viewer has loaded.
- Try to click it before and after loading. Should only work after loading and ROIs should load OK.
This has been cherry-picked to the jstree_2015 branch:
https://github.com/will-moore/openmicroscopy/commit/a4876000c03f8e2414da5e552072bf5ae73d1816
--no-rebase
=> Enable 'Show ROIs' after loaded

components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/browser/BrowserComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/browser/BrowserUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/util/TreeCellRenderer.java, components/insight/SRC/org/openmicroscopy/shoola/agents/util/browser/PartialNameVisitor.java, components/insight/SRC/org/openmicroscopy/shoola/agents/util/browser/TreeImageDisplay.java
Re-add control to display the  full name  w/o having to expand the
left hand pane.
To test: 
* Log in as any user
* Click on the "Abc" button to display the full name
* Check that the full name is displayed
This PR brings back a feature removed in gh-3770
cc @gusferguson @mporter-gre
=> Display full name

build.xml, components/blitz/resources/header.txt
This trivial PR simply changes "Api" in titles in public API docs to "API".
--no-rebase
=> render "API" as an acronym in docs

components/blitz/src/omero/cmd/graphs/ChildOptionsPolicy.java, components/tools/OmeroJava/test/integration/delete/AnnotationDeleteTest.java
In investigating http://trac.openmicroscopy.org/ome/ticket/12998 @ximenesuk uncovered an issue with how the server processes child options. This PR adjusts the behavior and expands an integration test to cover the case. Testing: both https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-java/lastCompletedBuild/testngreports/integration.delete/AnnotationDeleteTest/ and @ximenesuk should be happy.
--rebased-to #4098
=> Add tag set test

components/tools/OmeroWeb/omeroweb/feedback/views.py, components/tools/OmeroWeb/omeroweb/settings.py
This PR improves logging by logging full request and status code 
To test go to:
- http://host/weberror/error_404/
- http://host/weberror/error_500/
and check if OMEROweb_brokenrequest.log contains entire REQUEST OBJECT like:
```
2015-08-24 16:42:39,349 ERROR [                          django.request] (proc.34016) handle_uncaught_exception:226 HTTP 500 <WSGIRequest
path:/weberror/error_500/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
...
```
note that OMEROweb.log will only contains python stacktrace and HTTP 404 as a WARNING
cc @manics @sbesson
=> web logging

components/insight/SRC/org/openmicroscopy/shoola/agents/util/SelectionWizardUI.java
This is the same as gh-4063 but rebased onto dev_5_1.
----
Tiny fix for [Ticket 12300](https://trac.openmicroscopy.org/ome/ticket/12300) , has to be tested on Windows.
Try to add tags to an object, which opens the Tags dialog. The "Filter" text field should have the focus, and when start typing straight away the default text "Filter" should get removed (before: typing started after the text).
=> Make sure default "Filter" text is selected (rebased onto dev_5_1)

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/includes/name.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/metadata_general.html
See http://trac.openmicroscopy.org/ome/ticket/12958
Check that the right panel for plate Run is consistent with other objects and doesn't mention "Acquisition".
=> Fix display of 'Run' in right panel. See #12958

components/tools/OmeroPy/src/omero/cli.py
See: https://trac.openmicroscopy.org/ome/ticket/12979 for an example of the unhelpful message.
Changing the exception raised allows `argparse` to interpret the cause of the exception and provide helpful output. For background see discussion at http://bugs.python.org/issue9509#msg127007 This change affects three plugins. 
Testing
-------
```
omero export Image:1 --file foo.ome.tif
omero export Image:1 --file foo.ome.tif
```
The second call should display a file exists error message.
```
omero admin cleanse /nonexistent --dry-run
omero admin cleanse file.name --dry-run
```
Should display directory does not exist and not a directory messages respectively.
```
omero config set --file nonexistent.xml
omero config load nonexistent.xml
omero config parse --file nonexistent.xml
```
Should all …
=> Tidy up some CLI file errors

components/tools/OmeroPy/test/integration/clitest/test_delete.py
See gh-4097 the Python delete tests should pass with gh-4098 in place.
--depends-on #4098
--rebased-from #4097
=> Add and amend delete tests (dev 5.1)

components/tools/OmeroPy/test/integration/clitest/test_delete.py
This PR adds some tag set delete tests to reflect the behavious now expected by gh-4094 following the bug fix there. It also fixes and renames a test which should have failed but was passing due to the same issue, see https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-integration-python/61/testReport/OmeroPy.test.integration.clitest.test_delete/TestDelete/testIncludeExclude/ Finally, a couple of names and comments have been changed at the same time just to make the tests' intentions clearer.
The integration tests should pass.
--depends-on #4094 
--rebased-to #4100
=> Add and amend delete tests

components/tools/OmeroCpp/test/integration/chgrp.cpp, components/tools/OmeroCpp/test/integration/delete.cpp, components/tools/OmeroCpp/utils/chgrp.cpp
C++ integration tests should pass even with gcc 4.6. Cc: @rleigh-dundee.
--no-rebase because a bug in gcc 4.4 requires the namespace specifications
=> remove workaround for namespace bug in old gcc

components/server/src/ome/logic/PojosImpl.java, components/tools/OmeroJava/test/integration/PojosServiceTest.java
This PR fixes the loading issues of "orphaned" datasets or plates.
Some datasets (resp. plates) were returned as orphaned even if they were linked to a project (resp. screen)
This was the cases when
* user 1 has a project p1 and add dataset d2. d2 is owned by user-2
* user-2 logs in and d2 was returned as "orphaned" since it was not linked to any project owned by p1
See https://trello.com/c/6IztFNAq/29-orphaned-dataset-in-another-s-project
Tests have been added to cover that use case and all integration tests (PojosService) should remain green
cc @will-moore @pwalczysko
=> Data loading

components/blitz/src/omero/cmd/graphs/ChildOptionsPolicy.java, components/tools/OmeroJava/test/integration/delete/AnnotationDeleteTest.java
In graph operations child options previously had a bug such that they could affect how parents were treated. Intended child option behaviors are documented at http://downloads.openmicroscopy.org/omero/5.1.3/api/slice2html/omero/cmd/graphs.html. This PR fixes the bug and adds integration test coverage accordingly: make sure that the test looks sensible and check that https://ci.openmicroscopy.org/job/OMERO-5.1-merge-integration-java/lastCompletedBuild/testngreports/integration.delete/AnnotationDeleteTest/ passes.
--rebased-from #4089
--rebased-from #4094
=> have child options ignore parents (rebased from develop)

components/tools/OmeroPy/src/omero/plugins/web.py, components/tools/OmeroPy/test/unit/clitest/reference_templates/nginx-wsgi-development-withoptions.conf, components/tools/OmeroPy/test/unit/clitest/reference_templates/nginx-wsgi-development.conf, components/tools/OmeroPy/test/unit/clitest/test_web.py, components/tools/OmeroWeb/omeroweb/settings.py
This PR deprecats FastCGI deployment and improves WSGI commands
**Deprecation:**
**Make sure ``bin/omero config set omero.web.application_server`` is empty.**
To test:
- ``$ bin/omero web config nginx-development``
- ``$ bin/omero web config nginx``
- ``$ bin/omero web start ``
- ``$ bin/omero web status ``
gives:``WARNING: FastCGI support is deprecated and will be removed in OMERO 5.2. Install gunicorn and update config.``
**Improvement:**
To test:
- ``$ bin/omero web stop`` should show ``OMERO.web FASTCGI workers (PID ...) killed.`` assuming you continue.
- set ``bin/omero config set omero.web.application_server wsgi-tcp``**
- check if ``$ bin/omero web start -h`` shows new params
```
--workers WORKERS                     The number of worker processes for handling requests. …
```
=> Deprecatig fastcgi

components/server/src/ome/logic/PojosImpl.java, components/tools/OmeroJava/test/integration/PojosServiceTest.java
This is the same as gh-4065 but rebased onto dev_5_1.
----
This PR fixes the loading issues of "orphaned" datasets or plates.
Some datasets (resp. plates) were returned as orphaned even if they were linked to a project (resp. screen)
This was the cases when
* user 1 has a project p1 and add dataset d2. d2 is owned by user-2
* user-2 logs in and d2 was returned as "orphaned" since it was not linked to any project owned by p1
See https://trello.com/c/6IztFNAq/29-orphaned-dataset-in-another-s-project
Tests have been added to cover that use case and all integration tests (PojosService) should remain green
cc @will-moore @pwalczysko
=> Data loading (rebased onto dev_5_1)

components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/browser/BrowserComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/browser/BrowserUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/util/TreeCellRenderer.java, components/insight/SRC/org/openmicroscopy/shoola/agents/util/browser/PartialNameVisitor.java, components/insight/SRC/org/openmicroscopy/shoola/agents/util/browser/TreeImageDisplay.java
This is the same as gh-4039 but rebased onto develop.
----
Re-add control to display the  full name  w/o having to expand the
left hand pane.
To test: 
* Log in as any user
* Click on the "Abc" button to display the full name
* Check that the full name is displayed
This PR brings back a feature removed in gh-3770
cc @gusferguson @mporter-gre
=> Display full name (rebased onto develop)

components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewerComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewerModel.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/RenderingSettingsSaver.java
Fixes two minor issues with rendering settings:
- Copy the rendering settings from an image. "Paste and Save" them on to other images. Make sure a warning dialog is shown (like it is for other actions e. g. "Set Imported and Save"
- Modify the rendering settings of an image in the preview panel, *do not* save them but copy them. Select the dataset the image belongs to and trigger a "Paste and Save" action. Make sure that the rendering settings of all compatible images are modified accordingly *including* the image from which you copied the rendering settings.
- Do the same again, but now "Paste and Save" onto some other images excluding the image the rendering settings were copied from. Make sure this image does *not* change.
=> Rendering settings fixes

components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewerComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewerModel.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/RenderingSettingsSaver.java
This is the same as gh-4055 but rebased onto dev_5_1.
----
Fixes two minor issues with rendering settings:
- Copy the rendering settings from an image. "Paste and Save" them on to other images. Make sure a warning dialog is shown (like it is for other actions e. g. "Set Imported and Save"
- Modify the rendering settings of an image in the preview panel, *do not* save them but copy them. Select the dataset the image belongs to and trigger a "Paste and Save" action. Make sure that the rendering settings of all compatible images are modified accordingly *including* the image from which you copied the rendering settings.
- Do the same again, but now "Paste and Save" onto some other images excluding the image the rendering settings were copied from. Make sure this image does *not* change.
=> Rendering settings fixes (rebased onto dev_5_1)

components/blitz/src/omero/util/IceMapper.java, components/model/src/ome/util/PermDetails.java, components/server/src/ome/logic/QueryImpl.java, components/tools/OmeroPy/test/integration/test_permissions.py
Since no solution for properly loading a Permissions object
when the target of a project query (`select d.details.permissions`),
this workaround is being added which will allow wrapping a
object in HQL (`select new ome.util.PermDetails(d)`) to produce
the desired effect.
Primary effect of this PR is that the test_permissions.py tests which were marked xfail should start passing:
```
components/tools/OmeroPy$ ./setup.py test -t test/integration/test_permissions.py -k Projection -svx
...
test/integration/test_permissions.py::TestPermissionProjections::testProjectionPermissions[rw-----admin-admin] PASSED
test/integration/test_permissions.py::TestPermissionProjections::testProjectionPermissions[rw-----admin-owner] PASSED
test/integration/test_permissions.py::TestPermissionProjections::testProj …
```
=> Add wrapper class for loading permission info (Fix #12474)

components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/ome.webclient.actions.js, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/base/includes/toolbar_forms.html
This fixes the display of the warning that you will delete another user's data.
To test, try to delete your own data.
- You should not see any warning that you will delete anyone else's data.
- Delete someone else's data (need read-write permissions) and check that you DO see the warning in the delete confirm dialog.
This is fixed independently in jstree_2015 branch.
--no-rebase
=> Fix delete notOwned warning

components/insight/SRC/org/openmicroscopy/shoola/agents/dataBrowser/actions/DownloadAction.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/Editor.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorControl.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/actions/DownloadAction.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewerComponent.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/OMEROGateway.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/OmeroDataService.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/OmeroDataServiceImpl.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/model/DownloadArchivedActivityParam.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/MetadataHandlerView.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/MetadataHandlerViewImpl.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/ArchivedImageLoader.java, components/insight/SRC/org/openmicroscopy/shoola/env/ui/ArchivedLoader.java, components/insight/SRC/org/openmicroscopy/shoola/env/ui/DownloadArchivedActivity.java, components/insight/TEST/org/openmicroscopy/shoola/env/data/NullOmeroPojoService.java
See Trello card [Download multiple files - preserve directories](https://trello.com/c/asMv2nvz/27-download-multiple-files-preserve-directories)
With this PR original files will be downloaded as they are (not zipped like before) and their original folder structure will be preserved. Test: Download some original files and make sure the folder structure is correct (see File Path info dialog, folder structure should match the path in the managed repository).
=> Don't zip and preserve original paths when downloading images

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/AcquisitionDataUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/AnnotationDataUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/DocComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/Editor.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/GeneralPaneUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/view/MetadataViewer.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/view/MetadataViewerComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewerComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/util/ui/ScriptingDialog.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/model/ScriptObject.java
Same as #3993 just for Insight
Test:
- Install @emilroz  's script which uses file annotations: https://github.com/emilroz/omero-user-scripts/blob/populate_metadata_fa_additions/util_scripts/Populate_Metadata.py 
- Add some file annotations to a plate
- Select the plate and some file annotations and run the script, which should open the script dialog
- Make sure the Plate ID and the the file annotations IDs are set in the dialog
- Run the script. Will fail, but in 'Info' in the activities popup you should see, that the parameters were passed correctly to the script.
- Additional test: Run some other scripts, to make sure the changes didn't break the script dialog for other scripts.
=> Add ability to run scripts against fa's from OMERO.Insight

components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/util/model/AnalysisStatsWrapper.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/GraphPane.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/IntensityView.java, components/insight/SRC/org/openmicroscopy/shoola/env/rnd/roi/AbstractROIShapeStats.java, components/insight/SRC/org/openmicroscopy/shoola/env/rnd/roi/ROIAnalyser.java, components/insight/SRC/org/openmicroscopy/shoola/env/rnd/roi/ROIShapeStats.java, components/insight/SRC/org/openmicroscopy/shoola/env/rnd/roi/ROIShapeStatsSimple.java, components/insight/SRC/org/openmicroscopy/shoola/env/rnd/roi/ROIStats.java
See [Ticket 12995](https://trac.openmicroscopy.org/ome/ticket/12995)
For analyzing ROI shapes a LinkedHashMap was used, which consumed a lot of memory. This PR replaces it with a double array and a list of points. It also removes some unnecessary duplications of data structures which in total significantly reduces the memory usage.
Test: Analyze some ROIs: Make sure the histogram plots and intensity values are still calculated correctly. Analyze a rectangular ROI same size or bigger as the one mentioned in ticket (250x280px) on a multi channel image, make sure Insight doesn't crash and it doesn't take several minutes for the graphs to appear.
=> ROI tool OutOfMemory

components/tools/OmeroWeb/omeroweb/feedback/views.py, components/tools/OmeroWeb/omeroweb/settings.py
This is the same as gh-4090 but rebased onto develop.
----
This PR improves logging by logging full request and status code 
To test go to:
- http://host/weberror/error_404/
- http://host/weberror/error_500/
and check if OMEROweb_brokenrequest.log contains entire REQUEST OBJECT like:
```
2015-08-24 16:42:39,349 ERROR [                          django.request] (proc.34016) handle_uncaught_exception:226 HTTP 500 <WSGIRequest
path:/weberror/error_500/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
...
```
note that OMEROweb.log will only contains python stacktrace and HTTP 404 as a WARNING
cc @manics @sbesson
=> web logging (rebased onto develop)

components/tools/OmeroPy/src/omero/plugins/web.py, components/tools/OmeroPy/test/unit/clitest/reference_templates/nginx-wsgi-development-withoptions.conf, components/tools/OmeroPy/test/unit/clitest/reference_templates/nginx-wsgi-development.conf, components/tools/OmeroPy/test/unit/clitest/test_web.py, components/tools/OmeroWeb/omeroweb/settings.py
This is the same as gh-4056 but rebased onto develop.
----
This PR deprecats FastCGI deployment and improves WSGI commands
**Deprecation:**
**Make sure ``bin/omero config set omero.web.application_server`` is empty.**
To test:
- ``$ bin/omero web config nginx-development``
- ``$ bin/omero web config nginx``
- ``$ bin/omero web start ``
- ``$ bin/omero web status ``
gives:``WARNING: FastCGI support is deprecated and will be removed in OMERO 5.2. Install gunicorn and update config.``
**Improvement:**
To test:
- ``$ bin/omero web stop`` should show ``OMERO.web FASTCGI workers (PID ...) killed.`` assuming you continue.
- set ``bin/omero config set omero.web.application_server wsgi-tcp``**
- check if ``$ bin/omero web start -h`` shows new params
```
--workers WORKERS                     The …
```
=> Deprecatig fastcgi (rebased onto develop)

components/tools/OmeroPy/src/omero/plugins/web.py, components/tools/OmeroPy/test/unit/clitest/reference_templates/apache-wsgi-withoptions.conf, components/tools/OmeroPy/test/unit/clitest/reference_templates/apache-wsgi.conf, components/tools/OmeroPy/test/unit/clitest/reference_templates/nginx-wsgi-development-withoptions.conf, components/tools/OmeroPy/test/unit/clitest/reference_templates/nginx-wsgi-withoptions.conf, components/tools/OmeroPy/test/unit/clitest/test_web.py, etc/templates/apache-wsgi.conf.template, etc/templates/nginx-wsgi-development.conf.template, etc/templates/nginx-wsgi.conf.template
This PR customize wsgi application name based on prefix.
To test:
- **NGINX config:**
- no prefix:
- ``omero config set omero.web.application_server wsgi-tcp``
- ``omero web config nginx-wsgi``
```
upstream omeroweb_server {
...
location @proxy_to_app {
...
proxy_pass http://omeroweb_server;
```
- custom prefix ``/myprefix-123``:
- ``omero config set omero.web.prefix '/myprefix-123'``
-  should change ``omeroweb_server`` to ``omeroweb_myprefix123``
*NOTE: all non alphanumeric characters will be removed from the prefix*
- **APACHE config:**
- no prefix:
- ``omero config set omero.web.application_server wsgi``
- ``omero web config apache-wsgi``
```
<VirtualHost _default_:80>
...
WSGIDaemonProcess omeroweb_server ...
WSGIProcessGroup omeroweb_server
```
- custom prefix ``/myprefix-123``:
- …
=> Custom Wsgi app name

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/Editor.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/ArchivedImageLoader.java
Fix warning noticed during today's build
see https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-merge-build/ICE=3.5,jdk=8_LATEST,label=octopus/77/consoleText
To test:
make sure that there is no warnings
=> Insight minor javadoc

components/tools/OmeroPy/src/omero/plugins/web.py, components/tools/OmeroWeb/omeroweb/settings.py
This PR for the following error and change APPLICATION_SERVER_PORT from string to number.
```
Starting OMERO.web... Traceback (most recent call last):
File "/Users/ola/OMERO/openmicroscopy/dist/bin/omero", line 125, in <module>
rv = omero.cli.argv()
File "/Users/ola/OMERO/openmicroscopy/dist/lib/python/omero/cli.py", line 1432, in argv
cli.invoke(args[1:])
File "/Users/ola/OMERO/openmicroscopy/dist/lib/python/omero/cli.py", line 946, in invoke
stop = self.onecmd(line, previous_args)
File "/Users/ola/OMERO/openmicroscopy/dist/lib/python/omero/cli.py", line 1023, in onecmd
self.execute(line, previous_args)
File "/Users/ola/OMERO/openmicroscopy/dist/lib/python/omero/cli.py", line 1105, in execute
args.func(args)
File "/Users/ola/OMERO/openmicroscopy/dist/lib/python/omero/plugins/web.py", …
```
=> PORT number

components/tools/OmeroPy/src/omero/plugins/web.py, components/tools/OmeroWeb/omeroweb/settings.py
This is the same as gh-4119 but rebased onto develop.
----
This PR for the following error and change APPLICATION_SERVER_PORT from string to number.
```
Starting OMERO.web... Traceback (most recent call last):
File "/Users/ola/OMERO/openmicroscopy/dist/bin/omero", line 125, in <module>
rv = omero.cli.argv()
File "/Users/ola/OMERO/openmicroscopy/dist/lib/python/omero/cli.py", line 1432, in argv
cli.invoke(args[1:])
File "/Users/ola/OMERO/openmicroscopy/dist/lib/python/omero/cli.py", line 946, in invoke
stop = self.onecmd(line, previous_args)
File "/Users/ola/OMERO/openmicroscopy/dist/lib/python/omero/cli.py", line 1023, in onecmd
self.execute(line, previous_args)
File "/Users/ola/OMERO/openmicroscopy/dist/lib/python/omero/cli.py", line 1105, in execute
args.func(args)
File …
```
=> PORT number (rebased onto develop)

components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/ome.chgrp.js
This fixes issue with Move to group dialog box. URLs were missing trailing slash and redirected. Redirection was blocked loading mixed active content.
```
GET https://trout.o.org/integration/webclient/fileset_check/chgrp?Project=191 301 MOVED PERMANENTLY
GET https://trout.o.org/integration/webclient/load_chgrp_groups?Project=191 301 MOVED PERMANENTLY
Blocked loading mixed active content "http://trout.o.org/integration/webclient/fileset_check/chgrp/?Project=..."
Blocked loading mixed active content "http://trout.o.org/integration/webclient/load_chgrp_groups/?Project=..."
```
URL:
```
url(r'^load_chgrp_groups/$',
views.load_chgrp_groups,
name="load_chgrp_groups"),  # Query E.g. ?Image=1,2&Dataset=3
```
They must be consistent. By default …
=> Fixing trailing slash

components/tools/OmeroPy/src/omero/plugins/obj.py, components/tools/OmeroPy/test/integration/clitest/test_obj.py
See https://trello.com/c/5M0gWeCw/43-omero-obj-new-commands This addresses just the first bullet point.
```
omero obj get Object:XX field
```
should return the value of a simple field, name, description, etc. More complex fields should cause an error.
The one modified test, which checks one use of `get` should pass.
=> Add get subcommand to CLI obj command

components/blitz/src/omero/client.java, components/blitz/src/omero/cmd/CallContext.java, components/blitz/src/omero/cmd/CmdCallbackI.java, components/blitz/src/omero/cmd/HandleI.java, components/blitz/src/omero/cmd/Helper.java, components/blitz/src/omero/cmd/IRequest.java, components/blitz/src/omero/cmd/RequestObjectFactoryRegistry.java, components/blitz/src/omero/cmd/SessionI.java, components/blitz/src/omero/cmd/basic/DoAllI.java, components/blitz/src/omero/cmd/fs/OriginalMetadataRequestI.java, components/blitz/src/omero/cmd/graphs/BaseGraphTraversalProcessor.java, components/blitz/src/omero/cmd/graphs/Chgrp2I.java, components/blitz/src/omero/cmd/graphs/Chmod2I.java, components/blitz/src/omero/cmd/graphs/Chown2I.java, components/blitz/src/omero/cmd/graphs/Delete2I.java, components/blitz/src/omero/cmd/graphs/IGraphModifyRequest.java, components/blitz/src/omero/grid/ParamsHelper.java, components/blitz/src/omero/grid/ProcessCallbackI.java, components/blitz/src/omero/model/SmartShape.java, components/blitz/src/omero/rtypes.java, components/blitz/src/omero/sys/ParametersI.java, components/blitz/src/omero/util/IceMapper.java, components/blitz/src/omero/util/ObjectFactoryRegistry.java, components/blitz/src/omero/util/RPSTileLoop.java, components/blitz/src/omero/util/Resources.java, components/blitz/src/omero/util/ServantHolder.java, components/blitz/src/omero/util/TempFileManager.java, components/blitz/src/omero/util/TileLoop.java, components/blitz/src/omero/util/TileLoopIteration.java, components/blitz/src/org/hibernate/stat/ConcurrentStatisticsImpl.java
This PR should improve Blitz's Javadoc which should now report warnings from only,
* `ome.services.*`
* `omero.gateway.*`
* `pojos.*`
--no-rebase
=> improve Blitz Javadoc

components/tools/OmeroPy/src/omero/plugins/web.py, components/tools/OmeroPy/test/unit/clitest/reference_templates/apache-wsgi.conf, components/tools/OmeroPy/test/unit/clitest/reference_templates/nginx-wsgi-development-withoptions.conf, components/tools/OmeroPy/test/unit/clitest/reference_templates/nginx-wsgi-development.conf, components/tools/OmeroPy/test/unit/clitest/reference_templates/nginx-wsgi-withoptions.conf, components/tools/OmeroPy/test/unit/clitest/reference_templates/nginx-wsgi.conf, components/tools/OmeroPy/test/unit/clitest/test_web.py, etc/templates/apache-wsgi.conf.template, etc/templates/nginx-wsgi-development.conf.template, etc/templates/nginx-wsgi.conf.template
This PR prevent from duplicates when deploying multiple omeroweb in one server. Reported in https://github.com/openmicroscopy/management_tools/pull/47/
To test:
*NOTE: all non alphanumeric characters will be removed from the prefix*
- **NGINX config:**
- no prefix:
- ``omero config set omero.web.application_server wsgi-tcp``
- ``omero web config nginx-wsgi``
- check if it matches https://github.com/aleksandra-tarkowska/openmicroscopy/blob/wsgi_config_with_prefix/components/tools/OmeroPy/test/unit/clitest/reference_templates/nginx-wsgi.conf
- custom prefix ``/test`` try also with ASCII non alphanumeric characters:
- ``omero config set omero.web.prefix '/test'``
-  check if it matches https://github.com/aleksandra-tarkowska/openmicroscopy/blob/wsgi_config_with_prefix/components/tools/OmeroPy …
=> improving wsgi configs for multiple servers deployment

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/AcquisitionDataUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/AnnotationDataUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/DocComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/Editor.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/GeneralPaneUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/view/MetadataViewer.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/view/MetadataViewerComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewerComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/util/ui/ScriptingDialog.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/model/ScriptObject.java
This is the same as gh-4051 but rebased onto dev_5_1.
----
Same as #3993 just for Insight
Test:
- Install @emilroz  's script which uses file annotations: https://github.com/emilroz/omero-user-scripts/blob/populate_metadata_fa_additions/util_scripts/Populate_Metadata.py 
- Add some file annotations to a plate
- Select the plate and some file annotations and run the script, which should open the script dialog
- Make sure the Plate ID and the the file annotations IDs are set in the dialog
- Run the script. Will fail, but in 'Info' in the activities popup you should see, that the parameters were passed correctly to the script.
- Additional test: Run some other scripts, to make sure the changes didn't break the script dialog for other scripts.
=> Add ability to run scripts against fa's from OMERO.Insight (rebased onto dev_5_1)

components/tools/OmeroPy/src/omero/plugins/tag.py, components/tools/OmeroPy/test/integration/clitest/test_tag.py
This PR adds to the fix in https://github.com/ximenesuk/openmicroscopy/commit/32e3434a7b8d46b2d446005fe71e5ed1669e17af which included empty tagsets in the `listsets` command to include empty tagsets in the `list` command as a separate section below the tree view.
To test create some tags and tagsets and have some of those tagsets empty. To create empty tagsets from the CLI you need to create populated tagsets and then remove the contents, e.g.
```
$ omero tag create --name "tag1"
TagAnnotation:437
$ omero tag create --name "tag2"
TagAnnotation:438
$ omero tag create --name "tag3"
TagAnnotation:439
$ omero tag createset --name "tagset1" --tag 437
TagAnnotation:440
$ omero tag createset --name "tagset-empty" --tag 438
TagAnnotation:441
$ omero delete TagAnnotation:438
omero.cmd.Delete2 …
```
=> List empty tagsets when using omero tag list

components/tools/OmeroPy/src/omero/plugins/obj.py, components/tools/OmeroPy/test/integration/clitest/test_obj.py
See gh-4071
--rebased-from #4071
=> Add get subcommand to CLI obj command (rebased)

components/insight/SRC/org/openmicroscopy/shoola/env/data/OMEROGateway.java
Found a bug will trying to reproduce [Ticket 12744](https://trac.openmicroscopy.org/ome/ticket/12744)
Test:
- Select an image.
- Add a MapAnnotation by entering a key, press tab, enter a value, but **don't** hit enter, instead navigate away by selecting another image (before: an exception was thrown at this point because Insight tried to save the ImageAnnotationLink twice)
- Go back to the image and make sure the key/value pair has been saved
=> Bugfix: MapAnnotation Image link

components/tools/bump_bf_version.py
This is the same as gh-4024 but rebased onto dev_5_1.
----
This script should simplify the bump of the Bio-Formats version number to either a release (x.y.z) or a snapshot (x.y.z-SNAPSHOT) version. Both the version number under `etc/omero.properties` and the resolver under `etc/local.properties.example` should be updated.
To test this PR, try:
- `python bump_bf_version.py x.y.z` (should set `version.bioformats=x.y.z` under `etc/omero.properties` and `ome-resolver` under `etc/local.properties.example`)
- `python bump_bf_version.py x.y.z-SNAPSHOT` (should set `version.bioformats=x.y.z-SNAPSHOT`  under `etc/omero.properties` and `ome-simple-artifactory` under `etc/local.properties.example`)
- `python bump_bf_version.py x.y` should fail with an informative message
=> Add simple utility script to bump Bio-Formats version (rebased onto dev_5_1)

components/tools/OmeroPy/src/omero/plugins/web.py, components/tools/OmeroPy/test/unit/clitest/reference_templates/apache-wsgi-withoptions.conf, components/tools/OmeroPy/test/unit/clitest/reference_templates/apache-wsgi.conf, components/tools/OmeroPy/test/unit/clitest/reference_templates/nginx-wsgi-development-withoptions.conf, components/tools/OmeroPy/test/unit/clitest/reference_templates/nginx-wsgi-development.conf, components/tools/OmeroPy/test/unit/clitest/reference_templates/nginx-wsgi-withoptions.conf, components/tools/OmeroPy/test/unit/clitest/reference_templates/nginx-wsgi.conf, components/tools/OmeroPy/test/unit/clitest/test_web.py, etc/templates/apache-wsgi.conf.template, etc/templates/nginx-wsgi-development.conf.template, etc/templates/nginx-wsgi.conf.template
This is the same as gh-4110 and gh-4132 but rebased onto develop.
----
This PR prevent from duplicates when deploying multiple omeroweb in one server. Reported in https://github.com/openmicroscopy/management_tools/pull/47/
To test:
*NOTE: all non alphanumeric characters will be removed from the prefix*
- **NGINX config:**
- no prefix:
- ``omero config set omero.web.application_server wsgi-tcp``
- ``omero web config nginx-wsgi``
- check if it matches https://github.com/aleksandra-tarkowska/openmicroscopy/blob/wsgi_config_with_prefix/components/tools/OmeroPy/test/unit/clitest/reference_templates/nginx-wsgi.conf
- custom prefix ``/test`` try also with ASCII non alphanumeric characters:
- ``omero config set omero.web.prefix '/test'``
-  check if it matches …
=>  improving wsgi configs for multiple servers deployment (rebased develop)

components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/util/model/AnalysisStatsWrapper.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/GraphPane.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/IntensityView.java, components/insight/SRC/org/openmicroscopy/shoola/env/rnd/roi/AbstractROIShapeStats.java, components/insight/SRC/org/openmicroscopy/shoola/env/rnd/roi/ROIAnalyser.java, components/insight/SRC/org/openmicroscopy/shoola/env/rnd/roi/ROIShapeStats.java, components/insight/SRC/org/openmicroscopy/shoola/env/rnd/roi/ROIShapeStatsSimple.java, components/insight/SRC/org/openmicroscopy/shoola/env/rnd/roi/ROIStats.java
This is the same as gh-4083 but rebased onto dev_5_1.
----
See [Ticket 12995](https://trac.openmicroscopy.org/ome/ticket/12995)
For analyzing ROI shapes a LinkedHashMap was used, which consumed a lot of memory. This PR replaces it with a double array and a list of points. It also removes some unnecessary duplications of data structures which in total significantly reduces the memory usage.
Test: Analyze some ROIs: Make sure the histogram plots and intensity values are still calculated correctly. Analyze a rectangular ROI same size or bigger as the one mentioned in ticket (250x280px) on a multi channel image, make sure Insight doesn't crash and it doesn't take several minutes for the graphs to appear.
=> ROI tool OutOfMemory (rebased onto dev_5_1)

components/insight/SRC/org/openmicroscopy/shoola/env/data/OMEROGateway.java
This is the same as gh-4143 but rebased onto dev_5_1.
----
Found a bug will trying to reproduce [Ticket 12744](https://trac.openmicroscopy.org/ome/ticket/12744)
Test:
- Select an image.
- Add a MapAnnotation by entering a key, press tab, enter a value, but **don't** hit enter, instead navigate away by selecting another image (before: an exception was thrown at this point because Insight tried to save the ImageAnnotationLink twice)
- Go back to the image and make sure the key/value pair has been saved
=> Bugfix: MapAnnotation Image link (rebased onto dev_5_1)

components/tools/OmeroWeb/omeroweb/feedback/views.py
See https://trello.com/c/ra7UKuEJ/50-resurrect-5-1-web-method
This PR restores a handler removed in https://github.com/openmicroscopy/openmicroscopy/pull/4090 and deprecates it (removed in 5.2 via #4108).
--no-rebase
=> Custom server error deprecation

components/tools/OmeroM/src/annotations/linkAnnotation.m, components/tools/OmeroM/src/annotations/updateFileAnnotation.m, components/tools/OmeroM/src/io/createDataset.m, components/tools/OmeroM/src/io/createObject.m, components/tools/OmeroM/src/io/createPlate.m, components/tools/OmeroM/src/io/createProject.m, components/tools/OmeroM/src/io/createScreen.m, examples/Training/matlab/ConnectToOMERO.m, examples/Training/matlab/ReadData.m, examples/Training/matlab/WriteData.m, examples/Training/matlab/mydata.txt
See https://trello.com/c/gSKqCAe2/49-omero-matlab-group-support
This PR:
- addresses some comments from https://github.com/openmicroscopy/openmicroscopy/pull/4136
- reviews the object creation functions `createXXX` and add group support to them
- improves the performance of the `createDataset/createPlate` function when linking to projects/screens by performing a single transaction instead of multiple
- extends the `WriteData` training example to cover the semantics of the `createXXX` functions and cover the annotation creation function with a group argument.
/cc @emilroz
=> Matlab: add group support to create objects function

components/blitz/src/ome/formats/OMEROMetadataStoreClient.java, components/blitz/src/ome/services/blitz/impl/OmeroMetadata.java, components/tools/OmeroJava/test/integration/ExporterTest.java
Try exporting then importing an image with ROIs and make sure that the ROIs are preserved. Of course, this preserves only the properties defined in `ROI.xsd`. Also check that https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-java/lastCompletedBuild/testngreports/integration/ExporterTest/ passes.
Still does not work for mask ROIs, sorry @imunro.
--no-rebase
=> add ROIs to OME-TIFF export

components/common/resources/ome/config.xml, components/tools/OmeroPy/src/omero/gateway/__init__.py, components/tools/OmeroWeb/omeroweb/decorators.py, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/metadata_preview.html, components/tools/OmeroWeb/omeroweb/webclient/views.py, components/tools/OmeroWeb/omeroweb/webgateway/marshal.py, components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/ome.viewport.js, components/tools/OmeroWeb/omeroweb/webgateway/templates/webgateway/viewport/omero_image.html, components/tools/OmeroWeb/omeroweb/webgateway/views.py, etc/omero.properties
See http://trac.openmicroscopy.org/ome/ticket/12924
To test:
- Check in web full image viewer, that by default, interpolation is ON (checkbox is checked and image is not pixelated when zoomed right in).
```
$ bin/omero config set omero.client.viewer.interpolate_pixels False
$ bin/omero admin restart
```
- Re-open image viewer. Interpolation should be OFF (checkbox unchecked and pixellated image on zoom).
=> Interpolate config option

components/tools/OmeroM/src/annotations/linkAnnotation.m, components/tools/OmeroM/src/annotations/updateFileAnnotation.m, components/tools/OmeroM/src/io/createDataset.m, components/tools/OmeroM/src/io/createObject.m, components/tools/OmeroM/src/io/createPlate.m, components/tools/OmeroM/src/io/createProject.m, components/tools/OmeroM/src/io/createScreen.m, examples/Training/matlab/ConnectToOMERO.m, examples/Training/matlab/ReadData.m, examples/Training/matlab/WriteData.m, examples/Training/matlab/mydata.txt
This is the same as gh-4145 but rebased onto develop.
----
See https://trello.com/c/gSKqCAe2/49-omero-matlab-group-support
This PR:
- addresses some comments from https://github.com/openmicroscopy/openmicroscopy/pull/4136
- reviews the object creation functions `createXXX` and add group support to them
- improves the performance of the `createDataset/createPlate` function when linking to projects/screens by performing a single transaction instead of multiple
- extends the `WriteData` training example to cover the semantics of the `createXXX` functions and cover the annotation creation function with a group argument.
/cc @emilroz
=> Matlab: add group support to create objects function (rebased onto develop)

components/common/resources/ome/config.xml, components/tools/OmeroPy/src/omero/gateway/__init__.py, components/tools/OmeroWeb/omeroweb/decorators.py, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/metadata_preview.html, components/tools/OmeroWeb/omeroweb/webclient/views.py, components/tools/OmeroWeb/omeroweb/webgateway/marshal.py, components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/ome.viewport.js, components/tools/OmeroWeb/omeroweb/webgateway/templates/webgateway/viewport/omero_image.html, components/tools/OmeroWeb/omeroweb/webgateway/views.py, etc/omero.properties
This is the same as gh-4084 but rebased onto dev_5_1.
----
See http://trac.openmicroscopy.org/ome/ticket/12924
To test:
- Check in web full image viewer, that by default, interpolation is ON (checkbox is checked and image is not pixelated when zoomed right in).
- Also Preview viewer should be interpolated by default.
```
$ bin/omero config set omero.client.viewer.interpolate_pixels False
$ bin/omero admin restart
```
- Log out of webclient. Log In again.
- Re-open image viewer. Interpolation should be OFF (checkbox unchecked and pixellated image on zoom).
- Preview viewer should be pixelated too.
=> Interpolate config option (rebased onto dev_5_1)

components/dsl/resources/ome/dsl/psql-types.properties, components/dsl/src/ome/dsl/Property.java
This moves the translation map used for converting OME model types to
database types into a resource file that can be specialized on a
per-database-profile basis.
=> Parameterize DSL database types

components/insight/SRC/org/openmicroscopy/shoola/agents/dataBrowser/actions/DownloadAction.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/Editor.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorControl.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/actions/DownloadAction.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewerComponent.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/OMEROGateway.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/OmeroDataService.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/OmeroDataServiceImpl.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/model/DownloadArchivedActivityParam.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/MetadataHandlerView.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/MetadataHandlerViewImpl.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/ArchivedImageLoader.java, components/insight/SRC/org/openmicroscopy/shoola/env/ui/ArchivedLoader.java, components/insight/SRC/org/openmicroscopy/shoola/env/ui/DownloadArchivedActivity.java, components/insight/TEST/org/openmicroscopy/shoola/env/data/NullOmeroPojoService.java
This is the same as gh-4060 but rebased onto dev_5_1.
----
See Trello card [Download multiple files - preserve directories](https://trello.com/c/asMv2nvz/27-download-multiple-files-preserve-directories)
With this PR original files will be downloaded as they are (not zipped like before) and their original folder structure will be preserved. Test: Download some original files and make sure the folder structure is correct (see File Path info dialog, folder structure should match the path in the managed repository).
=> Don't zip and preserve original paths when downloading images (rebased onto dev_5_1)

components/tools/OmeroWeb/omeroweb/webgateway/templatetags/common_filters.py
This fixes a bug in python 2.6 when comparing Decimal with floats and also other bugs in the calculation of times for formatting.
https://trac.openmicroscopy.org/ome/ticket/13016
To test, user trout (python 2.6).
- Find Image 24551 (user-3), which has timepoints every 5 minutes.
- Look at Delta T times, Under POL channel on Acquisition tab.
- Should see human readable time values.
- Check that with timestamps over an hour, that minutes are shown correctly (don't go over 59!)
- We also round() the numbers before truncating to integers for display, but the only way to see the original values is to download the log file.
Before:
After:
=> Formatting timestamps

etc/ivysettings.xml
This PR registers a new Maven repository for downloading edu.ucar dependencies like netcdf instead of defaulting to the ome.external repository. bufr and grib are still consumed from the OME artifactory since their version is not available via Unidata Maven repository.
- from a clean Maven cache or minimally after running `rm -rf ~/.m2/repository/edu/ucar/`, run the default build command
- check the NetCDF dependency is properly retrieved from the Unidata artifactory (i.e. the build passes)
- under `dist/share/server/dependencies.html` check `netcdf 4.3.19` is included
- as a bonus check there is no more `joda-time` version evication with joda-time 2.2 being the only dependency (https://trello.com/c/YJJ4OAd4/64-fix-joda-time-version-mismatch)
This PR is a prerequisite for …
=> Use unidata Maven repository for edu.ucar dependencies

components/blitz/src/ome/formats/OMEROMetadataStoreClient.java
See http://trac.openmicroscopy.org/ome/ticket/11252. 
OME samples containing list annotations with annotation references were previously failing at import
during the references post-processing step at import. With this commit, the image should be properly imported with all its annotations.
To test this PR, try to import the file mentioned in the ticket and check the import works and a new image is created. To be complete, use HQL queries to check the annotations objects are creted and properly linked in the database.
As a side, this import-side fix may expose deficiencies in our clients as we likely never properly handled list annotations. My development Web server crashed with the following stacktrace when I tried to open the image /cc @will-moore @pwalczysko 
```
...
File …
```
=> Fix ListAnnotation Annotation links when importing sample images

components/dsl/resources/ome/dsl/psql-types.properties, components/dsl/src/ome/dsl/Property.java
This is the same as gh-4167 but rebased onto develop.
----
This moves the translation map used for converting OME model types to
database types into a resource file that can be specialized on a
per-database-profile basis.
=> Parameterize DSL database types (rebased onto develop)

build.xml
See https://trello.com/c/RpJxX7S7/35-javadoc-cleanup
This removes the remaining warnings thrown by `./build.py release-javadoc`. Spring framework jars are removed from the classpath - we might consider revisiting this when upgrading them. The custom `DEV.TODO` tag is removed from the Javadoc processing and broken Hibernate/Lucene links are removed. It seems the API for the versions included in OMERO is not hosted anymore by the official sites.
--no-rebase
=> Javadoc final warnings

components/server/src/ome/services/delete/DeleteException.java
With the graphs reimplementation `DeleteException` isn't used any more.
=> deprecate OMERO.server's DeleteException

components/tools/OmeroJava/test/integration/delete/AnnotationDeleteTest.java
Make sure that the diff makes sense and that CI is green, including https://ci.openmicroscopy.org/job/OMERO-5.1-merge-integration-java/lastCompletedBuild/testngreports/integration.delete/AnnotationDeleteTest/.
--rebased-from #4171
=> fix AnnotationDeleteTest (rebased from develop)

.travis.yml
As it looks like pytest 2.8.0 is causing some issues with our usage of `pytest.deprecated_call()` in Python unit tests, this commit is forcing an earlier version of pytest to be installed on Travis rather than downloading the latest.
To test this PR, check Travis is green. Note this PR is mostly targeted at keeping our PR validation via Travis ongoing. The reason of the regression should likely be investigated as a follow-up.
/cc @ximenesuk @aleksandra-tarkowska @will-moore @jburel
=> Cap pytest to 2.7.3

components/tools/OmeroWeb/omeroweb/webgateway/webgateway_cache.py
prevent throwing an exception if query_string is incorrect, see https://trac.openmicroscopy.org/ome/ticket/12969
to test:
- log in as `user-1` to `trout/merge`
- check if you see image https://trout.openmicroscopy.org/merge/webclient/render_image/8751/24/0/?c=1|119.5:1702.875$0000FF,2|141.05:458.4125$00FF00,3|363.65:818.2125$FF0000
- then go to https://trout.openmicroscopy.org/merge/webclient/render_image/8751/24/0/?c=1%257C119.5:1702.875$0000FF,2%257C141.05:458.4125$00FF00,3%257C363.65:818.2125$FF0000 (this URL contains badly encoded ``|`` -> ``%257C``). You should see black image as channels in query_string are incorrect
- to compare log as ``user-1`` to ``latest`` and using the same url https://trout.openmicroscopy.org/latest/webclient/render_image/8751/24/0/?c=1%257C119.5:1702.875$0000 …
=> ticket 12969

.travis.yml
This is the same as gh-4194 but rebased onto develop.
----
As it looks like pytest 2.8.0 is causing some issues with our usage of `pytest.deprecated_call()` in Python unit tests, this commit is forcing an earlier version of pytest to be installed on Travis rather than downloading the latest.
To test this PR, check Travis is green. Note this PR is mostly targeted at keeping our PR validation via Travis ongoing. The reason of the regression should likely be investigated as a follow-up.
/cc @ximenesuk @aleksandra-tarkowska @will-moore @jburel
=> Cap pytest to 2.7.3 (rebased onto develop)

components/tools/OmeroWeb/omeroweb/decorators.py, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/public/public.html
This PR fixes access to image when share is inactive or expired.
To test:
- log in as ``user-1`` and share image with ``user-5``
- log in as ``user-5`` check if image is visible in the viewer, copy the image URL ``http://host/webclient/img_detail/IMAGE_ID/``
- log in back to ``user-1`` and deactivate share (uncheck enable in share edit form)
- log in back to ``user-5`` and check if share is greyed out, you should also not being able to click on it. Go to the URL ``http://host/webclient/img_detail/IMAGE_ID/``, you should get 404
- as it is impossible to create expired share check if image in ``share 17754`` (owned by ``user-1``) is not visible by ``user-5``
=> ticket 13018

components/tools/OmeroJava/test/integration/PojosServiceTest.java
Create group with correct permissions.
The permission level of the group was not correctly set.
To test:
Check that the Java tests are greeen
=> test Security Violation

components/tools/OmeroPy/src/omero/gateway/__init__.py, components/tools/OmeroPy/test/integration/gatewaytest/test_annotation.py
See http://trac.openmicroscopy.org/ome/ticket/13022
This fixes the slow loading of right panel "General" tab when the P/D/I has several file annotations.
Two factors were causing the poor performance:
- Loading annotations didn't also load the files, so that ann.getFile() created a new ```OriginalFileWrapper``` with an unloaded file, causing the file to be loaded each time on the fly. Now, we include files when loading annotations.
- Further poor performance was caused by not caching the file for the FileAnnotationWrapper, so that repeated calls to getName() or getFileSize() were loading the file each time. We now cache the file in ann.getFile()
To test:
- Compare loading speed of right panel for P/D/I with lots of file annotations vv none. Should be about the same.
=> Right panel fileanns slow 13022

components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/ome.chgrp.js, components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/ome.webclient.actions.js, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/chgrp_target_tree.html, components/tools/OmeroWeb/omeroweb/webclient/urls.py, components/tools/OmeroWeb/omeroweb/webclient/views.py, components/tools/OmeroWeb/omeroweb/webclient/webclient_gateway.py, components/tools/OmeroWeb/omeroweb/webgateway/marshal.py, components/tools/OmeroWeb/test/integration/test_chgrp.py
See: http://trac.openmicroscopy.org/ome/ticket/12965
Webclient warns when you will lose lined annotations or child objects during chgrp.
Test setup:
- Add a bunch of annotations to P/D/I S/P/W - including some which ARE expected to chgrp with the data (Comments, MapAnnotations etc) and some of which are NOT expected to chgrp with the data, e.g. Tags, Multi-linked Files, Comments.
- Also put some images in multiple Datasets (so that when you chgrp one Dataset, some images will be left behind).
- Also, perform an image projection or Images_From_ROIs script or Channel_Offsets script so that some images will give an error on chgrp.
- Also, find a Multi-Image Fileset.
To test, try chgrp with different selections of your P/D/I S/PW data and you should be warned if:
- You try to move a P/D/S …
=> chgrp 'not included' warning

components/blitz/src/ome/formats/OMEROMetadataStoreClient.java
This is the same as gh-4174 but rebased onto develop.
----
See http://trac.openmicroscopy.org/ome/ticket/11252. 
OME samples containing list annotations with annotation references were previously failing at import
during the references post-processing step at import. With this commit, the image should be properly imported with all its annotations.
To test this PR, try to import the file mentioned in the ticket and check the import works and a new image is created. To be complete, use HQL queries to check the annotations objects are creted and properly linked in the database.
As a side, this import-side fix may expose deficiencies in our clients as we likely never properly handled list annotations. My development Web server crashed with the following stacktrace when I tried to open the …
=> Fix ListAnnotation Annotation links when importing sample images (rebased onto develop)

components/tools/OmeroWeb/omeroweb/webgateway/webgateway_cache.py
This is the same as gh-4181 but rebased onto develop.
----
prevent throwing an exception if query_string is incorrect, see https://trac.openmicroscopy.org/ome/ticket/12969
to test:
- log in as `user-1` to `eel/merge`
- check if you see image https://eel.openmicroscopy.org/merge/webclient/render_image/8751/24/0/?c=1|119.5:1702.875$0000FF,2|141.05:458.4125$00FF00,3|363.65:818.2125$FF0000
- then go to https://eel.openmicroscopy.org/merge/webclient/render_image/8751/24/0/?c=1%257C119.5:1702.875$0000FF,2%257C141.05:458.4125$00FF00,3%257C363.65:818.2125$FF0000 (this URL contains badly encoded ``|`` -> ``%257C``). You should see black image as channels in query_string are incorrect
- to compare log in as ``user-1`` to ``latest`` and using the same image …
=> ticket 12969 (rebased onto develop)

components/tools/OmeroPy/src/omero/gateway/__init__.py, components/tools/OmeroWeb/omeroweb/decorators.py
This should prevent python clients using OMERO.py gateway against older server where the following properties are not present.
To test:
- go to trout/merge choose seabass and log in as non admin user
- check if you were successfully logged in and there were no SecurityViolation exception thrown.
- log out and log in to merge
- check if interpolation is on in webviewer
cc: @sbesson @joshmoore @will-moore
=> Ticket 13030

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/ChannelAcquisitionComponent.java
Follow-up PR for #4154 
Display seconds as fraction with one decimal place; added whitespace between value and unit; always display next lower unit even if the value is 0 (e. g. 1 min 0 s ; or 1 h 0 min )
Test: Check that the Insight timestamp format matches OMERO.Web, for example on trout user-2 Image 9532
=> Time format follow up (dev_5_1)

components/server/src/ome/services/delete/DeleteException.java
With the graphs reimplementation `DeleteException` isn't used any more.
--rebased-from #4180
=> deprecate OMERO.server's DeleteException (rebased from develop)

etc/ivysettings.xml
This is the same as gh-4168 but rebased onto develop.
----
This PR registers a new Maven repository for downloading edu.ucar dependencies like netcdf instead of defaulting to the ome.external repository. bufr and grib are still consumed from the OME artifactory since their version is not available via Unidata Maven repository.
- from a clean Maven cache or minimally after running `rm -rf ~/.m2/repository/edu/ucar/`, run the default build command
- check the NetCDF dependency is properly retrieved from the Unidata artifactory (i.e. the build passes)
- under `dist/share/server/dependencies.html` check `netcdf 4.3.19` is included
- as a bonus check there is no more `joda-time` version evication with joda-time 2.2 being the only dependency …
=> Use unidata Maven repository for edu.ucar dependencies (rebased onto develop)

components/tools/OmeroJava/test/integration/PojosServiceTest.java
This is the same as gh-4193 but rebased onto dev_5_1.
----
Create group with correct permissions.
The permission level of the group was not correctly set.
To test:
Check that the Java tests are greeen
=> test Security Violation (rebased onto dev_5_1)

components/tools/OmeroWeb/omeroweb/settings.py
Spotted in reviewing https://github.com/openmicroscopy/ome-documentation/pull/1287.
--rebased-to #4211
cc: @sbesson
=> fix small typo in web configuration message

components/tools/OmeroWeb/omeroweb/settings.py
Spotted in reviewing openmicroscopy/ome-documentation#1287.
--rebased-from #4210
cc: @sbesson
=> fix small typo in web configuration message (rebased from dev_5_1)

components/tools/OmeroPy/src/omero/gateway/__init__.py, components/tools/OmeroWeb/omeroweb/decorators.py
This is the same as gh-4191 but rebased onto develop.
----
This should prevent python clients using OMERO.py gateway against older server where the following properties are not present.
To test:
- go to trout/merge choose seabass and log in as non admin user
- check if you were successfully logged in and there were no SecurityViolation exception thrown.
- log out and log in to merge
- check if interpolation is on in webviewer
cc: @sbesson @joshmoore @will-moore
=> Ticket 13030 (rebased onto develop)

components/blitz/src/omero/gateway/util/PojoMapper.java
While trying to reproduce [Ticket 13009](http://trac.openmicroscopy.org/ome/ticket/13009) Insight crashed, because PojoMapper didn't recognize the shape classes. This PR adds the various shape classes to the PojoMapper.
Test: Open an image, draw an ROI, save ROI. Close image and reopen it again, open Measurement tool again. No error dialog should pop up.
=> Add shape classes to PojoMapper

sql/psql/OMERO5.1DEV__18/OMERO5.1DEV__17.sql, sql/psql/OMERO5.1__1/OMERO5.0__0.sql
Accidentally used .vm file quoting syntax. Now with a wrong DB character encoding, upgrade from 5.0 should give an appropriate error message.
--no-rebase unless 5.1.5
=> fix typo in 5.0 to 5.1 SQL upgrade character encoding error

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/ChannelAcquisitionComponent.java
This is the same as gh-4195 but rebased onto develop.
----
Follow-up PR for #4154 
Display seconds as fraction with one decimal place; added whitespace between value and unit; always display next lower unit even if the value is 0 (e. g. 1 min 0 s ; or 1 h 0 min )
Test: Check that the Insight timestamp format matches OMERO.Web, for example on trout user-2 Image 9532
=> Time format follow up (dev_5_1) (rebased onto develop)

components/insight/SRC/org/openmicroscopy/shoola/agents/dataBrowser/browser/BrowserModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/dataBrowser/browser/ImageFinder.java
Fix selection problem noticed by @mporter-gre 
Nodes not visible in central panel were still selected in tree
to test this PR:
* log in as user-3
* Browse dataset non-archivedv
* in central panel, filter by name using for example R3D.
* 6 images out of 9 should be displayed.
* Select all 6 in the central panel
* Check that  the image ```/home/hudson/for_import_to_howe/non-archived-imoprt-case/user-3/read-only-1/no_projects/non-archivedv/off_by_1_a.dv``` is not selected in the tree. It is not visible in the central panel.
cc @pwalczysko
=> Selection browser

components/tools/OmeroWeb/omeroweb/webgateway/templatetags/common_filters.py
This is the same as gh-4131 but rebased onto develop.
----
This fixes a bug in python 2.6 when comparing Decimal with floats and also other bugs in the calculation of times for formatting.
https://trac.openmicroscopy.org/ome/ticket/13016
To test, user trout (python 2.6).
- Find Image 24551 (user-3), which has timepoints every 5 minutes.
- Look at Delta T times, Under POL channel on Acquisition tab.
- Should see human readable time values.
- Check that with timestamps over an hour, that minutes are shown correctly (don't go over 59!)
- We also round() the numbers before truncating to integers for display, but the only way to see the original values is to download the log file.
Before:
After:
=> Formatting timestamps (rebased onto develop)

components/tools/OmeroPy/src/omero/gateway/__init__.py, components/tools/OmeroPy/test/integration/gatewaytest/test_annotation.py
This is the same as gh-4176 but rebased onto develop.
----
See http://trac.openmicroscopy.org/ome/ticket/13022
This fixes the slow loading of right panel "General" tab when the P/D/I has several file annotations.
Two factors were causing the poor performance:
- Loading annotations didn't also load the files, so that ann.getFile() created a new ```OriginalFileWrapper``` with an unloaded file, causing the file to be loaded each time on the fly. Now, we include files when loading annotations.
- Further poor performance was caused by not caching the file for the FileAnnotationWrapper, so that repeated calls to getName() or getFileSize() were loading the file each time. We now cache the file in ann.getFile()
To test:
- Compare loading speed of right panel for P/D/I with lots of file …
=> Right panel fileanns slow 13022 (rebased onto develop)

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/PropertiesUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/util/EditorUtil.java
Bugfix: [Ticket 13034](http://trac.openmicroscopy.org/ome/ticket/13034)
Test: Check the pixelsizes for a few images (e.g. *.dv), especially the image mentioned in the ticket (nightshade image id: 4045578 ) Make sure the pixel size uses the same unit for all dimensions XYZ (it's shown in the tooltip when you hover over the pixelsize label), and make sure the values are correct (especially for Z dimension) by looking at the original meta data (unit can differ from the original meta data that's expected).
Note: The problem (wrong Z dimension unit) occured, when there was a two figure number for X, like in the example 66nm, but a three figure number for Z (200nm).
--no-rebase
=> Make sure the same pixelsize unit is used for all dimensions

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/ChannelAcquisitionComponent.java
Follow up PR for #4199 
Changes the term "t index" to simply "t", and start count for t from 1 (instead of 0), see 'Exposure Time' table in channel acquisition metadata.
(only the last commit is relevant for this PR, the other two are part for the previously mentioned PR)
=> Another formatting issue

components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/DataObjectUpdater.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewer.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewerComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/util/browser/TreeImageDisplay.java, components/insight/SRC/org/openmicroscopy/shoola/agents/util/dnd/DnDTree.java, components/insight/SRC/org/openmicroscopy/shoola/agents/util/dnd/TransferableNode.java
Fixes [Ticket 12959](http://trac.openmicroscopy.org/ome/ticket/12959)
First Workaround:
Autoscrolling while performing drag&drop operations on trees is basically broken, due to various Java bugs which apparently don't get fixed. This PR adds a workaround, which is mainly based on a suggestion in this [stackoverflow post](http://stackoverflow.com/questions/29126758/how-can-i-implement-a-workaround-for-the-autoscroll-during-drag-and-drop-bug-on).
It still doesn't work as neat as is it should be, but at least it works. In order to activate autoscroll, you have to drag an item to the egde of the tree's visible area.
Second Workaround:
DnD on Windows didn't work at all, also several Java issues there (DataFlavor.javaJVMLocalObjectMimeType throws an exception on Windows; objects transfered via …
=> DnD autoscroll fix

components/tools/OmeroPy/src/omero/util/ROI_utils.py, components/tools/OmeroPy/test/unit/test_rois.py, components/tools/OmeroWeb/omeroweb/webgateway/views.py
This is the same as gh-3932 but rebased onto metadata.
----
There are (at least) 2 formats for storing Points in ROI Polygons. The webgateway only had one of them.
https://trello.com/c/hJLlf1Xr/47-error-on-preview-rois
Are there any other formats?
=> Handle new ROI Points string format (rebased onto metadata)

components/blitz/resources/omero/Constants.ice, etc/grid/templates.xml
Import of the condensation screens failed with
```
==> Summary
63171 files uploaded, 0 filesets created, 0 images imported, 0 errors in 2:47:28.118
2015-09-10 15:20:46,922 10354261   [1-thread-1] ERROR  me.formats.importer.util.ClientKeepAlive - Exception while executing ping(), logging Connector out:
java.lang.RuntimeException: Ice.CommunicatorDestroyedException
at ome.formats.OMEROMetadataStoreClient.ping(OMEROMetadataStoreClient.java:763) ~[blitz.jar:na]
```
```
-! 09/10/15 15:20:14.841 OMERO.Glacier2: warning: dispatch exception: OutgoingAsync.cpp:720: Ice::UnknownLocalException:
unknown local exception:
Ice::MemoryLimitException
Ice.MemoryLimitException
reason = "requested 67108865 bytes, maximum allowed is 67108864 bytes (see Ice.MessageSizeMax)"
```
=> Temporarily bump MessageSizeMax to 250mb

components/blitz/src/ome/formats/OMEROMetadataStoreClient.java, components/blitz/src/ome/formats/importer/ImportLibrary.java, components/blitz/src/ome/formats/importer/cli/CommandLineImporter.java, components/blitz/src/ome/formats/importer/exclusions/AbstractFileExclusion.java, components/blitz/src/ome/formats/importer/exclusions/ClientPathExclusion.java, components/model/test/ome/util/utests/LSIDEquivilenceTest.java
These 2 commits were previously a part of gh-4125 and were extensively tested for the SiB demo.
=> Import improvements

components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/ome.chgrp.js, components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/ome.webclient.actions.js, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/chgrp_target_tree.html, components/tools/OmeroWeb/omeroweb/webclient/urls.py, components/tools/OmeroWeb/omeroweb/webclient/views.py, components/tools/OmeroWeb/omeroweb/webclient/webclient_gateway.py, components/tools/OmeroWeb/omeroweb/webgateway/marshal.py, components/tools/OmeroWeb/test/integration/test_chgrp.py
Rebased from #4165:
---------------------------
See: http://trac.openmicroscopy.org/ome/ticket/12965
Webclient warns when you will lose lined annotations or child objects during chgrp.
Test setup:
- Add a bunch of annotations to P/D/I S/P/W - including some which ARE expected to chgrp with the data (Comments, MapAnnotations etc) and some of which are NOT expected to chgrp with the data, e.g. Tags, Multi-linked Files, Comments.
- Also put some images in multiple Datasets (so that when you chgrp one Dataset, some images will be left behind).
- Also, perform an image projection or Images_From_ROIs script or Channel_Offsets script so that some images will give an error on chgrp.
- Also, find a Multi-Image Fileset.
To test, try chgrp with different selections of your P/D/I S/PW data and you …
=> Chgrp unlink warning 12965 develop

components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/jquery.jstree.omecut_plugin.js, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/containers.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/includes/center_plugin.thumbs.js.html, components/tools/OmeroWeb/omeroweb/webclient/urls.py, components/tools/OmeroWeb/omeroweb/webclient/views.py, components/tools/OmeroWeb/test/integration/test_csrf.py, components/tools/OmeroWeb/test/integration/test_links.py
This improves performance of cut, copy & paste and drag 'n' drop actions in jsTree.
It makes a single AJAX call to create or delete multiple links for each action.
In each case, check that child counts are updated correctly and confirm the links have been created / deleted successfully by refreshing the tree.
Also check that the centre panel is correct and in sync with the tree.
Include cases where one or more of the children being moved is already contained in the destination parent.
Tests:
- Drag and drop images, datasets & plates, moving from one parent to another in each case.
- Copy and paste, as above.
- Cut. Select a number of child nodes, some of which are also in other containers, others will become orphaned. Then Paste.
Any other actions you can think of?
=> Api link multiple

components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/browser/Browser.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/browser/BrowserComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/browser/BrowserModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/browser/ImageCanvas.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/util/UnitBarSizeDialog.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewer.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/Renderer.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/RendererComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/RendererModel.java, components/insight/SRC/org/openmicroscopy/shoola/env/rnd/RenderingControl.java, components/insight/SRC/org/openmicroscopy/shoola/env/rnd/RenderingControlProxy.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/lens/LensComponent.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/lens/ZoomWindow.java
With this PR the Unit objects for pixel sizes will be used directly in the scope of the image viewer, instead of constraining everything to micrometers.
This fixes also the scalebar problem in [Ticket 13035](http://trac.openmicroscopy.org/ome/ticket/13035)
Test: Open some images which use nm as default unit, e. g. the image mentioned in the ticket (nightshade image id 4045578 ) and make sure the scalebar is drawn (and labelled) correctly.
Note: Even the pixel size is reported in nm (on the 'General' tab) the scalebar unit doesn't have to be in nm, it should be a reasonable unit.
--no-rebase
=> Use Unit objects in image viewer

components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/browser/BrowserBICanvas.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/browser/BrowserComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewer.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerControl.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerModel.java
Fixes [Ticket 13052](https://trac.openmicroscopy.org/ome/ticket/13052)
Test: 
- Check that toggling the interpolation option still works (open a very small image and zoom in to the maximum in order to see an effect). 
- Check that toggling the interpolation option *does not* request the image from the server again (open a big, tiled image; if the image is reloaded you should see the tiles gradually building up again; this should *not* happen when the interpolation option is changed).
=> Don't reload image after dis/enabling interpolation

components/blitz/resources/omero/api/IRoi.ice
Deprecate methods in ROIService
I had to mark each method as deprecated in the slice so it is reflected in Java
There is maybe a more suitable way
cc @joshmoore
=> ROI service

components/tools/OmeroWeb/omeroweb/webclient/webclient_gateway.py
I'm not sure what this was added for, but I don't think it does anything and it changes the interface. I know it's not exactly a public API, but seems like it would be good not to change it if possible.
I noticed because it broke webtagging.
=> Removed seemingly unused TagWrapper class that changed interface

components/tools/OmeroPy/src/omero/plugins/admin.py
See https://trac.openmicroscopy.org/ome/ticket/13061
This commit addresses the special case where a fresh server is downloaded and `bin/omero admin diagnostics` is called before the server is started (or minimally before the `templates.xml` file is generated for the first time).
With this change, the command should return and the memory section should simply be skipped if there is no `templates.xml` file to be parsed.
=> Do not fail admin diagnostics subcommand if the server has never been started

components/common/resources/ome/config.xml, components/tools/OmeroPy/src/omero/gateway/__init__.py, components/tools/OmeroWeb/omeroweb/decorators.py, components/tools/OmeroWeb/omeroweb/webgateway/marshal.py, components/tools/OmeroWeb/omeroweb/webgateway/templates/webgateway/viewport/omero_image.html, components/tools/OmeroWeb/omeroweb/webgateway/views.py, etc/omero.properties
This PR prevents showing ROI button in a viewer if number of ROIs is bigger then limit.
To test:
- add more then 10000 ROIs and check if `Show ROIs` in web is not visible
- check image with less then 10000 ROIs if `Show ROIs` in web is visible
- check image with no ROIs if `Show ROIs` in web is not visible
Test image with ~1500 http://eel/merge/webclient/?show=image-24083 user-1
Insight may do the same? cc @dominikl
=> Roi count limit

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/container_tags.html
This fix multiple selection in a tag tree reported in http://trac.openmicroscopy.org/ome/ticket/13065
To test, go to tag tab and try to select multiple tags. You should be only allowed to select one.
cc: @jburel
=> Tag multiple selection

components/server/src/ome/services/sessions/SessionBean.java
See https://trello.com/c/azP0udku/37-rename-createsession-agent
Since this method uses a Principal object and is principally consumed as a way to sudo, the agent is renamed as OMERO.sudo.
- create a connection from the CLI using `bin/omero login --sudo sudoer user@hostname:port`
- import an image for another user in Insight
In both cases, list the server-side sessions using `bin/omero sessions who` and check both sessions listed above are created with the `OMERO.sudo` agent.
=> Rename agent of SessionsBean.createSessionWithTimeouts()

components/tools/OmeroWeb/omeroweb/webclient/static/webclient/css/dusty.css
I think these grouped rules (and by the looks of [dusty.css](https://github.com/dpwrussell/openmicroscopy/blob/dusty-overselection/components/tools/OmeroWeb/omeroweb/webclient/static/webclient/css/dusty.css), potentially a whole lot more) are meant to be selecting `.classname elementname` for each rule, or similar, but CSS selectors are not distributive. Instead only the first rule in the group has the `.classname` rule selector.
This is evident in a few places where this behaviour does not seem desirable. E.g. Edit the name of an image in the right panel, if you mousedown the `Save` and `Cancel` buttons, they have different behaviours. Also, when mousedown on `Save`, there is an unpleasant layout change which is much nicer to not have.
It is also very annoying to have overreaching CSS …
=> Tweak dusty.css which is misselecting on some rules

components/tools/OmeroPy/src/omero/plugins/admin.py
With the configuration template changes, deployment on Windows from a fresh server was not possible since the configuration files were not present initially. This commit migrates the Windows check function post configuration rewriting.
This PR fixes a Windows-specific bug introduced in https://github.com/openmicroscopy/openmicroscopy/pull/4093 (see https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-merge-deploy-win2012/4/console) and should be tested via the Windows deployment in this CI job.
=> Migrate checkwindows() call post configuration template writing

components/blitz/src/ome/services/blitz/fire/PermissionsVerifierI.java, components/server/src/ome/security/sharing/SharingACLVoter.java, components/server/src/ome/services/sessions/SessionManagerImpl.java, components/tools/OmeroPy/test/integration/test_ishare.py
When using `joinSession` on an inactive share, throw PermissionDenied:
```
CannotCreateSessionException Raised if the session
E       PermissionDeniedException: exception ::Glacier2::PermissionDeniedException
E       {
E           reason = Share:1489 (497c947c-8e57-4e9a-9886-f3f87e6016a6) is inactive
E       }
```
See: https://trac.openmicroscopy.org/ome/ticket/13018#comment:4
=> trac 13018: disabling inactive share access

components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/ImViewerAgent.java
Fix another out of synch issue
to test: 
Select image in centre pane.
Copy settings.
Open another image in full viewer.
Go back to main window - leaving Full Viewer open.
Select open image and click on Preview tab.
Paste settings and save using Preview pane buttons.
Preview pane updates as expected, Full Viewer updates as expected and Save button on both Preview and Full Viewer are disabled as expected.
Repeat but paste settings using right-click Paste and Save in centre pane or data tree.
Preview pane updates as expected and Save button in Preview is disabled as expected.
In Full Viewer image updates as expected, The  Save button should now become disabled (was enabled w/o this PR).
cc @dominikl  @gusferguson
=> Rnd copy/paste

components/tools/OmeroPy/src/omero/gateway/__init__.py, components/tools/OmeroPy/test/integration/gatewaytest/test_delete.py, components/tools/OmeroPy/test/integration/gatewaytest/test_get_objects.py, components/tools/OmeroPy/test/integration/test_chgrp.py, components/tools/OmeroPy/test/integration/test_repository.py, components/tools/OmeroWeb/omeroweb/webclient/controller/container.py, components/tools/OmeroWeb/omeroweb/webclient/webclient_gateway.py
This PR addresses the various items in https://trello.com/c/WMnOBpC6/31-improve-deleteobjects-deprecate-deleteobjectdirect-inpython-gateway both RFEs and deprecation of `deleteObjectDirect`.
Tests, both `OmeroPy` and `OmeroWeb` should pass.
Web functionality to be tested is that which deletes and unlinks P/D/I, S/P and Annotations. I.e quite wide-ranging, but concentrating on unlinking and deleting all types of annotations would be useful.
=> Python gateway & webclient delete improvements

components/tools/OmeroM/build.xml, components/tools/OmeroPy/src/omero/plugins/admin.py, components/tools/python.xml, etc/ice.config, etc/templates/grid/default.xml, etc/templates/grid/templates.xml, etc/templates/grid/windefault.xml, etc/templates/ice.config, etc/templates/internal.cfg, etc/templates/master.cfg
Follow-up of https://github.com/openmicroscopy/openmicroscopy/pull/4093, this PR:
- implements the substitutions of `@Ice.Default.Host@` for the configuration templates
- suppresses the help of `admin ports` 
- moves the Web templates to a subdirectory for clarity. The `web config` subcommand and the unit tests are updated accordingly
The CI servers will test the deployment of the servers on a non-default `Ice.Default.Host`. This PR should also be tested locally with `Ice.Default.Host` unset. Additionally, the Web configuration generation should be tested to make sure nothing was broken by the templates migration.
=> Configuration templates (part 2)

components/tools/OmeroWeb/omeroweb/settings.py, components/tools/OmeroWeb/omeroweb/webadmin/custom_forms.py, components/tools/OmeroWeb/omeroweb/webadmin/forms.py, components/tools/OmeroWeb/omeroweb/webclient/custom_forms.py
This is #4236 follow up PR. It fixes:
- adds TEMPLATES settings introduced in 1.8, see https://docs.djangoproject.com/en/1.8/ref/templates/upgrading/
- removes deprecated cache_choice (never used), see https://docs.djangoproject.com/en/1.8/releases/1.8/#cache-choices-option-of-modelchoicefield-and-modelmultiplechoicefield
- resolve experimenter form password order issue reported in https://trac.openmicroscopy.org/ome/ticket/13063 //cc: @pwalczysko 
Testing servers: cowfish/integration and eel/merge
To test:
- check on both servers if experimenter form fields are in the right order, see https://github.com/openmicroscopy/openmicroscopy/pull/4236#issuecomment-147668137
- test annotation forms (comment, tag, etc.)
=> Django upgrade follow up

components/tools/OmeroM/src/annotations/updateOriginalFile.m, components/tools/OmeroM/src/image/getRawPixelsStore.m, components/tools/OmeroM/src/image/getThumbnail.m, components/tools/OmeroM/src/image/getThumbnailByLongestSide.m, components/tools/OmeroM/src/image/getThumbnailByLongestSideSet.m, components/tools/OmeroM/src/image/getThumbnailSet.m, components/tools/OmeroM/src/image/loadChannels.m, components/tools/OmeroM/src/io/getObjects.m, examples/Training/matlab/ReadData.m
This PR fixes a bug encountered while working on MultiMOT with the new multi-group functionality included in OMERO.matlab 5.1.4.
When retrieving objects in a different group than the session group, the method call resulted in exceptions of type `java.lang.Character cannot be cast to java.lang.String`. This exception was not thrown when passing `-1` as the group.
This PR reviews all usages of the group context in OMERO.matlab and unconditionally casts the `groupId` as a `java.lang.String`. The training examples are updated to also read object in a specified group. /cc @emilroz
=> OMERO.matlab: always cast the group to a java.lang.String

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/metadata_acquisition.html
This is the equivalent on #4231 for Insight.
Removes the label "t index" to "t" and uses 1-based time indices.
To test, check that time stamps look same in web and Insight.
=> t index formatting

components/blitz/src/ome/formats/OMEROMetadataStoreClient.java, components/model/test/ome/util/utests/LSIDEquivilenceTest.java
The check of List.contains(LSID) was extremely time expensive.
This code could use a further refactoring but that will mean
changing public methods. Instead, here we simply maintain a
map of checks which can be used to speed up the parsing.
cc: @chris-allan @jburel @mtbc
=> OMEROMetadataStoreClient: speed up import for many LSIDs

components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/Analyser.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/GraphPane.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/IntensityView.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/MeasurementViewerControl.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/MeasurementViewerModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/MeasurementViewerUI.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/ImageDataView.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/ImageDataViewImpl.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/Analyser.java, components/insight/SRC/org/openmicroscopy/shoola/env/rnd/roi/ROIAnalyser.java
Further improvement of the ROI analysis, see [Trello card](https://trello.com/c/3HccWkMv/40-roi-memory-issue)
With this PR only the shape of the current active plane is analyzed, not the full stack, which should speed up the analysis significantly for large ROIs which are populated through several planes.
Test: Create a large ROI (which covers a lot of pixels), populate it through the stack. Perform an analysis by switching to the Graph Pane. Move through the stack via the sliders. The newly selected plane should then get analyzed and the diagram updated automatically. Check that the results make sense. Ideally this should be tested with different kinds of images (single plane, multi-z, multi-t, multi-z/t).
Also have a look at the Intensity View.
--
Second attempt, with less code changes, …
=> Only analyze shapes of the current plane

components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/jquery.jstree.truncatetext_plugin.js, components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/ome.webclient.actions.js
Fixes the jsTree truncation issue in Firefox reported at https://github.com/openmicroscopy/openmicroscopy/pull/4242#issuecomment-150160802
To test, try the truncation of long image names (and P/D names) in Firefox, Chrome, Safari and IE (not tried IE yet).
=> Fix jsTree truncation

build.xml, components/common/src/ome/system/UpgradeCheck.java
This should fix the remaining warning of https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-merge-build/
=> Fix broken link to the SpringFramework API in the Javadoc

components/tools/OmeroPy/src/omero/plugins/admin.py, components/tools/OmeroPy/test/integration/clitest/test_admin.py
Add `omero admin checkupgrade`
This allows scripts to automatically determine whether an updated server is available. Sets exit code 1 if so. To test.... you'll have to override the current server version somehow, or trust the integration test.
If you want to be thorough check an invalid `omero.upgrades.url` sets an exit code that's not 0 or 1.
~~TODO. Since this is going in to 5.2 should we set a specific agent to distinguish upgrade checks from server startups. e.g. `OMERO.status`, `OMERO.upgrade`, ... ?~~
=> Add `omero admin checkupgrade`

components/tests/ui/testcases/web/forms_test.txt, components/tests/ui/testcases/web/map_annotations_test.txt, components/tests/ui/testcases/web/tagging_test.txt, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/batch_annotate.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/includes/name.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/mapannotations.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/metadata_acquisition.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/metadata_general.html
This is the first part of the right panel update from https://docs.google.com/document/d/1C__ZB0uyX3295Fop-k-fcQIL53NaKrZcuZ3N0OBDMb0/edit#
In this PR we simply split the main "General" tab content into separate collapsible panes.
We don't yet change how data is loaded or provide annotation counts in the pane headers.
To test:
- Browse P/D/I S/P/W and check that panel looks OK and tabs expand when clicked and contain correct data (maybe compare with viewing same data in Insight)
- Filter Annotations by user and check this still works as expected
Some differences with mock-ups:
- I've kept ```Image ID``` and ```Owner``` above each other, with the "Show All" selector to the right. I think this looks neater than having them on the same row. @gusferguson Do you think the "Show All" selector …
=> Right panel general panes

components/tools/OmeroWeb/omeroweb/settings.py
This is #4277 follow up PR. It fixes:
- SECRET_KEY that become really secret and unique
To test:
- check if secret key was generated and saved in dist/var/django_secret_key
Note: looks like we cannot put it in web plugin as there are other places loading settings.
=> Generating key into the file

components/insight/SRC/org/openmicroscopy/shoola/env/data/OMEROGateway.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/OmeroMetadataServiceImpl.java
Fix for [Ticket 13067 - BUG: Cannot remove file attachment](https://trac.openmicroscopy.org/ome/ticket/13067)
Nearly missed this ticket, sorry. It's not a regression for 5.2.0, this bug has always been there, but would be nice to still get it into 5.2.0. What do you think, @jburel @sbesson , exclude or not?
**Test**: Add file annotations to a screen, a plate and a plate run. Remove the file annotations again.
=> Bugfix: Remove SPW attachments

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/public/public.html, components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/css/ome.jstree_theme.css
Fixes Row 28 of this morning's testing report:
To test, disable one of your shares and check (after refreshing tree) that the share in tree is a lighter colour icon.
=> Show own 'INACTIVE' shares in lighter color

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/container_tags.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/containers.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/public/public.html
As suggested in testing, this renames the "Public" tab to "Shares", which makes more sense since the data under that tab is in no way "Public". This is also more consistent with E.g. "Tags" tab containing Tags and "Shares" tab containing Shares.
@gusferguson @aleksandra-tarkowska Does this make sense to you?
@gusferguson If we go ahead with this fix and it requires changes to a lot of screenshots, I'm happy to help update screenshots in Photoshop (should be quite quick to patch the label change).
=> Rename 'Public' tab to 'Shares'

components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/ome.chgrp.js, components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/ome.webclient.actions.js, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/includes/center_plugin.thumbs.js.html
This fixes a number of bugs reported at today's testing. To test:
- Row 26 In Firefox & IE, browse a Dataset with many thumbnails (so that a scrollbar is shown to their right), select some thumbnails (drag select thumbs or select in tree). Then drag the scrollbar to scroll the thumbnails. Selection shouldn't change (shouldn't see drag-select region as you drag).
- Rows 21 & 22 - In a large Dataset (200 images) changes in selection in jsTree should be instantly updated in centre panel. No delay.
- Row 25: Selection changes in jsTree should not scroll centre panel. E.g scroll to bottom of thumbnail panel, select a thumbnail. Then in jsTree, select next thumbnail. Thumb panel shouldn't scroll.
Other fixes:
- Filter images by text in filter field. Then change selection of images (same …
=> Thumbnail scrolling & selection

components/tools/OmeroPy/src/omero/plugins/web.py, components/tools/OmeroPy/test/unit/clitest/reference_templates/apache-withoptions.conf, components/tools/OmeroPy/test/unit/clitest/reference_templates/apache.conf, components/tools/OmeroPy/test/unit/clitest/test_web.py, components/tools/OmeroWeb/omeroweb/settings.py, etc/templates/web/apache.conf.template, etc/templates/web/nginx-development.conf.template, etc/templates/web/nginx.conf.template
This PR improve web plugin starting and stopping OMERO.web app
To test:
- start web twice, you should get error message saying already started.
- check if ``WARNINGS: ?: (1_8.W001) The standalone TEMPLATE_* settings...`` disappeared. When deploying with development server you will see ``System check identified no issues (1 silenced).``
- check if ``dist/var/django_secret_key`` file has correct permission (CHECK WINDOWS!):
```
-rw-------   1 omero  staff   50 24 Oct 14:58 django_secret_key
```
- run ``bin\omero web iis -h`` and check if you see only:
```
usage: dist/bin/omero web iis [-h] [--remove] [--keep-sessions | --no-wait]
...
```
- run ``bin\omero web start|restart -h`` and check if you get 
```
usage: dist/bin/omero web start [-h] [--keep-sessions | --no-wait]
[--workers WORKERS] …
```
=> Web deploy

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/includes/center_plugin.thumbs.js.html
Fixes update of thumbnails on rendering settings 'Save' and 'Save to All'.
To test:
- Save rendering settings on an image in Preview panel - thumbnail should update.
- "Save All" should update all thumbnails.
- Also check that right-click Rendering Settings options update thumbnails as expected.
=> Fix update of thumbnails on rdef 'Save' and 'Save to All'

components/tools/OmeroPy/src/omero/plugins/web.py
Fix a bug reported during 5.2.0-rc2 testing
Without this PR, `bin/omero web restart` should fail with an `argparse` related error. With it, its behavior should be restored and OMERO.web should be restarted.
=> Add nginx arguments to restart command

components/tools/OmeroPy/src/omero/plugins/web.py
@manics this should fix https://trello.com/c/07pqxE0t/100-omero-web-config-nginx-should-warn-but-not-fail
```
$ dist/bin/omero web config nginx
upstream omeroweb {
server 127.0.0.1:4080 fail_timeout=0;
}
...
$ dist/bin/omero web config apache
ERROR: configuration mismatch. omero.web.application_server=wsgi-tcp cannot be used with 'omero web config apache'.
$ dist/bin/omero web start
Post-processed 'omeroweb.viewer.min.css' as 'omeroweb.viewer.min.css'
Post-processed 'omeroweb.viewer.min.js' as 'omeroweb.viewer.min.js'
0 static files copied to '/Users/ola/OMERO/openmicroscopy/dist/lib/python/omeroweb/static', 618 unmodified, 2 post-processed.
Clearing expired sessions. This may take some time... 
[OK]
Starting OMERO.web... [FAILED]
ERROR: FastCGI support was removed in OMERO 5.2. Install …
```
=> allowing generate config even gunicorn is not installed

history.txt
Adds the version history for the 5.2.0. Will be staged on https://www.openmicroscopy.org/site/support/omero5.2-staging/users/history.html once the builds have run
=> 5.2.0 history

components/tools/OmeroPy/src/omero/plugins/web.py
This PR should help preventing people from deploying web with incorrect Django version. As we noticed over testing, people tend to ``pip install django``, that in few weeks will install 1.9. Currently web is only compatible with 1.6 and 1.8
```
$ dist/bin/omero web start
Django version '1.9b1' is not supported!
$ dist/bin/omero web config nginx
Django version 1.5.9 is not supported!
$ dist/bin/omero web config nginx
Django version 1.4.22 is not supported!
```
=> restricting Django version

components/tools/OmeroPy/src/omero/config.py, components/tools/OmeroPy/test/unit/test_config.py
This PR addresses two related issues in `ConfigXml.open_source` (from `omero/config.py`):
* The method assumes that the config file is read-only if it cannot be opened in `a+` mode, while in reality the `open` call can fail for several other reasons. In particular, if `etc/grid` exists but it's not writable, the exception is raised by the subsequent open-for-read attempt, and the final error message suggests that something is missing:
```
$ dist/bin/omero config set omero.data.dir /OMERO
[Errno 2] No such file or directory: '[...]/dist/etc/grid/config.xml'
```
This is addressed by the first commit. **To test:**
```
$ mkdir -p dist/etc/grid
$ rm -rf dist/etc/grid/*
$ chmod 555 dist/etc/grid
$ dist/bin/omero config set omero.data.dir /OMERO
[Errno 13] Permission denied: …
```
=> Fix config creation

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/plate.html
Fixes https://trello.com/c/eyNU6sWg/25-critical-loss-of-hierarchy-selection
To test:
- Find / create a Plate with a Run and a Plate without Run (E.g. from Dataset to Plate script).
- Browse in tree, then select a Well by clicking.
- Parent Run / Plate should remain selected in tree, while right panel should show the selected well.
- Try selecting multiple wells by dragging or shift-click. Should get same result.
- In both cases, toolbar buttons in the tree should get disabled (except those for creating top-level P/D/S).
- Clicking parent in the tree should re-enable toolbar buttons as before, and show parent in right panel again.
=> SPW deselection in tree

components/blitz/src/omero/gateway/Connector.java, components/blitz/src/omero/gateway/Gateway.java, components/blitz/src/omero/gateway/SecurityContext.java, components/blitz/src/omero/gateway/facility/BrowseFacility.java, components/blitz/src/omero/gateway/facility/DataManagerFacility.java, components/blitz/src/omero/gateway/facility/Facility.java, components/blitz/src/omero/gateway/facility/ROIFacility.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/DataServicesFactory.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/GatewayMonitor.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/OMEROGateway.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/OmeroDataServiceImpl.java
Fixes [Ticket 12929](https://trac.openmicroscopy.org/ome/ticket/12929)
Problem: After an object has been saved the connector was shutdown. This could lead to an abortion of a parallel running import job. This PR removes the connector shutdown, because it's actually not necessary at that point anyway.
**Test**:
Follow the workflow which previously triggered this bug, which is:
- Log in as a group owner or administrator
- *Start*  (not just add to the queue) a long running import job for another user
- Now start another import for the user you're logged in with, but import into a particular dataset which you have to create first on the import dialog (this caused the crash)
- Make sure the imports are passing like expected.
Note: The actual bugfix is just commit 979098b . The first commits …
=> Bugfix: Import As freezes

examples/Training/python/ROIs.py, examples/Training/python/__main__.py
Update ROIs.py example in python training docs.
Also turns on the ROIs.py examples in the training job - check status at https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-merge-training/
=> Fix python Training ROIs

components/tools/OmeroPy/src/omero/plugins/web.py, components/tools/OmeroPy/test/unit/clitest/test_web.py
Test nginx (no webserver needed)
```
$ dist/bin/omero web restart
Stopping OMERO.web... [NOT STARTED]
Post-processed 'omeroweb.viewer.min.css' as 'omeroweb.viewer.min.css'
Post-processed 'omeroweb.viewer.min.js' as 'omeroweb.viewer.min.js'
0 static files copied to '/Users/ola/OMERO/openmicroscopy/dist/lib/python/omeroweb/static', 618 unmodified, 2 post-processed.
Clearing expired sessions. This may take some time... [OK]
Starting OMERO.web... [OK]
```
Open localhost:4080 (you won't see statics)
```
$ dist/bin/omero web status
OMERO.web status... [RUNNING] (PID 7272)
$ cat dist/var/django.pid 
7272
$ dist/bin/omero web start
Post-processed 'omeroweb.viewer.min.css' as 'omeroweb.viewer.min.css'
Post-processed 'omeroweb.viewer.min.js' as 'omeroweb.viewer.min.js'
0 static files copied to …
```
=> Improve web deploy

components/tools/OmeroWeb/omeroweb/feedback/views.py, components/tools/OmeroWeb/omeroweb/settings.py
This PR fixes https://trac.openmicroscopy.org/ome/ticket/13091
With Django 1.8 ``repr(request)`` is no longer friendly that means we were missing WSGIRequest details in feedback form.
To test on eel (Django 1.6) and cowfish (Django 1.8):
- go to ``weberror/error_500`` and check if you get WSGIRequest GET, POST, COOKIE and META information along side stacktrace
```
Traceback (most recent call last):
...
NameError: global name 'view_raise_500' is not defined
<WSGIRequest
path:/weberror/error_500/,
GET:...
POST:...
COOKIES:...
META:...
```
- check if admin notification sent exactly the same data (notofication goes to: ci-web-errors).
- check if log on eel shows WSGIRequest details (this is still broken on cowfish, see https://trac.openmicroscopy.org/ome/ticket/13090)
=> Error report via feedback

components/blitz/resources/ome/services/blitz-graph-rules.xml, components/blitz/resources/ome/services/blitz-servantDefinitions.xml, components/blitz/resources/ome/services/graph-rules/blitz-delete-rules.xml, components/blitz/resources/ome/services/graph-rules/blitz-duplicate-rules.xml, components/blitz/resources/omero/RTypes.ice, components/blitz/resources/omero/cmd/Graphs.ice, components/blitz/src/omero/cmd/RequestObjectFactoryRegistry.java, components/blitz/src/omero/cmd/graphs/Chgrp2I.java, components/blitz/src/omero/cmd/graphs/Chmod2I.java, components/blitz/src/omero/cmd/graphs/Delete2I.java, components/blitz/src/omero/cmd/graphs/DuplicateI.java, components/blitz/src/omero/cmd/graphs/GraphUtil.java, components/blitz/src/omero/cmd/graphs/SkipHeadI.java, components/blitz/src/omero/cmd/graphs/SkipTailPolicy.java, components/blitz/src/omero/cmd/graphs/SpecificityClassifier.java, components/blitz/test/omero/cmd/graphs/SpecificityClassifierTest.java, components/server/src/ome/logic/QueryImpl.java, components/server/src/ome/services/fulltext/FullTextThread.java, components/server/src/ome/services/graphs/GraphPathBean.java, components/server/src/ome/services/graphs/GraphTraversal.java, components/tools/OmeroJava/test/integration/DuplicationTest.java
To copy instruments for http://trac.openmicroscopy.org/ome/ticket/11532 and ROIs for the folder/template work, some ability for deep copy would be useful. This is the initial version sufficient to serve those two needs. It does not yet offer everything: for instance, original files cannot be copied without a breaking database schema change, so if one tries to copy an image, one will still find acquisition data, etc., but no actual pixels. Check that https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-java/lastCompletedBuild/testngreports/integration/DuplicationTest/ passes and that `./build.py -f components/blitz/build.xml test -DTEST=omero/cmd/graphs/SpecificityClassifierTest` passes.
To test further, you would have to try creating `DuplicateI` requests from a client. If …
=> add initial version of deep copy to server

components/tests/ui/resources/robot.template, components/tests/ui/testcases/web/create_scenario.txt, components/tests/ui/testcases/web/rdef_test.txt
Fixes various failing robot tests:
- In Create Scenario, https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-robotframework/157/robot/Web%20&%20Web/Web/Create%20Scenario/Test%20Container%20Creation%20Enabled/ instead of checking that the full Firstname and Lastname is in jsTree, we just check for Lastname, so that ```...irstname Lastname``` is matched, since it contains Lastname.
- For rdef tests, we now click on the jsTree to select images following a "Save All" or other actions that refreshThumbnails(), since the clicking thumbnails gives us "Element not in DOM". Fixes E.g. https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-robotframework/157/robot/Web%20&%20Web/Web/Rdef%20Test/Test%20Owners%20Rdef/
- We now reset rdefs to "imported" on the Dataset at the start of …
=> Fix Robot failure when long usernames truncated in jstree

components/tools/OmeroPy/test/unit/clitest/reference_templates/nginx-development-withoptions.conf, components/tools/OmeroPy/test/unit/clitest/reference_templates/nginx-development.conf, components/tools/OmeroPy/test/unit/clitest/reference_templates/nginx-withoptions.conf, components/tools/OmeroPy/test/unit/clitest/reference_templates/nginx.conf, components/tools/OmeroWeb/omeroweb/settings.py, etc/templates/web/nginx-development.conf.template, etc/templates/web/nginx.conf.template
This PR should fix incorrect redirection to ``​http://`` instead of ​``https://``
```
curl -i -s -c cookies.txt -b cookies.txt -e https://omero.local/omero/webclient/login/ -d 'csrfmiddlewaretoken=kyuLRduNLY3OQNUMUBiFjuQMDYrcEwt4&username=user-1&password=ome&server=2&url=url=%2Fmerge%2Fwebclient%2F' -X POST https://omero.local/omero/webclient/login/
HTTP/1.1 302 FOUND
Server: nginx/1.8.0
Date: Wed, 18 Nov 2015 13:00:58 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Cookie
Location: https://omero.local/omero/webclient/
Set-Cookie: sessionid=jix75augbw8i6xdwvydru249sq8vaj9n; httponly; Path=/
```
cc @manics see https://trello.com/c/7eFWt9Bj/8-django-secure-proxy-ssl-header
=> Incorrect redirect to http instead of https

components/blitz/src/ome/formats/importer/ImportCandidates.java, components/blitz/src/ome/formats/model/BlitzInstanceProvider.java, components/blitz/src/ome/formats/model/ChannelData.java, components/blitz/src/ome/formats/model/ChannelProcessor.java, components/blitz/src/ome/formats/model/ColorsFactory.java, components/blitz/src/ome/formats/model/IObjectContainerStore.java, components/blitz/src/ome/formats/model/InstanceProvider.java, components/blitz/src/ome/formats/model/InstrumentProcessor.java, components/blitz/src/ome/formats/model/ModelException.java, components/blitz/src/ome/formats/model/ModelProcessor.java, components/blitz/src/ome/formats/model/PixelsProcessor.java, components/blitz/src/ome/formats/model/PlaneInfoProcessor.java, components/blitz/src/ome/formats/model/ReferenceProcessor.java, components/blitz/src/ome/formats/model/ShapeProcessor.java, components/blitz/src/ome/formats/model/TargetProcessor.java, components/blitz/src/ome/formats/model/UnitsFactory.java, components/blitz/src/ome/formats/model/WellProcessor.java
This PR fixes a few docstrings in the blitz code. It also reindents `blitz/src/ome/formats/model/*.java`, where a mix of different conventions (most notably tabs and spaces) makes the code hard to read.
**TEST:** check that it does not break anything
=> Blitz: docstring & indentation fixes

components/blitz/src/ome/formats/OMEROMetadataStoreClient.java
This PR addresses a problem encountered when importing `.screen` files.
* *Without* this patch, if the user specifies a screen target, plates are linked to that screen *and* to the screen specified by Bio-Formats' `ScreenReader`
* *With* this patch, the target specified by the user overrides the BF one
**NOTES**
* It would be nice to simply skip `addReference` in `setScreenPlateRef`, but at that point in the import process `userSpecifiedTarget` has not been set yet (on the server's side)
* `screenKey` should probably be changed to a list, or removed altogether if scanning the whole `referenceCache` for screen-plate refs is not too intensive
* BF adds a screen -> plate ref, while `TargetProcessor` [adds a plate -> screen one](https://github.com/openmicroscopy/openmicroscopy/blob/983abca738b …
=> Fix duplicate screen target

components/blitz/test/ome/formats/utests/ContainerCacheOrderTest.java, components/blitz/test/ome/formats/utests/MetadataValidatorTest.java, components/model/test/ome/util/utests/LSIDEquivalenceTest.java
A trivial PR that fixes the spelling of "equivalence". All should remain green.
--no-rebase
=> fix equivalence typos

components/dsl/resources/ome/dsl/psql-footer.vm, components/tools/travis-build
This is the same as gh-4334 but rebased onto regions.
----
see: https://trello.com/c/ztZtO5t6/75-5-2-schema-generation-is-busted
To test:
* `ant build-schema`
* `ant build-default`
* `dist/bin/omero db script --password ome -f- | psql $YOURDB` should no longer fail.
Note: https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration has been updated to perform the same test.
=> 5.2 DB: fix script generation (rebased onto regions)

components/dsl/resources/ome/dsl/psql-footer.vm, components/tools/travis-build
see: https://trello.com/c/ztZtO5t6/75-5-2-schema-generation-is-busted
To test:
* `ant build-schema`
* `ant build-default`
* `dist/bin/omero db script --password ome -f- | psql $YOURDB` should no longer fail.
Note: https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration has been updated to perform the same test.
=> 5.2 DB: fix script generation

components/server/src/ome/services/graphs/GraphPathBean.java, components/tools/OmeroJava/test/integration/delete/AdditionalDeleteTest.java, components/tools/OmeroPy/test/integration/clitest/test_delete.py
Now for the CLI graph operations you should be able to name classes as `FooI` rather than just `Foo`. See https://trello.com/c/xdnCqVZy/609-omero-delete-doesn-t-handle-objecti.
--no-rebase
=> for graph operations allow model subclasses to be named

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorModel.java
Fixes  [Ticket 13109](http://trac.openmicroscopy.org/ome/ticket/13109)
Test: Select a large image ( > 47k x 47k), check that the export options (JPG, PNG, etc.) are all disabled.
Fortunately it could only cause Insight to crash with an OOM exception, no spacecraft disasters...
=> Fixed integer overflow

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/icon_thumbnails_underscore.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/includes/center_plugin.thumbs.js.html
This addresses comment at https://github.com/openmicroscopy/openmicroscopy/pull/4242#issuecomment-150147878 which is listed on https://trello.com/c/6ugBp0HG/5-web-center-panel-follow-up.
To test, find a dataset with a large number of images (so that the centre panel needs scrolling).
- In the tree, select the dataset, then select an image near the bottom. Centre panel should scroll to that thumbnail.
- Hotkeys should continue to work in jsTree as usual, with centre panel scrolling as needed to show selected thumbnail.
- This should also work when in "table" view in centre panel
- Switching between table and icon views should maintain the selected thumbnail in view (scroll to show it if needed)
=> Scroll to selected thumbnail

components/tools/OmeroWeb/omeroweb/webadmin/templates/webadmin/includes/drivespaceStats.js
See http://trac.openmicroscopy.org/ome/ticket/13042
As suggested by @mtbc, just removed the 'tilt' attribute from the pie chart plugin.
To test, login as admin and look at Statistics tab for all users, and/or group owner and look at statistics for your owned groups.
In both cases, pie chart should be round, not an ellipse:
=> Remove 'tilt' from stats pie chart

components/blitz/src/omero/cmd/graphs/Chgrp2I.java, components/blitz/src/omero/cmd/graphs/Chmod2I.java, components/blitz/src/omero/cmd/graphs/Chown2I.java, components/blitz/src/omero/cmd/graphs/Delete2I.java, components/blitz/src/omero/cmd/graphs/DuplicateI.java, components/blitz/src/omero/cmd/graphs/GraphUtil.java, components/blitz/src/omero/cmd/graphs/SkipHeadI.java
Adjust ` etc/logback.xml` such that `omero.cmd.graphs` is logged at `DEBUG`, then try some graph requests (delete, move, whatever you like) and see that the request parameters and the response values are logged in `Blitz-0.log`.
--no-rebase
=> log parameters and results of graph requests

build.xml, components/tools/bump_bf_version.py
See https://trello.com/c/jyrfor6w/99-cross-reference-javadocs. This Request:
- modifies the `release-javadocs` build target to allow the OMERO API to create hyperlink to the Bio-Formats API documentation
- modifies the `bump_bf_version.py` script to bump this Javadoc link for release version numbers
To test it:
- check the [OMERO Javadoc](https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-merge-build/ICE=3.5,jdk=8_LATEST,label=octopus/javadoc/) links to the [Bio-Formats Javadoc](http://downloads.openmicroscopy.org/bio-formats/5.1.6/api/) - see the Trello card for an example of page with cross-references
- check that the bump script also bumps the Bio-Formats API URL when a non-SNAPSHOT version number is passed i.e. 
```
./components/tools/bump_bf_version.py 5.1.7-SNAPSHOT …
```
=> Bio-Formats Javadoc

components/tools/OmeroPy/src/omero/plugins/web.py, components/tools/OmeroPy/test/unit/clitest/reference_templates/apache22-withoptions.conf, components/tools/OmeroPy/test/unit/clitest/reference_templates/apache22.conf, components/tools/OmeroPy/test/unit/clitest/reference_templates/apache24-withoptions.conf, components/tools/OmeroPy/test/unit/clitest/reference_templates/apache24.conf, components/tools/OmeroPy/test/unit/clitest/test_web.py, etc/templates/web/apache22.conf.template, etc/templates/web/apache24.conf.template
1. hanging web
> For each vhost Django site should use a separate daemon process group. WSGIApplicationGroup %{GLOBAL} https://code.google.com/p/modwsgi/wiki/ConfigurationDirectives#WSGIApplicationGroup is forcing the use of the main interpreter context within the respective process groups. It is not shared across process groups.
Looks like we are using Python modules (IcePy?) that are not loaded correctly in Python sub interpreters, see https://code.google.com/p/modwsgi/wiki/ApplicationIssues#Python_Simplified_GIL_State_API
To test:
- delete image and check activities, it shouldn't hang anymore.
1. I also updated python-path as it was missing env, cc @kennethgillen 
To test:
-  default ``PYTHONPATH``
- set ``bin/omero config set omero.web.application_server 'wsgi'``
- make sure there is …
=> Fixing hanging Ice callback

components/model/resources/ome/util/actions/default.properties
This changes the `stats_info_creation` SQL action from using a `select`
subclause to the more appropriate `values (...)`.
=> Correct the stats_info_creation SQL action

components/insight/SRC/org/openmicroscopy/shoola/env/ui/OpenObjectActivity.java, components/insight/SRC/org/openmicroscopy/shoola/env/ui/OpenObjectLoader.java, components/insight/SRC/org/openmicroscopy/shoola/env/ui/UserNotifierImpl.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/UIUtilities.java
See [Ticket 13055](http://trac.openmicroscopy.org/ome/ticket/13055)
There were two issues:
- Open with ImageJ/Fiji always failed on Windows, because of the backslash path separator.
- Open with ImageJ/Fiji also failed on OSX with images which had spaces in the image name
With this PR non-word characters in the name for the temporary file for the 'open with' action are always replaced by underscores (to reduce the risk of complications with any external application) and the windows backslash is replaced by a slash before passing the path on to the ImageJ/Fiji bioformats importer.
**Test:**
- 'Open with' ImageJ and Fiji on OSX and Windows with an image which previously triggered the issue (white space(s) in image name).
- 'Open with' another application, e. g. Paint etc.; just to be sure …
=> Bugfix: 'Open with' external application

components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/MeasurementViewerUI.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/MessageBox.java
Bugfix for [Ticket 13037](trac.openmicroscopy.org/ome/ticket/13037), [Trello - Insight: Measurement tool follow up](https://trello.com/c/DMWzJr97/6-insight-measurement-tool-follow-up)
**Test**:
Open an image with several ROIs. Make sure, deleting *single* ROIs (via context menu), deleting *multiple* ROIs (via context menu) and deleting *all* ROIs (via toolbar menu) works like expected. After each step close the full viewer and reopen it again. In every case the ROIs should get deleted immediately, no confirmation dialog should pop up when closing the full viewer.
Note: There is still a little discrepancy between ROIs and other annotation. Deleting ROIs triggers an 'activity' whereas for example removing tags does not. Might tackle this in separate PR.
=> Immediately delete ROIs

components/tools/OmeroPy/src/omero/plugins/admin.py, components/tools/OmeroPy/src/omero/plugins/prefs.py, components/tools/OmeroPy/test/integration/clitest/test_admin.py
This should allow both the diagnostics and the checkupgrade upgrade check call to share the same logic especially when retrieving the upgrade URL from the server configuration.
To test this PR, run `bin/omero admin diagnostics` and `bin/omero admin checkupgrade` from a server configured to use the staging registry URL and check both `OMERO.diagnostics` and `OMERO.test` agents are recorded in the staging registry DB.
=> Refactor upgrade_check functionalities in the CLI admin plugin

components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/ImageAcquisitionComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/util/EditorUtil.java
Don't try to convert the unit for image acquisition position to reference frame, just display as it is.
Fixes [Ticket 13097](https://trac.openmicroscopy.org/ome/ticket/13097)
Test:
Display image acquisition metadata for an image which does not use reference frame as unit, e. g. eel, user-5,image id 26061 (or the images from the bug report, eel, user-5/read-write-1, Dataset name 16890)
=> Don't try to convert to referenceframe

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/CommentsTaskPaneUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorControl.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/MapTaskPaneUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/PropertiesUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/ToolBar.java
See [Trello - insight: Right-hand panel follow up](https://trello.com/c/74yV81oZ/9-insight-right-hand-panel-follow-up)
- Removes the "Save" button from the metadata panel (changes are saved anyway, no need for the button anymore); *Test*: Make sure the button is gone; add/edit some data, make sure its stored automatically.
- Fixes "Comments" for multiselection, [Ticket 13083](https://trac.openmicroscopy.org/ome/ticket/13083); *Test*: Select multiple dataobjects and add a comment; make sure the comment is added to all objects. Select multiple dataobjects with different comments; make sure you see all comments of all selected objects.
- Fixes [Small bug in Dataset_To_Plate.py](https://www.openmicroscopy.org/community/viewtopic.php?f=4&t=7920). Problem wasn't caused by python script, just …
=> Metadata panel followup 1

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/containers.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/includes/center_plugin.thumbs.js.html
Fixes a failure of the centre panel to update when you paste an image into selected Dataset.
To test:
- Copy an image from a Dataset
- Select another Dataset
- Paste the image and check that centre panel updates to show it
=> Fix centre panel refresh on paste

components/insight/SRC/org/openmicroscopy/shoola/agents/dataBrowser/browser/Browser.java, components/insight/SRC/org/openmicroscopy/shoola/agents/dataBrowser/browser/BrowserControl.java, components/insight/SRC/org/openmicroscopy/shoola/agents/dataBrowser/browser/BrowserModel.java
Fixes [Ticket 13092](https://trac.openmicroscopy.org/ome/ticket/13092)
Test: Check that multi-selection (holding shift key) works for wells; check that the bug fixed by #4219 isn't re-introduced again by this PR
/cc @jburel
=> Bugfix for ticket 13092

components/insight/SRC/org/openmicroscopy/shoola/agents/dataBrowser/view/DataBrowserComponent.java
This would fix the NPE of ticket 12546, although I don't know the real cause for this (and therefore can't say how to test it). ```wm.getSelectedWell()``` is the only object which theoretically could be ```null``` in the line of code which triggered the NPE, so this PR at least provides a workaround for the issue (i. e. prevents Insight from crashing).
Test: Code review only (as I've not been able to reproduce the NPE)
=> Ticket 12546

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/RendererComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewerComponent.java, components/insight/SRC/org/openmicroscopy/shoola/util/PojosUtil.java
Proposal for fixing [Ticket 13104](http://trac.openmicroscopy.org/ome/ticket/13104)
With this PR a warning dialog is only shown when all images of a dataset are affected by a rendering settings change action:
- Save to All
- Paste rendering settings on a dataset
- Reset to owner on dataset level
- Reset to imported on dataset level
But *not* if only one or a selection of images is affected, i. e. deliberately pasting a rendering setting on a selected image (in that case the user is well aware what he's doing - in my opinion). 
This is not in sync with OMERO.web yet. But as I just noticed, the current state is also not in sync with OMERO.web anyway (e. g. web doesn't show a warning on "save to all").
/cc @gusferguson @pwalczysko
=> Rendering settings warning

components/insight/ivy.xml
Build logs contain,
```
javax.xml#jaxrpc;1.1 is relocated to javax.xml#jaxrpc-api;1.1. Please update your dependencies.
```
See http://mvnrepository.com/artifact/javax.xml/jaxrpc/1.1: "This artifact was moved..."
--no-rebase
=> update Insight's reference to JAX-RPC artifact

components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/GraphPane.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/IntensityView.java
Bugfix: Unevenly propagated 4D ROIs sometimes caused unnecessary (and ineffective) Z/T sliders being displayed in Graph Pane and Intensity View.
See [Trello - Insight: Measurement tool follow up](https://trello.com/c/DMWzJr97/6-insight-measurement-tool-follow-up)
**Test:**
- Open measurement tool for a 4D multi-Z/T image
- Create an ROI and propagate it through several Z planes and through several T planes (but not for all Z planes!), so that you have something like on the screenshot below.
Check the Graph Pane and the Intensity View:
- Make sure, that the T slider is only displayed if the current Z plane has multiple timepoints
- Make sure, that the Z slider is only displayed if the current T plane has multiple Z planes.
=> Bugfix: ROI tool z/t slider

components/tools/OmeroPy/test/unit/clitest/reference_templates/apache22-withoptions.conf, components/tools/OmeroPy/test/unit/clitest/reference_templates/apache22.conf, components/tools/OmeroPy/test/unit/clitest/reference_templates/apache24-withoptions.conf, components/tools/OmeroPy/test/unit/clitest/reference_templates/apache24.conf, components/tools/OmeroPy/test/unit/clitest/test_web.py, components/tools/OmeroWeb/omeroweb/wsgi.py, etc/templates/web/apache22.conf.template, etc/templates/web/apache24.conf.template
This PR improve Apache templates to allow multiple wsgi apps deployment under the same VirtualHost
----------
As we do not have any apache testing environment, this is deployed on 2.2
- http://ola-test-1.docker.openmicroscopy.org/omero/
- http://ola-test-1.docker.openmicroscopy.org/omero2/
-----------
**Follow the https://www.openmicroscopy.org/site/support/omero5.2/sysadmins/unix/install-web/install-apache.html with new output of the apache config this PR changed. Then merge 2 configs within one VirtualHost as show below**
```
<VirtualHost _default_:80>
WSGIDaemonProcess omeroweb_omero processes=5 threads=1 display-name=%{GROUP} user=omero python-path=/opt/Ice-3.5.1/python:/home/omero/OMERO.server...
WSGIScriptAlias /omero /home/omero/OMERO.server/lib/python/omeroweb/wsgi.py
<Directory …
```
=> Apache cleanup

components/blitz/src/omero/gateway/facility/AdminFacility.java, components/blitz/src/omero/gateway/facility/BrowseFacility.java, components/blitz/src/omero/gateway/facility/DataManagerFacility.java, components/blitz/src/omero/gateway/facility/MetadataFacility.java, components/blitz/src/omero/gateway/facility/ROIFacility.java, components/blitz/src/omero/gateway/facility/SearchFacility.java, components/blitz/src/omero/gateway/facility/TransferFacility.java, components/blitz/src/omero/gateway/facility/TransferFacilityHelper.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/OMEROGateway.java, components/tools/OmeroJava/test/integration/gateway/BrowseFacilityTest.java, components/tools/OmeroJava/test/integration/gateway/MetadataFacilityTest.java, components/tools/OmeroJava/test/integration/gateway/RawDataFacilityTest.java
Contains critical bugfixes which have to go into 5.2.1
- Removes the leaves() parameter where it can be dangerous (accidentally pull *everything* from the server)
=> Gateway followup critical

components/server/src/ome/services/graphs/GraphTraversal.java
This PR should improve the performance of model graph traversal operations without any change in behavior. @joshmoore managed to run into a performance issue that this change should fix.
--no-rebase
=> in graph traversal avoid awful removeAll performance

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/includes/core_metadata.html, components/tools/OmeroWeb/omeroweb/webclient/webclient_gateway.py, components/tools/OmeroWeb/test/integration/test_metadata.py
See https://trello.com/c/7IzMpre0/15-unit-display-in-web
Previously we got the suitable units for sizeX and only displayed these, alongside the most suitable value for sizeX, sizeY and sizeZ. So, if the sizeZ for example was using different units this would appear incorrect:
Now, if units are different for any dimension, we show them:
This is slightly different from Insight's strategy, but to get it exactly the same will require a bigger re-working of the code here (worth it)?
=> Handle display of pixel size units for each dimension

components/tools/OmeroPy/src/omero/gateway/__init__.py, components/tools/OmeroPy/test/integration/gatewaytest/test_plate_wrapper.py
https://trello.com/c/oPlGJKqQ/60-plateacquisitions-in-web-should-show-starttime
Show `PlateAcquisition.startDate` if it's set, otherwise fallback to the previous behaviour.
To test: find a PlateAcquisition with a startTime set. OMERO.web should show this time as the Creation date instead of the import time.
=> Plate acquisition date

components/tools/OmeroWeb/omeroweb/webclient/controller/container.py, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/metadata_general.html
Temporary OMERO.web workarounds so that other metadata PRs can be viewed:
- Display Well annotations as well as Image annotations e.g. Bulk-MapAnnotations from #4037 (normally only Image Annotations are shown when a Well is selected).
- Linkify keys/values in MapAnnotations
--on-hold
=> Temporary web UI workarounds

components/tools/OmeroPy/src/omero/plugins/children.py
Contains methods for moving all children of a parent object, and for managing orphans
I though this might be handy after @eleanorwilliams discovered some problematic screen imports were resulting in a large number of orphaned images, and attempting to delete them in web takes a very long time.
```
omero children move Image:orphan Dataset:1
omero children move --all Dataset:1 Dataset:2
omero children delete Image:orphan
omero children delete --all Image:orphan
```
Todo: Add tests
=> Add CLI children plugin

components/tools/OmeroWeb/omeroweb/webclient/show.py
Fix for https://trello.com/c/XPrUXfTV/49-browse-spw-image-in-search-results-doesn-t-work
cc @manics.
Fixes show=?image-123 when the image is in a well - We browse to the well - Not necessarily the correct well-index (just first index).
This is the first fix I found for this that seems to work (maybe not the 'proper' fix, and no tests etc - in fact it's possible that 'show' tests may fail - haven't tried them yet).
=> Show image in well

components/tools/OmeroPy/src/omero/cli.py, components/tools/OmeroPy/test/integration/clitest/test_delete.py
This PR adds object id elision to the basic output from CLI delete, chgrp, etc. This has been in the detailed report for some time but had been omitted from the default response. See https://trello.com/c/Y37tzyrK/25-missing-range-collapsing-on-delete
To test import and then move or delete a number of objects and check the response. 
```
$ omero delete Image:1,2,3
...
omero.cmd.Delete2 Image:1-3 ok
```
Try with broken sequences of ids too, the results should not be surprising!
The added test should pass.
=> Elide object ids in standard CLI output

components/server/src/ome/services/graphs/GraphPathBean.java
RFE documented at https://trello.com/c/XyOslw9x/24-reduce-warn-in-graphpathbean. Check the `Blitz-0.log` after the server starts up for a lack of the mentioned warnings. One needn't do anything with a client.
--no-rebase
=> adjust log level for probing nested simple properties

components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewerComponent.java
This PR makes sure the project/dataset is expanded when you double click on the project/dataset node in the Location dialog; fixes [Ticket 13076](https://trac.openmicroscopy.org/ome/ticket/13076)
**Test**: Follow the workflow described in the ticket.
=> Ticket 13076

components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/IntensityResultsView.java
Just fixes a NPE in the measurement tool, see [Trello - Measurement Tool](https://trello.com/c/HbaU4XcU/17-measurement-tool).
**Test**: Open a multi-z (and/or -t) image. Create an ROI. Propagate the ROI through some z (and/or t) planes. Select the ROI. Go to intensity results view. Click on "Add selected". The ROI of the current plane should be added to the results table (without the PR: Crash due to NPE).
=> Prevent NPE in IntensityResultsView

components/insight/SRC/org/openmicroscopy/shoola/env/ui/SplashScreenManager.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/UIUtilities.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/tdialog/TinyDialog.java
This is a workaround for https://bugzilla.gnome.org/show_bug.cgi?id=759492 , respectively  [OME forum post](http://www.openmicroscopy.org/community/viewtopic.php?f=5&t=7966). I wrapped the workaround in a method in UIUtilities so it can be easily removed again when/if this gets fixed in Gnome3.
**Test**:
Start Insight on an OS with Gnome3 desktop (i. e. Debian (Jessie) default desktop). You should see the normal login screen (without the PR you'd just see a grey rectangle). Test the "Show parent project" and "Show location on server" pop up dialogs (buttons see toolbar in right hand side metadata panel). Select an image with a file attachment. Test the "Info..." dialog on the attachment. Again, without the PR these would just be grey rectangles.
=> Workaround for Gnome3 bug

components/tools/OmeroPy/src/omero/plugins/admin.py, components/tools/OmeroWeb/omeroweb/settings.py, etc/templates/grid/default.xml, etc/templates/grid/templates.xml, etc/templates/grid/windefault.xml, etc/templates/ice.config, etc/templates/internal.cfg, etc/templates/master.cfg
`Ice.Default.Host` is useful when running multiple servers on the same host, but appears to break a multi-host OMERO.grid setup. My guess is that `Ice.Default.Host` is propagated to the slave nodes which then attempt to listen on that invalid IP (feature? bug? your guess).
This replaces `Ice.Default.Host` with a new property `omero.master.host` that allows the master's IP to be set in all templates as described in https://www.openmicroscopy.org/site/support/omero5.2/sysadmins/grid.html#nodes-on-multiple-hosts without actually setting `Ice.Default.Host`.
The single host behaviour should be identical to before, `Ice.Default.Host` is used in all templates and the server should only listen on `Ice.Default.Host`.
See
- https://trello.com/c/3fY2taKP/37-omero-grid-omero-node-bugs-issues
- …
=> Don't set Ice.Default.Host by default

components/blitz/src/ome/services/blitz/impl/OmeroMetadata.java
Fixes export of ROIs to write valid OME-XML. To test:
1. Draw ROIs on an image (no masks).
1. Export as OME-TIFF.
1. Import the exported file.
1. Ensure that the ROIs are preserved.
1. Check that the exported file's XML is valid.
For that last step https://www.openmicroscopy.org/site/support/bio-formats5/users/comlinetools/xml-validation.html may help.
--no-rebase
=> fix LSID creation for Shape to fit OME-XML schema

components/blitz/src/ome/formats/OMEROMetadataStoreClient.java
setPixelsFile in OMEROMetadataStoreClient is the only method
which silently catches ServerError. Most methods wrap the SE
in a runtime exception. This avoids silently having
corrupted images.
See:
http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-December/005770.html
**Testing:** Unclear how to reproduce from the email thread. Likely a low-memory issue. Primarily a code-review is necessary.
cc: @chris-allan
=> Raise exception on setPixelsFile failure

components/tools/OmeroWeb/omeroweb/webgateway/urls.py, components/tools/OmeroWeb/omeroweb/webgateway/views.py
This addresses various errors that arise when non-integer values are used in webgateway urls.
The url regex expressions were previously were not ensuring that numbers were used in the url for IDs etc, hence allowing any values to be used.
E.g. ```/webgateway/render_thumbnail/3933597/Simon-Josh/```
See https://trello.com/c/dPcurAje/41-render-thumbnail-invalid-int
Now, all IDs and sizes in webgateway urls use ```[0-9]``` to match only numerical values.
To test, try to go to that url.
In addition, check that the viewer still works OK, line plot, ROIs etc.
In addition, this fixes https://trello.com/c/H1uBUxL8/39-render-roi-thumbnail-index-out-of-range where you get an error ```IndexError: list index out of range``` at ``` webgateway/render_roi_thumbnail/0 ```. This will now give a simple 404 …
=> Webgateway url ids

examples/Training/python/ROIs.py
Carry-on from:
* gh-4412
* http://lists.openmicroscopy.org.uk/pipermail/ome-users/2016-January/005804.html
Thanks to @emilroz
=> Mask python training example

components/tools/OmeroPy/src/omero/gateway/__init__.py, examples/Training/python/Delete.py, examples/Training/python/ROIs.py
This improves our documentation & examples of deleting ROIs with conn.deleteObjects() and gives an example of using the ```wait=True``` parameter.
See http://lists.openmicroscopy.org.uk/pipermail/ome-users/2016-January/005822.html
Check that tests are passing for these examples and the code changes & comments make sense.
=> Delete rois docs

components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/browser/BrowserComponent.java
This would "fix" [Ticket 9490](https://trac.openmicroscopy.org/ome/ticket/9490) by simply just not throwing the exception. I couldn't replicate the issue by any of the actions reported in the QAs, but I found a different way which also throws the exception: In the Projects/Datasets tree switch to Group Display (i. e. disable "Display Users"). Expand the groups. Go to search tab. Search for any image. Select an image in the search results view. Open the "Located in" tab on the right hand side metadata panel. Double click on the dataset. This will trigger the exception. With the PR the Project/Datasets tab will be active again, with the dataset selected.
/cc @jburel
=> Node not valid exception

etc/ivysettings.xml
Previously the local Maven resolver was using the default Ivy pattern (ending with `.xml`) which was making the build incompatible with local artifacts build by Maven i.e. when working on coupled branches. This PR attempts to improve the developer workflow by taking advantage of the resolution of `.pom` files by Ivy.
1. clean `~/.m2/repository/ome` (or alternatively clean the entire local Maven repository), re-run `./build.py build-dev` and check the build completes and the `~/.m2/repository/ome` is regenerated with the release version of Bio-Formats
2. re-run `./build.py build-dev` and check the build completes without waiting on artifacts retrieval
3. test a local coupled Bio-Formats/OMERO development workflow
1. from a local Bio-Formats repository, checkout …
=> Improve OMERO build system integration with local Maven build

components/tools/OmeroPy/src/omero/plugins/node.py
- Adds a `--foreground` flag to `omero node`
- Forces a call to `admin rewrite` before `node start`, otherwise you may get a warning about a missing `/etc/internal.cfg` file
- I've added `die` to `node start` on windows because the code doesn't appear to have been tested for a while- `args.node` isn't an argument AFAICT.
See also
- https://trello.com/c/3fY2taKP/37-omero-grid-omero-node-bugs-issues
- https://github.com/openmicroscopy/openmicroscopy/pull/4414
In conjunction with #4414 it should be possible to remove the workarounds in https://github.com/ome/ome-docker/pull/24 ... I'll test assuming this ends up in the next merge build.
=> Rewrite templates in `omero node start`, add --foreground

components/insight/SRC/org/openmicroscopy/shoola/env/data/OmeroMetadataServiceImpl.java
Tiny bug fix for [Ticket 13129](http://trac.openmicroscopy.org/ome/ticket/13129)
**Test**: Select lots of images on a remote server (local just works too fast), add a tag to them. Now quickly - while the previous action is still running - do the same again (select the images again, add **the same** tag again). Maybe repeat this a few times, to be sure.
=> Make linkAnnotation synchronized

components/insight/SRC/org/openmicroscopy/shoola/agents/dataBrowser/ThumbnailProvider.java, components/insight/SRC/org/openmicroscopy/shoola/agents/dataBrowser/browser/Thumbnail.java, components/insight/SRC/org/openmicroscopy/shoola/agents/dataBrowser/view/DataBrowserFactory.java, components/insight/SRC/org/openmicroscopy/shoola/agents/dataBrowser/view/DataBrowserStatusBar.java, components/insight/SRC/org/openmicroscopy/shoola/agents/dataBrowser/view/DataBrowserUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/chooser/ImportDialog.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/ImViewerAgent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ToolBar.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/MetadataViewerAgent.java, components/insight/SRC/org/openmicroscopy/shoola/env/LookupNames.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/DataServicesFactory.java, components/insight/SRC/org/openmicroscopy/shoola/env/rnd/RenderingControl.java
This PR addresses two issues which came up on the [Forum](https://www.openmicroscopy.org/community/viewtopic.php?f=4&t=7991).
- Only switch the default to high compression for non-LAN connections (previously the compression for large images ( between 512x512px and 2000x2000px) was automatically set to "high" which led to visible JPEG artifacts). **Test**: Open a large image in full viewer, make sure compression is set to "none" (when your connection is set to be a LAN connection) Note: On this occasion I changed the Insight property "CONNECTION_SPEED" to "IMAGE_QUALITY_LEVEL" because that's what the property is actually about. [Ticket 13148](http://trac.openmicroscopy.org/ome/ticket/13148)
- Preserve the chosen thumbnail size. **Test**: Change the thumbnail size (slider at the bottom left …
=> Compression and thumbnail scaling

etc/ivysettings.xml
This commit follows-up 8aedc97834af6edea75de58747f5c760bce24ac3 and defines two Ivy patterns in the `user-maven` file system resolver:
- the first pattern ending in `.xml` will be used for artifacts downloaded by Ivy from a remote repository (e.g. Maven Central)
- the second pattern ending with `.pom` will be used for components built locally by Maven
Apart from checking the CI builds are green, the same testing procedure as in https://github.com/openmicroscopy/openmicroscopy/pull/4411 could be reapplied here. In a nutshell, clean the Maven repository under `~/.m2`, install the Bio-Formats artifacts locally using `mvn clean install` and then build the server using `./build.py build-dev`. In addition to `build-dev`, one should check the `release-javadoc` target also completes without …
=> Separate pom and xml filesystem resolvers

components/tools/OmeroPy/src/omero/gateway/__init__.py, components/tools/OmeroPy/test/integration/gatewaytest/test_config_service.py
This fixes a bug in Blitz Gateway (#4191) where conn.getInterpolateSetting() always returns True.
See https://www.openmicroscopy.org/community/viewtopic.php?f=4&t=7991&p=16657
To test
```
$ bin/omero config set omero.client.viewer.interpolate_pixels false
```
Restart omero server and log out of web client.
Then log in and check that viewer has interpolation off by default.
Question: is there any way we could have tests for config service methods within Blitz Gateway? Seems tricky if they require a server restart?
=> Fix conn.getInterpolateSetting() always return True

components/tools/OmeroWeb/omeroweb/webclient/controller/container.py, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/metadata_general.html
This is the same as gh-4038 but rebased onto metadata52.
----
Temporary OMERO.web workarounds so that other metadata PRs can be viewed:
- Display Well annotations as well as Image annotations e.g. Bulk-MapAnnotations from #4037 (normally only Image Annotations are shown when a Well is selected).
- Linkify keys/values in MapAnnotations
--on-hold
=> Temporary web UI workarounds (rebased onto metadata52)

.travis.yml
This JDK version seems to alleviate the memory issues our Travis build have been suffering from in the last few days. See https://travis-ci.org/sbesson/openmicroscopy/builds for the local tests, each build having built relaunched a few times.
/cc @aleksandra-tarkowska @joshmoore @jburel
=> Travis: use oraclejdk8

components/blitz/resources/ome/services/graph-rules/blitz-chgrp-rules.xml, components/blitz/resources/ome/services/graph-rules/blitz-chmod-rules.xml, components/blitz/resources/ome/services/graph-rules/blitz-chown-rules.xml, components/blitz/resources/ome/services/graph-rules/blitz-delete-rules.xml, components/blitz/resources/ome/services/graph-rules/blitz-duplicate-rules.xml, components/blitz/src/omero/cmd/graphs/BaseGraphPolicyAdjuster.java, components/blitz/src/omero/cmd/graphs/DuplicateI.java, components/tools/OmeroJava/test/integration/AbstractServerTest.java, components/tools/OmeroJava/test/integration/DuplicationTest.java, components/tools/OmeroJava/test/integration/ModelMockFactory.java, components/tools/OmeroJava/test/integration/chgrp/HierarchyMoveAndPermissionsTest.java, components/tools/OmeroJava/test/integration/chmod/PermissionsTest.java, components/tools/OmeroJava/test/integration/chown/PermissionsTest.java, components/tools/OmeroJava/test/integration/delete/HierarchyDeleteTest.java
Adjusts graph policies to incorporate Folders and adds corresponding integration tests:
* Delete2: http://regions-ci.docker.openmicroscopy.org:8080/job/OMERO-start/lastCompletedBuild/testReport/integration.delete/HierarchyDeleteTest/
* Chgrp2: http://regions-ci.docker.openmicroscopy.org:8080/job/OMERO-start/lastCompletedBuild/testReport/integration.chgrp/HierarchyMoveAndPermissionsTest/
* Chown2: http://regions-ci.docker.openmicroscopy.org:8080/job/OMERO-start/lastCompletedBuild/testReport/integration.chown/PermissionsTest/
* Chmod2: http://regions-ci.docker.openmicroscopy.org:8080/job/OMERO-start/lastCompletedBuild/testReport/integration.chmod/PermissionsTest/
* Duplicate: http://regions-ci.docker.openmicroscopy.org:8080/job/OMERO-start/lastCompletedBuild/testReport/integration/Duplicatio …
=> add OMERO graph policies for Folders

components/blitz/src/ome/formats/OMEROMetadataStoreClient.java
This is the same as gh-4348 but rebased onto develop.
----
This PR addresses a problem encountered when importing `.screen` files.
* *Without* this patch, if the user specifies a screen target, plates are linked to that screen *and* to the screen specified by Bio-Formats' `ScreenReader`
* *With* this patch, the target specified by the user overrides the BF one
**NOTES**
* It would be nice to simply skip `addReference` in `setScreenPlateRef`, but at that point in the import process `userSpecifiedTarget` has not been set yet (on the server's side)
* `screenKey` should probably be changed to a list, or removed altogether if scanning the whole `referenceCache` for screen-plate refs is not too intensive
* BF adds a screen -> plate ref, while `TargetProcessor` [adds a plate -> screen …
=> Fix duplicate screen target (rebased onto develop)

examples/Training/python/ROIs.py, examples/Training/python/Tables.py, examples/Training/training_setup.sh
Now that the webclient will display bulk metadata for Plates #4446 (and Insight has done for some time), this gives users an example of how to use populate_metadata from within a python script to upload Table data to a plate from a csv.
To test:
- try running the code sample, then check result in webclient (using PR https://github.com/openmicroscopy/openmicroscopy/pull/4446)
=> Populate metadata example

components/tools/OmeroWeb/omeroweb/webclient/tree.py, components/tools/OmeroWeb/omeroweb/webclient/views.py
This fixes/handles a couple of QA bugs which are due to async when deleting lots of images (webclient showing images that have been deleted): See https://www.openmicroscopy.org/qa2/qa/feedback/16974/
https://trello.com/c/EaUFEq8m/74-batch-annotate-no-groupids
https://trello.com/c/W1AFZ231/75-getthumbversion-no-images
To test these it is easiest if you load the tree and images in one browser, then delete the images in another client (Insight or web with a different browser).
- Expand a dataset of thumbnails in web, then delete these images in another browser/Insight.
- Now select several thumbnails in web - should see a suitable message (same as for single image)
- Load the tree in web, pick a Dataset that has images but don't expand Dataset.
- Then empty this Dataset in another …
=> Get thumb version no images

components/tools/OmeroWeb/omeroweb/webclient/show.py, components/tools/OmeroWeb/test/integration/test_show.py
This is https://github.com/openmicroscopy/openmicroscopy/pull/4241/ rebased onto develop (with extra changes to work with new jsTree).
Fixes ```webclient/?show=image-123``` when the image is in a well.
- To test, pick ID of an image in a Well and use it in the link above.
- This will browse to the well containing the image - Not necessarily the correct well-index (just first index).
=> Show image in well develop

components/blitz/src/omero/gateway/SecurityContext.java, components/blitz/src/omero/gateway/ServerInformation.java, components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/DataLoader.java, components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/chooser/ImportDialog.java, components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/chooser/LocationDialog.java, components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/view/Importer.java, components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterModel.java
Fixes [Ticket 13113](https://trac.openmicroscopy.org/ome/ticket/13113)
**Test:** Log in as user who has many projects/datasets. Open the import dialog, select a file to import, which brings up the LocationDialog. The Project and Dataset selection boxes should only show one item "Loading..." while the projects and datasets are loading. When the projects/datasets are loaded, the selection boxes should be populated. 
*This is not easy to test, I had to artifically delay the loading by adding a Thread.sleep() to the DMLoader. Created a 1000 datasets and projects for user-3/read-only, but still the loading is so fast, that you can't see the bug.*
=> LocationDialog loading

components/tools/OmeroPy/test/integration/helpers.py, components/tools/OmeroPy/test/integration/test_iquery.py, components/tools/OmeroPy/test/integration/test_pixelsService.py, components/tools/OmeroWeb/omeroweb/webclient/tree.py, components/tools/OmeroWeb/test/integration/test_tree.py
This uses the ```select map( )``` format of iQuery when loading tagged data, as we already do with other jsTree data, in order to work-around the hibernate projection permissions issues.
This fixes permissions on tagged objects belonging to other users.
Also adds tests to check this.
To review:
- Check that all tests are passing
- Look at the queries to check they make sense (that there isn't an obviously better way than the inner ```select``` to ensure that results are distinct)?
=> Api tagged perms

docs/install/VM/README.md
See https://trello.com/c/gKMVgoQ8/3-consider-replacing-virtual-applicance-with-docker
Marking VM as discontinued. Don't know if there is another readme somewhere I've missed?
=> Adding discontinued note to VM readme

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/RatingTaskPaneUI.java, components/tools/travis-build
Travis should be red until https://github.com/openmicroscopy/openmicroscopy/pull/4347#discussion_r52726799 is fixed to remove,
```java
import edu.emory.mathcs.backport.java.util.Arrays;
```
Then, restarting travis for *this* PR should turn it green.
--no-rebase
--depends-on #4347
=> Eschew edu.emory.mathcs.backport imports

components/blitz/src/omero/gateway/facility/TransferFacility.java, components/tools/travis-build
The use of `sh` led to failures of the form:
```
./components/tools/travis-build: 66: ./components/tools/travis-build: [[: not found]]
```
See:
https://trello.com/c/Bh0YqjQU/631-fix-bashism-in-travis-shell-script
cc: @sbesson
=> Use bash in travis-build

components/blitz/src/ome/formats/importer/ImportContainer.java, components/tools/OmeroPy/test/integration/clitest/test_import.py
Fixes the error reported by @mtbc in https://trac.openmicroscopy.org/ome/ticket/13074
To test:
```
mkdir fakes
for x in $(seq 10 20); do touch $x.fake; done
bin/omero import -- --auto_close --annotation-text foo --annotation-ns foo fakes/
bin/omero -q hql "select i.id, a.ns, count(a.id) from Image i join i.annotationLinks l join l.child a group by i.id, a.ns order by i.id desc"
```
**Without this PR** one sees:
```
----+------+-------------------------------------------+------
0  | 144  | foo                                       | 1
1  | 144  | openmicroscopy.org/omero/import/autoClose | 11
2  | 143  | foo                                       | 1
3  | 143  | openmicroscopy.org/omero/import/autoClose | 10
4  | 142  | foo                                       | 1
5  | 142  | …
```
=> 13074 autoclose anotations

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/AttachmentsTaskPaneUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/CommentsTaskPaneUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/GeneralPaneUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/RatingTaskPaneUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/TagsTaskPaneUI.java
The permissions weren't checked properly on the right hand side metadata panel (for Tags, Attachments and Rating), which leads to actions being enabled although the user is not allowed to perform the action (which throws an exception on attempt to execute the action), see [Ticket 13130](http://trac.openmicroscopy.org/ome/ticket/13130).
**Test**: 
- Perform a couple of metadata actions (adding/removing tags, attachments and ratings) within a read-only group on your own data. Make sure you can't perform these actions (add/remove button, rating panel should be disabled) for other users' data in the read-only group.
- Make sure filtering by "added by me", "added by others" works
- Test adding and removing tags with multiselection, while also making sure, same tags aren't shown multiple times. …
=> Metadata panel bugfixes

components/insight/SRC/org/openmicroscopy/shoola/util/ui/lens/DisplayAction.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/lens/LensComponent.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/lens/LensMenu.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/lens/StatusPanel.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/lens/ZoomWindow.java
Fixes [QA 16995](https://www.openmicroscopy.org/qa2/qa/feedback/16995/)
Test:
- Use the lens tool with an image which has pixel size information. Toggle between pixels and microns. Make sure the values make sense.
- Use the lens tool with an image without pixel size information. Make sure lens tools also works and doesn't crash. The "Microns" option should be disabled.
=> Make lens tool work properly with units

components/blitz/resources/ome/services/blitz-servantDefinitions.xml, components/blitz/src/ome/services/blitz/repo/ManagedImportRequestI.java, components/blitz/src/ome/services/blitz/repo/RequestObjectFactoryRegistry.java, components/blitz/src/omero/util/Resources.java, components/tools/OmeroPy/test/integration/clitest/test_import.py
Recently reported by Christian Sachs, when `--auto_close` is
used, long-running imports may die in unusual ways. This maintains
a keep-alive as long as the `ManagedImportRequestI` servant is
open.
Testing this was facilitated by placing an artificial sleep in
```
@@ -1593,6 +1593,12 @@ public class OMEROMetadataStoreClient
public void setPixelsFile(long pixelsId, String file, String repo) throws ServerError {
```
and setting the default session timeout to 10 seconds.
See:
http://lists.openmicroscopy.org.uk/pipermail/ome-users/2016-January/005791.html
=> Use omero.util.Resources to keep imports alive

components/tools/travis-build
This should increase the readability of Travis builds since we are installing Ice 3.5.1 manually.
To test this PR, check each step in the Travis log is folded.
=> Travis: fold Ice installation step

components/tests/ui/testcases/web/view_image.txt, components/tools/OmeroWeb/omeroweb/webgateway/templates/webgateway/viewport/omero_image.html
This fixes the broken "Prev" and "Next" buttons in the image viewer (were always disabled).
Bug is in 5.2.1, probably as a result of https://github.com/openmicroscopy/openmicroscopy/pull/4242
To test:
- Open a Dataset with multiple images, double click first image to open viewer.
- "Next" button should be enabled, allowing you to move to next image
- "Prev" button should be disabled when viewing first image, but become enabled for other images.
- Check that new Robot test is passing.
=> Viewer prev next btns

components/tests/ui/resources/web/tree.txt, components/tests/ui/testcases/web/delete_test.txt, components/tests/ui/testcases/web/forms_test.txt, components/tests/ui/testcases/web/search.txt, components/tests/ui/testcases/web/tagging_test.txt, components/tests/ui/testcases/web/webadmin_create_group_and_user.txt, components/tests/ui/testcases/web/webadmin_user_settings.txt
The buttons in the jQuery UI dialog seems to have been changed by some jQuery UI issue, which
causes a lot of tests to fail.
I previously saw this on my old laptop where tests failed (without this PR change) but it has been passing on the CI job until recently.
=> Robot fix xpath to dialog button

components/blitz/resources/omero/Constants.ice, etc/templates/grid/templates.xml
This is the same as gh-4159 but rebased onto develop.
----
Import of the condensation screens failed with
```
==> Summary
63171 files uploaded, 0 filesets created, 0 images imported, 0 errors in 2:47:28.118
2015-09-10 15:20:46,922 10354261   [1-thread-1] ERROR  me.formats.importer.util.ClientKeepAlive - Exception while executing ping(), logging Connector out:
java.lang.RuntimeException: Ice.CommunicatorDestroyedException
at ome.formats.OMEROMetadataStoreClient.ping(OMEROMetadataStoreClient.java:763) ~[blitz.jar:na]
```
```
-! 09/10/15 15:20:14.841 OMERO.Glacier2: warning: dispatch exception: OutgoingAsync.cpp:720: Ice::UnknownLocalException:
unknown local exception:
Ice::MemoryLimitException
Ice.MemoryLimitException
reason = "requested 67108865 bytes, maximum allowed is 67108864 bytes …
```
=> bump MessageSizeMax to 250mb (rebased onto develop)

components/tools/OmeroWeb/omeroweb/webgateway/marshal.py
The expectation of all downstream code is that the physical pixel
dimensions are in microns.  This commit restores the behaviour to that
expected prior to the introduction of units to OMERO and the
introduction of blind `getValue()` retrieval.
The downstream code in the OMERO.web that relies on physical dimensions being in microns:
* https://github.com/openmicroscopy/openmicroscopy/blob/develop/components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/omero_image.js#L346
* https://github.com/openmicroscopy/openmicroscopy/blob/develop/components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/ome.popup.js#L131
The underlying gateway code in action as an illustration:
```
$ dist/bin/omero shell
Python 2.7.9 (default, Apr  2 2015, 15:33:21) 
Type "copyright", "credits" or …
```
=> Make sure pixel dimensions are in microns

components/tools/OmeroWeb/omeroweb/settings.py, components/tools/OmeroWeb/omeroweb/webclient/urls.py
Add OMERO.web viewer view configurability which allows for the complete override or installation of a redirect view for the existing full viewer. This is particularly useful where an OMERO.web plugin is being used in production that replaces or extends the current full viewer, during development or during proof of concept work on new full viewer technology.
Out of the box there should be no affect on existing functionality. The additional configuration option is `omeroweb.web.viewer.view` and this accepts a fully qualified view function name which defaults to `omeroweb.webclient.views.image_viewer`. It can be tested at a very basic level by running the following:
```
bin/omero config set omero.web.viewer.view 'omeroweb.webclient.views.list_scripts'
```
This will display the current list …
=> Add OMERO.web viewer view configurability

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/mapannotations.html
Just found this bug (hence the last minute PR).
Fixes editng keys or values in map annotations with single quotes in them.
To test:
- Edit keys and values in a Map Annotation, including a single quote in the text.
- When you re-edit the text, the text field should be correctly with the text, without truncating at the quote mark.
=> Fix editing of map annotation values containing single quote

components/server/src/ome/services/graphs/GraphTraversal.java
With thanks to @joshmoore, adjust how graph traversal uses Hibernate to determine the exact class of model objects. Testing is by CI.
--no-rebase
(Supersedes #4378 because I don't have a reopen button.)
=> improve graph operation performance

components/server/src/ome/services/graphs/GraphTraversal.java
With thanks to @joshmoore, adjust how graph traversal uses Hibernate to determine the exact class of model objects.
--rebased-from #4398 to `metadata` to assist testing
=> improve graph operation performance (rebased from develop)

history.txt
Will be staged at https://www.openmicroscopy.org/site/support/omero5.2-staging/users/history.html but not until the autogen branches have been updated so initial review should be of the text and I'll check the formatting later (although it should be fine).
=> 5.2.2 version history

components/blitz/src/omero/cmd/graphs/DuplicateI.java, components/server/src/ome/services/graphs/GraphPathBean.java, components/server/src/ome/services/graphs/GraphPathReport.java
This PR refactors the graph path bean to offer the information required to construct the model object report. (The bean's API changes are fairly simple and minimal; it isn't worth putting much design work into it until the extended metadata functionality is understood then subsumed.) The model object report code is thus made far simpler without changing the output. Broadly, this PR should bring fewer code lines with no regressions. To generate the report used as the source for http://www.openmicroscopy.org/site/support/omero/developers/Model/EveryObject.html enter something like,
```
java -cp lib/server/\* `bin/omero config get | awk '{print"-D"$1}'` ome.services.graphs.GraphPathReport EveryObject.txt
```
which is how https://github.com/openmicroscopy/ome-documentation/pull/1408 was …
=> refactor the generation of the model object glossary

components/blitz/src/omero/client.java, components/blitz/src/omero/gateway/model/FileAnnotationData.java
Has OMERO's Java code use file content to guess MIME type before falling back to `application/octet-stream`. To test, try attaching files from your local system *using Insight* and check their resulting "mimetype" property. For instance, for an attachment with Annotation ID 123, from the CLI one can do,
```
$ bin/omero hql "SELECT file.mimetype FROM FileAnnotation WHERE id = 123"
```
Generally you should find that sensible things happen for common file extensions like ".pdf". However, where you have files with unknown or no extension, named "myfile" or "foo.bar.wibble" or whatever, with this PR you should now find that they still tend to get a sensible MIME type guessed according to their content: PDF, ASCII text, whatever. Also try a really random file (e.g., `head -c 64 </dev/urandom …
=> try harder to guess MIME type

components/blitz/src/omero/gateway/util/Requests.java
Adds request builders to the Java gateway utility class `Requests`. Testing is largely via CI already using these builders in the new implementation (hence plenty of examples) of the now-deprecated previous helper methods for creating graph requests. (Deprecation due to that they are a pain to create and maintain and already falling behind the requests now offered.) Do feel free to try out the builders yourself too and let me know if you want working examples for disk usage and duplicate (helpers newly offered in this PR so without automated indirect testing).
Not changing much of our existing code to use the new builders until `dev_5_2` is branched to avoid conflicts with `regions`.
--no-rebase
=> add request builders to Java gateway

components/blitz/resources/ome/services/graph-rules/blitz-chgrp-rules.xml, components/blitz/resources/ome/services/graph-rules/blitz-chown-rules.xml, components/blitz/resources/ome/services/graph-rules/blitz-delete-rules.xml
Enabled by #3966 uses the `OUTSIDE` graph node state less now that error-checking order does not need to be worked around. CI should remain blue and `Chgrp2`, `Delete2` should not show regressions.
=> slightly simplify graph policy rules

components/tools/OmeroJava/test/integration/DiskUsageTest.java, components/tools/OmeroJava/test/integration/DuplicationTest.java
Add use of the new builders for `DiskUsage` and `Duplicate` so that those builders actually get some automated testing. On `regions` instead of `develop` because those test classes have already diverged to include folders.
=> use new request builders in DiskUsage and Duplicate tests

components/tools/OmeroPy/src/omero/plugins/obj.py, components/tools/OmeroPy/src/omero_model_ElectricPotentialI.py, components/tools/OmeroPy/src/omero_model_FrequencyI.py, components/tools/OmeroPy/src/omero_model_LengthI.py, components/tools/OmeroPy/src/omero_model_PowerI.py, components/tools/OmeroPy/src/omero_model_PressureI.py, components/tools/OmeroPy/src/omero_model_TemperatureI.py, components/tools/OmeroPy/src/omero_model_TimeI.py, components/tools/OmeroPy/test/integration/clitest/test_obj.py
This was a quick fix for the issue raised by @mtbc in https://trello.com/c/sBjOWOWT/588-omero-obj-follow-up  If the requested field has an `id` rather than a `val` return the result in the form `Klass:id`. It now extends the command to handle fields that have units, returning the value and the units. It also adds the more general form to get all reasonable OMERO fields and values for a given object. 
Testing should use fields that have ids. For instance import an image from the command line and then use the returned Pixels id to get linked object ids:
```
$ bin/omero obj get Pixels:101 image
Image:101
$ bin/omero obj get Image:101 fileset
Fileset:51
```
To test a field with units import a fake, e.g.:
```
$ omero import ~/Work/images/fakes/image\&physicalSizeX\=123.fake
Imported pixels: …
```
=> Extend obj get command

components/tools/OmeroPy/src/omero/plugins/web.py, components/tools/OmeroPy/test/unit/clitest/test_web.py
cf https://www.openmicroscopy.org/community/viewtopic.php?f=5&t=8012&p=16820#p16820 and https://trello.com/c/aHKgiVXW/36-mention-apache-2-4-in-docs - message from OMERO.web states user should generate web config with "omero web apache" yet user is using Apache 2.4. We're improving docs to include references to the new command for Apache 2.4+, but the output from OMERO.web needs to mention it too.
Test updated.
=> Adding omero web config apache24 to message from `web start`

components/blitz/src/omero/gateway/facility/ROIFacility.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/util/roitable/ROINode.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/util/roitable/TableRowTransferHandler.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/MeasurementViewerModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/MeasurementViewerUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/ObjectManager.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/ROITable.java, components/insight/SRC/org/openmicroscopy/shoola/agents/util/SelectionWizard.java, components/insight/SRC/org/openmicroscopy/shoola/agents/util/ViewerSorter.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/ROIFolderSaver.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/treetable/OMETreeTable.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/treetable/model/OMETreeNode.java
This PR adds drag and drop support to the ROI table. There's just a little flaw, with drag and drop enabled the CTRL click multi selection sometimes doesn't work properly when clicked in the first column of the table (but fine when the other columns are used). Not sure if this is just an OSX issue. Will check with other platforms, too.
Other points fixed in this PR:
- Folders are now alphabetically sorted
- Folders can now contain sub folders as well as ROIs
(based on PR #4497)
=> Measurementtool DnD

components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/util/roitable/ROINode.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/MeasurementViewerModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/MeasurementViewerUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/ObjectManager.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/ROITable.java, components/insight/SRC/org/openmicroscopy/shoola/agents/util/SelectionWizard.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/ROIFolderSaver.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/treetable/OMETreeTable.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/treetable/model/OMETreeNode.java
The next bugfix PR, see [Trello - ROI Folders Insight Bugs](https://trello.com/c/XUI38KAp/27-roi-folders-insight-bugs)
Fixed:
- Changes of folder visibility won't affect orphaned ROIs any more.
- Expanded folders will stay expanded after the ROI table is refreshed (e. g. after a "add folders" action); additionally modified folders (e. g. if ROIs are moved to a folder) will be expanded, too (is this helpful, your thoughts @pwalczysko ? ).
- Deleted folders will immediately be removed from the table
- The column width is preserved after table refresh
- Folders created via 'Add ROIs to Folder" dialog won't have "Description" as Folder description any more.
=> Insight folders Step 3.0 - Bugfixes - 2

components/blitz/resources/ome/services/blitz-graph-rules.xml, components/blitz/resources/ome/services/blitz-servantDefinitions.xml, components/blitz/resources/ome/services/graph-rules/blitz-contained-rules.xml, components/blitz/resources/ome/services/graph-rules/blitz-container-rules.xml, components/blitz/resources/ome/services/graph-rules/blitz-duplicate-rules.xml, components/blitz/resources/omero/cmd/Graphs.ice, components/blitz/src/omero/cmd/RequestObjectFactoryRegistry.java, components/blitz/src/omero/cmd/graphs/Delete2I.java, components/blitz/src/omero/cmd/graphs/DuplicateI.java, components/blitz/src/omero/cmd/graphs/FindChildrenI.java, components/blitz/src/omero/cmd/graphs/FindParentsI.java, components/blitz/src/omero/cmd/graphs/GraphHelper.java, components/blitz/src/omero/cmd/graphs/GraphRequestFactory.java, components/blitz/src/omero/cmd/graphs/GraphUtil.java, components/blitz/src/omero/cmd/graphs/NullGraphTraversalProcessor.java, components/blitz/src/omero/cmd/graphs/SkipHeadPolicy.java, components/blitz/src/omero/cmd/graphs/StopBeforeHelper.java, components/blitz/src/omero/gateway/util/Requests.java, components/tools/OmeroJava/test/integration/FindParentsChildrenTest.java
These are generic model graph traversal requests for finding the parents and children of model objects. Integration tests are provided. They are intended to be useful for existing code such as https://github.com/openmicroscopy/openmicroscopy/commit/dd532abb92ec82803df97983ea999d0759756816 and will be even more useful with arbitrarily nested folders for single-query traversal.
Beyond #4519 this PR adds Folder support and automatic assistance with `stopBefore`.
Integration tests are provided at http://regions-ci.docker.openmicroscopy.org:8080/job/OMERO-start/lastCompletedBuild/testReport/integration/FindParentsChildrenTest/ and the curious could turn on debug logging for `omero.cmd.graphs` to see the extra `stopBefore` classes being added.
I am certainly happy to assist with the creation of …
=> provide new FindParents and FindChildren requests

components/blitz/src/ome/services/roi/GeomTool.java, components/blitz/src/omero/gateway/model/EllipseData.java, components/blitz/src/omero/model/SmartEllipseI.java, components/blitz/src/omero/model/SmartPolygonI.java, components/blitz/src/omero/model/SmartPolylineI.java, components/blitz/src/omero/model/SmartShape.java, components/tools/OmeroM/src/roi/createPoint.m
See https://trello.com/c/LW8l7U8x/20-shape-attribute-renaming-cleanup
Following the [Shape property renaming](https://github.com/openmicroscopy/openmicroscopy/pull/4481), this PR reviews the usages of `cx,` `cy`, `rx` and `ry` variables in the server components and fixes one of the MATLAB functions to use the new methods.
To test this PR, check the changes make sense and there are no more occurences of `[cC][xy]` and `[rR][xy]` in the modified components.
=> Shape attributes cleanup

components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/chooser/LocationDialog.java
This wee PR should fix [QA 17060](https://www.openmicroscopy.org/qa2/qa/feedback/17060/). I couldn't reproduce the issue, but the only explanation for the NPE is that the "Add to Queue" button must have been hit before the dialog was fully initialized (in particular before the user/group boxes have been populated). With this PR the button is only enabled after full UI initialization.
**Review**: Check if code makes sense; test if you can still add files to the import queue.
=> NPE Importer Dialog

components/insight/SRC/org/openmicroscopy/shoola/util/ui/lens/LensModel.java
Bugfix for [QA 17054](https://www.openmicroscopy.org/qa2/qa/feedback/17054/)
**Test**: Open an image. Set compression level to high. Open lens tool. Set zoom to > 800%.
=> Lens tool compressed image bugfix

components/tests/ui/resources/web/tree.txt, components/tests/ui/robot_setup.sh, components/tests/ui/testcases/web/delete_test.txt, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/containers.html
This fixes a tiny bug where deleting with the toolbar Delete button doesn't properly check for partially deleted filesets. 
To test:
- Pick a single image from a MIF, try deleting with the toolbar button.
- Should get the appropriate split-MIF warning that prevents you from going ahead with delete.
=> deletebutton fileset check

components/tools/OmeroWeb/omeroweb/webclient/static/webclient/css/layout.css, components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/ome.plateview.js
This is a partial solution to the problem of knowing which wells are which on a large plate when the row and column labels have scrolled off screen.
See https://trello.com/c/TXLXoyeU/64-critical-loss-of-context-when-looking-for-well
We simply show a well label when you hover over each well:
=> Display well label on hover over well

components/model/src/ome/model/internal/Details.java
At some point (either during the move to blitz or later
during the hiding of Details implementations), the copying
of ExternalInfo objects from one Details to the next was
lost. Since then, no ExternalInfo objects could have been
linked to any IObject, and it's even unlikely that they
could have been created at all.
=> Re-enable saving of ExternalInfo

components/tools/OmeroWeb/omeroweb/webgateway/templates/webgateway/viewport/omero_image.html
Fixes the zoom input in the main image viewer.
See http://trac.openmicroscopy.org/ome/ticket/13175
To test:
- Zoom the image, check the zoom input value updates
- Change the zoom input by typing in a number & Enter or with the up/down buttons - image should zoom.
=> Fix the zoom input in the main image viewer. See #13175

components/blitz/src/omero/gateway/facility/ROIFacility.java, components/blitz/src/omero/gateway/model/FolderData.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/util/roitable/ROINode.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/ObjectManager.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/ROITable.java, components/tools/OmeroJava/test/integration/gateway/ROIFacilityTest.java
This PR...
- enables the saving of imageless ROIs; **Test**: Just check integration test (`testSaveImagelessROIs`); it doesn't have a real significance in the client, yet.
- adds some performance tweaks to the ROITable/ObjectManager; **Test**: Check that the ROI/Folder table performs well with images with many ROIs. For example each ROI/Folder action (e. g. add ROI to folder, via menu or DnD, doesn't matter) as well as putting folders on display via the filter menu, refreshes the table. The refresh lag should not be too long, so that you're still able to interact with the table in a reasonable way.
- fixes the bug that it was not possible to deselect all folders for display (filter popup menu). **Test**: Select some folders for display, successively deselect them again (*not* via the …
=> Roifolders improvements

components/tools/OmeroWeb/omeroweb/webclient/show.py, components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/ome.tree.js, components/tools/OmeroWeb/test/integration/test_show.py
This fixes the navigation to an image with the url ``` webclient/?show=image-<id> ``` when that image is not on the first page of a Dataset.
To test:
- find a Dataset with pagination (>200 images)
- browse to the second or other page, click an image and copy the link to it
- paste the url in browser and check that this browses to show the image on the correct page
- Bonus: The same should work for Orphaned images (if you have > 200 orphaned images)
Also added web integration test which should pass!
=> Show image with pagination

components/blitz/resources/ome/services/blitz-graph-rules.xml, components/blitz/resources/ome/services/blitz-servantDefinitions.xml, components/blitz/resources/ome/services/graph-rules/blitz-disk-usage-rules.xml, components/blitz/resources/omero/cmd/FS.ice, components/blitz/resources/omero/cmd/Graphs.ice, components/blitz/src/omero/cmd/RequestObjectFactoryRegistry.java, components/blitz/src/omero/cmd/graphs/DiskUsage2I.java, components/blitz/src/omero/cmd/graphs/DiskUsageI.java, components/blitz/src/omero/cmd/graphs/GraphHelper.java, components/blitz/src/omero/gateway/util/Requests.java, components/server/src/ome/services/graphs/GraphTraversal.java, components/tools/OmeroJava/test/integration/DiskUsageTest.java, components/tools/OmeroPy/src/omero/plugins/fs.py
Changes the `DiskUsage` request to use the graph machinery instead of its own different implementation of graph traversal. Behavior should be unchanged except for reporting attachments as `FileAnnotation` instead of `Annotation`. Note that this can be accessed from the CLI via the `bin/omero fs usage` subcommand (see the `--report` option).
=> refactor disk usage

components/dsl/resources/ome/dsl/psql-footer.vm, sql/psql/OMERO5.3DEV__3/psql-footer.sql
Remove check for `pg_advisory_lock` which has been available since PostgreSQL 8.2.
=> remove obsolete database check

components/blitz/src/omero/cmd/graphs/DuplicateI.java, components/blitz/src/omero/cmd/graphs/GraphUtil.java
`DuplicateI` failed in duplicating `ome/data_repo/curated/mias/frans/siRNA_PRIM1_03102008/001-365700055641`. This PR adjusts for Hibernate so as to,
* not rely on deferring flushes
* never persist an object whose properties contain transient instances
* never try to reorder an existing collection
* fill in back-references before persisting objects.
Fixes http://trac.openmicroscopy.org/ome/ticket/13171. Will probably conflict with regions so I will do that rebasing myself. (I have kept most graphs changes to regions, but this is a bugfix.)
https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-java/lastCompletedBuild/testngreports/integration/DuplicationTest/ should continue to pass. Also feel free to try submitting `DuplicateI` requests yourself, including for the above plate. …
=> refactor DuplicateI to copy more complex subgraphs

components/tools/OmeroWeb/omeroweb/webgateway/views.py
This is the same as gh-4410 but rebased onto develop.
----
Additional logging to try and debug a mysterious 404, suggested by @aleksandra-tarkowska 
Unfortunately I have no idea how to intentionally trigger this error
=> Warn when a 404 occurs due to a SecurityViolation in webgateway.views (rebased onto develop)

components/tests/ui/plugins/robot.py, components/tests/ui/resources/robot.template, components/tests/ui/resources/web/login.txt, components/tests/ui/resources/web/webadmin.txt
Allow running robot tests using selenium remote server
test via selenium hub https://github.com/openmicroscopy/devspace/pull/20
test locally using:
```
dist/bin/omero --path components/tests/ui/plugins robot config --protocol http --webhost 'your_webserver' --remoteurl 'http://develop-seleniumhub.docker.openmicroscopy.org:4444/wd/hub' --dc 'browserName:${BROWSER},javascriptEnabled:True' > components/tests/ui/resources/config.txt
./build.py -f components/tests/ui/build.xml web-firefox -DTEST=view_image.txt
```
=> Robot remote driver

components/blitz/src/omero/gateway/facility/ROIFacility.java, components/insight/SRC/org/openmicroscopy/shoola/agents/events/measurement/ROIEvent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/ImViewerAgent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewer.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/MeasurementViewerComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/MeasurementViewerFactory.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/MetadataViewerAgent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/ROICountLoader.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/Editor.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorControl.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/PropertiesUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/view/MetadataViewer.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/view/MetadataViewerComponent.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/ImageDataView.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/ImageDataViewImpl.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/ROICountLoader.java, components/tools/OmeroJava/test/integration/gateway/ROIFacilityTest.java
At the moment Insight loads all ROIs and counts them on the client side for showing the number of ROIs in the right hand side meta data panel. This PR adds a method for directly getting the number of ROIs via an HQL query.
Test: Check some images with ROIs, make sure the ROI count (right hand side metadata panel) is correct.
(based on #4549 to avoid merge conflicts)
=> Get ROI count

etc/omero.properties
Unfortunately the version of Quartz we use is so ancient that one must now dig somewhat to find documentation. Companion to https://github.com/openmicroscopy/ome-documentation/pull/1446.
=> rewrite how to access information on Quartz cron expressions

components/tools/OmeroWeb/omeroweb/settings.py
This PR allows customizing STATIC_ROOT, the absolute path to the directory where collectstatic will collect static files for deployment
```
bin/omero config set omero.web.static_root '/path/to/static'
location /omero/static {
alias /path/to/static;
}
```
=> allow custom STATIC_ROOT

components/blitz/src/omero/cmd/graphs/FindChildrenI.java, components/blitz/src/omero/cmd/graphs/FindParentsI.java, components/blitz/src/omero/cmd/graphs/StopBeforeHelper.java, components/tools/OmeroJava/test/integration/DuplicationTest.java, components/tools/OmeroJava/test/integration/FindParentsChildrenTest.java, components/tools/OmeroJava/test/integration/ModelMockFactory.java, components/tools/OmeroJava/test/integration/chmod/PermissionsTest.java, components/tools/OmeroJava/test/integration/delete/AdditionalDeleteTest.java, components/tools/OmeroJava/test/integration/delete/DeleteProjectedImageTest.java
Adds stricter argument checking for `FindParents` and `FindChildren` and extra tests for:
* http://regions-ci.docker.openmicroscopy.org:8080/job/OMERO-start/lastCompletedBuild/testReport/integration/DuplicationTest/
* http://regions-ci.docker.openmicroscopy.org:8080/job/OMERO-start/lastCompletedBuild/testReport/integration/FindParentsChildrenTest/
* http://regions-ci.docker.openmicroscopy.org:8080/job/OMERO-start/lastCompletedBuild/testReport/integration.chmod/PermissionsTest/
* http://regions-ci.docker.openmicroscopy.org:8080/job/OMERO-start/lastCompletedBuild/testReport/integration.delete/AdditionalDeleteTest/
CI should remain a pleasing shade of blue.
=> expand integration testing for graphs operations

components/tests/ui/testcases/web/spw_test.txt, components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/ome.tree.js, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/includes/center_plugin.thumbs.js.html
When a Plate is selected, the centre panel will display it if the Plate has only a single Run (or none).
Same behaviour as Insight.
See https://trello.com/c/vR04i5uF/63-minor-auto-load-single-runs
To test:
- Browse to Plate in tree.
- If it has a single Run, this will load in centre panel without needing to select the Run.
=> Auto load single run

examples/RegionsOfInterest/Main.cpp, examples/RegionsOfInterest/Main.java, examples/RegionsOfInterest/Main.py, examples/Training/java/src/training/ROIs.java, examples/Training/matlab/ROIs.m, examples/Training/python/Advanced/Simple_FRAP.py, examples/Training/python/ROIs.py
See https://trello.com/c/LW8l7U8x/20-shape-attribute-renaming-cleanup
This PR reviews the variable/methods used when retrieving Point and Ellipse attributes in the `examples` directory. In particular the output of the two following greps should return nothing:
```
$ git grep -I [sg]et[RrCc][xy] -- examples
$ git grep -I [^a-zA-Z][RrCc][XxYy] -- examples
```
=> Shape renaming: examples review

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/LightSourceComponent.java
Fixes a potential class cast and NPE if metadata contains an unknown entry.
**Test**: Import fake plate `PW&plates=2&plateRows=1&plateCols=1&fields=1&plateAcqs=2.fake`, select a well, view all metadata (i. e. expand all tabs) in right hand side metadata panel.
=> Fix potential class cast/NPE for unknown metadata key

components/tools/OmeroM/src/roi/createEllipse.m, components/tools/OmeroM/test/unit/TestEllipse.m, components/tools/OmeroPy/src/omero/util/OmeroPopo.py, components/tools/OmeroPy/src/omero/util/ROIDrawingUtils.py, components/tools/OmeroPy/src/omero/util/ROI_utils.py, components/tools/OmeroWeb/omeroweb/webgateway/marshal.py, components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/ome.roidisplay.js, components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/ome.roiutils.js, components/tools/OmeroWeb/omeroweb/webgateway/views.py, components/tools/OmeroWeb/test/unit/test_marshal.py
See https://trello.com/c/LW8l7U8x/20-shape-attribute-renaming-cleanup
This PR reviews the variable/methods used when retrieving `Point` and `Ellipse` attributes in the `component/tools` directory. In particular the output of the two following greps should be reviewed with this PR included:
```
$ git grep -I [sg]et[RrCc][xy] -- $(git ls-files components/tools/ | grep -v 3rdparty | grep -v gtest)
$ git grep -I [^a-zA-Z][RrCc][XxYy] -- $(git ls-files components/tools/ | grep -v 3rdparty | grep -v gtest)
```
Additionally:
- review the breaking changes proposed in `webgateway/marshal.py` and the associated unit tests /cc @will-moore @chris-allan 
- check all Python/Web integration tests keep passing
- check the shape rendering in OMERO.web client is unmodified
=> Shape renaming: components/tools review

components/blitz/resources/omero/api/IMetadata.ice, components/blitz/resources/omero/api/IPixels.ice, components/blitz/resources/omero/api/IProjection.ice, components/blitz/resources/omero/api/IQuery.ice, components/blitz/resources/omero/api/IRepositoryInfo.ice
See https://trello.com/c/KLCaZX4X/19-copy-ome-api-documentation-to-omero-api
Follow-up of https://github.com/openmicroscopy/openmicroscopy/pull/4547, this PR copies more of the ome.api.*  Javadoc documentation into the slice classes.
To review this PR, either build the slice documentation via `release-slice2html` or use the published CI documentation or `OMERO.docs*` artifacts. Check the links are all working and the method parameters match.
=> Copy ome.api.* documentation to omero.api.* (2)

components/tools/OmeroM/src/annotations/getFileAnnotationContent.m, components/tools/OmeroM/src/annotations/getOriginalFileContent.m
Add get OriginalFileContent.m for possible consumption by getFileAnnotationContent
=> Add get OriginalFileContent.m for possible consumption by getFileAnnotationContent

components/insight/SRC/org/openmicroscopy/shoola/util/roi/io/InputServerStrategy.java, components/insight/SRC/org/openmicroscopy/shoola/util/roi/io/ROIReader.java
See https://trello.com/c/LW8l7U8x/20-shape-attribute-renaming-cleanup
This PR reviews the variable/methods used when retrieving Point and Ellipse attributes in the Insight component. In particular the following grep should return nothing
```
$ git grep -I [sg]et[RrCc][xy] -- examples
```
and the output of the following one should be reviewed:
```
$ git grep -I [^a-zA-Z][RrCc][XxYy] -- components/insight
```
All remaining usages of the variables above should either used in the context of JHotDraw or SVG  elements or have a different meaning e.g. ratio along x.
=> Shape renaming: insight review

components/blitz/resources/ome/services/graph-rules/blitz-chgrp-rules.xml, components/blitz/resources/ome/services/graph-rules/blitz-chmod-rules.xml, components/blitz/resources/ome/services/graph-rules/blitz-chown-rules.xml, components/blitz/resources/ome/services/graph-rules/blitz-delete-rules.xml, components/blitz/resources/ome/services/graph-rules/blitz-duplicate-rules.xml, components/server/src/ome/services/graphs/GraphTraversal.java, components/tools/OmeroJava/test/integration/DuplicationTest.java, components/tools/OmeroJava/test/integration/chgrp/HierarchyMoveTest.java
Fixes:
* http://trac.openmicroscopy.org/ome/ticket/13128 -- Bug: moving fake plate loses light settings
* http://trac.openmicroscopy.org/ome/ticket/13199 -- RFE: improve handling of shared logical channels
Adds corresponding integration tests in:
* http://regions-ci.docker.openmicroscopy.org:8080/job/OMERO-start/lastCompletedBuild/testReport/integration/DuplicationTest/
* http://regions-ci.docker.openmicroscopy.org:8080/job/OMERO-start/lastCompletedBuild/testReport/integration.chgrp/HierarchyMoveTest/
To test manually:
* move a single-plate fake to another group and check that it retains its light source settings
* duplicate individual plates from a multi-plate fake and check that it works
Everything else should still work fine.
=> fix minor graph bugs in acquisition metadata for fake plates

components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/util/roitable/TableRowTransferHandler.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/ROITable.java
Workaround to enable auto scrolling when dragging items on the ROITable.
Test: Select a few ROIs somewhere in the middle of the table, try to drag them to a position which currently lies outside of the visible part of the table by moving the cursor close to the upper or lower edge of the table. Make sure the table automatically scrolls up or down.
=> Workaround for DnD autoscroll

components/tests/ui/resources/web/tree.txt, components/tests/ui/testcases/web/rdef_test.txt, components/tests/ui/testcases/web/view_image.txt, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/includes/toolbar.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/metadata_preview.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/icon_thumbnails_underscore.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/includes/center_plugin.thumbs.js.html
See https://trello.com/c/vRHQSsTs/59-full-viewer-button-to-be-link and https://github.com/openmicroscopy/openmicroscopy/issues/4558
This PR makes the thumbnails and the Full Viewer buttons into html ```<a>``` links which means you can right-click and "Open link in new tab".
To test:
- Right-click on thumbnail -> open link in new tab. Repeat on other thumbnails.
- Right-click on "Full Viewer" button -> open link in new tab.
- Test "Full Viewer" button in General tab *and* Preview tab.
- Check that images have been opened in a series of new tabs.
Also check that other clicks on thumbnails and button are still working OK - E.g. double-click thumb to open image in new window, selecting images, shift-select range of thumbs etc.
=> Full viewer button link

components/tests/ui/resources/web/login.txt
Allow choosing robot server id from the drop down menu on login page.
This is available in webadmin tests but not in webclient
=> choose server id

components/blitz/src/ome/formats/importer/targets/ServerTemplateImportTarget.java, components/blitz/src/ome/services/blitz/repo/ManagedImportRequestI.java, components/tools/OmeroPy/test/integration/clitest/test_import.py
This fixes the behaviour seen in https://trello.com/c/oBRyeuuI/50-multiple-import-targets. It also fixes a bug seen in passing. Integration tests are added for both fixes.
To test a nested import create a folder structure similar to the one below,
```
~/outer/inner-1
~/outer/inner-2
```
with an image or screen or more in each of the inner folders. Then import using a regex template,
```
omero import ~/outer -T "regex:name:^.*outer/(?<Container1>.*?)" 
```
The result should be that the images/screens are imported into two separate Datasets/Plates, inner-1 and inner-2.
The bug noticed was was that the `-name` discriminator was not being respected for Dataset regex imports . This bug arose because I failed to add an integration test when the initial work was done here! That has been …
=> Import target fixes for regex templates

etc/omero.properties
This should be the last dependency bump in preparation of OMERO 5.3.0-m2. To test PR, check that
```
touch test.fake
bin/omero import -f test.fake
```
reports the correct version/revision for Bio-Formats
=> Set Bio-Formats version to 5.2.0-m3 for upcoming development milestone

components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/ROITable.java
**Test**: Select multiple folders (also nested ones), move them to another folder (*via context menu*). All of them should be moved (before: only the first one was). For nested folders: Their hierarchy should be preserved. E. g. "B" is a sub folder of "A". Select "A" and "B", move them to folder "C", then "B" should still be a sub folder of "A" (this is just to make sure that I did not reintroduce a bug I fixed earlier).
=> Bugfix: Moving multiple folders via context menu didn't work

components/blitz/src/omero/cmd/graphs/SkipHeadI.java, components/server/src/ome/security/basic/CurrentDetails.java, components/tools/OmeroJava/test/integration/DuplicationTest.java
Fixes http://trac.openmicroscopy.org/ome/ticket/13197 and is checked by https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-java/lastCompletedBuild/testngreports/integration/DuplicationTest/testDuplicateImageViaSkipHead/.
Enthusiastic manual testers may wish to read @ximenesuk's description in the ticket and avail themselves of #4574.
=> fix #13197: allow Duplicate to be used with SkipHead

components/tools/OmeroPy/src/omero/plugins/web.py, components/tools/OmeroPy/test/unit/clitest/reference_templates/nginx-withoptions.conf, components/tools/OmeroPy/test/unit/clitest/test_web.py, etc/templates/web/nginx.conf.template
This PR allow custom virtual server name in nginx config
see https://github.com/openmicroscopy/devspace/issues/35
to test:
- `bin/omero web config nginx` and check if 
```
server {
listen 80;
server_name $hostname;
```
- `bin/omero web config nginx --servername "mydomain.com"` and check if 
```
server {
listen 80;
server_name mydomain.com;
```
=> Customize server_name

etc/omero.properties
This should allow OMERO 5.3 to consume the development SNAPSHOT of Bio-Formats.
=> Revert Bio-Formats version to 5.2.0-SNAPSHOT for next milestone development

components/tests/ui/resources/web/tree.txt, components/tests/ui/robot_setup.sh, components/tests/ui/testcases/web/show_test.txt, components/tools/OmeroWeb/omeroweb/webclient/show.py, components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/ome.tree.js, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/containers.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/includes/center_plugin.thumbs.js.html, components/tools/OmeroWeb/omeroweb/webclient/views.py, components/tools/OmeroWeb/test/integration/test_show.py
This fixes a lot of "show" functionality that was broken with the new jsTree in 5.2.x as noticed in https://github.com/openmicroscopy/openmicroscopy/pull/4534#issuecomment-200354950
To test:
- check that all the examples in https://github.com/openmicroscopy/openmicroscopy/pull/2611 are working, that urls load and select the specified items.
- Select multiple wells in Plate, copy link url, paste in browser and check that it loads and selects the same wells.
- Repeat for multiple Images in a Dataset
I will also add Robot tests to this PR...
=> Show image.name fix

components/tools/OmeroWeb/omeroweb/webgateway/views.py
This PR change default thumbnail size loaded to plate grid to 96. This is because cached thumbnails in `omero.data.dir` are 96 not 64. There is no point to render them again
Should we also change default in https://github.com/openmicroscopy/openmicroscopy/blob/develop/components/tools/OmeroWeb/omeroweb/webgateway/views.py#L308 ? If so in 5.3 if that is ok?
@chris-allan @will-moore do you see any implications?
To test:
- open plate and inspect thumbnail URL
=> cached thumbnail size is 96

components/tools/OmeroJava/test/integration/AbstractServerTest.java, components/tools/OmeroJava/test/integration/ClientUsageTest.java, components/tools/OmeroJava/test/integration/DeleteServicePermissionsTest.java, components/tools/OmeroJava/test/integration/RenderingSettingsServicePermissionsTest.java, components/tools/OmeroJava/test/integration/chgrp/AnnotationMoveTest.java, components/tools/OmeroJava/test/integration/chgrp/HierarchyMoveCombinedDataTest.java, components/tools/OmeroJava/test/integration/chgrp/HierarchyMoveDatasetTest.java, components/tools/OmeroJava/test/integration/chgrp/HierarchyMoveImageWithRoiFromOtherUserTest.java, components/tools/OmeroJava/test/integration/chgrp/MultiImageFilesetMoveTest.java, components/tools/OmeroJava/test/integration/chgrp/RenderingSettingsMoveTest.java
Add test to check if the ```_del_``` method actually deletes the session
This is not the case with ice version < 3.6
cf. https://trac.openmicroscopy.org/ome/ticket/12921
I have fixed a bug in the disconnect method. We will need to watch if some tests failed (wrong assumption in the tests)
=> Session test

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/includes/core_metadata.html
Remove status field from UI See https://trac.openmicroscopy.org/ome/ticket/13066
To Test:
* Log as user-1 (already imported plane)
* Browse a plate
* Check that the "Status" field is no longer displayed.
=> Status field

components/tools/OmeroWeb/omeroweb/webclient/show.py, components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/ome.tree.js, components/tools/OmeroWeb/omeroweb/webclient/views.py, components/tools/OmeroWeb/test/integration/test_show.py
This fixes the links to "show" tag when tag is under a tagset or to show tagset.
To test:
- Browse to Tag under a Tag set, copy link to it ```/webclient/?show=tag-801```, paste to a different browser (not logged in), log in as a different user (who can access the tag) and check you are taken to the tag in tag tree.
- Repeat with a Tag set. ```/webclient/?show=tagset-801```
- When combined with #4540 this should also work for tags (in tagset or orphaned) ```webclient/usertags/?show=tag.textValue-Bod1```
- Also test with a Tag NOT under a Tag set.
=> Show tag tagset

components/blitz/src/omero/gateway/facility/ROIFacility.java, components/insight/SRC/org/openmicroscopy/shoola/agents/events/measurement/ROIEvent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/ImViewerAgent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewer.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/ROISaver.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/MeasurementViewer.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/MeasurementViewerComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/MeasurementViewerFactory.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/MetadataViewerAgent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/ROICountLoader.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/Editor.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorControl.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/PropertiesUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/view/MetadataViewer.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/view/MetadataViewerComponent.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/ImageDataView.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/ImageDataViewImpl.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/ROICountLoader.java, components/tools/OmeroJava/test/integration/gateway/ROIFacilityTest.java
Same as #4550 rebased to develop.
**Testing**: See https://github.com/openmicroscopy/openmicroscopy/pull/4602#issuecomment-214204547
=> Get ROI count 

components/blitz/resources/omero/api/IRenderingSettings.ice, components/blitz/resources/omero/api/ISession.ice, components/blitz/resources/omero/api/IShare.ice, components/blitz/resources/omero/api/ITypes.ice
See https://trello.com/c/KLCaZX4X/19-copy-ome-api-documentation-to-omero-api
Follow-up of #4547 and https://github.com/openmicroscopy/openmicroscopy/pull/4569, this PR copies more of the ome.api.* Javadoc documentation into the slice classes.
To review this PR, either build the slice documentation via release-slice2html or use the published CI documentation or OMERO.docs* artifacts. Check the links are all working and the method parameters match.
=> Copy ome.api.* documentation to omero.api.* (3)

components/blitz/resources/ome/services/graph-rules/blitz-chgrp-rules.xml, components/blitz/resources/ome/services/graph-rules/blitz-chmod-rules.xml, components/blitz/resources/ome/services/graph-rules/blitz-delete-rules.xml, components/tools/OmeroJava/test/integration/chgrp/AnnotationMoveTest.java, components/tools/OmeroJava/test/integration/chmod/RolesTest.java, components/tools/OmeroWeb/omeroweb/webclient/controller/container.py, components/tools/OmeroWeb/omeroweb/webclient/webclient_gateway.py
To assist http://trac.openmicroscopy.org/ome/ticket/2999 in preventing orphaned non-sharable annotations littering databases and in making the graph policy rules more consistent this PR ensures that when a non-sharable annotation is orphaned by being unlinked it is also deleted.
Testing: ensure that http://regions-ci.docker.openmicroscopy.org:8080/job/OMERO-test-integration/ is blue. Also, try deleting different things from different clients (e.g., comments, ratings, attachments, images, whatever, from Insight and Web) to watch out for regressions in deletion.
=> automatically delete orphaned non-sharable annotations

components/tools/OmeroPy/src/omero/plugins/web.py
This PR allows starting OMERO.web without daemon, in docker web won't start otherwise 
```
$bin/omero web start --foreground
... gunicorn -p ...
```
```
$bin/omero web start
... gunicorn -D -p ...
```
=> web start --foreground

components/tools/OmeroPy/src/omero/plugins/web.py, components/tools/OmeroPy/test/unit/clitest/test_web.py
https://trello.com/c/SOvbfoLq/57-docs-pr-omero-web-pr-re-web-start-stop-gunicorn
To test:
- `bin/omero config set omero.web.application_server wsgi`
- `bin/omero web start|status`
```
$ dist/bin/omero web start
Post-processed 'omeroweb.viewer.min.css' as 'omeroweb.viewer.min.css'
Post-processed 'omeroweb.viewer.min.js' as 'omeroweb.viewer.min.js'
0 static files copied to '/Users/ola/OMERO/ome.git/dist/lib/python/omeroweb/static', 616 unmodified, 2 post-processed.
Clearing expired sessions. This may take some time... [OK]
[ERROR] You are deploying OMERO.web using Apache and mod_wsgi. OMERO.web does not provide any management for daemon process which communicate with Apache child processes using UNIX sockets to handle a request. Please check Apache directly.
Generate apache config using …
```
=> get better message for status when using apache

components/tests/python/library/__init__.py, components/tools/OmeroPy/test/integration/clitest/test_import.py
This an attempt to fix the three fails record on the card https://trello.com/c/EavoXnp4/649-importas-and-multigroup-cli-tests
This adds a `keepAlive` for the root connection so that the connection is still available when these three tests need it. This is the most minimal solution and appears to work when testing locally against a remote server - it needs this latency for the tests to take long enough for the connection to be lost, see below. 
Testing
-------
The tests on Jenkins should pass, though given the intermittency the tests will need to be checked for a number of runs.
Local testing is possible though dependent on a slower connection. Set ice.config to point at `eel.openmicroscopy.org:24064` and then:
```
./setup.py test -t test/integration/clitest/test_import.py -m "not broken" …
```
=> Add keepalive for root connection

components/tools/OmeroJava/test/integration/AbstractServerTest.java, components/tools/OmeroJava/test/integration/ClientUsageTest.java, components/tools/OmeroJava/test/integration/DeleteServicePermissionsTest.java, components/tools/OmeroJava/test/integration/DuplicationTest.java, components/tools/OmeroJava/test/integration/RenderingSettingsServicePermissionsTest.java, components/tools/OmeroJava/test/integration/chgrp/AnnotationMoveTest.java, components/tools/OmeroJava/test/integration/chgrp/HierarchyMoveAndPermissionsTest.java, components/tools/OmeroJava/test/integration/chgrp/HierarchyMoveCombinedDataTest.java, components/tools/OmeroJava/test/integration/chgrp/HierarchyMoveDatasetTest.java, components/tools/OmeroJava/test/integration/chgrp/HierarchyMoveImageWithRoiFromOtherUserTest.java, components/tools/OmeroJava/test/integration/chgrp/HierarchyMoveTest.java, components/tools/OmeroJava/test/integration/chgrp/MultiImageFilesetMoveTest.java, components/tools/OmeroJava/test/integration/chgrp/RenderingSettingsMoveTest.java, components/tools/OmeroJava/test/integration/chmod/PermissionsTest.java, components/tools/OmeroJava/test/integration/chown/PermissionsTest.java
Rebases @jburel's work from #4594 and removes extra `disconnect()`s in tests that either I added recently or that @sbesson accuses. Should improve integration test situation in CI without further regressions.
=> Fix tests for Ice 3.6

components/tools/OmeroJava/test/integration/AbstractServerTest.java
Attempts to correct failing tests in `RenderingSettingsServicePermissionsTest`.
=> have AbstractServerTest.resetGroupPerms use Chmod2

components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/util/roimenu/ROIPopupMenu.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/MeasurementViewerControl.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/ROITable.java
The ROI context menu didn't work properly when triggered by right click on the ROIs in the image viewer. See respective point on checklist on the [Trello card - ROI Folders Insight Bugs/RFEs](https://trello.com/c/XUI38KAp/27-roi-folders-insight-bugs-rfes) This PR fixes the problems. 
**Test**: Check that the ROI context menu triggered from the image viewer works like the context menu triggered from the ROI table (and that both work like expected).
=> Roi popupmenu fix

components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/util/roitable/TableRowTransferHandler.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/ROITable.java
Some more improvements/bug fixes with respect to ROI Folders handling, see [Trello - ROI Folders Insight Bugs/RFEs](https://trello.com/c/XUI38KAp/27-roi-folders-insight-bugs-rfes).
* Enable Drag/Drop only on the first column of the ROI table
* If a Folder name matches the filter expression, don't filter the sub folders, always show them.
=> Roi table improvements

components/tools/OmeroJava/test/integration/AbstractServerTest.java, components/tools/OmeroJava/test/integration/RenderingSettingsServicePermissionsTest.java
Inlines a short method that is used only once in integration tests. CI should remain green.
Suggested by https://github.com/openmicroscopy/openmicroscopy/pull/4634#issuecomment-217374147.
=> inline singly used test method

components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/chooser/ImportDialog.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/AttachmentsTaskPaneUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/DocComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/GeneralPaneUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/MapTaskPaneUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/OtherTaskPaneUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/PropertiesUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/RatingTaskPaneUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/TagsTaskPaneUI.java
Fixes some tooltips of the right hand side metadata panel, see [Trello - Insight - Right Hand Pane tooltip changes + one other issue](https://trello.com/c/POjkfKpE/392-insight-right-hand-pane-tooltip-changes-one-other-issue).
**Test**: Check that the tooltips match the proposed ones on the trello card.
Note: When testing the last point (select files for scripts), I noticed that it doesn't work with @emilroz 's "Populate metadata" script which is deployed on eel. Reason for this is, that the scripts define the FileAnnotation parameter as list of Strings, but it should be a list of Longs instead!
=> Fix tooltips metadata panel

components/tools/OmeroPy/src/omero/util/ROI_utils.py
The Z and T properties look to get mixed up in using the ROI coordinate to set a shape in ROI utils.
=> fix typo in copying shape properties

components/blitz/src/ome/formats/OMEROMetadataStoreClient.java
Stubs new BinData methods so that OMERO still works and metadata mapping to-do's are logged.
See openmicroscopy/bioformats#2319. Expect Travis to fail.
=> bring BinData changes into OMERO

etc/omero.properties
See https://ci.openmicroscopy.org/view/Docs/job/OMERO-DEV-merge-docs/343/warnings3Result/ - docs build was unstable this morning because this link is broken. I'm not sure if it's temporary but the `/git/javadoc/com/google/common/cache/CacheBuilderSpec.html` bit is giving a 404 and the `http://docs.guava-libraries.googlecode.com` domain is redirecting to this github repo instead so I've changed the link to point directly at the code.
Will need the autogen docs build to run before this will feed through into the docs page.
=> Update guava CacheBuilderSpec link in config

.travis.yml
This reverts commit 70ab7a67c2daa72c40c70550e10f89336505bbbf.
With the large part of the breaking Bio-Formats changes having been included, purging the `ome` directory in the Maven cache should not be necessary anymore. With this change Travis should remain green and upcoming builds should not need to fetch from Artifactory.
=> Revert "Cleanup local OME Maven cache for every Travis build"

components/tools/OmeroPy/src/omero/plugins/duplicate.py
This PR adds a basic duplicate command to the CLI, this should duplicate simple objects and hierarchies. It includes integration tests for simple objects.
See:
```
$ omero duplicate --help
...
Examples:
omero duplicate Dataset:50
omero duplicate Dataset:50 --report
omero duplicate Dataset:53 --dry-run
omero duplicate Dataset:53 --dry-run --report
```
Multiple IDs and objects should also work:
```
$ omero duplicate Dataset:263,264
$ omero duplicate Dataset:263 Dataset:264
```
In addition hierarchies (P/D/I for example) and other complex objects should be duplicated. Create a simple P/D/I structure or import a Screen, then:
```
$ omero duplicate Project:123 --report
$ omero duplicate Screen:321 --report
```
the `--report` option is useful here to check the graph duplication.
To do
----- …
=> CLI duplicate command

components/tools/OmeroPy/src/omero/install/config_parser.py
See https://github.com/openmicroscopy/ome-documentation/pull/1481 this line remaining in the code was trying to reintroduce deleted windows server installation page links into the docs.
=> Remove link to deleted windows server install page

components/blitz/src/omero/gateway/util/Requests.java
This is a simple code PR that fixes a copy-and-paste slip in method naming. CI should remain green.
(As this affects gateway API it is a 5.2 backport candidate; I've no idea where/how we note those.)
=> fix method name for Chown2Builder.toGroup

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/DocComponent.java
Attach files to data in Insight. Check that when you hover over the filename in the metadata pane then the tooltip sensibly reports the file size. (It would previously use units like `KBkb`.)
=> have tooltip not add units to file size

components/blitz/src/omero/gateway/facility/DataManagerFacility.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/OMEROGateway.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/OmeroDataServiceImpl.java, examples/Delete/FileAnnotationDelete.java
With this PR the only remaining uses of deprecated `Requests` methods are in the integration tests. CI should remain green. This probably mostly affects permissions operations from Insight.
=> update uses of Requests to avoid deprecated methods

components/tools/OmeroJava/test/integration/AdminServiceTest.java, components/tools/OmeroJava/test/integration/DeleteServiceFilesTest.java, components/tools/OmeroJava/test/integration/DeleteServicePermissionsTest.java, components/tools/OmeroJava/test/integration/DeleteServiceTest.java, components/tools/OmeroJava/test/integration/PermissionsTestAll.java, components/tools/OmeroJava/test/integration/TableTest.java, components/tools/OmeroJava/test/integration/UpdateServiceTest.java, components/tools/OmeroJava/test/integration/chgrp/HierarchyMoveAndPermissionsTest.java, components/tools/OmeroJava/test/integration/chgrp/HierarchyMoveCombinedDataTest.java, components/tools/OmeroJava/test/integration/chgrp/HierarchyMoveDatasetTest.java, components/tools/OmeroJava/test/integration/chgrp/HierarchyMoveImageWithAcquisitionDataTest.java, components/tools/OmeroJava/test/integration/chgrp/HierarchyMoveImageWithRoiFromOtherUserTest.java, components/tools/OmeroJava/test/integration/chgrp/HierarchyMoveImageWithRoiTest.java, components/tools/OmeroJava/test/integration/chgrp/HierarchyMoveTest.java, components/tools/OmeroJava/test/integration/chgrp/MultiImageFilesetMoveTest.java, components/tools/OmeroJava/test/integration/chgrp/RenderingSettingsMoveTest.java, components/tools/OmeroJava/test/integration/chmod/PermissionsTest.java, components/tools/OmeroJava/test/integration/chown/PermissionsTest.java, components/tools/OmeroJava/test/integration/delete/AdditionalDeleteTest.java, components/tools/OmeroJava/test/integration/delete/AnnotationDeleteTest.java, components/tools/OmeroJava/test/integration/delete/DeleteProjectedImageTest.java, components/tools/OmeroJava/test/integration/delete/HierarchyDeleteTest.java, components/tools/OmeroJava/test/integration/delete/MultiImageFilesetDeleteTest.java, components/tools/OmeroJava/test/integration/delete/RelatedToTest.java, components/tools/OmeroJava/test/integration/delete/RoiDeleteTest.java, components/tools/OmeroJava/test/integration/delete/SpwDeleteTest.java
With this PR and #4653 there should be no more uses of deprecated Requests methods in OMERO. CI should remain green. The code changes should be reviewed to ensure that tests are still acting as intended.
=> update uses of Requests in tests to avoid deprecated methods

components/common/resources/ome/config.xml, components/tools/OmeroWeb/omeroweb/webclient/decorators.py, components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/ome.tree.js, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/base/base_container.html, etc/omero.properties
this PR adds ability to sort client tree nodes by type. 
`omero.client.ui.tree.type_order`by default is `tagset,tag,project,dataset,screen,plate,acquisition,image`
to mix types in a tree and sort them by default sorting strategy impleented in client set `omero.client.ui.tree.type_order false`
Note: removing type from the list won't turn off appearance of nodes, it only allows to order them
**Testing: if you update server configuration you must logout from web (even public user) to pick up changes, server config is stored in session and loaded only for the first time when connection is created**
=> remove rank and sort by name regardless of node type

components/insight/SRC/org/openmicroscopy/shoola/util/roi/figures/MeasurePointFigure.java, components/insight/SRC/org/openmicroscopy/shoola/util/roi/io/InputServerStrategy.java
Tiny bugfix for [Ticket 13232](http://trac.openmicroscopy.org/ome/ticket/13232) / [Trello - Insight drawing bug](https://trello.com/c/YFAxjYtL/60-insight-drawing-bug). 
**Test**: Draw a point ROI close (< 10px) to the upper and/or left edge of the image, check the x,y coordinates via Results tab and make sure the point is displayed in the place where it's supposed to be.
=> Bugfix: Point figure offset when close to x and or y axis

components/tools/OmeroPy/src/omero/plugins/search.py
Fixes minor typo in `bin/omero search -h`, see diff.
Cc: @ximenesuk for presentation slide.
=> close parenthesis in CLI help

components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/MeasurementViewerUI.java
Fix for [Ticket 12883](http://trac.openmicroscopy.org/ome/ticket/12883)
I noticed that the `MeasureBezierFigure.calculateMeasurements()` is called a couple of times on each point for a polygon you draw. There's a weird add-up effect the more polygons you draw, which ends up calling the method hundreds of thousand times when you've drawn >= 7 polygons, which makes Insight practically unresponsive. I haven't found out the reason for this yet, however preventing to set the `SHOWMEASUREMENT` attribute (which triggers the call), when it's not necessary, stops this odd behavior.
**Test**: Draw a couple of polygons (at least more than 7), check that the measurement tool doesn't slow down with the number of polygons you add.
=> 7th polygon problem

components/tools/OmeroWeb/omeroweb/feedback/views.py
This is the same as gh-4680 but rebased onto develop.
----
This PR fixes incorrect status code returned when omeroweb catch an exception
https://trello.com/c/qHCkMDIN/88-web-500-error-with-http-200-status
```
$ curl -I http://omero.local/omero/webclient/render_image/2102/
HTTP/1.1 500 INTERNAL SERVER ERROR
Server: nginx/1.8.1
Date: Wed, 25 May 2016 10:20:40 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Vary: Cookie
Set-Cookie: csrftoken=Yhp07TdEGY7BMYRzbE0NoKWiGCk5ax0U; expires=Wed, 24-May-2017 10:20:40 GMT; Max-Age=31449600; Path=/
```
=> fix 500 (rebased onto develop)

components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/GraphPane.java
While investigating [QA 17196](https://www.openmicroscopy.org/qa2/qa/feedback/17196) I noticed that  a map of tooltips is generated for the measurement "Graph Pane", which actually doesn't work anyway (there are no tooltips displayed on the graph), but can block for a large ROI for example up to 1 GB of memory. This PR removes that.
**Test**:  Draw/Select an ROI, check that the Graph Pane still works (for large ROIs (eg rectangle nearly completely covering a 4kx4k image) you should also notice a slight performance increase). Also check with latest build (not including this PR) that there are really no tooltips shown on the Graph (maybe I just missed them).
=> Removed (not working) tooltips from GraphPane to save memory

components/tools/OmeroPy/src/omero/plugins/admin.py, components/tools/OmeroPy/src/omero/util/cleanse.py
This PR limits cleansing to admins. Test that it otherwise works exactly as before: so, test with both admin and non-admin users. Also test both `bin/omero admin cleanse` and the direct `cleanse.py`.
--rebased-from #4683
=> make the CLI cleanse operation admin-only (rebased from develop)

components/tools/OmeroPy/src/omero/plugins/admin.py, components/tools/OmeroPy/src/omero/util/cleanse.py
This PR limits cleansing to admins. Test that it otherwise works exactly as before: so, test with both admin and non-admin users. Also test both `bin/omero admin cleanse` and the direct `cleanse.py`.
--rebased-to #4691
=> make the CLI cleanse operation admin-only

components/insight/SRC/org/openmicroscopy/shoola/agents/dataBrowser/actions/DownloadAction.java, components/insight/SRC/org/openmicroscopy/shoola/agents/events/hiviewer/DownloadEvent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/ToolBar.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/TreeViewerAgent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/actions/DownloadAction.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewer.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewerComponent.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/model/DownloadArchivedActivityParam.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/MetadataHandlerView.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/MetadataHandlerViewImpl.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/ArchivedImageLoader.java, components/insight/SRC/org/openmicroscopy/shoola/env/ui/ArchivedLoader.java, components/insight/SRC/org/openmicroscopy/shoola/util/PojosUtil.java
Enable Plate download, taking the `omero.policy.binary_access` property into account, [Trello - Allow SPW download in Insight](https://trello.com/c/ydtmsP1Z/75-allow-spw-download-in-insight)
**Test** : Add Plates to the `binary_access` property: `./omero config set omero.policy.binary_access "+read,+write,+image,+plate"` (restart server). Make sure you can download plates on the plate, plate acquisition ("Run") and well level, by the context menu on the treeviewer and central databrowser and download menu in the right hand side metadata panel. Note: This will always download the whole plate even if just specific wells are selected. That should probably raise a warning dialog, as it's not intuitively expected. What are your thoughts about that?
=> Enable Plate download

components/tools/OmeroWeb/omeroweb/settings.py, components/tools/OmeroWeb/omeroweb/webgateway/templates/webgateway/viewport/omero_image.html, components/tools/OmeroWeb/omeroweb/webgateway/views.py
This is the same as gh-4260 but rebased onto metadata52.
----
I've had this lurking around since January 2014. Given that we now have a public resource and Twitter no longer require manual approvals I thought it's time to resurrect it. See https://dev.twitter.com/cards/types/summary-large-image
The `title` and `description` fields are mandatory, I'm assuming there will always be a non-empty image name, description is set to the owner's name if empty.
At risk of stating the obvious this can only be tested with a public image on an external server. Open an image in the full image viewer, copy the url into a tweet.
=> Add support for twitter cards (full image viewer only) (rebased onto metadata52)

components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/ome.right_panel_mapanns_pane.js, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/metadata_general.html
A rebase issue, this left many parts of the UI unusable
(link button, k/v dropdown, etc) after certain operations.
See: https://trello.com/c/gmCgOvwU/326-metadata52-web-problems
=> Prefix linkify_element with OME.

components/romio/src/ome/io/nio/PixelsService.java, components/server/resources/ome/services/service-ome.io.nio.PixelsService.xml, components/server/src/ome/security/SecuritySystem.java, components/server/src/ome/security/SecuritySystemHolder.java, components/server/src/ome/security/basic/BasicSecuritySystem.java, components/server/src/ome/security/sharing/SharingSecuritySystem.java, components/server/src/ome/services/RawPixelsBean.java, etc/omero.properties
To prevent DoS'ing a server, this flag can be set which
requires that all files have a valid cached Memoizer. A
next step will be to allow selectively permitting access
based on some flag.
See https://github.com/openmicroscopy/bioformats/pull/2435
NB: The boolean added to PixelsService should likely be refactored
into a more general "options" class to reduce future method
clutter.
=> PixelsService: use Memoizer.failIfMissing

components/blitz/resources/omero/Tables.ice, components/tools/OmeroPy/src/omero/util/populate_metadata.py, components/tools/OmeroPy/test/integration/metadata/test_populate.py
This PR carries on from work by @emilroz  (PR 120) which makes it possible to specify the column types for OMERO.tables when using populate_metadata.py to parse the csv files and adds support for datasets and projects as the target object for a metadata table.
=> Metadata column column types and datasets

components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/ome.viewport.js, components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/ome.viewportImage.js
attempt to fix viewer cleanup issue reported in https://www.openmicroscopy.org/community/viewtopic.php?f=6&t=8058&p=17131
to test:
- use https://raw.githubusercontent.com/aleksandra-tarkowska/weblabs/7c396e8a5e5c8e3d29f5f6064f010904e4121ba2/image_viewer_demo/index.html
- make sure header contains:
```
<link href="https://cowfish.openmicroscopy.org/webmerge/static/omeroweb.viewer.min.css" type="text/css" rel="stylesheet"></link>
<script src="https://cowfish.openmicroscopy.org/webmerge/static/omeroweb.viewer.min.js" type="text/javascript"></script>
```
see http://aleksandra-tarkowska.github.io/weblabs/image_viewer_demo/ 
you have to VPN 
=> clean up viewer before reloading

components/blitz/src/ome/services/blitz/repo/ManagedRepositoryI.java, components/tools/OmeroJava/test/integration/ImporterTest.java
Fixes the problem described at https://trello.com/c/Plm8Mrfu/12-usernames-can-contain-filepath-separators:
> Users such as `foo/bar` and `../ManagedRepository` can be created legitimately but they are not able to import any data!
Also adds a new integration test https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-java/lastCompletedBuild/testngreports/integration/ImporterTest/testImportSimpleImageOddlyNamedUser/.
=> sanitize user and group name for import paths

components/blitz/resources/ome/services/graph-rules/blitz-chgrp-rules.xml, components/tools/OmeroJava/test/integration/chgrp/AnnotationMoveTest.java, components/tools/OmeroJava/test/integration/delete/AnnotationDeleteTest.java
Discussion at the users' meeting made me think to improve handling of when multiple attachments refer to the same underlying file. CI should be green, including https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-java/lastCompletedBuild/testngreports/integration.delete/AnnotationDeleteTest/ and https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-java/lastCompletedBuild/testngreports/integration.chgrp/AnnotationMoveTest/.
=> improve test coverage for attachments sharing files

components/blitz/resources/omero/api/Exporter.ice, components/blitz/resources/omero/api/IAdmin.ice, components/blitz/resources/omero/api/IConfig.ice, components/blitz/resources/omero/api/IContainer.ice, components/blitz/resources/omero/api/IProjection.ice, components/blitz/resources/omero/api/IQuery.ice, components/blitz/resources/omero/api/IRoi.ice, components/blitz/resources/omero/api/IScript.ice, components/blitz/resources/omero/api/IShare.ice, components/blitz/resources/omero/api/ITimeline.ice, components/blitz/resources/omero/api/IUpdate.ice, components/blitz/resources/omero/api/JobHandle.ice, components/blitz/resources/omero/api/RawFileStore.ice, components/blitz/resources/omero/api/RenderingEngine.ice, components/blitz/resources/omero/api/Search.ice, components/blitz/resources/omero/api/ThumbnailStore.ice
See https://trello.com/c/JQ9AcNa2/77-copy-ome-api-documentation-to-omero-api
Follow-up of #4547, #4569, #4578 and #4605, this PR copies the remaining `ome.api.*` Javadoc documentation into the slice `omero.api.*` classes. It also includes a minor fix reported in https://github.com/openmicroscopy/openmicroscopy/pull/4605#discussion_r66062485. This should be the final set of migration PRs associated with this documentation epic. Thanks to @ximenesuk for his infinite patience.
To review this PR, either build the slice documentation via release-slice2html or use the published CI documentation or OMERO.docs* artifacts. Check the links are all working and the method parameters match.
=>  Copy ome.api.* documentation to omero.api.* (5)

components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/ome.tree.js
Fixes disabled 'Create Share' option in tree right-click menu.
http://trac.openmicroscopy.org/ome/ticket/13250
To test:
- Create Share in right-click menu should be enabled when you select one or more images that you 'canLink' (same as toolbar Share button).
- Should be disabled for other data types P/D/S/P/W and for images you don't own / can't link
=> contextmenu_create_share

components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/util/ui/ResultsCellRenderer.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/IntensityView.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/MeasurementResults.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/MeasurementTableModel.java, components/insight/SRC/org/openmicroscopy/shoola/util/roi/figures/MeasureBezierFigure.java, components/insight/SRC/org/openmicroscopy/shoola/util/roi/model/annotation/AnnotationKeys.java
While investigating [Ticket 13202](https://trac.openmicroscopy.org/ome/ticket/13202) I fixed some problems with the ResultsTable of the MeasurementTool. This should also fix the error the user reported, although I couldn't reproduce it (but my suspicion is, it was some kind of unit conversion problem).
On that occassion I also made sure, that no unit up or down conversion ("round to reasonable unit") happens and that the ResultTable does not contain any unit symbols (numbers only),therefore the unit is shown in the headers of the table only (if it is a real unit and not in pixels). That means the numbers in the table should all be of the same dimension so that they are easily comparable and regonized by Excel as numbers when the results are exported as excel file.
**Test**
-  Make sure …
=> Ticket 13202

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/OtherTaskPaneUI.java
If an image had "other" annotations, simply opening and closing the image triggered a save action of these annotations, which failed because the image-annotation link already existed in the database.
This PR fixes the problem. See [Ticket 13129](https://trac.openmicroscopy.org/ome/ticket/13129).
Get an image with an "Other" annotations, e. g. like the image mentioned in [QA 17236](https://www.openmicroscopy.org/qa2/qa/feedback/17236/): http://jcb-dataviewer.rupress.org/jcb/img_detail/573821/22507/ . Import it to OMERO. Open the image in full viewer and close the full viewer again. No "Save" dialog should pop up when doing this.
Also test that you can still edit and delete "Other" annotations.
=> Bugfix: Ticket 13129

components/blitz/src/omero/gateway/facility/BrowseFacility.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/ExperimenterImageLoader.java
Tiny bugfix for [QA 17191](https://www.openmicroscopy.org/qa2/qa/feedback/17191/) to prevent potential ClassCastException (`result` object is not guaranteed to be an instance of Set, e.g. see https://github.com/openmicroscopy/openmicroscopy/blob/develop/components/blitz/src/omero/gateway/facility/BrowseFacility.java#L1008 ).
**Test**: Code review should be sufficient. Don't know how to easily replicate the bug. Would need an experimenter without user image set, but all experimenters actually have this user icon as default user image.
=> Fixed ClassCastException

components/insight/SRC/org/openmicroscopy/shoola/util/ui/drawingtools/creationtools/DrawingObjectCreationTool.java
Previously if an ROI was smaller than a minimum size, its bounds were set to this minimum size. In case of a Point ROI this led to an offset by usually 2px into x and y direction when created by a single click. This PR removes this minimum size constraint to fix this problem, as I can't see a particular reason for this constraint.
Draw a Point ROI by a single click (no dragging) and make sure it appears where you expect it.
[Trello - BUG: Point ROI drawn offset](https://trello.com/c/rrYdO13a/91-bug-point-roi-drawn-offset)
=> Bugfix: Point ROI drawn offset

components/insight/SRC/org/openmicroscopy/shoola/env/init/SplashScreenInit.java, components/insight/SRC/org/openmicroscopy/shoola/env/ui/SplashScreenManager.java, components/tools/OmeroWeb/omeroweb/http.py, etc/mime.types
Remove ref to jnlp since we no longer use webstart.
Check that the Desktop client works and web is up.
Original card (5.2.0) https://trello.com/c/sqkNtuBY/58-drop-webstart
=> Remove ref to jnlp (Web start)

components/common/resources/ome/config.xml, components/tools/OmeroWeb/omeroweb/webclient/decorators.py, components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/ome.tree.js, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/base/base_container.html, etc/omero.properties
This is the same as gh-4627 but rebased onto develop.
----
this PR adds ability to sort client tree nodes by type. 
`omero.client.ui.tree.type_order`by default is `tagset,tag,project,dataset,screen,plate,acquisition,image`
to mix types in a tree and sort them by default sorting strategy impleented in client set `omero.client.ui.tree.type_order false`
Note: removing type from the list won't turn off appearance of nodes, it only allows to order them
**Testing: if you update server configuration you must logout from web (even public user) to pick up changes, server config is stored in session and loaded only for the first time when connection is created**
=> remove rank and sort by name regardless of node type (rebased onto develop)

components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/ome.plateview.js
As pointed in https://github.com/openmicroscopy/openmicroscopy/pull/4687#issuecomment-226798195 plate should load data using GET rather then POST 
load a plate and check if query string contains size like ``http://.../webgateway/plate/PLATE_ID/INDEX/?size=96&callback=...``
cc @chris-allan @will-moore
=> modify the WeblitzPlateview.load() to tell gs_json to use GET

components/tools/OmeroPy/src/omero/util/OmeroPopo.py, components/tools/OmeroPy/src/omero/util/script_utils.py
See https://trello.com/c/0dkqUU9f/51-deprecate-omeropopo-py
The `omero.util.OmeroPopo` module is no longer actively used in our repositories. As suggested in the card, this PR deprecates the various classes as well as the two isolated methods `omero.util.script_utils.registerNamespace()` and `omero.util.script_utils.findROIByImage()` which were consuming it.
To test this PR, check all tests remain green and that there is no other place in this code or elsewhere (scripts) where these methods are used.
=> Deprecate OmeroPopo module

etc/omero.properties
With the finalization of the 2016-06 model and the release of Bio-Formats 5.2.0-m4, there is no more need for the development branch in OMERO to overwrite the Bio-Formats version and consume a SNAPSHOT version.
To test this PR, check that Travis is green, all integration tests pass and that OMERO bundles Bio-Formats 5.2.0-m4 (`bin/omero import -f test.fake` should report the version).
Once merged, as in previous versions, a staging PR can be opened bumping the `versions.bioformats` version to 5.2.0-SNAPSHOT to allow BIo-Formats PRs to be tested in the daily merge build of OMERO>
=> Bump Bio-Formats version to 5.2.0-m4

components/tools/OmeroPy/test/integration/clitest/cli.py, components/tools/OmeroPy/test/integration/clitest/test_chown.py, components/tools/OmeroPy/test/integration/clitest/test_delete.py
See [chown trello card](https://trello.com/c/RpdAOmKp/37-permissions-system-problems-chown#comment-5734d47e92374a1dec3292d5).
This PR should be a suggestion to cpmplement the tests and changes of existing tests in [chown trello card](https://trello.com/c/RpdAOmKp/37-permissions-system-problems-chown#comment-5734d47e92374a1dec3292d5). It deals with Python tests only. 
The tests added here should deal with the comments [comment1 on trello](https://trello.com/c/RpdAOmKp/37-permissions-system-problems-chown#comment-5734d6a14a903d90c3e3b14a) and [comment2 on trello](https://trello.com/c/RpdAOmKp/37-permissions-system-problems-chown#comment-5734d47e92374a1dec3292d50) as well as other tests which bring the [chown test](https://github.com/openmicroscopy/openmicroscopy/blob/develop/components/tools …
=> Chown tests

components/tools/OmeroPy/src/omero/cli.py, components/tools/OmeroPy/test/integration/clitest/test_delete.py
Adds new python integration tests for new functionelity of CLI. See details below.
1. required setup
Check that the python integration tests are passing on CI.
2. actions to perform
No special actions to perform except checking that the three added tests make sense and are complying with the standards.
3. expected observations
Tests on CI pass.
See https://github.com/openmicroscopy/openmicroscopy/pull/4707
1. background for understanding this PR
Elision means shorthand input, where a continuous row of IDs is approximated with first-hphen-last pattern (see https://github.com/openmicroscopy/openmicroscopy/pull/4707).
This PR here adds 3 new tests (one of them parametrized) for CLI for Elision input and does it specifically in the [delete …
=> Elision on CLI tests

components/insight/SRC/org/openmicroscopy/shoola/util/ui/login/ScreenLogin.java
The login screen of Insight and Importer are for our dual screen setups (Ubuntu 14.04) positioned in the middle of the two screens. Meaning that the login-window spans over two screens. This is quite annoying, especially because the window is not movable. 
This PR fixes that by setting setResizable to true. There seem to my (limited) testing no negative side effects from this. Looking back at the history of this code, there seem to be no particular reason why setResizable was set to false. 
* Linux (Ubuntu 14.04 in our case)
* OMERO.insight
* Start OMERO.insight
* Watch position on screen of splash window and login window
* With this PR the login window should be positioned in the middle of the primary screen
* Without this PR the login window is positioned in the middle of both screen …
=> Fix window position of login screen of Insight on dual screen Linux.

components/blitz/resources/omero/model/Units.ice, components/blitz/resources/templates/combined.vm, components/blitz/src/omero/model/PressureI.java, components/model/src/ome/model/enums/UnitsPressure.java, components/tools/OmeroCpp/CMakeLists.txt, components/tools/OmeroCpp/src/omero/IcePortPop.h, components/tools/OmeroCpp/src/omero/IcePortPush.h, components/tools/OmeroCpp/src/omero/internal/fixes.h, components/tools/OmeroCpp/src/omero/model/ElectricPotentialI.h, components/tools/OmeroCpp/src/omero/model/FrequencyI.h, components/tools/OmeroCpp/src/omero/model/LengthI.h, components/tools/OmeroCpp/src/omero/model/PowerI.h, components/tools/OmeroCpp/src/omero/model/PressureI.cpp, components/tools/OmeroCpp/src/omero/model/PressureI.h, components/tools/OmeroCpp/src/omero/model/TemperatureI.h, components/tools/OmeroCpp/src/omero/model/TimeI.h, components/tools/OmeroPy/src/omero_model_PressureI.py, components/tools/OmeroPy/test/unit/test_model.py
- Search and replace of `Pascal` to `PASCAL`
- Add PASCAL workaround for windows by adding a private header sourced by the generated Ice sources during compilation.
- May need additional workarounds at a higher level where the units headers get included, as done for the other C++ components.  But there are no such users at this time.
Due to the nature of the Ice code generation, it's not possible to put the workaround in the public header itself as for the other C++ code; we don't have control over this.  But `slice2cpp` does make provision for a single header to be added to the generated source, which we use here.
Check builds remain green.  The OMERO C++ jobs should be unchanged if this is all working.
https://trello.com/c/4NOpYKza/39-header-problems-on-windows …
=> Change Pascal case to PASCAL

components/tools/OmeroWeb/omeroweb/settings.py, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/includes/toolbar.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/metadata_general.html, components/tools/OmeroWeb/omeroweb/webclient/views.py, components/tools/OmeroWeb/omeroweb/webgateway/views.py
The web metadata panel `Link to this <object>` contains a server side URL created from the HTTP `Host` header. This causes problems with server-side caching.
- Wherever possible client-side URLs should be constructed in javascript using the `location` object, so that the `/path` will be cached but the `protocol://host` will be handled by the client browser
- Where this isn't possible (e.g. embedded non-javascript metadata such as URLs parsed by social media) this can be overridden using `omero.web.ui.omero.web.ui.external_link_baseurl` (this must include the protocol).
1. Setup OMERO.web, optionally with a public user (makes testing easier)
2. Check `Link to this <object>` in the web RH metadata panel. The URL should use whatever the browser has in the location bar, and in additional …
=> Configuration of web link-to URL protocol/host

components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/base/base_container.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/containers.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/public/public.html
This PR adds url_suffix to all ome custom JavaScript files
To test this PR go to:
- page webclient/userdata/ check:
- `<script type="text/javascript" src="{% static "webclient/javascript/ome.right_panel_tags_*` 
- `<script type="text/javascript" src="{% static "webclient/javascript/jquery.jstree.*`
- page webclient/public/ check:
- `<script type="text/javascript" src="{% static "webclient/javascript/jquery.jstree.*`
has build number
Basically, make sure if all JS files contains either build number or 3rd party libraries container version number in the path
cc @will-moore
=> add url_suffix for custom javascript files

components/tools/OmeroWeb/omeroweb/webgateway/templates/webgateway/viewport/omero_image.html
As requested https://github.com/openmicroscopy/openmicroscopy/pull/4725#issuecomment-229962048 this renames the "Visibility" column in the web ROI table to "Show" in line with Insight.
View ROIs on an image in webclient. Table column should be renamed "Show".
=> Rename ROI 'Visibility' to 'Show'

components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/browser/BrowserUI.java, components/insight/SRC/org/openmicroscopy/shoola/env/LookupNames.java
Implements #4682 for Insight.
**Test**: Also see above mentioned PR.
- Start Insight, check the tree in left hand side panel. Make sure, Projects are listed before Datasets, Screens are listed before Plates, TagSets are listed before Tags.
- On the server set the `omero.client.ui.tree.type_order` property *to something else* than `tagset,tag,project,dataset,screen,plate,acquisition,image` (that's the default).
- Restart the server
- Now check again and make sure the different data types are listed in the order you specified
=> Tree type order

components/tests/python/library/__init__.py, components/tools/OmeroPy/src/omero/plugins/metadata.py, components/tools/OmeroPy/src/omero/util/populate_metadata.py, components/tools/OmeroPy/test/integration/metadata/test_populate.py
The new `QueryContext` implementations in `populate_metadata.py` were not batching in their `write_to_omero` methods. For very large screens (e.g. idr0016):
* `BulkToMapAnnotationContext` tends to hit MESSAGESIZEMAX limits and
* `DeleteMapAnnotationContext` hits `Caused by: java.io.IOException: Tried to send an out-of-range integer as a 2-byte value: 109734`
Now both are done in batches of 1000.
*Note:* projections are also causing issues so batching is being added to invocations of `projection` as well.
1. A bulk annotation YML configuration is required. This is minimal possible via `test/integration/metadata/test_populate.py`.
2. There should be no change in functionality and no overt slowdown in creation or deletion.
* https://trello.com/c/urQCwi0v/470-error-creating-map-annotations-in- …
=> populate_metadata.py: add batches to write_to_omero

components/tools/OmeroJava/test/integration/chown/PermissionsTest.java
This PR expands the java integration tests for changing ownership for complementing the python tests. The additions are concentrating at first on the annotations behaviour. See the gist of the changes in the [trello card comment](https://trello.com/c/RpdAOmKp/102-permissions-system-problems-chown#comment-5761290e6d2d6f948a4e181a)
Check the java integration tests are still passing.
Check that the [chown permissions test](https://github.com/openmicroscopy/openmicroscopy/blob/develop/components/tools/OmeroJava/test/integration/chown/PermissionsTest.java) makes sense in that it is covering the most used objects of annotations and their combination as compared with the [cli-delete-test](https://github.com/openmicroscopy/openmicroscopy/blob/develop/components/tools/OmeroPy/test/integration/clite …
=> Chown java integration test

components/tools/OmeroPy/src/omero/util/populate_metadata.py
This is the same as gh-4743 but rebased onto metadata52.
----
Fix bug with populate_metadata.py reported at http://lists.openmicroscopy.org.uk/pipermail/ome-devel/2016-July/003701.html where the script fails if the plate has more than 26 rows.
- Use the Dataset_To_Plate.py script to create a Plate with more than 26 rows.
- Create a csv file that names Wells using A->Z then AA->AZ etc. 
E.g.
```
Well,	Well Type,	TestValue
A01,	Treatment,	1
A02,	Control,	2
AA01,	Treatment,	3
AB02,	Treatment,	4
```
- Attach CSV to Plate and run Populate_Metadata as described http://help.openmicroscopy.org/scripts.html#metadata
- The Script should complete without error. Selecting Wells specified in the csv file should show the corresponding values in the Tables section, with the Well Name of that well.
cc …
=> populate_metadata many rows (rebased onto metadata52)

components/tools/OmeroPy/src/omero/util/populate_metadata.py
Fix bug with populate_metadata.py reported at http://lists.openmicroscopy.org.uk/pipermail/ome-devel/2016-July/003701.html where the script fails if the plate has more than 26 rows.
- Use the Dataset_To_Plate.py script to create a Plate with more than 26 rows.
- Create a csv file that names Wells using A->Z then AA->AZ etc. 
E.g.
```
Well,	Well Type,	TestValue
A01,	Treatment,	1
A02,	Control,	2
AA01,	Treatment,	3
AB02,	Treatment,	4
```
- Attach CSV to Plate and run Populate_Metadata as described http://help.openmicroscopy.org/scripts.html#metadata
- The Script should complete without error. Selecting Wells specified in the csv file should show the corresponding values in the Tables section, with the Well Name of that well.
cc @chris-allan
=> populate_metadata many rows

components/blitz/src/omero/gateway/facility/TablesFacility.java, components/blitz/src/omero/gateway/model/TableData.java, components/blitz/src/omero/gateway/model/TableDataColumn.java, components/tools/OmeroJava/test/gateway.testng.xml, components/tools/OmeroJava/test/integration/gateway/GatewayTest.java, components/tools/OmeroJava/test/integration/gateway/TablesFacilityTest.java
This is the same as gh-4666 but rebased onto metadata52.
----
Resurrected the `TablesFacility` from  #4347 (which was closed and only a subset merged into 5.2.3).
The TablesFacility would provide an easy way for adding and getting table structured data to/from OMERO, this would be very useful for the R gateway (i.e attaching/loading dataframes to/from OME objects, https://github.com/dominikl/rOMERO/blob/dev_5_3/examples/dataframes.R ).
Probably needs some more discussion, but it would be very handy to open up the tables accessibility, so I could create some more realistic R examples.
/cc @jburel
=> TablesFacility (rebased onto metadata52)

components/insight/SRC/org/openmicroscopy/shoola/util/PojosUtil.java
Fixes [Ticket 13269](https://trac.openmicroscopy.org/ome/ticket/13269) (NPE when a Well without PlateAcquisition is selected).
Instead of checking the PlateAcquisition now the Well of the WellsampleData is checked if it is restricted with respect to downloading. But I don't really understand the implications here. Can a WellsampleData have a PlateAcquisition and a Well or both, and what to check in that case?
Import the file mentioned in the ticket. Click on the Well.
=>  Ticket 13269

components/tools/OmeroPy/src/omero/clients.py, components/tools/OmeroPy/src/omero/util/cleanse.py
This attempts to fix the problem in ticket 13251 where an erroneous null repository would break cleanse. This PR uses a modified client call to get a non-null managed repository.
I'm not sure how easy it is to test the fail case here since I'm not sure how to create the set-up of a null repository. Any advice @joshmoore ? For now cleanse should work - with slightly improved output for any empty directories. And the integration tests should pass.
Following Josh's comment below here is a way to reproduce the underlying problem. This needs to be locally unless you really want to annoy everyone on the merge build server!! Without this PR:
- start a  clean local server
- import a simple image (ADDED in response to @dominikl as the output is different with no data imported)
- try `omero admin …
=> Fix cleanse for null repositories

components/blitz/src/omero/gateway/facility/BrowseFacility.java, components/blitz/src/omero/gateway/util/PojoMapper.java, components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/util/FileImportComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/ExperimenterDataLoader.java, components/insight/SRC/org/openmicroscopy/shoola/agents/util/EditorUtil.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/OMEROGateway.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/OmeroDataService.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/OmeroDataServiceImpl.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/OmeroImageService.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/OmeroImageServiceImpl.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/OmeroMetadataService.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/OmeroMetadataServiceImpl.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/util/StatusLabel.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/MetadataHandlerView.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/MetadataHandlerViewImpl.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/DMLoader.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/DMRefreshLoader.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/HierarchyLoader.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/ImageSplitChecker.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/ImagesLoader.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/StructuredAnnotationLoader.java, components/insight/TEST/org/openmicroscopy/shoola/env/data/NullOmeroPojoService.java, components/insight/TEST/org/openmicroscopy/shoola/examples/data/LoginHeadless.java
Refactoring the PojoMapper class: Replaces various similar methods with one method `convertToDataObjects` (previous methods are marked as deprecated). Makes more use of generics. Use general `Collection` interface instead of returning `Set` and `List`. Marks unused methods as deprecated.
Nothing particular to test. PojoMapper class is used throughout Insight. Just leave the PR in the build for a while and see if something breaks? I know that's generally not a good strategy for testing... Your thoughts @jburel , @pwalczysko ?
There was one piece of code (the Importer component) where the program logic depended on wether the Collection was a Set or List, which was quite a bad design (fixed that, see last commit bd966ac ). I'm a bit worried that there might be other similar cases. They will …
=> Refactor PojoMapper

components/blitz/resources/omero/api/ITimeline.ice
This PR addresses https://github.com/openmicroscopy/openmicroscopy/pull/4702#issuecomment-225578494 by cleaning the introduction of the `omero.api.ITimeline` documentation page.
To test this PR, check the Slice generated documentation page under https://ci.openmicroscopy.org/view/DEV/job/OMERO-DEV-merge-build/ICE=3.6,jdk=8_LATEST,label=octopus/javadoc/slice2html/omero/api/ITimeline.html
=> Improve formatting of omero.api.ITimeline slice2html page

components/blitz/src/ome/services/blitz/impl/ScriptI.java, components/tools/OmeroJava/test/integration/ScriptServiceTest.java
* Delete the script, the file was removed from disk but the entry was not removed from DB
Integration tests added.
Also fixed the upload script
Making the tests are green
Problem found out when working on LUT
cc @mtbc 
The ``simpleDelete`` in ``scriptRepoHelper`` could be marked as deprecated.
=> Script test

components/tools/OmeroWeb/omeroweb/webgateway/static/webgateway/js/ome.viewportImage.js
Fixes a bug reported in forum comment at https://www.openmicroscopy.org/community/viewtopic.php?f=6&t=8058&start=10#p17150
This is tested by example and Robot test at webtest PR: https://github.com/openmicroscopy/webtest/pull/10
=> multi-viewer zoom buttons

components/blitz/src/omero/cmd/admin/CurrentSessionsRequestI.java
This reorders operations in the current sessions request API implementation to avoid attempting to wrap a `SessionContextImpl` in an rtype.
Experiment with `bin/omero sessions who` and anything else that queries current sessions to check that:
1. they still work as before
1. no warnings with stack traces are written to `Blitz-0.log` as they work.
http://trac.openmicroscopy.org/ome/ticket/13275
=> fix 13275: in current sessions request don't try to map session context

components/tools/OmeroWeb/omeroweb/webclient/show.py, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/metadata_general.html, components/tools/OmeroWeb/test/integration/test_show.py
Fixes https://trac.openmicroscopy.org/ome/ticket/13255. When an Image from SPW is found in a search and loaded in the right panel, we don't know that this is in a Well.
Therefore, the *Tables* tab was not shown so you couldn't query for tables data (needs Well Id).
Now, we always show the Tables tab, and if a user expands it then we do an AJAX call to check whether the image is in a Well (uses the paths_to_object query). If we get a Well Id then we do a second query to load the Tables data as normal.
See ticket above. 
- Need to have tables data in SPW as described http://help.openmicroscopy.org/scripts.html#metadata
- Add table data for a bunch of wells in plate (doesn't have to be all)
- Table data should be displayed as normal when the Well is loaded in right panel.
- Add unique tag …
=> Search result tables 13255

components/tools/OmeroWeb/omeroweb/webclient/show.py, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/metadata_general.html, components/tools/OmeroWeb/test/integration/test_show.py
This is the same as gh-4774 but rebased onto metadata52.
----
Fixes https://trac.openmicroscopy.org/ome/ticket/13255. When an Image from SPW is found in a search and loaded in the right panel, we don't know that this is in a Well.
Therefore, the *Tables* tab was not shown so you couldn't query for tables data (needs Well Id).
Now, we always show the Tables tab, and if a user expands it then we do an AJAX call to check whether the image is in a Well (uses the paths_to_object query). If we get a Well Id then we do a second query to load the Tables data as normal.
See ticket above. 
- Need to have tables data in SPW as described http://help.openmicroscopy.org/scripts.html#metadata
- Add table data for a bunch of wells in plate (doesn't have to be all)
- Table data should be displayed as …
=> Search result tables 13255 (rebased onto metadata52)

components/tests/ui/library/java/ivy.xml, etc/ivysettings.xml, etc/omero.properties
OMERO cannot be fully built because the UI testing component depends on presently unavailable Maven artifacts. This PR updates the dependencies to allow more reliable fetching.
Wipe out your `.m2/repository/` and try building OMERO's `build-dev` target. After a couple of goes (for instance, `backport-util-concurrent` often fails for me and I have to wipe its directory and retry) the build should succeed.
https://github.com/robotframework/SwingLibrary/issues/87
=> adjust SwingLibrary dependencies

components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/actions/CreateTopContainerAction.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/DMRefreshLoader.java
If you create a new Tag or TagSet while browsing another user's Tags, the newly created Tag/TagSet might not be shown, because it gets listed within the logged in user's branch (which might not be expanded), see example screenshot (logged in as user-6, browsing user-3 tags). The create new Tag/TagSet menus should therefore be disabled in that case.
(Also fixes two `ClassCastExceptions` when creating Tags/TagSets which probably have been introduced by  #4734)
Make sure that you *cannot* create a new Tag/TagSet while browsing through another user's Tags (another user's tag, tagset, object is selected), check the right click context menu and toolbar menu. 
Make sure you *can* create a new Tag/TagSet while you're browsing your own tags. 
https://trello.com/c/WN0W4D3l/69-minor-tag-bugs-insight
=> Tagging bugfixes

components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/AnnotationTaskPane.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/AnnotationTaskPaneUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/AttachmentsTaskPaneUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/CommentsTaskPaneUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/DummyTaskPaneUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/MapTaskPaneUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/OtherTaskPaneUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/RatingTaskPaneUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/TagsTaskPaneUI.java
In Insight the right-hand metadata browser panel should now show annotation counts even before accordion tabs are expanded.
Try adding and removing annotations and see that the annotation counts generally stay correct, especially after selecting a different entity then moving back. Counts under multiselect should also be reasonable. Will generally correspond to *total* that is visible *across* different filtering options in right pane (e.g., show mine or others').
(Sync isn't always immediately perfect but trying to keep implementation sane.)
https://trello.com/c/bc6ZtV0x/144-rfe-indication-of-number-of-annotations-on-an-image-in-brackets-5-on-accordion-tabs-in-right-hand-pane
=> have metadata browser show annotation counts

sql/README.txt
Fixes the SQL script path description in the README.
Take a look at `sql/README.txt` and compare with the directory's contents and with https://www.openmicroscopy.org/site/support/omero5.2/sysadmins/server-upgrade.html#run-the-upgrade-script.
https://trello.com/c/ftdGIEl4/163-sql-readme-v-s-web-docs
=> adjust SQL readme

components/insight/SRC/org/openmicroscopy/shoola/util/roi/io/InputServerStrategy.java
Makes sure that the line width used for drawing ROIs is at least 1 px.
Draw an ROI; set the line width in the DB to a value < 1; make sure ROI tool doesn't crash.
[[ome-users] OMERO Client crashes when lauching ROI tool](http://lists.openmicroscopy.org.uk/pipermail/ome-users/2016-August/006117.html)
The user imported ROIs with stroke width < 1, which made Insight ROI tool practically unusable.
I'm not sure if it's worth fixing in Insight, as it's a problem with the ROIs, but on the other hand, using a 1px default is better than crashing Insight in these cases.
=> Ignore stroke width < 1

components/tests/ui/testcases/web/webadmin_login.txt, components/tools/OmeroWeb/omeroweb/webadmin/forms.py, components/tools/OmeroWeb/test/integration/test_login.py
Simple fix for https://trello.com/c/U47AiD1R/682-weird-guest-login
To test, try logging in as 'g' or 's', or 't'. Shouldn't see the "guest not supported" error.
Only when logging is as "guest" should you see this.
=> guest login check

components/tools/OmeroWeb/omeroweb/settings.py, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/includes/toolbar.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/metadata_general.html, components/tools/OmeroWeb/omeroweb/webclient/views.py
Partial rebase of #4744 
The web metadata panel `Link to this <object>` contains a server side URL created from the HTTP `Host` header. This causes problems with server-side caching.
- Wherever possible client-side URLs should be constructed in javascript using the `location` object, so that the `/path` will be cached but the `protocol://host` will be handled by the client browser
1. Setup OMERO.web, optionally with a public user (makes testing easier)
2. Check `Link to this <object>` in the web RH metadata panel. The URL should use whatever the browser has in the location bar, and in additional examination of the returned html such as `http://host/webclient/metadata_details/image/ID/` should show `var lnk = location.protocol + "//" + location.host + "/webclient/";` instead of a URL.
The …
=> Partial rebase of 4744 Use client-side protocol/host in URL

components/tools/OmeroPy/src/omero/plugins/prefs.py, components/tools/OmeroPy/test/unit/clitest/test_prefs.py
Adds `--set` option to `omero config append`, to indicate a value should only be added if it's not already in the list, taking into account the defaults, see https://github.com/openmicroscopy/openmicroscopy/issues/4597
Adds `--report` option to `omero config {append,set,remove}`. This will always print out `Changed: ...` if a change was made, and nothing if no change was made.
1. Check `omero config append/set/remove` behaves as before.
2. Try something like
omero config append --set omero.web.ui.top_links '["History", "history", {"title": "History"}]'
this should have no effect (E.g. `omero config get`, or `omero web restart` and check the top-links) because this value is part of the standard defaults.
3. Try it without `--set`, you should see the old behaviour i.e. the duplicate value …
=> Add --set to config append, --report to config {set,append,remove}

components/tools/OmeroPy/src/omero/install/python_warning.py, components/tools/OmeroPy/src/omero/plugins/web.py, components/tools/OmeroWeb/omeroweb/settings.py, components/tools/OmeroWeb/requirements-py26-apache.txt, components/tools/OmeroWeb/requirements-py26-nginx.txt
This PR remove Python 2.7 support from OMERO.web cli plugin.
See new jobs in https://github.com/openmicroscopy/management_tools/pull/173
to test:
-  run `bin/omero web *` on python 2.6 and 2.7 environment and see if it behaves as expected
- report any concerns and suggestion about Warnings/Errors in this PR
=> OMERO.web only supports Python 2.7

components/tests/ui/library/java/ivy.xml, etc/ivysettings.xml, etc/omero.properties
OMERO cannot be fully built because the UI testing component depends on presently unavailable Maven artifacts. This PR updates the dependencies to allow more reliable fetching.
Move your `.m2/repository/` elsewhere and try building OMERO's `build-dev` target. After a couple of goes (for instance, `backport-util-concurrent` often fails for me and I have to wipe its directory and retry) the build should succeed.
https://github.com/robotframework/SwingLibrary/issues/87
--rebased-from #4790
=> Swing library dependency

etc/build.properties
Increases the timeout for integration tests from 5s to 10s
Check integration tests.
There've been a lot of cases recently where integration tests didn't finish within the current timeout of 5 sec: https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-integration-java/
The callback has to finish within the given value times 10 (in ms) before a TimoutException is thrown, see https://github.com/openmicroscopy/openmicroscopy/blob/92e1b1751926b1472393fc92a16abf128caab279/components/tools/OmeroJava/test/integration/AbstractServerTest.java#L2011 (the timeout value is the `scalingFactor` in that case)
/cc @sbesson
=> Increase test timeout

components/insight/SRC/org/openmicroscopy/shoola/agents/dataBrowser/view/DataBrowserFactory.java, components/insight/SRC/org/openmicroscopy/shoola/agents/dataBrowser/view/WellsModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorControl.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/EditorUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/editor/GeneralPaneUI.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/view/MetadataViewerModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/PlateWellsLoader.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/ProjectsLoader.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/TimeIntervalsLoader.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewer.java, components/insight/SRC/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewerComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/util/browser/TreeViewerTranslator.java, components/insight/SRC/org/openmicroscopy/shoola/env/data/views/calls/DMRefreshLoader.java
Some bug fixes for Insight, see [Trello - Insight Bugs](https://trello.com/c/1gwgUlz9/165-insight-bugs)
- Fixed a ClassCastException (1)
- Fixed multiple save actions when selection changes (2)
- Fixed disappearing Annotation task panes when the view was changed to Tags and/or Attachment view (3)
- Bugfix 1: Search for an image which is part of a project. Expand the "Located in" tab in preview panel, click on the project. The project should open, no exception thrown.
- Bugfix 2: Attach some (newly created) tags to multiple images (> 200, so that the tagging action takes a while). Immediately switch to the "Tags" view (left hand side panel). Refresh the view until all images have been tagged, ie tagging action finished. Make sure the tags only were created once (no duplicates with same …
=> Insight Bugfixes

components/tools/OmeroPy/src/omero/plugins/admin.py
This PR attempts to increase accuracy in counting errors and warnings in OMERO.server logs.
Arrange some warnings and/or errors among the regular logs (like `Blitz-0.log`) and also `master.err` and suchlike. Run `bin/omero admin diagnostics` and check that they are correctly counted.
If it's too tricky to stimulate such log entries locally, just copy logs from some other system or append them to the end of yours: [from CI](https://www.openmicroscopy.org/private/ome-internal/instructions/server-logs.html), some bug report in a ticket, etc.
https://trello.com/c/ecsPd9WE/87-diag-false-positives-on-error
=> properly count warnings and errors in OMERO server logs

components/tools/OmeroPy/src/omero/plugins/prefs.py, components/tools/OmeroPy/test/unit/clitest/test_prefs.py
This is the same as gh-4791 but rebased onto develop.
----
Adds `--set` option to `omero config append`, to indicate a value should only be added if it's not already in the list, taking into account the defaults, see https://github.com/openmicroscopy/openmicroscopy/issues/4597
Adds `--report` option to `omero config {append,set,remove}`. This will always print out `Changed: ...` if a change was made, and nothing if no change was made.
1. Check `omero config append/set/remove` behaves as before.
2. Try something like
omero config append --set omero.web.ui.top_links '["History", "history", {"title": "History"}]'
this should have no effect (E.g. `omero config get`, or `omero web restart` and check the top-links) because this value is part of the standard defaults.
3. Try it without `--set`, …
=> Add --set to config append, --report to config {set,append,remove} (rebased onto develop)

components/tools/OmeroWeb/omeroweb/settings.py, components/tools/OmeroWeb/omeroweb/urls.py, components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/jquery.jstree.pagination_plugin.js, components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/ome.right_panel_mapanns_pane.js, components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/ome.tree.js, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/mapannotations.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/mapanns_underscore.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/metadata_general.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/base/base_container.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/containers.html, components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/data/includes/center_plugin.thumbs.js.html, components/tools/OmeroWeb/omeroweb/webclient/tree.py, components/tools/OmeroWeb/omeroweb/webclient/urls.py, components/tools/OmeroWeb/omeroweb/webclient/views.py, components/tools/OmeroWeb/omeroweb/webgateway/templates/webgateway/base/includes/shortcut_icon.html, components/tools/OmeroWeb/omeroweb/webgateway/templates/webgateway/base_site.html, components/tools/OmeroWeb/omeroweb/webgateway/templates/webgateway/core_html.html
This is the same as #4704 but rebased onto develop.
----
This make OMERO.web more customizable.
- light test scenario
- concentrate on tree and pagination.
- check functionality of right hand panel, most of the changes were done to map annotation
----
MAPR test was removed as this is no longer on breaking
=> Allow customizing tree (rebase onto develop)

components/tools/OmeroPy/src/omero/plugins/web.py
Deprecate apache that will be removed in next release
- generate config:
```
$ bin/omero config set omero.web.application_server wsgi
$ bin/omero web config apache 2>&1 > apache.conf
WARNING: Apache and mod_wsgi is deprecated. Please use nginx.
```
- check if `apache.conf` does not contains WARNING message,
- download 5.2.5 release
```
$ bin/omero config set omero.web.application_server wsgi
$ bin/omero web config apache > apache_525.conf
```
- `diff /path/to/apache.conf /path/to/apache_525.conf` should give only diff in paths
=> Deprecate apache

components/blitz/src/omero/client.java, components/tools/OmeroJava/test/integration/ClientUsageTest.java
This PR has the client's `closeSession()` also destroy the session via the router as already occurs in Python. It is probably one to keep in a bit to see if any problems are noticed. See https://trello.com/c/NWT3qUma/172-client-del-session-still-alive for more specific discussion.
=> adjust how Java clients have Blitz close sessions

components/tools/OmeroWeb/omeroweb/webgateway/marshal.py
Fixes error reported at https://trello.com/c/kcMiqyHF/122-use-omero-marshal-for-webgateway-shapemarshal with the marshalling of the new Transform object.
In Insight, in measurement tool draw an Ellipse, rotate it and save to OMERO.
In webclient, check that the rotated Ellipse shows up OK in image viewer.
=> shapeMarshal transform fix

components/insight/SRC/org/openmicroscopy/shoola/env/data/OmeroImageServiceImpl.java
Add try/catch block to handle error when loading supported files
Open the importer, 
Make sure the application does not need to crash if the list of
supported file formats cannot be retrieved.
This can be triggered by not having a "readers.txt" file, the file is read by B-F
The "readers.txt" file is in the``formats-api.jar``. This is part of the jars shipped with insight
Open the ``formats-api.jar``, and remove the file.
See https://www.openmicroscopy.org/qa2/qa/feedback/17307/
=> File filter from B-F

components/dsl/resources/ome/dsl/object.vm
Just corrects a trivial typo. Everything should just keep on working.
=> fix minor typo in autogen comment

components/tools/OmeroFS/setup.py, components/tools/OmeroPy/setup.py, components/tools/OmeroWeb/setup.py
This PR caps the  `pytest` version to below `3.0.0` due to the bug at: https://github.com/pytest-dev/pytest/issues/1905 
The test previously failing at https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-breaking-integration-Python27/26/testReport/OmeroPy.test.integration.clitest/test_download/TestDownload/ should pass.
When the issue above if resolved the commit in this PR should be reverted or otherwise amended.
See: https://trello.com/c/FjmLqCum/709-uncap-pytest
--rebased-to #4848
=> Cap pytest to below 3.0

components/model/resources/ome/util/actions/psql.properties, components/model/src/ome/util/SqlAction.java, components/model/src/ome/util/actions/PostgresSqlAction.java, components/server/resources/ome/services/startup.xml, components/server/src/ome/logic/TypesImpl.java, components/server/src/ome/services/util/BaseDBCheck.java, components/server/src/ome/services/util/DBEnumCheck.java, components/server/src/ome/services/util/DBMappedEnumCheck.java, components/server/src/ome/services/util/EnsureEnum.java
When a new version of OMERO.server starts up (minor or major) it reviews the enumeration values defined in `<enum>` tags in `components/model/resources/mappings/` and ensures that all those strings exist in the corresponding database tables.
In an older version of OMERO delete a few enumeration values from the database. Upgrade to and start up the latest version of OMERO with this PR included and see if those values are added back.
Additionally the `format` table should continue to be populated with new image formats as reported by Bio-Formats readers whenever a new version of Bio-Formats is detected so in the above testing maybe also delete a few formats too that you know should be there (beyond just those listed in `acquisition.ome.xml`). …
=> have OMERO server populate database with missing enumeration values

components/tools/OmeroFS/setup.py, components/tools/OmeroPy/setup.py, components/tools/OmeroWeb/setup.py
This is the same as gh-4826 but rebased onto metadata52.
----
This PR caps the  `pytest` version to below `3.0.0` due to the bug at: https://github.com/pytest-dev/pytest/issues/1905 
The test previously failing at https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-breaking-integration-Python27/26/testReport/OmeroPy.test.integration.clitest/test_download/TestDownload/ should pass.
When the issue above if resolved the commit in this PR should be reverted or otherwise amended.
See: https://trello.com/c/FjmLqCum/709-uncap-pytest
--rebased-to #4848
=> Cap pytest to below 3.0 (rebased onto metadata52)

components/model/resources/mappings/acquisition.ome.xml, sql/psql/OMERO5.3DEV__10/enums_update.sql, sql/psql/OMERO5.3DEV__10/psql-footer.sql
To the OMERO model object mapping adds acquisition modes,
* BrightField
* SweptFieldConfocal
* SPIM
The BIOFORMATS-DEV-merge-full-repository job's logs record various "Unknown AcquisitionMode value" warnings. Pick one of the corresponding images and import it into OMERO. Without these changes (including the entailed Bio-Formats changes) the Blitz log will warn that the enumeration does not exist and will set the image's acquisition mode to "Other". With this PR, having run the `enums_update.sql` script or used a build with #4837 included, the correct acquisition mode should be noted among the image's metadata for subsequent imports. (With these changes in OMERO but without running that database script import is as if OMERO hadn't been changed at all.) …
=> add enumeration values for acquisition mode

components/tools/OmeroJava/test/integration/ClientUsageTest.java, components/tools/OmeroJava/test/integration/gateway/DataManagerFacilityTest.java
- Slight improvement of the `testPerformanceAttachFile` integration test. The test now uploads all 25 attachments synchronously and then compares the average to the asynchronous upload of the same files. Before just a single attachment upload was performed and compared to the asynchronous upload. 
**Update**: That still didn't fix the flakiness of the test running on the CI. Therefore I disabled the job (marked it as 'broken').
- Added a delay before disconnect and attempt to re-join the session (as suggested by @mtbc ). This is expected to fail, otherwise it would mean the session has not been closed probably. Without the delay it was sometimes possible to re-join the session (ie. integration job was failing, flaky). 
Check that the java merge integration job passes.
=> Java integration test fixes

components/tools/OmeroM/src/annotations/getOriginalFileContent.m
ref:
https://www.openmicroscopy.org/community/viewtopic.php?f=6&t=8117
1. Test the Matlab toolbox with the code snippet given in the forum post.
2. Check if the test-code runs without any errors.
=> OMERO_Matlab:Fix the casting from *unit8 to int8

components/server/src/ome/services/graphs/GraphPathReport.java
This makes the `GraphPathReport` model object glossary generation procedure generate a glossary page that matches what is now in our documentation.
Use the class' documentation at http://downloads.openmicroscopy.org/omero/5.2.5/api/ome/services/graphs/GraphPathReport.html to see how to test it and check that it generates an `EveryObject.txt` matching https://github.com/openmicroscopy/ome-documentation/blob/develop/omero/developers/Model/EveryObject.txt exactly. E.g., with a server with this PR configured but not running, check out the current `develop` branch of our docs and from the server's top directory do,
```shell
$ java -cp lib/server/\* `bin/omero config get | awk '{print"-D"$1}'` ome.services.graphs.GraphPathReport /tmp/EveryObject.txt
$ diff /tmp/EveryObject.txt …
```
=> have graph path report include new EveryObjectOverview.inc file

components/tools/OmeroPy/test/integration/gatewaytest/test_get_objects.py
This PR fixes a gateway test that failed due to the changes in gh-4829.
It looks like the test had a benign error in it where the created OriginalFile object had its ID set to 0. The changes in the above PR uncovered this. It might be that Carlos intended something else here but with this change the test still checks the same functionality.
The integration test should pass.
=> Fix gateway test

components/server/src/ome/logic/UpdateImpl.java, components/tools/OmeroPy/test/integration/test_iupdate.py
This causes the update service to throw a validation exception if a client attempts to save an object with an ID that does not exist in the database.
See https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-python/lastCompletedBuild/testReport/OmeroPy.test.integration.test_iupdate/TestIUpdate/
https://trello.com/c/qWNt9vLN/178-save-deleted-object
=> prevent clients from saving deleted objects

sql/psql/OMERO5.2__0/OMERO5.2-5.1-format-syntax-patch.sql
This PR provides a patch script for correcting PL/pgSQL format string syntax errors reported by @chris-allan.
Test that the script fixes for OMERO 5.2 users the mistake also addressed by https://github.com/openmicroscopy/openmicroscopy/commit/53885287e68258ab3e7d48d578aec60ca76c2e75.
#4201 - the problem report
#4822 - the fix for the existing scripts and for OMERO 5.3
https://github.com/openmicroscopy/ome-documentation/pull/1520 - describes this new script
https://trello.com/c/2tDzi0xP/114-detect-buggy-sql-scripts -- related to testing
https://trello.com/c/lF0aMP5I/7-db-upgrade-script-errors -- tracking fix for 5.2
=> add patch script for format syntax errors in PL/pgSQL functions

components/tools/OmeroPy/src/omero/plugins/fs.py
This PR adds an `fs logfile` subcommand to get the import logfile associated with a Fileset. The logfile can be saved to a local file or output to standard out. Additional options provide the file name (full path within the ManagedRepository) and the file size. 
Import some images as different users and note the Fileset IDs. 
```
$ omero fs logfile 1 --size
Log file not accessible for Fileset:1
$ omero fs logfile 2 --name
user-0_2/2016-09/01/09-53-57.029.log
$ omero fs logfile 2 --size
32720
$ omero fs logfile Fileset:2 local.log
$ cat local.log
2016-09-01 09:53:58,095 INFO  [    ome.formats.OMEROMetadataStoreClient] (2-thread-3) Call context: {omero.logfilename:user-0_2/2016-09/01/09-53-57.029.log}
...
2016-09-01 09:53:59,839 INFO  [    o.s.blitz.repo.ManagedImportRequestI] (2-thread-3) …
```
=> CLI: get import log for Fileset

components/tools/OmeroPy/src/omero/gateway/__init__.py, components/tools/OmeroPy/src/omero/gateway/scripts/dbhelpers.py, components/tools/OmeroPy/src/omero/gateway/scripts/testdb_create.py, components/tools/OmeroPy/test/integration/gatewaytest/test_connection.py, components/tools/OmeroWeb/omeroweb/webclient/views.py, components/tools/OmeroWeb/omeroweb/webgateway/views.py, components/tools/OmeroWeb/test/integration/test_config.py
This PR deprecates the offensively named `seppuku` method in the Python gateway replacing it with `close` and not providing its `softclose` option.
Integration testing suffices, see https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-python/lastCompletedBuild/testReport/OmeroPy.test.integration.gatewaytest.test_connection/TestConnectionMethods/.
https://trello.com/c/bS7vTB10/114-rfe-replace-conn-seppuku-with-less-offensive-term-in-code-base
=> change terminator method name to "close"

components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/ome.webclient.actions.js
Fixes duplication of scripts menu - see https://trello.com/c/Gkvvidg9/139-duplication-of-scripts-menu-random-event
1. Double-click (or more!) on the scripts menu button.
Shouldn't be possible to get duplication of script menu items.
=> scripts menu duplicate bugfix

components/tools/OmeroPy/src/omero/plugins/chgrp.py, components/tools/OmeroPy/src/omero/plugins/chown.py, components/tools/OmeroPy/src/omero/plugins/delete.py
This PR adds examples to the help for `delete`, `chgrp` and `chown` that use the hyphen syntax for specifying id ranges. See gh-4707. This form of input is only currently available for the `GraphControl` commands, hence this PR's limited scope.
Check that the command line help for the above commands makes sense.
=> Include hyphen syntax in graph command help

components/tools/OmeroWeb/omeroweb/webgateway/views.py, components/tools/OmeroWeb/test/integration/test_rendering.py, components/tools/OmeroWeb/test/integration/weblibrary.py
Version of #4832, atop of develop.
When certain request arguments are missing or malformed the
`render_image_region` view allows an exception to bubble up the stack
where it is handled by Django.  As the `BlitzGateway` relies on a
`__del__` destructor to clean up the rendering engine stateful service
this can lead to situations where the destructor is not called.
The rendering engine is then leaked for the duration of the session's
lifetime unless it is explicitly cleaned up by re-instantiating a
proxy to the service and the `close` method is called.
The semantics under which a destructor is called when an exception is
thrown are quite complicated and get into Python interpreter internals.
In short, objects with a `__del__` method are not subject to garbage
collection, they are collected …
=> Fix rendering engine leak on missing or malformed request arguments (develop)

components/tools/OmeroPy/src/omero/gateway/__init__.py
Close RawPixelsStore before getPixelRange method returns otherwise the service stays open.
Connect to the same session uuid using BlitzGateway and omero.client. Check session.activeService() before and after calling getPixelRange() and make sure the RawPixelsStore is not on the list.
=> Close RawPixelsStore when done

components/tools/OmeroWeb/omeroweb/urls.py
allows to customize app urls regardless of original web app name is and allow loading apps that has no urls.py
if the app urls need to be different then package name, custom app would have to provide `label` value using AppConfig, see https://github.com/openmicroscopy/weberror/pull/9 as an example
```
from django.apps import AppConfig
class MyWebAppConfig(AppConfig):
name = "module_name"
label = "custom_label"  # this is used by urls
```
To test this PR is required to have a basic understanding of web deployment including nginx and Django.
**testing matrix: Python2.7 Django 1.8.(latest)**
- test custom label
install omeroweb http://www.openmicroscopy.org/site/support/omero5.3-staging/sysadmins/unix/install-web/install-web-trial.html or use https://github.com/ome/omeroweb-install Do not …
=> allow customizing django apps using AppConfig

components/tools/OmeroPy/src/omero/gateway/__init__.py, components/tools/OmeroPy/test/integration/gatewaytest/test_image.py, components/tools/OmeroWeb/omeroweb/webclient/tree.py
Handles invalid acquisition dates in DB
See https://www.openmicroscopy.org/qa2/qa/feedback/17313/
which gives ```ValueError: year is out of range```
<details>
<summary>Full stack trace</summary>
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/omero/OMERO.server/lib/python/omeroweb/decorators.py", line 497, in wrapped
retval = f(request, *args, **kwargs)
File "/home/omero/OMERO.server/lib/python/omeroweb/webclient/views.py", line 745, in api_image_list
limit=limit)
File "/home/omero/OMERO.server/lib/python/omeroweb/webclient/tree.py", line 693, in marshal_images
images.append(_marshal_image(**kwargs))
File …
=> Year out of range

components/tests/ui/robot_setup.sh
replace the way populate_metadata.py is run by recommanded `bin/omero metadata populate`
CI will test it https://ci.openmicroscopy.org/job/OMERO-DEV-merge-robotframework/
before:
```
20:53:09 + python lib/python/omero/util/populate_metadata.py -s cowfish.openmicroscopy.org -p 24064 -k 24ba5a42-8a1c-463d-84d7-842288057e2a Plate:176 bulk_annotation.csv
20:53:09 INFO:omero.util.Resources:Starting
20:53:09 INFO:omero.util.populate_metadata:Missing image name column, skipping.
20:53:09 INFO:omero.util.populate_metadata:Missing plate name column, skipping.
20:53:09 INFO:omero.util.populate_metadata:Missing image name column, skipping.
20:53:09 INFO:omero.util.populate_metadata:Missing plate name column, skipping.
20:53:15 Traceback (most recent call last):
20:53:15   File …
```
=> populate metadata using bin/omero

components/tools/OmeroPy/src/omero/util/populate_metadata.py, components/tools/OmeroPy/test/integration/metadata/test_populate.py
When a well is missing from a plate, a warning is printed. The
same now happens when an image is missing from a dataset. Likely,
a `--strict` argument should be added which will force the existence
of all objects.
1. Check all 29 `test/integration/metadata/test_populate.py` tests continue passing.
2. Attempt to annotate idr0023 (cc @eleanorwilliams). All present images should be annotated.
* https://trello.com/c/q8Fr2ERU/477-in-non-screen-datasets-if-image-file-is-missing-then-bulk-annotation-can-t-be-added-as-gives-error
=> populate_metadata: warn on missing image

components/tools/OmeroWeb/omeroweb/webgateway/views.py, components/tools/OmeroWeb/test/integration/test_rendering.py, components/tools/OmeroWeb/test/integration/weblibrary.py
When certain request arguments are missing or malformed the
`render_image_region` view allows an exception to bubble up the stack
where it is handled by Django.  As the `BlitzGateway` relies on a
`__del__` destructor to clean up the rendering engine stateful service
this can lead to situations where the destructor is not called.
The rendering engine is then leaked for the duration of the session's
lifetime unless it is explicitly cleaned up by re-instantiating a
proxy to the service and the `close` method is called.
The semantics under which a destructor is called when an exception is
thrown are quite complicated and get into Python interpreter internals.
In short, objects with a `__del__` method are not subject to garbage
collection, they are collected using reference counting.  Raising …
=> Fix rendering engine leak on missing or malformed request arguments (dev_5_2)

components/blitz/src/omero/client.java, components/tools/OmeroJava/test/integration/ClientUsageTest.java
This PR has the client's `closeSession()` also destroy the session via the router as already occurs in Python. See https://trello.com/c/NWT3qUma/172-client-del-session-still-alive for more specific discussion.
--rebased-from #4817
=> adjust how Java clients have Blitz close sessions (rebased from develop)

sql/psql/OMERO5.0__0/OMERO4.4__0.sql
@chris-allan reports syntax errors in our PL/pgSQL code. This PR fixes the SQL upgrade script from OMERO 4.4 to 5.0.
Upgrade from OMERO 4.4 to 5.2. Ensure that the upgrade scripts introduce to the database no functions with the overquoted `%%`.
#4201
https://github.com/openmicroscopy/openmicroscopy/pull/4793#discussion_r77590764
https://trello.com/c/2tDzi0xP/114-detect-buggy-sql-scripts
--rebased-from #4822 partially
=> fix SQL syntax errors from database upgrade script (rebased from develop)

components/tools/OmeroPy/src/omero/plugins/web.py
This is the same as gh-4825 but rebased onto dev_5_2.
----
Deprecate apache that will be removed in next release
- generate config:
```
$ bin/omero config set omero.web.application_server wsgi
$ bin/omero web config apache 2>&1 > apache.conf
WARNING: Apache and mod_wsgi is deprecated. Please use nginx.
```
- check if `apache.conf` does not contains WARNING message,
- download 5.2.5 release
```
$ bin/omero config set omero.web.application_server wsgi
$ bin/omero web config apache > apache_525.conf
```
- `diff /path/to/apache.conf /path/to/apache_525.conf` should give only diff in paths
=> Deprecate apache (rebased onto dev_5_2)

components/tools/OmeroFS/setup.py, components/tools/OmeroPy/setup.py, components/tools/OmeroWeb/setup.py
This is a rebase of gh-4826 to fix the same problem caused by `pytest`. See that PR for more details.
--rebased-from #4826
=> Cap pytest to below 3.0 (rebased)

components/tools/OmeroPy/src/omero/gateway/__init__.py, components/tools/OmeroPy/test/integration/gatewaytest/test_image.py
This is the same as gh-4841 but rebased onto dev_5_2.
----
Fixes error in logs on getProjectedThumbnail.
See https://trello.com/c/gl6sfCdI/146-getprojectedthumbnail-bug
1. Need to check web logs:  ```$ tail -f dist/var/log/OMEROweb.log```
2. Pick a Z-stack image, open in full web image viewer, turn Projection ON.
3. Save rendering settings (may need to tweak sliders to enable Save button)
4. Logs should not show any error on Save (see trello card exception).
=> getProjectedThumbnail bugfix (rebased onto dev_5_2)

components/tools/OmeroPy/src/omero/gateway/__init__.py, components/tools/OmeroPy/test/integration/gatewaytest/test_image.py
Fixes error in logs on getProjectedThumbnail.
See https://trello.com/c/gl6sfCdI/146-getprojectedthumbnail-bug
1. Need to check web logs:  ```$ tail -f dist/var/log/OMEROweb.log```
2. Pick a Z-stack image, open in full web image viewer, turn Projection ON.
3. Save rendering settings (may need to tweak sliders to enable Save button)
4. Logs should not show any error on Save (see trello card exception).
=> getProjectedThumbnail bugfix

components/tools/OmeroPy/src/omero/util/metadata_mapannotations.py, components/tools/OmeroPy/src/omero/util/metadata_utils.py, components/tools/OmeroPy/src/omero/util/populate_metadata.py, components/tools/OmeroPy/test/integration/metadata/bulk_to_map_annotation_context_ns.yml, components/tools/OmeroPy/test/integration/metadata/bulk_to_map_annotation_context_ns2.yml, components/tools/OmeroPy/test/integration/metadata/test_metadata_mapannotations.py, components/tools/OmeroPy/test/integration/metadata/test_populate.py, components/tools/OmeroPy/test/unit/test_metadata_mapannotations.py, components/tools/OmeroPy/test/unit/test_metadata_utils.py
This is a follow-up to https://github.com/openmicroscopy/openmicroscopy/pull/4775 to use/update existing map-annotations in the database instead of creating duplicates.
There are several limitations which is why I've kept this as a separate PR:
- De-duplication only occurs between different screens/projects. This mean you can't re-run `metadata populate` on the same screen with the same `bulkmap-config.yml` file unless you first delete the map-annotations on the target.
- The database query loads all map-annotations in the given namespace, this is potentially resource intensive on both server and client
- Haven't figured out proper deletion semantics yet
- Can you delete only annotation links, unless it's the last one in which case also delete the annotation?
1. Setup is similar to …
=> Mapr annotations: query database for existing map-annotations

components/tools/OmeroPy/test/integration/clitest/test_import.py
As the output form of import commands changed in https://github.com/openmicroscopy/openmicroscopy/pull/4812, this PR is adjusting the import integration tests in such a manner that the new Default output is being tested in all tests. Also, 2 new explicit tests have been added, for the default option output (single image and single and multiple plates).
Give this PR a descriptive title then expand on that here.
Check the integration tests are passing.
Check the sensibility of the test additions here.
Note that follow-up PR(s) will add new tests for the 2 new non-default options introduced by the https://github.com/openmicroscopy/openmicroscopy/pull/4812 - A) yaml and B) legacy
=> Output test - put all to default

components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/ome.chgrp.js, components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/ome.tree.js
A couple of minor bug fixes:
1. See https://trello.com/c/GEK62sim/195-move-dialog-double-click-bug In the "Move To Group" (chgrp) dialog, click a target group.
- Check that the spinner shows up while the 'dry run' is performed
- Check that clicking again on the group (or double-clicking) doesn't repeat the dry-run and display the results multiple times.
2. Place an image in 2 Datasets, and place one of the Datasets in a Project (the other Dataset is orphaned). Copy the link to the image ```webclient/?show=image-123``` and visit that url in the browser. 
- Both of the 'paths' to the image should be expanded (both Datasets opened) and the image should be selected in one of the Datasets.
=> Bug fixes oct 2016

components/tools/OmeroWeb/omeroweb/webclient/static/webclient/css/layout.css
Fixes the drag-select of Dataset thumbnails, allowing you to start the drag from anywhere in the centre panel (don't need to start dragging on a thumbnail).
cc @pwalczysko 
1. Drag select Dataset thumbnails with OR without starting on a thumbnail.
=> dataset_thumb_drag_select_fix

components/blitz/resources/ome/services/graph-rules/blitz-chgrp-rules.xml, components/blitz/resources/ome/services/graph-rules/blitz-chown-rules.xml, components/tools/OmeroJava/test/integration/chgrp/HierarchyMoveImageWithAcquisitionDataTest.java
This PR resurrects and extends `HierarchyMoveImageWithAcquisitionDataTest` to check that objective settings move along with images and fixes the graph policy rules so that they actually do.
CI suffices, especially https://ci.openmicroscopy.org/job/OMERO-DEV-merge-integration-java/lastCompletedBuild/testngreports/integration.chgrp/HierarchyMoveImageWithAcquisitionDataTest/
=> preserve objective settings on moves and chowns

components/tools/OmeroWeb/omeroweb/webgateway/urls.py, components/tools/OmeroWeb/omeroweb/webgateway/views.py, components/tools/OmeroWeb/test/integration/test_rendering.py
Retrieving all rendering defs for an image is at the moment a 2 step procedure that requires knowing the ids to the rendering defs that have to be retrieved. The present omero web viewer accomplishes the latter task by receiving an html/js response. In specific this is used in the preview section that shows user rendering settings by their respective thumbnails. 
For the purpose of being able to do likewise in the viewer-ng, but really it's useful in any case where that information is needed and cannot be used with an html response as is I propose this simple webgateway extension that will return all rendering settings for a given image as json (and within one request).
I have added an integration test in what seemed to me the most appropriate place, namely where copy and paste of the …
=> Add get_image_rdefs_json method/resource to webgateway

components/tests/ui/testcases/web/tagging_test.txt, components/tools/OmeroWeb/omeroweb/webclient/controller/container.py, components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/ome.right_panel_tags_pane.js, components/tools/OmeroWeb/omeroweb/webclient/static/webclient/javascript/ome.tagging_form.js, components/tools/OmeroWeb/omeroweb/webclient/views.py, components/tools/OmeroWeb/test/integration/test_annotate.py, components/tools/OmeroWeb/test/integration/test_tags.py
A couple of performance improvements for removing tags from images.
See https://trello.com/c/gPkTUuw5/23-tags-removal-takes-too-long-on-200-images
We now use the batch ```conn.deleteObjects()``` with ```wait=False``` to not wait on async delete, instead of doing a single ```conn.deleteObject()``` for each link in turn.
1. Select many images, add Tag to all of them and Save.
2. Remove tag either with (-) icon on tag itself OR via Tag dialog (moving tag into left column)
3. In both cases this should be much improved performance.
=> Tag removal performance

components/blitz/resources/ome/services/graph-rules/blitz-chgrp-rules.xml, components/blitz/resources/ome/services/graph-rules/blitz-chmod-rules.xml, components/blitz/resources/ome/services/graph-rules/blitz-chown-rules.xml, components/blitz/resources/ome/services/graph-rules/blitz-contained-rules.xml, components/blitz/resources/ome/services/graph-rules/blitz-container-rules.xml, components/blitz/resources/ome/services/graph-rules/blitz-delete-rules.xml, components/blitz/resources/ome/services/graph-rules/blitz-disk-usage-rules.xml, components/blitz/resources/ome/services/graph-rules/blitz-duplicate-rules.xml, components/blitz/resources/omero/ROMIO.ice, components/blitz/resources/omero/api/RenderingEngine.ice, components/blitz/src/ome/services/blitz/impl/RenderingEngineI.java, components/blitz/src/omero/util/IceMapper.java, components/common/src/omeis/providers/re/RenderingEngine.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/RendererModel.java, components/insight/SRC/org/openmicroscopy/shoola/env/rnd/RenderingControl.java, components/insight/SRC/org/openmicroscopy/shoola/env/rnd/RenderingControlProxy.java, components/rendering/src/omeis/providers/re/HSBStrategy.java, components/rendering/src/omeis/providers/re/Renderer.java, components/rendering/src/omeis/providers/re/RenderingStats.java, components/rendering/src/omeis/providers/re/codomain/CodomainChain.java, components/server/src/ome/logic/RenderingSettingsImpl.java, components/server/src/ome/services/RenderingBean.java, components/server/src/ome/services/ThumbnailBean.java, components/tools/OmeroJava/test/integration/AbstractServerTest.java, components/tools/OmeroJava/test/integration/RenderingEngineTest.java, components/tools/OmeroJava/test/integration/RenderingSettingsServicePermissionsTest.java, components/tools/OmeroJava/test/integration/RenderingSettingsServiceTest.java
Re-activate the codomain map context. This was initially per rendering. Part I of the work
This is now per channel (part II). see https://github.com/openmicroscopy/openmicroscopy/pull/4793
Existing methods ``add/remove/update`` have been deprecated. Note that they have never been used.
New methods have been added to ``add/remove/retrieve`` the codomain contexts associated to a channel
No update method.
Only the ``ReverseIntensityMapContext`` has been added.
Integration test has been updated
https://trello.com/c/9iAe3Sg9/95-lut-support
cc @will-moore @dominikl
=> Codomain per channel rnd

components/insight/SRC/org/openmicroscopy/shoola/agents/dataBrowser/browser/BrowserControl.java, components/insight/SRC/org/openmicroscopy/shoola/agents/dataBrowser/view/WellsModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ControlPane.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewer.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerControl.java, components/insight/SRC/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/measurement/view/MeasurementViewerControl.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/Renderer.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/RendererComponent.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/RendererControl.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/RendererModel.java, components/insight/SRC/org/openmicroscopy/shoola/agents/metadata/rnd/RendererUI.java, components/insight/SRC/org/openmicroscopy/shoola/env/rnd/ChannelBindingsProxy.java, components/insight/SRC/org/openmicroscopy/shoola/env/rnd/PixelsServicesFactory.java, components/insight/SRC/org/openmicroscopy/shoola/env/rnd/RenderingControl.java, components/insight/SRC/org/openmicroscopy/shoola/env/rnd/RenderingControlProxy.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/colourpicker/ColourIcon.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/colourpicker/ColourObject.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/colourpicker/ColourPicker.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/colourpicker/ColourSwatchUI.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/colourpicker/LookupTableListRenderer.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/colourpicker/PaintPotUI.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/colourpicker/RGBControl.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/colourpicker/RGBModel.java, components/insight/SRC/org/openmicroscopy/shoola/util/ui/colourpicker/TabbedPaneUI.java
Adds the reverse intensity functionality to Insight.
In preview and full viewer: Open the color picker for a channel, reverse the intensity by ticking the checkbox in the upper right corner of the color picker.
=> Reverse intensity (Insight)

components/blitz/src/omero/gateway/facility/TablesFacility.java, components/blitz/src/omero/gateway/model/TableData.java, components/blitz/src/omero/gateway/model/TableDataColumn.java, components/tools/OmeroJava/test/gateway.testng.xml, components/tools/OmeroJava/test/integration/gateway/GatewayTest.java, components/tools/OmeroJava/test/integration/gateway/TablesFacilityTest.java
Resurrected the `TablesFacility` from  #4347 (which was closed and only a subset merged into 5.2.3).
The TablesFacility would provide an easy way for adding and getting table structured data to/from OMERO, this would be very useful for the R gateway (i.e attaching/loading dataframes to/from OME objects, https://github.com/dominikl/rOMERO/blob/dev_5_3/examples/dataframes.R ).
Probably needs some more discussion, but it would be very handy to open up the tables accessibility, so I could create some more realistic R examples.
**Test**
Basically check if the `TablesFacility.java` 'API' makes sense and the according integration test is sufficient and passes. Optional: Run above mentioned `dataframes.R` example code.
**Status**
In my opinion this could be merged. But there was still some …
=> TablesFacility

components/tools/OmeroPy/src/omero/cli.py
During plugin loading, loop over the contents of sys.path
(i.e. PYTHONPATH) and for all directories which contain a
subdirectory `omero/plugin` run the loadpath method as if
it had been passed to `bin/omero` with `--path`.
NB: This currently does not handle plugins packaged as eggs.
See https://github.com/ome/omero-cli-duplicate/pull/1 for an example of how this would be used.
Further explanation is now on https://trello.com/c/qMrZfcoU/78-external-cli-plugins
=> Load all `omero/plugins` subdirs on the PYTHONPATH
